# Unified Validation Pipeline

This notebook rebuilds the core modeling workflow in one place using the raw CSV as the only source-of-truth input.

## Scope
- Load the dataset from `data/smart_grid_stability_augmented.csv`
- Apply feature engineering
- Apply consensus feature selection on the training split only
- Evaluate baseline models with scaler selection
- Run Grey Wolf Optimization (GWO)
- Run Tree-structured Parzen Estimator (TPE)
- Produce train-side out-of-fold metrics, held-out test metrics, and confidence intervals for the 8 evaluation metrics

 ## imports and constants

In [1]:
import json
import math
import time
import warnings
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import optuna
import pandas as pd
import xgboost as xgb
from catboost import CatBoostClassifier
import lightgbm as lgb
from IPython.display import display
from sklearn.base import clone
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier, RandomForestClassifier
from sklearn.feature_selection import RFE, SelectFromModel, VarianceThreshold, f_classif, mutual_info_classif
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.metrics import (
    accuracy_score,
    cohen_kappa_score,
    f1_score,
    log_loss,
    matthews_corrcoef,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.model_selection import StratifiedKFold, cross_validate, train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler, PowerTransformer, QuantileTransformer, RobustScaler, StandardScaler
from sklearn.svm import LinearSVC, SVC

warnings.filterwarnings("ignore")
optuna.logging.set_verbosity(optuna.logging.WARNING)


def find_project_root(start: Path) -> Path:
    current = start.resolve()
    for candidate in [current, *current.parents]:
        if (candidate / "data" / "smart_grid_stability_augmented.csv").exists():
            return candidate
    raise FileNotFoundError("Could not locate project root from the current notebook working directory.")


PROJECT_ROOT = find_project_root(Path.cwd())
DATA_PATH = PROJECT_ROOT / "data" / "smart_grid_stability_augmented.csv"
RESULTS_DIR = PROJECT_ROOT / "results" / "tables" / "sum_logic"
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

RANDOM_STATE = 42
TEST_SIZE = 0.20
N_SPLITS = 5
N_TRIALS_PER_MODEL = 50
GWO_POPULATION_SIZE = 10
GWO_ITERATIONS = 4  # 10 init + 4*10 iterations = 50 total, identical to TPE budget
N_BOOTSTRAP = 2000
VOTE_THRESHOLD = 3
VAR_THRESHOLD = 0.01
CORR_THRESHOLD = 0.95
TOP_K_FRACTION = 0.50

TARGET_COLUMN = "stabf"
LEAKAGE_COLUMN = "stab"
METRICS = ["Accuracy", "Precision", "Recall", "F1", "AUC", "LogLoss", "Kappa", "MCC"]
METHOD_ORDER = ["Baseline", "GWO", "TPE"]
MODEL_ORDER = ["LR", "LDA", "QDA", "NB", "KNN", "LinearSVC", "SVM", "AdaBoost", "RF", "GB", "XGB", "LGBM", "CB", "SGD"]

SCALER_FACTORIES = {
    "Raw": lambda: None,
    "Standard": StandardScaler,
    "MinMax": MinMaxScaler,
    "Robust": RobustScaler,
    "Power": PowerTransformer,
    "Quantile": lambda: QuantileTransformer(output_distribution="normal", random_state=RANDOM_STATE),
}

MODEL_LABELS = {
    "LR": "LogisticRegression",
    "LDA": "LDA",
    "QDA": "QDA",
    "NB": "NaiveBayes",
    "KNN": "KNN",
    "LinearSVC": "LinearSVC",
    "SVM": "SVC",
    "AdaBoost": "AdaBoost",
    "RF": "RandomForest",
    "GB": "GradientBoosting",
    "XGB": "XGBoost",
    "LGBM": "LightGBM",
    "CB": "CatBoost",
    "SGD": "SGD",
}

SEARCH_SPACES = {
    "LR": {
        "C": {"type": "float", "range": [1e-4, 100.0], "log": True},
        "penalty": {"type": "categorical", "choices": ["l1", "l2"]},
    },
    "SGD": {
        "loss": {"type": "categorical", "choices": ["log_loss", "modified_huber"]},
        "penalty": {"type": "categorical", "choices": ["l1", "l2", "elasticnet"]},
        "alpha": {"type": "float", "range": [1e-6, 1e-1], "log": True},
        "l1_ratio": {"type": "float", "range": [0.0, 1.0], "log": False},
    },
    "LDA": {
        "solver": {"type": "categorical", "choices": ["svd", "lsqr", "eigen"]},
    },
    "QDA": {
        "reg_param": {"type": "float", "range": [0.0, 1.0], "log": False},
    },
    "NB": {
        "var_smoothing": {"type": "float", "range": [1e-12, 1e-6], "log": True},
    },
    "KNN": {
        "n_neighbors": {"type": "int", "range": [1, 50], "log": False},
        "weights": {"type": "categorical", "choices": ["uniform", "distance"]},
        "metric": {"type": "categorical", "choices": ["euclidean", "manhattan", "minkowski"]},
        "p": {"type": "int", "range": [1, 5], "log": False},
    },
    "LinearSVC": {
        "C": {"type": "float", "range": [1e-4, 100.0], "log": True},
        "loss": {"type": "categorical", "choices": ["hinge", "squared_hinge"]},
    },
    "SVM": {
        "kernel": {"type": "categorical", "choices": ["rbf", "poly", "sigmoid"]},
        "C": {"type": "float", "range": [1e-3, 1000.0], "log": True},
        "gamma": {"type": "categorical", "choices": ["scale", "auto"]},
        "degree": {"type": "int", "range": [2, 5], "log": False},
        "coef0": {"type": "float", "range": [0.0, 1.0], "log": False},
    },
    "RF": {
        "n_estimators": {"type": "int", "range": [50, 500], "log": False},
        "max_depth": {"type": "int", "range": [3, 30], "log": False},
        "min_samples_split": {"type": "int", "range": [2, 20], "log": False},
        "min_samples_leaf": {"type": "int", "range": [1, 10], "log": False},
        "max_features": {"type": "categorical", "choices": ["sqrt", "log2", None]},
    },
    "AdaBoost": {
        "n_estimators": {"type": "int", "range": [50, 500], "log": False},
        "learning_rate": {"type": "float", "range": [0.01, 2.0], "log": True},
        "algorithm": {"type": "categorical", "choices": ["SAMME", "SAMME.R"]},
    },
    "GB": {
        "n_estimators": {"type": "int", "range": [50, 500], "log": False},
        "learning_rate": {"type": "float", "range": [0.01, 0.5], "log": True},
        "max_depth": {"type": "int", "range": [3, 15], "log": False},
        "min_samples_split": {"type": "int", "range": [2, 20], "log": False},
        "min_samples_leaf": {"type": "int", "range": [1, 10], "log": False},
        "subsample": {"type": "float", "range": [0.5, 1.0], "log": False},
    },
    "XGB": {
        "n_estimators": {"type": "int", "range": [50, 500], "log": False},
        "learning_rate": {"type": "float", "range": [0.01, 0.5], "log": True},
        "max_depth": {"type": "int", "range": [3, 15], "log": False},
        "min_child_weight": {"type": "int", "range": [1, 10], "log": False},
        "subsample": {"type": "float", "range": [0.5, 1.0], "log": False},
        "colsample_bytree": {"type": "float", "range": [0.5, 1.0], "log": False},
        "gamma": {"type": "float", "range": [0.0, 5.0], "log": False},
        "reg_alpha": {"type": "float", "range": [1e-8, 10.0], "log": True},
        "reg_lambda": {"type": "float", "range": [1e-8, 10.0], "log": True},
    },
    "LGBM": {
        "n_estimators": {"type": "int", "range": [50, 500], "log": False},
        "learning_rate": {"type": "float", "range": [0.01, 0.5], "log": True},
        "max_depth": {"type": "int", "range": [3, 15], "log": False},
        "num_leaves": {"type": "int", "range": [20, 150], "log": False},
        "min_child_samples": {"type": "int", "range": [5, 100], "log": False},
        "subsample": {"type": "float", "range": [0.5, 1.0], "log": False},
        "colsample_bytree": {"type": "float", "range": [0.5, 1.0], "log": False},
        "reg_alpha": {"type": "float", "range": [1e-8, 10.0], "log": True},
        "reg_lambda": {"type": "float", "range": [1e-8, 10.0], "log": True},
    },
    "CB": {
        "iterations": {"type": "int", "range": [50, 500], "log": False},
        "learning_rate": {"type": "float", "range": [0.01, 0.5], "log": True},
        "depth": {"type": "int", "range": [3, 10], "log": False},
        "l2_leaf_reg": {"type": "float", "range": [1e-8, 10.0], "log": True},
        "border_count": {"type": "int", "range": [32, 255], "log": False},
        "bagging_temperature": {"type": "float", "range": [0.0, 10.0], "log": False},
    },
}

CV = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=RANDOM_STATE)

print(f"Project root: {PROJECT_ROOT}")
print(f"Raw data path: {DATA_PATH}")
print(f"Results path: {RESULTS_DIR}")
print(f"Optimizer search spaces defined for {len(SEARCH_SPACES)} models.")

c:\Users\omar8\miniconda3\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Project root: C:\Users\omar8\Desktop\2026\Master & Research\smart-grid-stability-v01
Raw data path: C:\Users\omar8\Desktop\2026\Master & Research\smart-grid-stability-v01\data\smart_grid_stability_augmented.csv
Results path: C:\Users\omar8\Desktop\2026\Master & Research\smart-grid-stability-v01\results\tables\sum_logic
Optimizer search spaces defined for 14 models.

## system resource setup

In [3]:
# =====================================================================
# SYSTEM RESOURCE DETECTION & OPTIMIZATION
# =====================================================================

import psutil
import gc
import os

# Detect system resources
CPU_COUNT = os.cpu_count() or 4
AVAILABLE_MEMORY_GB = psutil.virtual_memory().available / (1024**3)
TOTAL_MEMORY_GB = psutil.virtual_memory().total / (1024**3)
MEMORY_PERCENT_AVAILABLE = (AVAILABLE_MEMORY_GB / TOTAL_MEMORY_GB) * 100

# Adaptive n_jobs based on memory and CPU
def compute_optimal_n_jobs(cpu_count: int, available_memory_gb: float, operation: str = "cv") -> int:
    """
    Compute optimal n_jobs to balance parallelization with memory constraints.
    
    Rules:
    - CV/Training: Use min(cpu_count - 2, cpu_available * 0.7)
    - Optimization: Use min(cpu_count - 2, 4) to prevent worker exhaustion
    - If <4GB available: Use 1 (single process only)
    """
    reserved_cores = 2
    available_cores = max(1, cpu_count - reserved_cores)
    
    if available_memory_gb < 4:
        return 1  # Single process if memory critical
    elif available_memory_gb < 8:
        return min(2, available_cores)
    elif operation == "optimization":
        return min(3, available_cores)  # Conservative for optimization loops
    else:
        return min(4, available_cores)  # Regular CV/training

N_JOBS_CV = compute_optimal_n_jobs(CPU_COUNT, AVAILABLE_MEMORY_GB, "cv")
N_JOBS_OPT = compute_optimal_n_jobs(CPU_COUNT, AVAILABLE_MEMORY_GB, "optimization")

print("="*80)
print("SYSTEM RESOURCE ANALYSIS & OPTIMIZATION")
print("="*80)
print(f"CPU Cores Available:        {CPU_COUNT}")
print(f"Total Memory:               {TOTAL_MEMORY_GB:.2f} GB")
print(f"Available Memory:           {AVAILABLE_MEMORY_GB:.2f} GB ({MEMORY_PERCENT_AVAILABLE:.1f}%)")
print(f"Optimized n_jobs (CV):      {N_JOBS_CV}")
print(f"Optimized n_jobs (OPT):     {N_JOBS_OPT}")
print("="*80)

# Resource monitoring class
class ResourceMonitor:
    def __init__(self, label: str = "Operation"):
        self.label = label
        self.start_time = None
        self.start_memory = None
        self.peak_memory = None
    
    def __enter__(self):
        self.start_time = time.perf_counter()
        self.start_memory = psutil.Process(os.getpid()).memory_info().rss / (1024**2)  # MB
        return self
    
    def __exit__(self, *args):
        elapsed = time.perf_counter() - self.start_time
        current_memory = psutil.Process(os.getpid()).memory_info().rss / (1024**2)
        memory_delta = current_memory - self.start_memory
        print(f"  [{self.label}] Time: {elapsed:7.2f}s | Memory Δ: {memory_delta:+7.1f}MB | Peak: {current_memory:7.1f}MB")
        gc.collect()  # Explicit garbage collection

# Memory profiling decorator
def profile_memory(func):
    def wrapper(*args, **kwargs):
        gc.collect()  # Clean before
        start_mem = psutil.Process(os.getpid()).memory_info().rss / (1024**2)
        result = func(*args, **kwargs)
        end_mem = psutil.Process(os.getpid()).memory_info().rss / (1024**2)
        print(f"  └─ Memory change: {end_mem - start_mem:+.1f}MB")
        return result
    return wrapper

print("\n✓ Resource monitoring ready. Using adaptive parallelization.")
print("✓ Garbage collection enabled between major operations.")

================================================================================
SYSTEM RESOURCE ANALYSIS & OPTIMIZATION
================================================================================
CPU Cores Available:        8
Total Memory:               15.73 GB
Available Memory:           4.56 GB (29.0%)
Optimized n_jobs (CV):      2
Optimized n_jobs (OPT):     2
================================================================================

✓ Resource monitoring ready. Using adaptive parallelization.
✓ Garbage collection enabled between major operations.

## data load, engineering, selection

In [3]:
def engineer_features(X: pd.DataFrame) -> pd.DataFrame:
    X = X.copy()
    tau_cols = ["tau1", "tau2", "tau3", "tau4"]
    g_cols = ["g1", "g2", "g3", "g4"]

    X["tau_mean"] = X[tau_cols].mean(axis=1)
    X["g_sum"] = X[g_cols].sum(axis=1)
    X["tau1_g1"] = X["tau1"] * X["g1"]
    X["tau2_g2"] = X["tau2"] * X["g2"]
    X["tau3_g3"] = X["tau3"] * X["g3"]
    X["tau4_g4"] = X["tau4"] * X["g4"]
    X["g_tau_ratio"] = X["g_sum"] / (X["tau_mean"] + 1e-5)
    return X


def consensus_feature_selection(X_train_input: pd.DataFrame, y_train_input: pd.Series) -> Tuple[List[str], pd.DataFrame]:
    votes = pd.DataFrame(index=X_train_input.columns)
    feature_select_jobs = max(1, min(N_JOBS_CV, 2))

    var_selector = VarianceThreshold(threshold=VAR_THRESHOLD)
    var_selector.fit(X_train_input)
    var_features = X_train_input.columns[var_selector.get_support()].tolist()
    votes["Variance"] = votes.index.isin(var_features).astype(int)

    corr_matrix = X_train_input[var_features].corr().abs()
    upper_triangle = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))
    to_drop = [column for column in upper_triangle.columns if (upper_triangle[column] > CORR_THRESHOLD).any()]
    corr_features = [feature for feature in var_features if feature not in to_drop]
    votes["Correlation"] = votes.index.isin(corr_features).astype(int)

    X_corr = X_train_input[corr_features]
    X_corr_scaled = StandardScaler().fit_transform(X_corr)
    k_best = max(1, int(len(corr_features) * TOP_K_FRACTION))

    mi_scores = mutual_info_classif(X_corr_scaled, y_train_input, random_state=RANDOM_STATE)
    mi_features = X_corr.columns[np.argsort(mi_scores)[-k_best:]].tolist()
    votes["Mutual_Info"] = votes.index.isin(mi_features).astype(int)

    f_scores = f_classif(X_corr_scaled, y_train_input)[0]
    anova_features = X_corr.columns[np.argsort(f_scores)[-k_best:]].tolist()
    votes["ANOVA"] = votes.index.isin(anova_features).astype(int)

    rfe_selector = RFE(
        estimator=RandomForestClassifier(n_estimators=50, random_state=RANDOM_STATE, n_jobs=feature_select_jobs),
        n_features_to_select=k_best,
    )
    rfe_selector.fit(X_corr_scaled, y_train_input)
    rfe_features = X_corr.columns[rfe_selector.support_].tolist()
    votes["RFE"] = votes.index.isin(rfe_features).astype(int)

    embedded_selector = SelectFromModel(
        RandomForestClassifier(n_estimators=100, random_state=RANDOM_STATE, n_jobs=feature_select_jobs)
    )
    embedded_selector.fit(X_corr_scaled, y_train_input)
    embedded_features = X_corr.columns[embedded_selector.get_support()].tolist()
    votes["Embedded"] = votes.index.isin(embedded_features).astype(int)

    votes["Total"] = votes.sum(axis=1)
    selected_features = votes[votes["Total"] >= VOTE_THRESHOLD].index.tolist()
    return selected_features, votes.sort_values(["Total"], ascending=False)


def summarize_integrity(df: pd.DataFrame, X_engineered: pd.DataFrame, y_binary: pd.Series, selected: List[str]) -> pd.DataFrame:
    reproducible_split = train_test_split(
        X_engineered,
        y_binary,
        test_size=TEST_SIZE,
        stratify=y_binary,
        random_state=RANDOM_STATE,
    )
    reproducible = reproducible_split[0].index.equals(X_train_full.index) and reproducible_split[1].index.equals(X_test_full.index)

    summary = pd.DataFrame(
        [
            {"Check": "Raw rows", "Value": len(df)},
            {"Check": "Raw columns", "Value": df.shape[1]},
            {"Check": "Raw duplicate rows", "Value": int(df.duplicated().sum())},
            {"Check": "Raw missing values", "Value": int(df.isna().sum().sum())},
            {"Check": "Engineered feature count", "Value": X_engineered.shape[1]},
            {"Check": "Selected feature count", "Value": len(selected)},
            {"Check": "Train rows", "Value": len(X_train_full)},
            {"Check": "Test rows", "Value": len(X_test_full)},
            {"Check": "Train positive rate", "Value": float(y_train.mean())},
            {"Check": "Test positive rate", "Value": float(y_test.mean())},
            {"Check": "Split reproducible", "Value": bool(reproducible)},
        ]
    )
    return summary


df = pd.read_csv(DATA_PATH)
y = (df[TARGET_COLUMN] == "unstable").astype(int)
X_raw = df.drop(columns=[TARGET_COLUMN, LEAKAGE_COLUMN])
X_engineered = engineer_features(X_raw)

X_train_full, X_test_full, y_train, y_test = train_test_split(
    X_engineered,
    y,
    test_size=TEST_SIZE,
    stratify=y,
    random_state=RANDOM_STATE,
)

selected_features, feature_votes = consensus_feature_selection(X_train_full, y_train)
X_train = X_train_full[selected_features].copy()
X_test = X_test_full[selected_features].copy()

reference_selected_path = PROJECT_ROOT / "results" / "tables" / "selected_features.json"
reference_selected_features = None
if reference_selected_path.exists():
    reference_selected_features = json.loads(reference_selected_path.read_text())

integrity_summary = summarize_integrity(df, X_engineered, y, selected_features)
validation_payload = {
    "selected_features": selected_features,
    "reference_selected_features": reference_selected_features,
    "matches_reference_selection": selected_features == reference_selected_features if reference_selected_features is not None else None,
}

feature_votes.to_csv(RESULTS_DIR / "feature_votes.csv")
pd.DataFrame({"feature": selected_features}).to_csv(RESULTS_DIR / "selected_features.csv", index=False)
integrity_summary.to_csv(RESULTS_DIR / "data_integrity_summary.csv", index=False)
with open(RESULTS_DIR / "validation_payload.json", "w", encoding="utf-8") as handle:
    json.dump(validation_payload, handle, indent=2)

assert df.isna().sum().sum() == 0, "Raw dataset contains missing values."
assert not X_train.isna().any().any(), "Training design matrix contains missing values."
assert not X_test.isna().any().any(), "Test design matrix contains missing values."
assert len(selected_features) > 0, "Feature selection returned no features."

print(f"Loaded raw dataset with shape {df.shape}")
print(f"Engineered feature matrix shape: {X_engineered.shape}")
print(f"Selected feature matrix shape: train={X_train.shape}, test={X_test.shape}")
print(f"Selection matches reference artifact: {validation_payload['matches_reference_selection']}")
display(integrity_summary)
display(feature_votes.head(10))

Loaded raw dataset with shape (60000, 14)
Engineered feature matrix shape: (60000, 19)
Selected feature matrix shape: train=(48000, 13), test=(12000, 13)
Selection matches reference artifact: True

                       Check  Value
0                   Raw rows  60000
1                Raw columns     14
2         Raw duplicate rows      0
3         Raw missing values      0
4   Engineered feature count     19
5     Selected feature count     13
6                 Train rows  48000
7                  Test rows  12000
8        Train positive rate  0.638
9         Test positive rate  0.638
10        Split reproducible   True

          Variance  Correlation  Mutual_Info  ANOVA  RFE  Embedded  Total
g_sum            1            1            1      1    1         1      6
tau1_g1          1            1            1      1    1         1      6
tau2_g2          1            1            1      1    1         1      6
tau_mean         1            1            1      1    1         1      6
tau3_g3          1            1            1      1    1         1      6
tau1             1            1            1      0    1         1      5
tau3             1            1            0      1    1         1      5
tau4_g4          1            1            0      1    1         1      5
tau4             1            1            0      1    1         1      5
tau2             1            1            0      1    0         0      3

## model and metrics utilities

In [4]:
def get_scaler(scaler_name: str):
    factory = SCALER_FACTORIES[scaler_name]
    return None if factory is None or scaler_name == "Raw" else factory()


def build_model(model_code: str, params: Optional[Dict[str, Any]] = None):
    params = dict(params or {})

    if model_code == "LR":
        penalty = params.pop("penalty", "l2")
        solver = params.pop("solver", "saga")
        if penalty == "l1" and solver not in {"liblinear", "saga"}:
            solver = "saga"
        return LogisticRegression(
            C=params.pop("C", 1.0),
            penalty=penalty,
            solver=solver,
            max_iter=params.pop("max_iter", 2000),
            random_state=params.pop("random_state", RANDOM_STATE),
            **params,
        )

    if model_code == "LDA":
        solver = params.pop("solver", "svd")
        shrinkage = params.pop("shrinkage", None)
        if solver == "svd":
            return LinearDiscriminantAnalysis(solver=solver, **params)
        return LinearDiscriminantAnalysis(solver=solver, shrinkage=shrinkage, **params)

    if model_code == "QDA":
        return QuadraticDiscriminantAnalysis(reg_param=params.pop("reg_param", 0.0), **params)

    if model_code == "NB":
        return GaussianNB(var_smoothing=params.pop("var_smoothing", 1e-9), **params)

    if model_code == "KNN":
        return KNeighborsClassifier(
            n_neighbors=params.pop("n_neighbors", 5),
            weights=params.pop("weights", "uniform"),
            metric=params.pop("metric", "minkowski"),
            p=params.pop("p", 2),
            **params,
        )

    if model_code == "LinearSVC":
        return LinearSVC(
            C=params.pop("C", 1.0),
            loss=params.pop("loss", "squared_hinge"),
            dual=params.pop("dual", "auto"),
            max_iter=params.pop("max_iter", 5000),
            random_state=params.pop("random_state", RANDOM_STATE),
            **params,
        )

    if model_code == "SVM":
        return SVC(
            kernel=params.pop("kernel", "rbf"),
            C=params.pop("C", 1.0),
            gamma=params.pop("gamma", "scale"),
            degree=params.pop("degree", 3),
            coef0=params.pop("coef0", 0.0),
            probability=True,
            random_state=RANDOM_STATE,
            **params,
        )

    if model_code == "AdaBoost":
        algorithm = params.pop("algorithm", "SAMME")
        if algorithm == "SAMME.R":
            algorithm = "SAMME"
        return AdaBoostClassifier(
            n_estimators=params.pop("n_estimators", 50),
            learning_rate=params.pop("learning_rate", 1.0),
            algorithm=algorithm,
            random_state=params.pop("random_state", RANDOM_STATE),
            **params,
        )

    if model_code == "RF":
        max_features = params.pop("max_features", "sqrt")
        if max_features == "None":
            max_features = None
        return RandomForestClassifier(
            n_estimators=params.pop("n_estimators", 100),
            max_depth=params.pop("max_depth", None),
            min_samples_split=params.pop("min_samples_split", 2),
            min_samples_leaf=params.pop("min_samples_leaf", 1),
            max_features=max_features,
            random_state=params.pop("random_state", RANDOM_STATE),
            n_jobs=N_JOBS_OPT,
            **params,
        )

    if model_code == "GB":
        return GradientBoostingClassifier(
            n_estimators=params.pop("n_estimators", 100),
            learning_rate=params.pop("learning_rate", 0.1),
            max_depth=params.pop("max_depth", 3),
            min_samples_split=params.pop("min_samples_split", 2),
            min_samples_leaf=params.pop("min_samples_leaf", 1),
            subsample=params.pop("subsample", 1.0),
            random_state=params.pop("random_state", RANDOM_STATE),
            **params,
        )

    if model_code == "XGB":
        return xgb.XGBClassifier(
            n_estimators=params.pop("n_estimators", 100),
            learning_rate=params.pop("learning_rate", 0.1),
            max_depth=params.pop("max_depth", 6),
            min_child_weight=params.pop("min_child_weight", 1),
            subsample=params.pop("subsample", 1.0),
            colsample_bytree=params.pop("colsample_bytree", 1.0),
            gamma=params.pop("gamma", 0.0),
            reg_alpha=params.pop("reg_alpha", 0.0),
            reg_lambda=params.pop("reg_lambda", 1.0),
            eval_metric="logloss",
            random_state=params.pop("random_state", RANDOM_STATE),
            n_jobs=N_JOBS_OPT,
            verbosity=0,
            **params,
        )

    if model_code == "LGBM":
        return lgb.LGBMClassifier(
            n_estimators=params.pop("n_estimators", 100),
            learning_rate=params.pop("learning_rate", 0.1),
            max_depth=params.pop("max_depth", -1),
            num_leaves=params.pop("num_leaves", 31),
            min_child_samples=params.pop("min_child_samples", 20),
            subsample=params.pop("subsample", 1.0),
            colsample_bytree=params.pop("colsample_bytree", 1.0),
            reg_alpha=params.pop("reg_alpha", 0.0),
            reg_lambda=params.pop("reg_lambda", 0.0),
            random_state=params.pop("random_state", RANDOM_STATE),
            verbose=-1,
            n_jobs=N_JOBS_OPT,
            **params,
        )

    if model_code == "CB":
        return CatBoostClassifier(
            iterations=params.pop("iterations", 100),
            learning_rate=params.pop("learning_rate", 0.1),
            depth=params.pop("depth", 6),
            l2_leaf_reg=params.pop("l2_leaf_reg", 3.0),
            border_count=params.pop("border_count", 128),
            bagging_temperature=params.pop("bagging_temperature", 0.0),
            random_seed=params.pop("random_state", RANDOM_STATE),
            verbose=0,
            allow_writing_files=False,
            **params,
        )

    if model_code == "SGD":
        return SGDClassifier(
            loss=params.pop("loss", "log_loss"),
            penalty=params.pop("penalty", "l2"),
            alpha=params.pop("alpha", 1e-4),
            l1_ratio=params.pop("l1_ratio", 0.15),
            max_iter=params.pop("max_iter", 2000),
            random_state=params.pop("random_state", RANDOM_STATE),
            **params,
        )

    raise ValueError(f"Unsupported model code: {model_code}")


def make_pipeline(model_code: str, params: Optional[Dict[str, Any]], scaler_name: str) -> Pipeline:
    steps = []
    scaler = get_scaler(scaler_name)
    if scaler is not None:
        steps.append(("scaler", scaler))
    steps.append(("model", build_model(model_code, params)))
    return Pipeline(steps)


def get_scores_and_probabilities(fitted_pipeline: Pipeline, X_input: pd.DataFrame) -> Tuple[np.ndarray, Optional[np.ndarray], Optional[np.ndarray]]:
    y_pred = fitted_pipeline.predict(X_input)
    y_proba = None
    y_score = None
    if hasattr(fitted_pipeline, "predict_proba"):
        y_proba = fitted_pipeline.predict_proba(X_input)[:, 1]
        y_score = y_proba.copy()
    elif hasattr(fitted_pipeline, "decision_function"):
        y_score = fitted_pipeline.decision_function(X_input)
    return y_pred, y_score, y_proba


def compute_metric_dict(
    y_true: np.ndarray,
    y_pred: np.ndarray,
    y_score: Optional[np.ndarray] = None,
    y_proba: Optional[np.ndarray] = None,
) -> Dict[str, float]:
    metrics = {
        "Accuracy": float(accuracy_score(y_true, y_pred)),
        "Precision": float(precision_score(y_true, y_pred, zero_division=0)),
        "Recall": float(recall_score(y_true, y_pred, zero_division=0)),
        "F1": float(f1_score(y_true, y_pred, zero_division=0)),
        "Kappa": float(cohen_kappa_score(y_true, y_pred)),
        "MCC": float(matthews_corrcoef(y_true, y_pred)),
        "AUC": np.nan,
        "LogLoss": np.nan,
    }

    if y_score is not None and len(np.unique(y_true)) > 1:
        try:
            metrics["AUC"] = float(roc_auc_score(y_true, y_score))
        except ValueError:
            metrics["AUC"] = np.nan

    if y_proba is not None and len(np.unique(y_true)) > 1:
        try:
            clipped = np.clip(y_proba, 1e-12, 1 - 1e-12)
            metrics["LogLoss"] = float(log_loss(y_true, clipped))
        except ValueError:
            metrics["LogLoss"] = np.nan

    return metrics


def bootstrap_metric_cis(
    y_true: np.ndarray,
    y_pred: np.ndarray,
    y_score: Optional[np.ndarray] = None,
    y_proba: Optional[np.ndarray] = None,
    n_bootstrap: int = N_BOOTSTRAP,
) -> Dict[str, Tuple[float, float]]:
    rng = np.random.default_rng(RANDOM_STATE)
    indices = np.arange(len(y_true))
    boot_samples = {metric: [] for metric in METRICS}

    for _ in range(n_bootstrap):
        sampled_idx = rng.choice(indices, size=len(indices), replace=True)
        sampled_metrics = compute_metric_dict(
            y_true[sampled_idx],
            y_pred[sampled_idx],
            None if y_score is None else y_score[sampled_idx],
            None if y_proba is None else y_proba[sampled_idx],
        )
        for metric_name, metric_value in sampled_metrics.items():
            if not pd.isna(metric_value):
                boot_samples[metric_name].append(metric_value)

    intervals = {}
    for metric_name, values in boot_samples.items():
        if not values:
            intervals[metric_name] = (np.nan, np.nan)
        else:
            intervals[metric_name] = (
                float(np.percentile(values, 2.5)),
                float(np.percentile(values, 97.5)),
            )
    return intervals


def as_optional_array(values: np.ndarray) -> Optional[np.ndarray]:
    return None if np.isnan(values).all() else values


def evaluate_on_split(
    method_name: str,
    model_code: str,
    scaler_name: str,
    params: Optional[Dict[str, Any]],
    X_train_input: pd.DataFrame,
    y_train_input: pd.Series,
    X_test_input: pd.DataFrame,
    y_test_input: pd.Series,
) -> Tuple[pd.DataFrame, pd.DataFrame, Pipeline]:
    oof_predictions = np.zeros(len(y_train_input), dtype=int)
    oof_scores = np.full(len(y_train_input), np.nan, dtype=float)
    oof_proba = np.full(len(y_train_input), np.nan, dtype=float)
    fold_rows = []

    for fold_index, (fit_idx, val_idx) in enumerate(CV.split(X_train_input, y_train_input), start=1):
        pipeline = make_pipeline(model_code, params, scaler_name)
        X_fit = X_train_input.iloc[fit_idx]
        y_fit = y_train_input.iloc[fit_idx]
        X_val = X_train_input.iloc[val_idx]
        y_val = y_train_input.iloc[val_idx]

        pipeline.fit(X_fit, y_fit)
        y_pred_fold, y_score_fold, y_proba_fold = get_scores_and_probabilities(pipeline, X_val)

        oof_predictions[val_idx] = y_pred_fold
        if y_score_fold is not None:
            oof_scores[val_idx] = y_score_fold
        if y_proba_fold is not None:
            oof_proba[val_idx] = y_proba_fold

        fold_rows.append(
            {
                "Method": method_name,
                "Model": model_code,
                "Optimal_Scaler": scaler_name,
                "Fold": fold_index,
                **compute_metric_dict(
                    y_val.to_numpy(),
                    y_pred_fold,
                    None if y_score_fold is None else np.asarray(y_score_fold),
                    None if y_proba_fold is None else np.asarray(y_proba_fold),
                ),
            }
        )

    final_pipeline = make_pipeline(model_code, params, scaler_name)
    final_pipeline.fit(X_train_input, y_train_input)
    y_pred_test, y_score_test, y_proba_test = get_scores_and_probabilities(final_pipeline, X_test_input)

    train_metrics = compute_metric_dict(
        y_train_input.to_numpy(),
        oof_predictions,
        as_optional_array(oof_scores),
        as_optional_array(oof_proba),
    )
    test_metrics = compute_metric_dict(
        y_test_input.to_numpy(),
        y_pred_test,
        None if y_score_test is None else np.asarray(y_score_test),
        None if y_proba_test is None else np.asarray(y_proba_test),
    )

    train_ci = bootstrap_metric_cis(
        y_train_input.to_numpy(),
        oof_predictions,
        as_optional_array(oof_scores),
        as_optional_array(oof_proba),
    )
    test_ci = bootstrap_metric_cis(
        y_test_input.to_numpy(),
        y_pred_test,
        None if y_score_test is None else np.asarray(y_score_test),
        None if y_proba_test is None else np.asarray(y_proba_test),
    )

    summary_rows = []
    for split_name, metric_values, ci_values in [("Train_OOF", train_metrics, train_ci), ("Test", test_metrics, test_ci)]:
        row = {
            "Method": method_name,
            "Model": model_code,
            "Optimal_Scaler": scaler_name,
            "Split": split_name,
        }
        row.update(metric_values)
        for metric_name in METRICS:
            row[f"{metric_name}_CI_Lower"] = ci_values[metric_name][0]
            row[f"{metric_name}_CI_Upper"] = ci_values[metric_name][1]
        summary_rows.append(row)

    return pd.DataFrame(fold_rows), pd.DataFrame(summary_rows), final_pipeline


def sample_params_tpe(trial: optuna.trial.Trial, model_code: str) -> Dict[str, Any]:
    sampled = {}
    for param_name, spec in SEARCH_SPACES[model_code].items():
        if spec["type"] == "categorical":
            sampled[param_name] = trial.suggest_categorical(param_name, spec["choices"])
        elif spec["type"] == "int":
            sampled[param_name] = trial.suggest_int(param_name, spec["range"][0], spec["range"][1], log=spec["log"])
        elif spec["type"] == "float":
            sampled[param_name] = trial.suggest_float(param_name, spec["range"][0], spec["range"][1], log=spec["log"])
        else:
            raise ValueError(f"Unsupported parameter type: {spec['type']}")

    if model_code == "LR":
        sampled.update({"solver": "saga", "max_iter": 2000, "random_state": RANDOM_STATE})
    elif model_code == "SGD":
        sampled.update({"max_iter": 2000, "random_state": RANDOM_STATE})
    elif model_code == "LinearSVC":
        sampled.update({"dual": "auto", "max_iter": 5000, "random_state": RANDOM_STATE})
    elif model_code in {"RF", "AdaBoost", "GB", "XGB", "LGBM", "CB"}:
        sampled.update({"random_state": RANDOM_STATE})
    return sampled


def decode_gwo_position(position: np.ndarray, model_code: str) -> Dict[str, Any]:
    params = {}
    for dim_index, (param_name, spec) in enumerate(SEARCH_SPACES[model_code].items()):
        raw_value = float(np.clip(position[dim_index], 0.0, 1.0))
        if spec["type"] == "categorical":
            choices = spec["choices"]
            choice_index = int(round(raw_value * (len(choices) - 1)))
            params[param_name] = choices[min(max(choice_index, 0), len(choices) - 1)]
        elif spec["type"] == "int":
            low, high = spec["range"]
            params[param_name] = int(round(low + raw_value * (high - low)))
        elif spec["type"] == "float":
            low, high = spec["range"]
            if spec["log"]:
                params[param_name] = float(np.exp(np.log(low) + raw_value * (np.log(high) - np.log(low))))
            else:
                params[param_name] = float(low + raw_value * (high - low))
        else:
            raise ValueError(f"Unsupported parameter type: {spec['type']}")

    if model_code == "LR":
        params.update({"solver": "saga", "max_iter": 2000, "random_state": RANDOM_STATE})
    elif model_code == "SGD":
        params.update({"max_iter": 2000, "random_state": RANDOM_STATE})
    elif model_code == "LinearSVC":
        params.update({"dual": "auto", "max_iter": 5000, "random_state": RANDOM_STATE})
    elif model_code in {"RF", "AdaBoost", "GB", "XGB", "LGBM", "CB"}:
        params.update({"random_state": RANDOM_STATE})
    return params


def compare_search_spaces() -> pd.DataFrame:
    rows = []
    for model_code, space in SEARCH_SPACES.items():
        for param_name, spec in space.items():
            rows.append(
                {
                    "Model": model_code,
                    "Hyperparameter": param_name,
                    "Type": spec["type"],
                    "Lower_Bound": None if spec["type"] == "categorical" else spec["range"][0],
                    "Upper_Bound": None if spec["type"] == "categorical" else spec["range"][1],
                    "Choices": None if spec["type"] != "categorical" else "|".join([str(choice) for choice in spec["choices"]]),
                    "Log_Scale": None if spec["type"] == "categorical" else spec["log"],
                }
            )
    return pd.DataFrame(rows)


search_space_df = compare_search_spaces()
search_space_df.to_csv(RESULTS_DIR / "inline_search_space.csv", index=False)
display(search_space_df.head(20))

,Model,Hyperparameter,Type,Lower_Bound,Upper_Bound,Choices,Log_Scale
0,LR,C,float,1.000000e-04,100.000000,None,True
1,LR,penalty,categorical,NaN,NaN,l1|l2,None
2,SGD,loss,categorical,NaN,NaN,log_loss|modified_huber,None
3,SGD,penalty,categorical,NaN,NaN,l1|l2|elasticnet,None
4,SGD,alpha,float,1.000000e-06,0.100000,None,True
5,SGD,l1_ratio,float,0.000000e+00,1.000000,None,False
6,LDA,solver,categorical,NaN,NaN,svd|lsqr|eigen,None
7,QDA,reg_param,float,0.000000e+00,1.000000,None,False
8,NB,var_smoothing,float,1.000000e-12,0.000001,None,True
9,KNN,n_neighbors,int,1.000000e+00,50.000000,None,False
10,KNN,weights,categorical,NaN,NaN,uniform|distance,None
11,KNN,metric,categorical,NaN,NaN,euclidean|manhattan|minkowski,None
12,KNN,p,int,1.000000e+00,5.000000,None,False
13,LinearSVC,C,float,1.000000e-04,100.000000,None,True
14,LinearSVC,loss,categorical,NaN,NaN,hinge|squared_hinge,None
15,SVM,kernel,categorical,NaN,NaN,rbf|poly|sigmoid,None
16,SVM,C,float,1.000000e-03,1000.000000,None,True
17,SVM,gamma,categorical,NaN,NaN,scale|auto,None
18,SVM,degree,int,2.000000e+00,5.000000,None,False
19,SVM,coef0,float,0.000000e+00,1.000000,None,False

## baseline evaluation

In [12]:
baseline_cv_rows = []
baseline_summary_rows = []
baseline_best_scalers = []

print("\n" + "="*80)
print("BASELINE EVALUATION - Scaler Sweep (14 models × 6 scalers)")
print("="*80)
baseline_total_start = time.perf_counter()

for model_idx, model_code in enumerate(MODEL_ORDER, start=1):
    model_start = time.perf_counter()
    print(f"\n[{model_idx:2d}/{len(MODEL_ORDER)}] {model_code:10s} | Scaler Sweep (6 scalers)")
    
    scaler_scores = []
    for scaler_idx, scaler_name in enumerate(SCALER_FACTORIES, start=1):
        with ResourceMonitor(f"  {scaler_name:12s}") as rm:
            pipeline = make_pipeline(model_code, None, scaler_name)
            cv_out = cross_validate(
                pipeline,
                X_train,
                y_train,
                cv=CV,
                scoring="accuracy",
                n_jobs=N_JOBS_CV,
                return_train_score=False,
            )
        fold_scores = cv_out["test_score"]
        scaler_scores.append(
            {
                "Model": model_code,
                "Scaler": scaler_name,
                "Mean": float(np.mean(fold_scores)),
                "Std": float(np.std(fold_scores, ddof=0)),
                **{f"Fold_{index}": float(score) for index, score in enumerate(fold_scores, start=1)},
            }
        )

    scaler_scores_df = pd.DataFrame(scaler_scores).sort_values(["Mean", "Std"], ascending=[False, True])
    best_row = scaler_scores_df.iloc[0].to_dict()
    best_scaler = best_row["Scaler"]
    baseline_best_scalers.append(
        {
            "Model": model_code,
            "Optimal_Scaler": best_scaler,
            "CV_Mean": best_row["Mean"],
            "CV_Std": best_row["Std"],
        }
    )
    baseline_cv_rows.append(scaler_scores_df)

    with ResourceMonitor(f"  Eval {model_code}") as rm:
        fold_df, summary_df, _ = evaluate_on_split(
            method_name="Baseline",
            model_code=model_code,
            scaler_name=best_scaler,
            params=None,
            X_train_input=X_train,
            y_train_input=y_train,
            X_test_input=X_test,
            y_test_input=y_test,
        )
    baseline_summary_rows.append(summary_df)
    
    model_time = time.perf_counter() - model_start
    print(f"       ✓ {model_code} best scaler: {best_scaler:12s} | CV: {best_row['Mean']:.4f} | Time: {model_time:6.1f}s")

baseline_total_time = time.perf_counter() - baseline_total_start

baseline_scaler_grid = pd.concat(baseline_cv_rows, ignore_index=True)
baseline_best_scalers_df = pd.DataFrame(baseline_best_scalers).sort_values("Model")
baseline_results_df = pd.concat(baseline_summary_rows, ignore_index=True).sort_values(["Model", "Split"])

baseline_train_results_df = baseline_results_df[baseline_results_df["Split"] == "Train_OOF"].reset_index(drop=True)
baseline_test_results_df = baseline_results_df[baseline_results_df["Split"] == "Test"].reset_index(drop=True)

baseline_scaler_grid.to_csv(RESULTS_DIR / "baseline_scaler_grid.csv", index=False)
baseline_best_scalers_df.to_csv(RESULTS_DIR / "baseline_optimal_scalers.csv", index=False)
baseline_train_results_df.to_csv(RESULTS_DIR / "baseline_train_results_with_ci.csv", index=False)
baseline_test_results_df.to_csv(RESULTS_DIR / "baseline_test_results_with_ci.csv", index=False)

print("\n" + "="*80)
print(f"Baseline evaluation completed in {baseline_total_time:.1f}s ({baseline_total_time/60:.2f} min)")
print("="*80)
display(baseline_best_scalers_df)
display(baseline_test_results_df[["Method", "Model", "Optimal_Scaler", *METRICS]].sort_values("Accuracy", ascending=False))

================================================================================
BASELINE EVALUATION - Scaler Sweep (14 models × 6 scalers)
================================================================================

[ 1/14] LR         | Scaler Sweep (6 scalers)
  [  Raw         ] Time:    8.30s | Memory Δ:    +5.9MB | Peak:   255.6MB
  [  Standard    ] Time:    0.91s | Memory Δ:    -4.9MB | Peak:   250.8MB
  [  MinMax      ] Time:    1.74s | Memory Δ:    +0.0MB | Peak:   250.8MB
  [  Robust      ] Time:    1.43s | Memory Δ:    +5.8MB | Peak:   256.5MB
  [  Power       ] Time:    5.09s | Memory Δ:    +0.3MB | Peak:   256.8MB
  [  Quantile    ] Time:    1.72s | Memory Δ:    -5.5MB | Peak:   251.3MB
  [  Eval LR] Time:  110.95s | Memory Δ:    +1.1MB | Peak:   252.4MB
       ✓ LR best scaler: Power        | CV: 0.8953 | Time:  130.8s

[ 2/14] LDA        | Scaler Sweep (6 scalers)
  [  Raw         ] Time:    0.33s | Memory Δ:    +6.2MB | Peak:   258.6MB
  [  Standard    ] Time:    0.33s | Memory Δ:    +1.0MB | Peak:   259.6MB
  [  MinMax      ] Time:    0.29s | Memory Δ:    +0.0MB | Peak:   259.6MB
  [  Robust      ] Time:    0.44s | Memory Δ:    +0.0MB | Peak:   259.6MB
  [  Power       ] Time:    2.95s | Memory Δ:    -6.8MB | Peak:   252.7MB
  [  Quantile    ] Time:    1.27s | Memory Δ:    +1.3MB | Peak:   254.0MB
  [  Eval LDA] Time:  109.40s | Memory Δ:    +1.5MB | Peak:   255.6MB
       ✓ LDA best scaler: Power        | CV: 0.8953 | Time:  115.8s

[ 3/14] QDA        | Scaler Sweep (6 scalers)
  [  Raw         ] Time:    0.24s | Memory Δ:    -1.4MB | Peak:   254.1MB
  [  Standard    ] Time:    0.43s | Memory Δ:    +1.2MB | Peak:   255.4MB
  [  MinMax      ] Time:    0.28s | Memory Δ:    -0.0MB | Peak:   255.4MB
  [  Robust      ] Time:    0.38s | Memory Δ:    -0.0MB | Peak:   255.4MB
  [  Power       ] Time:    2.91s | Memory Δ:    -0.0MB | Peak:   255.4MB
  [  Quantile    ] Time:    1.22s | Memory Δ:    +0.4MB | Peak:   255.8MB
  [  Eval QDA] Time:  113.39s | Memory Δ:    -4.9MB | Peak:   250.9MB
       ✓ QDA best scaler: Power        | CV: 0.8924 | Time:  119.6s

[ 4/14] NB         | Scaler Sweep (6 scalers)
  [  Raw         ] Time:    0.10s | Memory Δ:    -1.8MB | Peak:   249.1MB
  [  Standard    ] Time:    0.19s | Memory Δ:    +0.4MB | Peak:   249.5MB
  [  MinMax      ] Time:    0.14s | Memory Δ:    +0.4MB | Peak:   249.8MB
  [  Robust      ] Time:    0.23s | Memory Δ:    +0.0MB | Peak:   249.8MB
  [  Power       ] Time:    2.12s | Memory Δ:    +0.0MB | Peak:   249.8MB
  [  Quantile    ] Time:    1.07s | Memory Δ:    +0.4MB | Peak:   250.2MB
  [  Eval NB] Time:  270.77s | Memory Δ:    -0.6MB | Peak:   249.6MB
       ✓ NB best scaler: Power        | CV: 0.8430 | Time:  275.3s

[ 5/14] KNN        | Scaler Sweep (6 scalers)
  [  Raw         ] Time:   29.68s | Memory Δ:    +0.5MB | Peak:   250.1MB
  [  Standard    ] Time:   42.91s | Memory Δ:    +0.8MB | Peak:   250.9MB
  [  MinMax      ] Time:   27.28s | Memory Δ:    -0.1MB | Peak:   250.8MB
  [  Robust      ] Time:   30.35s | Memory Δ:    -0.0MB | Peak:   250.8MB
  [  Power       ] Time:   45.30s | Memory Δ:    -0.0MB | Peak:   250.8MB
  [  Quantile    ] Time:   53.21s | Memory Δ:    -0.4MB | Peak:   250.4MB
  [  Eval KNN] Time:  278.93s | Memory Δ:    -6.7MB | Peak:   243.7MB
       ✓ KNN best scaler: Raw          | CV: 0.9327 | Time:  508.8s

[ 6/14] LinearSVC  | Scaler Sweep (6 scalers)
  [  Raw         ] Time:    1.69s | Memory Δ:    +2.8MB | Peak:   246.5MB
  [  Standard    ] Time:    1.10s | Memory Δ:    -1.3MB | Peak:   245.2MB
  [  MinMax      ] Time:    1.26s | Memory Δ:    +1.3MB | Peak:   246.5MB
  [  Robust      ] Time:    1.32s | Memory Δ:    -0.0MB | Peak:   246.5MB
  [  Power       ] Time:    6.33s | Memory Δ:    -0.0MB | Peak:   246.5MB
  [  Quantile    ] Time:    2.94s | Memory Δ:    +0.3MB | Peak:   246.8MB
  [  Eval LinearSVC] Time:  243.79s | Memory Δ:   -22.2MB | Peak:   224.6MB
       ✓ LinearSVC best scaler: Power        | CV: 0.8970 | Time:  259.5s

[ 7/14] SVM        | Scaler Sweep (6 scalers)
  [  Raw         ] Time:  991.78s | Memory Δ:  -193.1MB | Peak:    31.6MB
  [  Standard    ] Time:  699.00s | Memory Δ:    +2.9MB | Peak:   147.3MB
  [  MinMax      ] Time:  637.52s | Memory Δ:    +1.0MB | Peak:   148.4MB
  [  Robust      ] Time:  851.17s | Memory Δ:    +1.6MB | Peak:   150.0MB
  [  Power       ] Time: 1257.92s | Memory Δ:  -130.2MB | Peak:    19.8MB
  [  Quantile    ] Time: 1843.23s | Memory Δ:  -104.0MB | Peak:    36.3MB
  [  Eval SVM] Time: 2641.55s | Memory Δ:  -114.9MB | Peak:    38.1MB
       ✓ SVM best scaler: Standard     | CV: 0.9790 | Time: 8925.0s

[ 8/14] AdaBoost   | Scaler Sweep (6 scalers)
  [  Raw         ] Time:   46.52s | Memory Δ:    +9.6MB | Peak:   163.0MB
  [  Standard    ] Time:   57.01s | Memory Δ:    +0.9MB | Peak:   163.9MB
  [  MinMax      ] Time:   59.94s | Memory Δ:    +0.0MB | Peak:   164.0MB
  [  Robust      ] Time:   59.28s | Memory Δ:    +0.1MB | Peak:   164.1MB
  [  Power       ] Time:   60.76s | Memory Δ:    -0.5MB | Peak:   163.6MB
  [  Quantile    ] Time:   54.25s | Memory Δ:    +2.4MB | Peak:   166.0MB
  [  Eval AdaBoost] Time:  387.54s | Memory Δ:    -9.2MB | Peak:   157.2MB
       ✓ AdaBoost best scaler: Raw          | CV: 0.8876 | Time:  726.5s

[ 9/14] RF         | Scaler Sweep (6 scalers)
  [  Raw         ] Time:   58.53s | Memory Δ:   +96.7MB | Peak:   254.0MB
  [  Standard    ] Time:   72.08s | Memory Δ:    -6.4MB | Peak:   247.7MB
  [  MinMax      ] Time:   58.36s | Memory Δ:   +93.2MB | Peak:   250.3MB
  [  Robust      ] Time:   51.75s | Memory Δ:    +1.6MB | Peak:   251.8MB
  [  Power       ] Time:   64.03s | Memory Δ:    +1.3MB | Peak:   253.1MB
  [  Quantile    ] Time:   57.65s | Memory Δ:    -3.4MB | Peak:   249.8MB
  [  Eval RF] Time:  471.15s | Memory Δ:  -100.8MB | Peak:   149.0MB
       ✓ RF best scaler: MinMax       | CV: 0.9600 | Time:  835.0s

[10/14] GB         | Scaler Sweep (6 scalers)
  [  Raw         ] Time:  323.25s | Memory Δ:   +20.4MB | Peak:   188.6MB
  [  Standard    ] Time:  331.13s | Memory Δ:    +0.2MB | Peak:   188.8MB
  [  MinMax      ] Time:  240.82s | Memory Δ:    -2.4MB | Peak:   186.5MB
  [  Robust      ] Time:  215.15s | Memory Δ:  -126.8MB | Peak:    59.7MB
  [  Power       ] Time:  201.13s | Memory Δ:    +3.0MB | Peak:   179.3MB
  [  Quantile    ] Time:  149.53s | Memory Δ:    +2.4MB | Peak:   181.6MB
  [  Eval GB] Time:  326.27s | Memory Δ:   -29.1MB | Peak:   153.1MB
       ✓ GB best scaler: Raw          | CV: 0.9226 | Time: 1789.6s

[11/14] XGB        | Scaler Sweep (6 scalers)
  [  Raw         ] Time:   16.39s | Memory Δ:   +27.8MB | Peak:   180.9MB
  [  Standard    ] Time:   11.99s | Memory Δ:    +2.5MB | Peak:   183.4MB
  [  MinMax      ] Time:   12.91s | Memory Δ:    +0.1MB | Peak:   183.6MB
  [  Robust      ] Time:    9.23s | Memory Δ:    +0.1MB | Peak:   183.7MB
  [  Power       ] Time:   14.05s | Memory Δ:   -20.3MB | Peak:   163.4MB
  [  Quantile    ] Time:   14.11s | Memory Δ:   +22.7MB | Peak:   186.1MB
  [  Eval XGB] Time:  140.41s | Memory Δ:   -20.2MB | Peak:   165.9MB
       ✓ XGB best scaler: MinMax       | CV: 0.9690 | Time:  220.0s

[12/14] LGBM       | Scaler Sweep (6 scalers)
  [  Raw         ] Time:    8.29s | Memory Δ:   +17.8MB | Peak:   183.7MB
  [  Standard    ] Time:    8.58s | Memory Δ:    +2.2MB | Peak:   185.9MB
  [  MinMax      ] Time:    8.59s | Memory Δ:    +0.4MB | Peak:   186.2MB
  [  Robust      ] Time:    9.15s | Memory Δ:    +2.1MB | Peak:   188.4MB
  [  Power       ] Time:   13.29s | Memory Δ:    +0.9MB | Peak:   189.3MB
  [  Quantile    ] Time:   10.88s | Memory Δ:    +2.7MB | Peak:   192.0MB
  [  Eval LGBM] Time:  135.88s | Memory Δ:   -21.9MB | Peak:   170.0MB
       ✓ LGBM best scaler: Raw          | CV: 0.9677 | Time:  195.6s

[13/14] CB         | Scaler Sweep (6 scalers)
  [  Raw         ] Time:    6.61s | Memory Δ:   +24.8MB | Peak:   190.2MB
  [  Standard    ] Time:    6.55s | Memory Δ:    +1.9MB | Peak:   192.0MB
  [  MinMax      ] Time:    6.60s | Memory Δ:    +0.2MB | Peak:   192.3MB
  [  Robust      ] Time:    6.83s | Memory Δ:    +0.3MB | Peak:   192.6MB
  [  Power       ] Time:    9.09s | Memory Δ:   -11.6MB | Peak:   181.0MB
  [  Quantile    ] Time:    7.08s | Memory Δ:   +16.2MB | Peak:   192.5MB
  [  Eval CB] Time:  138.73s | Memory Δ:    -9.3MB | Peak:   183.1MB
       ✓ CB best scaler: MinMax       | CV: 0.9393 | Time:  182.3s

[14/14] SGD        | Scaler Sweep (6 scalers)
  [  Raw         ] Time:    2.30s | Memory Δ:    +5.1MB | Peak:   188.2MB
  [  Standard    ] Time:    1.07s | Memory Δ:    +1.5MB | Peak:   189.7MB
  [  MinMax      ] Time:    0.65s | Memory Δ:    +0.0MB | Peak:   189.7MB
  [  Robust      ] Time:    0.96s | Memory Δ:    +0.0MB | Peak:   189.7MB
  [  Power       ] Time:    3.74s | Memory Δ:    +0.9MB | Peak:   190.5MB
  [  Quantile    ] Time:    1.88s | Memory Δ:    +3.1MB | Peak:   193.6MB
  [  Eval SGD] Time:  128.90s | Memory Δ:   -13.8MB | Peak:   179.8MB
       ✓ SGD best scaler: Power        | CV: 0.8913 | Time:  140.3s

================================================================================
Baseline evaluation completed in 14424.1s (240.40 min)
================================================================================

        Model Optimal_Scaler   CV_Mean    CV_Std
7    AdaBoost            Raw  0.887562  0.007040
12         CB         MinMax  0.939271  0.001707
9          GB            Raw  0.922583  0.003934
4         KNN            Raw  0.932667  0.002626
1         LDA          Power  0.895312  0.002253
11       LGBM            Raw  0.967750  0.001915
0          LR          Power  0.895271  0.003145
5   LinearSVC          Power  0.897000  0.002657
3          NB          Power  0.843042  0.001900
2         QDA          Power  0.892437  0.001838
8          RF         MinMax  0.959979  0.002021
13        SGD          Power  0.891271  0.002202
6         SVM       Standard  0.979021  0.001402
10        XGB         MinMax  0.969021  0.002839

,Method,Model,Optimal_Scaler,Accuracy,Precision,Recall,F1,AUC,LogLoss,Kappa,MCC
12,Baseline,SVM,Standard,0.982333,0.984635,0.987722,0.986176,0.998714,0.043883,0.961707,0.961716
13,Baseline,XGB,MinMax,0.972083,0.971896,0.984718,0.978265,0.997072,0.104082,0.939257,0.939415
5,Baseline,LGBM,Raw,0.971083,0.971488,0.983542,0.977478,0.996897,0.106920,0.937100,0.937239
10,Baseline,RF,MinMax,0.969000,0.967402,0.984587,0.975919,0.996245,0.138566,0.932430,0.932715
1,Baseline,CB,MinMax,0.942583,0.945745,0.965387,0.955465,0.988919,0.171676,0.874706,0.875072
3,Baseline,KNN,Raw,0.939417,0.946514,0.959248,0.952838,0.982171,0.245021,0.868166,0.868318
2,Baseline,GB,Raw,0.926250,0.928490,0.958203,0.943112,0.982510,0.204890,0.838366,0.839206
7,Baseline,LinearSVC,Power,0.905167,0.917928,0.934953,0.926362,0.968560,NaN,0.793232,0.793496
4,Baseline,LDA,Power,0.903500,0.917287,0.932863,0.925010,0.967520,0.234272,0.789725,0.789945
6,Baseline,LR,Power,0.903083,0.915525,0.934300,0.924817,0.968221,0.220371,0.788531,0.788852
9,Baseline,QDA,Power,0.901583,0.910486,0.937957,0.924017,0.965135,0.251091,0.784457,0.785155
11,Baseline,SGD,Power,0.895583,0.915078,0.921891,0.918472,0.963230,0.236267,0.773303,0.773345
0,Baseline,AdaBoost,Raw,0.893500,0.904285,0.931688,0.917782,0.960154,0.521496,0.766742,0.767430
8,Baseline,NB,Power,0.847500,0.887986,0.870820,0.879319,0.927360,0.349683,0.672266,0.672502

## 🔁 Recovery Cells
Run these cells **after a kernel restart** to continue optimization without rerunning expensive feature selection or baseline sweep.

| Cell | Restores |
|---|---|
| Recovery 1 | `df`, `y`, `X_raw`, `X_engineered`, `X_train_full`, `X_test_full`, `y_train`, `y_test`, `selected_features`, `X_train`, `X_test` |
| Recovery 2 | `baseline_best_scalers_df` (loaded from `baseline_optimal_scalers.csv`) |
| Optimization shared helpers | all utility functions required by TPE/GWO resume, including model/scaler builders, samplers, metrics, and `evaluate_on_split` |

After a restart, run in this order:
1. setup/imports
2. system resource setup
3. Recovery 1
4. Recovery 2
5. optimization shared helpers
6. the TPE or GWO model cell you want to continue

In [30]:
# ============================================================
# RECOVERY 1 — Data split + selected features (no recomputation)
# Prerequisite: setup cell (imports + constants)
# ============================================================

def engineer_features(X: pd.DataFrame) -> pd.DataFrame:
    X = X.copy()
    tau_cols = ["tau1", "tau2", "tau3", "tau4"]
    g_cols   = ["g1",  "g2",  "g3",  "g4"]
    X["tau_mean"]    = X[tau_cols].mean(axis=1)
    X["g_sum"]       = X[g_cols].sum(axis=1)
    X["tau1_g1"]     = X["tau1"] * X["g1"]
    X["tau2_g2"]     = X["tau2"] * X["g2"]
    X["tau3_g3"]     = X["tau3"] * X["g3"]
    X["tau4_g4"]     = X["tau4"] * X["g4"]
    X["g_tau_ratio"] = X["g_sum"] / (X["tau_mean"] + 1e-5)
    return X

df           = pd.read_csv(DATA_PATH)
y            = (df[TARGET_COLUMN] == "unstable").astype(int)
X_raw        = df.drop(columns=[TARGET_COLUMN, LEAKAGE_COLUMN])
X_engineered = engineer_features(X_raw)

X_train_full, X_test_full, y_train, y_test = train_test_split(
    X_engineered, y, test_size=TEST_SIZE, stratify=y, random_state=RANDOM_STATE
)

# Load from saved artifact — skips expensive consensus_feature_selection()
_sf_path = RESULTS_DIR / "selected_features.csv"
selected_features = pd.read_csv(_sf_path)["feature"].dropna().astype(str).tolist()

_missing = [f for f in selected_features if f not in X_train_full.columns]
if _missing:
    raise ValueError(f"[Recovery] Features missing from engineered matrix: {_missing}")

X_train = X_train_full[selected_features].copy()
X_test  = X_test_full[selected_features].copy()

assert len(X_train) == 48000 and len(X_test) == 12000
print(f"[Recovery 1] train={X_train.shape}  test={X_test.shape}  features={len(selected_features)}")

[Recovery 1] train=(48000, 13)  test=(12000, 13)  features=13

In [31]:
# ============================================================
# RECOVERY 2 — Restore only scaler map needed by optimization
# Prerequisite: setup cell
# ============================================================

baseline_best_scalers_df = pd.read_csv(RESULTS_DIR / "baseline_optimal_scalers.csv")

required_cols = {"Model", "Optimal_Scaler"}
missing_cols = required_cols - set(baseline_best_scalers_df.columns)
if missing_cols:
    raise KeyError(f"baseline_optimal_scalers.csv missing required columns: {sorted(missing_cols)}")

baseline_best_scalers_df = baseline_best_scalers_df.sort_values("Model").reset_index(drop=True)

print(f"[Recovery 2] Restored baseline_best_scalers_df with {len(baseline_best_scalers_df)} models")
display(baseline_best_scalers_df)

[Recovery 2] Restored baseline_best_scalers_df with 14 models

        Model Optimal_Scaler   CV_Mean    CV_Std
0    AdaBoost            Raw  0.887562  0.007040
1          CB         MinMax  0.939271  0.001707
2          GB            Raw  0.922583  0.003934
3         KNN            Raw  0.932667  0.002626
4         LDA          Power  0.895312  0.002253
5        LGBM            Raw  0.967750  0.001915
6          LR          Power  0.895271  0.003145
7   LinearSVC          Power  0.897000  0.002657
8          NB          Power  0.843042  0.001900
9         QDA          Power  0.892437  0.001838
10         RF         MinMax  0.959979  0.002021
11        SGD          Power  0.891271  0.002202
12        SVM       Standard  0.979021  0.001402
13        XGB         MinMax  0.969021  0.002839

## optimization shared helpers

In [32]:
# Recovery shim: define optimization dependencies if utility cell was not run.

if "get_scaler" not in globals():
    def get_scaler(scaler_name: str):
        factory = SCALER_FACTORIES[scaler_name]
        return None if factory is None or scaler_name == "Raw" else factory()

if "build_model" not in globals():
    def build_model(model_code: str, params: Optional[Dict[str, Any]] = None):
        params = dict(params or {})

        if model_code == "LR":
            penalty = params.pop("penalty", "l2")
            solver = params.pop("solver", "saga")
            if penalty == "l1" and solver not in {"liblinear", "saga"}:
                solver = "saga"
            return LogisticRegression(
                C=params.pop("C", 1.0),
                penalty=penalty,
                solver=solver,
                max_iter=params.pop("max_iter", 2000),
                random_state=params.pop("random_state", RANDOM_STATE),
                **params,
            )

        if model_code == "LDA":
            solver = params.pop("solver", "svd")
            shrinkage = params.pop("shrinkage", None)
            if solver == "svd":
                return LinearDiscriminantAnalysis(solver=solver, **params)
            return LinearDiscriminantAnalysis(solver=solver, shrinkage=shrinkage, **params)

        if model_code == "QDA":
            return QuadraticDiscriminantAnalysis(reg_param=params.pop("reg_param", 0.0), **params)

        if model_code == "NB":
            return GaussianNB(var_smoothing=params.pop("var_smoothing", 1e-9), **params)

        if model_code == "KNN":
            return KNeighborsClassifier(
                n_neighbors=params.pop("n_neighbors", 5),
                weights=params.pop("weights", "uniform"),
                metric=params.pop("metric", "minkowski"),
                p=params.pop("p", 2),
                **params,
            )

        if model_code == "LinearSVC":
            return LinearSVC(
                C=params.pop("C", 1.0),
                loss=params.pop("loss", "squared_hinge"),
                dual=params.pop("dual", "auto"),
                max_iter=params.pop("max_iter", 5000),
                random_state=params.pop("random_state", RANDOM_STATE),
                **params,
            )

        if model_code == "SVM":
            return SVC(
                kernel=params.pop("kernel", "rbf"),
                C=params.pop("C", 1.0),
                gamma=params.pop("gamma", "scale"),
                degree=params.pop("degree", 3),
                coef0=params.pop("coef0", 0.0),
                probability=True,
                random_state=RANDOM_STATE,
                **params,
            )

        if model_code == "AdaBoost":
            algorithm = params.pop("algorithm", "SAMME")
            if algorithm == "SAMME.R":
                algorithm = "SAMME"
            return AdaBoostClassifier(
                n_estimators=params.pop("n_estimators", 50),
                learning_rate=params.pop("learning_rate", 1.0),
                algorithm=algorithm,
                random_state=params.pop("random_state", RANDOM_STATE),
                **params,
            )

        if model_code == "RF":
            max_features = params.pop("max_features", "sqrt")
            if max_features == "None":
                max_features = None
            return RandomForestClassifier(
                n_estimators=params.pop("n_estimators", 100),
                max_depth=params.pop("max_depth", None),
                min_samples_split=params.pop("min_samples_split", 2),
                min_samples_leaf=params.pop("min_samples_leaf", 1),
                max_features=max_features,
                random_state=params.pop("random_state", RANDOM_STATE),
                n_jobs=N_JOBS_OPT,
                **params,
            )

        if model_code == "GB":
            return GradientBoostingClassifier(
                n_estimators=params.pop("n_estimators", 100),
                learning_rate=params.pop("learning_rate", 0.1),
                max_depth=params.pop("max_depth", 3),
                min_samples_split=params.pop("min_samples_split", 2),
                min_samples_leaf=params.pop("min_samples_leaf", 1),
                subsample=params.pop("subsample", 1.0),
                random_state=params.pop("random_state", RANDOM_STATE),
                **params,
            )

        if model_code == "XGB":
            return xgb.XGBClassifier(
                n_estimators=params.pop("n_estimators", 100),
                learning_rate=params.pop("learning_rate", 0.1),
                max_depth=params.pop("max_depth", 6),
                min_child_weight=params.pop("min_child_weight", 1),
                subsample=params.pop("subsample", 1.0),
                colsample_bytree=params.pop("colsample_bytree", 1.0),
                gamma=params.pop("gamma", 0.0),
                reg_alpha=params.pop("reg_alpha", 0.0),
                reg_lambda=params.pop("reg_lambda", 1.0),
                eval_metric="logloss",
                random_state=params.pop("random_state", RANDOM_STATE),
                n_jobs=N_JOBS_OPT,
                verbosity=0,
                **params,
            )

        if model_code == "LGBM":
            return lgb.LGBMClassifier(
                n_estimators=params.pop("n_estimators", 100),
                learning_rate=params.pop("learning_rate", 0.1),
                max_depth=params.pop("max_depth", -1),
                num_leaves=params.pop("num_leaves", 31),
                min_child_samples=params.pop("min_child_samples", 20),
                subsample=params.pop("subsample", 1.0),
                colsample_bytree=params.pop("colsample_bytree", 1.0),
                reg_alpha=params.pop("reg_alpha", 0.0),
                reg_lambda=params.pop("reg_lambda", 0.0),
                random_state=params.pop("random_state", RANDOM_STATE),
                verbose=-1,
                n_jobs=N_JOBS_OPT,
                **params,
            )

        if model_code == "CB":
            return CatBoostClassifier(
                iterations=params.pop("iterations", 100),
                learning_rate=params.pop("learning_rate", 0.1),
                depth=params.pop("depth", 6),
                l2_leaf_reg=params.pop("l2_leaf_reg", 3.0),
                border_count=params.pop("border_count", 128),
                bagging_temperature=params.pop("bagging_temperature", 0.0),
                random_seed=params.pop("random_state", RANDOM_STATE),
                verbose=0,
                allow_writing_files=False,
                **params,
            )

        if model_code == "SGD":
            return SGDClassifier(
                loss=params.pop("loss", "log_loss"),
                penalty=params.pop("penalty", "l2"),
                alpha=params.pop("alpha", 1e-4),
                l1_ratio=params.pop("l1_ratio", 0.15),
                max_iter=params.pop("max_iter", 2000),
                random_state=params.pop("random_state", RANDOM_STATE),
                **params,
            )

        raise ValueError(f"Unsupported model code: {model_code}")

if "make_pipeline" not in globals():
    def make_pipeline(model_code: str, params: Optional[Dict[str, Any]], scaler_name: str) -> Pipeline:
        steps = []
        scaler = get_scaler(scaler_name)
        if scaler is not None:
            steps.append(("scaler", scaler))
        steps.append(("model", build_model(model_code, params)))
        return Pipeline(steps)

if "get_scores_and_probabilities" not in globals():
    def get_scores_and_probabilities(fitted_pipeline: Pipeline, X_input: pd.DataFrame) -> Tuple[np.ndarray, Optional[np.ndarray], Optional[np.ndarray]]:
        y_pred = fitted_pipeline.predict(X_input)
        y_proba = None
        y_score = None
        if hasattr(fitted_pipeline, "predict_proba"):
            y_proba = fitted_pipeline.predict_proba(X_input)[:, 1]
            y_score = y_proba.copy()
        elif hasattr(fitted_pipeline, "decision_function"):
            y_score = fitted_pipeline.decision_function(X_input)
        return y_pred, y_score, y_proba

if "compute_metric_dict" not in globals():
    def compute_metric_dict(
        y_true: np.ndarray,
        y_pred: np.ndarray,
        y_score: Optional[np.ndarray] = None,
        y_proba: Optional[np.ndarray] = None,
    ) -> Dict[str, float]:
        metrics = {
            "Accuracy": float(accuracy_score(y_true, y_pred)),
            "Precision": float(precision_score(y_true, y_pred, zero_division=0)),
            "Recall": float(recall_score(y_true, y_pred, zero_division=0)),
            "F1": float(f1_score(y_true, y_pred, zero_division=0)),
            "Kappa": float(cohen_kappa_score(y_true, y_pred)),
            "MCC": float(matthews_corrcoef(y_true, y_pred)),
            "AUC": np.nan,
            "LogLoss": np.nan,
        }

        if y_score is not None and len(np.unique(y_true)) > 1:
            try:
                metrics["AUC"] = float(roc_auc_score(y_true, y_score))
            except ValueError:
                metrics["AUC"] = np.nan

        if y_proba is not None and len(np.unique(y_true)) > 1:
            try:
                clipped = np.clip(y_proba, 1e-12, 1 - 1e-12)
                metrics["LogLoss"] = float(log_loss(y_true, clipped))
            except ValueError:
                metrics["LogLoss"] = np.nan

        return metrics

if "bootstrap_metric_cis" not in globals():
    def bootstrap_metric_cis(
        y_true: np.ndarray,
        y_pred: np.ndarray,
        y_score: Optional[np.ndarray] = None,
        y_proba: Optional[np.ndarray] = None,
        n_bootstrap: int = N_BOOTSTRAP,
    ) -> Dict[str, Tuple[float, float]]:
        rng = np.random.default_rng(RANDOM_STATE)
        indices = np.arange(len(y_true))
        boot_samples = {metric: [] for metric in METRICS}

        for _ in range(n_bootstrap):
            sampled_idx = rng.choice(indices, size=len(indices), replace=True)
            sampled_metrics = compute_metric_dict(
                y_true[sampled_idx],
                y_pred[sampled_idx],
                None if y_score is None else y_score[sampled_idx],
                None if y_proba is None else y_proba[sampled_idx],
            )
            for metric_name, metric_value in sampled_metrics.items():
                if not pd.isna(metric_value):
                    boot_samples[metric_name].append(metric_value)

        intervals = {}
        for metric_name, values in boot_samples.items():
            if not values:
                intervals[metric_name] = (np.nan, np.nan)
            else:
                intervals[metric_name] = (
                    float(np.percentile(values, 2.5)),
                    float(np.percentile(values, 97.5)),
                )
        return intervals

if "as_optional_array" not in globals():
    def as_optional_array(values: np.ndarray) -> Optional[np.ndarray]:
        return None if np.isnan(values).all() else values

if "evaluate_on_split" not in globals():
    def evaluate_on_split(
        method_name: str,
        model_code: str,
        scaler_name: str,
        params: Optional[Dict[str, Any]],
        X_train_input: pd.DataFrame,
        y_train_input: pd.Series,
        X_test_input: pd.DataFrame,
        y_test_input: pd.Series,
    ) -> Tuple[pd.DataFrame, pd.DataFrame, Pipeline]:
        oof_predictions = np.zeros(len(y_train_input), dtype=int)
        oof_scores = np.full(len(y_train_input), np.nan, dtype=float)
        oof_proba = np.full(len(y_train_input), np.nan, dtype=float)
        fold_rows = []

        for fold_index, (fit_idx, val_idx) in enumerate(CV.split(X_train_input, y_train_input), start=1):
            pipeline = make_pipeline(model_code, params, scaler_name)
            X_fit = X_train_input.iloc[fit_idx]
            y_fit = y_train_input.iloc[fit_idx]
            X_val = X_train_input.iloc[val_idx]
            y_val = y_train_input.iloc[val_idx]

            pipeline.fit(X_fit, y_fit)
            y_pred_fold, y_score_fold, y_proba_fold = get_scores_and_probabilities(pipeline, X_val)

            oof_predictions[val_idx] = y_pred_fold
            if y_score_fold is not None:
                oof_scores[val_idx] = y_score_fold
            if y_proba_fold is not None:
                oof_proba[val_idx] = y_proba_fold

            fold_rows.append(
                {
                    "Method": method_name,
                    "Model": model_code,
                    "Optimal_Scaler": scaler_name,
                    "Fold": fold_index,
                    **compute_metric_dict(
                        y_val.to_numpy(),
                        y_pred_fold,
                        None if y_score_fold is None else np.asarray(y_score_fold),
                        None if y_proba_fold is None else np.asarray(y_proba_fold),
                    ),
                }
            )

        final_pipeline = make_pipeline(model_code, params, scaler_name)
        final_pipeline.fit(X_train_input, y_train_input)
        y_pred_test, y_score_test, y_proba_test = get_scores_and_probabilities(final_pipeline, X_test_input)

        train_metrics = compute_metric_dict(
            y_train_input.to_numpy(),
            oof_predictions,
            as_optional_array(oof_scores),
            as_optional_array(oof_proba),
        )
        test_metrics = compute_metric_dict(
            y_test_input.to_numpy(),
            y_pred_test,
            None if y_score_test is None else np.asarray(y_score_test),
            None if y_proba_test is None else np.asarray(y_proba_test),
        )

        train_ci = bootstrap_metric_cis(
            y_train_input.to_numpy(),
            oof_predictions,
            as_optional_array(oof_scores),
            as_optional_array(oof_proba),
        )
        test_ci = bootstrap_metric_cis(
            y_test_input.to_numpy(),
            y_pred_test,
            None if y_score_test is None else np.asarray(y_score_test),
            None if y_proba_test is None else np.asarray(y_proba_test),
        )

        summary_rows = []
        for split_name, metric_values, ci_values in [("Train_OOF", train_metrics, train_ci), ("Test", test_metrics, test_ci)]:
            row = {
                "Method": method_name,
                "Model": model_code,
                "Optimal_Scaler": scaler_name,
                "Split": split_name,
            }
            row.update(metric_values)
            for metric_name in METRICS:
                row[f"{metric_name}_CI_Lower"] = ci_values[metric_name][0]
                row[f"{metric_name}_CI_Upper"] = ci_values[metric_name][1]
            summary_rows.append(row)

        return pd.DataFrame(fold_rows), pd.DataFrame(summary_rows), final_pipeline

if "sample_params_tpe" not in globals():
    def sample_params_tpe(trial: optuna.trial.Trial, model_code: str) -> Dict[str, Any]:
        sampled = {}
        for param_name, spec in SEARCH_SPACES[model_code].items():
            if spec["type"] == "categorical":
                sampled[param_name] = trial.suggest_categorical(param_name, spec["choices"])
            elif spec["type"] == "int":
                sampled[param_name] = trial.suggest_int(param_name, spec["range"][0], spec["range"][1], log=spec["log"])
            elif spec["type"] == "float":
                sampled[param_name] = trial.suggest_float(param_name, spec["range"][0], spec["range"][1], log=spec["log"])
            else:
                raise ValueError(f"Unsupported parameter type: {spec['type']}")

        if model_code == "LR":
            sampled.update({"solver": "saga", "max_iter": 2000, "random_state": RANDOM_STATE})
        elif model_code == "SGD":
            sampled.update({"max_iter": 2000, "random_state": RANDOM_STATE})
        elif model_code == "LinearSVC":
            sampled.update({"dual": "auto", "max_iter": 5000, "random_state": RANDOM_STATE})
        elif model_code in {"RF", "AdaBoost", "GB", "XGB", "LGBM", "CB"}:
            sampled.update({"random_state": RANDOM_STATE})
        return sampled

if "decode_gwo_position" not in globals():
    def decode_gwo_position(position: np.ndarray, model_code: str) -> Dict[str, Any]:
        params = {}
        for dim_index, (param_name, spec) in enumerate(SEARCH_SPACES[model_code].items()):
            raw_value = float(np.clip(position[dim_index], 0.0, 1.0))
            if spec["type"] == "categorical":
                choices = spec["choices"]
                choice_index = int(round(raw_value * (len(choices) - 1)))
                params[param_name] = choices[min(max(choice_index, 0), len(choices) - 1)]
            elif spec["type"] == "int":
                low, high = spec["range"]
                params[param_name] = int(round(low + raw_value * (high - low)))
            elif spec["type"] == "float":
                low, high = spec["range"]
                if spec["log"]:
                    params[param_name] = float(np.exp(np.log(low) + raw_value * (np.log(high) - np.log(low))))
                else:
                    params[param_name] = float(low + raw_value * (high - low))
            else:
                raise ValueError(f"Unsupported parameter type: {spec['type']}")

        if model_code == "LR":
            params.update({"solver": "saga", "max_iter": 2000, "random_state": RANDOM_STATE})
        elif model_code == "SGD":
            params.update({"max_iter": 2000, "random_state": RANDOM_STATE})
        elif model_code == "LinearSVC":
            params.update({"dual": "auto", "max_iter": 5000, "random_state": RANDOM_STATE})
        elif model_code in {"RF", "AdaBoost", "GB", "XGB", "LGBM", "CB"}:
            params.update({"random_state": RANDOM_STATE})
        return params

print("Optimization recovery shim ready: model/scaler builders, samplers, metrics, and evaluate_on_split restored.")

Optimization recovery shim ready: model/scaler builders, samplers, metrics, and evaluate_on_split restored.

In [33]:
CHECKPOINT_DIR = RESULTS_DIR / "checkpoints"
CHECKPOINT_DIR.mkdir(parents=True, exist_ok=True)
PROGRESS_LOG = RESULTS_DIR / "optimization_progress.json"

FIXED_N_JOBS_CV = N_JOBS_CV
FIXED_N_JOBS_OPT = N_JOBS_OPT


def load_progress_log() -> Dict[str, Dict[str, str]]:
    if PROGRESS_LOG.exists():
        return json.loads(PROGRESS_LOG.read_text())
    return {}


def save_progress_log(log: Dict[str, Dict[str, str]]) -> None:
    with open(PROGRESS_LOG, "w", encoding="utf-8") as handle:
        json.dump(log, handle, indent=2)


def refresh_memory_snapshot() -> Dict[str, float]:
    vm = psutil.virtual_memory()
    return {
        "available_gb": float(vm.available / (1024**3)),
        "used_percent": float(vm.percent),
        "process_mb": float(psutil.Process(os.getpid()).memory_info().rss / (1024**2)),
    }


def enforce_fair_resource_policy() -> None:
    global N_JOBS_CV, N_JOBS_OPT
    N_JOBS_CV = FIXED_N_JOBS_CV
    N_JOBS_OPT = FIXED_N_JOBS_OPT


def collect_runtime_garbage() -> None:
    gc.collect()


def method_paths(method_name: str) -> Dict[str, Path]:
    prefix = method_name.lower()
    return {
        "best": RESULTS_DIR / f"{prefix}_best_params.csv",
        "history": RESULTS_DIR / f"{prefix}_trials_full.csv",
        "train": RESULTS_DIR / f"{prefix}_train_results_with_ci.csv",
        "test": RESULTS_DIR / f"{prefix}_test_results_with_ci.csv",
        "timing": RESULTS_DIR / f"{prefix}_timing_per_model.csv",
    }


def load_existing_method_outputs(method_name: str) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    paths = method_paths(method_name)
    best_df = pd.read_csv(paths["best"]) if paths["best"].exists() else pd.DataFrame()
    history_df = pd.read_csv(paths["history"]) if paths["history"].exists() else pd.DataFrame()
    timing_df = pd.read_csv(paths["timing"]) if paths["timing"].exists() else pd.DataFrame()

    result_frames = []
    if paths["train"].exists():
        result_frames.append(pd.read_csv(paths["train"]))
    if paths["test"].exists():
        result_frames.append(pd.read_csv(paths["test"]))
    results_df = pd.concat(result_frames, ignore_index=True) if result_frames else pd.DataFrame()
    return best_df, history_df, results_df, timing_df


def deduplicate_rows(df: pd.DataFrame, subset: List[str]) -> pd.DataFrame:
    if df.empty:
        return df
    available_subset = [column for column in subset if column in df.columns]
    if not available_subset:
        return df
    return df.drop_duplicates(subset=available_subset, keep="last").reset_index(drop=True)


def save_model_checkpoint(method_name: str, model_code: str, payload: Dict[str, Any]) -> None:
    checkpoint_file = CHECKPOINT_DIR / f"{method_name.lower()}_{model_code}.json"
    with open(checkpoint_file, "w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2, default=str)


def export_method_outputs(
    method_name: str,
    best_df: pd.DataFrame,
    history_df: pd.DataFrame,
    results_df: pd.DataFrame,
    timing_df: pd.DataFrame,
    print_status: bool = False,
) -> None:
    paths = method_paths(method_name)
    if not best_df.empty:
        best_df.sort_values("Model").to_csv(paths["best"], index=False)
    if not history_df.empty:
        history_df.to_csv(paths["history"], index=False)
    if not results_df.empty:
        results_df[results_df["Split"] == "Train_OOF"].to_csv(paths["train"], index=False)
        results_df[results_df["Split"] == "Test"].to_csv(paths["test"], index=False)
    if not timing_df.empty:
        timing_df.sort_values("Model").to_csv(paths["timing"], index=False)
    if print_status:
        print(f"       Exported {method_name} artifacts")


def objective_from_params(model_code: str, scaler_name: str, params: Dict[str, Any]) -> float:
    enforce_fair_resource_policy()
    pipeline = make_pipeline(model_code, params, scaler_name)
    cv_out = cross_validate(
        pipeline,
        X_train,
        y_train,
        cv=CV,
        scoring="accuracy",
        n_jobs=N_JOBS_CV,
        return_train_score=False,
    )
    return float(np.mean(cv_out["test_score"]))


def run_tpe_for_model(model_code: str, scaler_name: str) -> Tuple[Dict[str, Any], pd.DataFrame]:
    trial_rows = []
    best_so_far = -np.inf

    def objective(trial: optuna.trial.Trial) -> float:
        start_time = time.perf_counter()
        params = sample_params_tpe(trial, model_code)
        score = objective_from_params(model_code, scaler_name, params)
        runtime_sec = float(time.perf_counter() - start_time)
        trial.set_user_attr("runtime_sec", runtime_sec)
        return score

    sampler = optuna.samplers.TPESampler(seed=RANDOM_STATE)
    study = optuna.create_study(direction="maximize", sampler=sampler)

    def callback(study_obj: optuna.Study, frozen_trial: optuna.trial.FrozenTrial) -> None:
        nonlocal best_so_far
        if frozen_trial.value is None:
            return
        best_so_far = max(best_so_far, float(frozen_trial.value))
        trial_rows.append(
            {
                "Model": model_code,
                "Trial": len(trial_rows) + 1,
                "CV_Mean": float(frozen_trial.value),
                "Best_Score_So_Far": best_so_far,
                "Trial_Runtime_Sec": float(frozen_trial.user_attrs.get("runtime_sec", np.nan)),
            }
        )

    study.optimize(objective, n_trials=N_TRIALS_PER_MODEL, callbacks=[callback], show_progress_bar=False)
    return {
        "Model": model_code,
        "Optimal_Scaler": scaler_name,
        "Best_CV_Mean": float(study.best_value),
        "Best_Trial": int(study.best_trial.number),
        **study.best_trial.params,
    }, pd.DataFrame(trial_rows)


def run_gwo_for_model(model_code: str, scaler_name: str) -> Tuple[Dict[str, Any], pd.DataFrame]:
    rng = np.random.default_rng(RANDOM_STATE)
    dim = len(SEARCH_SPACES[model_code])
    wolves = rng.random((GWO_POPULATION_SIZE, dim))

    alpha_pos   = np.zeros(dim)
    beta_pos    = np.zeros(dim)
    delta_pos   = np.zeros(dim)
    alpha_score = -np.inf
    beta_score  = -np.inf
    delta_score = -np.inf
    alpha_params: Dict[str, Any] = {}
    history_rows = []
    evaluation_counter = 0
    best_iteration = 0
    total_evals = GWO_POPULATION_SIZE * (GWO_ITERATIONS + 1)  # 10 init + 4*10 = 50

    print(f"       GWO progress for {model_code}: 0/{total_evals} evaluations", flush=True)

    # Base implementation kept here so shared helpers remain runnable before later override cells.
    print(f"       GWO {model_code}: initializing population ({GWO_POPULATION_SIZE} wolves)...", flush=True)
    for wolf_idx in range(GWO_POPULATION_SIZE):
        position = wolves[wolf_idx].copy()
        params = decode_gwo_position(position, model_code)
        start_time = time.perf_counter()
        score = objective_from_params(model_code, scaler_name, params)
        runtime_sec = float(time.perf_counter() - start_time)
        evaluation_counter += 1

        if score > alpha_score:
            delta_score, delta_pos = beta_score, beta_pos.copy()
            beta_score, beta_pos = alpha_score, alpha_pos.copy()
            alpha_score, alpha_pos = score, position.copy()
            alpha_params = dict(params)
            best_iteration = evaluation_counter
        elif score > beta_score:
            delta_score, delta_pos = beta_score, beta_pos.copy()
            beta_score, beta_pos = score, position.copy()
        elif score > delta_score:
            delta_score, delta_pos = score, position.copy()

        history_rows.append(
            {
                "Model": model_code,
                "Iteration": evaluation_counter,
                "CV_Mean": float(score),
                "Best_Score_So_Far": float(alpha_score),
                "Iteration_Runtime_Sec": runtime_sec,
            }
        )

    for outer_iter in range(GWO_ITERATIONS):
        a_value = 2.0 - 2.0 * (outer_iter / max(GWO_ITERATIONS - 1, 1))
        scores = np.full(GWO_POPULATION_SIZE, -np.inf)
        params_list = []

        for wolf_idx in range(GWO_POPULATION_SIZE):
            position = wolves[wolf_idx].copy()
            params = decode_gwo_position(position, model_code)
            start_time = time.perf_counter()
            score = objective_from_params(model_code, scaler_name, params)
            runtime_sec = float(time.perf_counter() - start_time)
            scores[wolf_idx] = score
            params_list.append(params)
            evaluation_counter += 1

            history_rows.append(
                {
                    "Model": model_code,
                    "Iteration": evaluation_counter,
                    "CV_Mean": float(score),
                    "Best_Score_So_Far": float(alpha_score),
                    "Iteration_Runtime_Sec": runtime_sec,
                }
            )

        for wolf_idx in range(GWO_POPULATION_SIZE):
            score = scores[wolf_idx]
            position = wolves[wolf_idx].copy()
            params = params_list[wolf_idx]
            if score > alpha_score:
                delta_score, delta_pos = beta_score, beta_pos.copy()
                beta_score, beta_pos = alpha_score, alpha_pos.copy()
                alpha_score, alpha_pos = score, position.copy()
                alpha_params = dict(params)
                best_iteration = evaluation_counter - (GWO_POPULATION_SIZE - wolf_idx - 1)
            elif score > beta_score:
                delta_score, delta_pos = beta_score, beta_pos.copy()
                beta_score, beta_pos = score, position.copy()
            elif score > delta_score:
                delta_score, delta_pos = score, position.copy()

        for i in range(GWO_POPULATION_SIZE):
            history_rows[-(GWO_POPULATION_SIZE - i)]["Best_Score_So_Far"] = float(alpha_score)

        new_wolves = np.zeros_like(wolves)
        for wolf_idx in range(GWO_POPULATION_SIZE):
            position = wolves[wolf_idx].copy()

            r1 = rng.random(dim)
            r2 = rng.random(dim)
            A1 = 2.0 * a_value * r1 - a_value
            C1 = 2.0 * r2
            D_alpha = np.abs(C1 * alpha_pos - position)
            X1 = alpha_pos - A1 * D_alpha

            r1 = rng.random(dim)
            r2 = rng.random(dim)
            A2 = 2.0 * a_value * r1 - a_value
            C2 = 2.0 * r2
            D_beta = np.abs(C2 * beta_pos - position)
            X2 = beta_pos - A2 * D_beta

            r1 = rng.random(dim)
            r2 = rng.random(dim)
            A3 = 2.0 * a_value * r1 - a_value
            C3 = 2.0 * r2
            D_delta = np.abs(C3 * delta_pos - position)
            X3 = delta_pos - A3 * D_delta

            new_wolves[wolf_idx] = np.clip((X1 + X2 + X3) / 3.0, 0.0, 1.0)

        wolves = new_wolves

    return {
        "Model": model_code,
        "Optimal_Scaler": scaler_name,
        "Best_CV_Mean": float(alpha_score),
        "Best_Iteration": int(best_iteration),
        **alpha_params,
    }, pd.DataFrame(history_rows)


def select_scaler_for_optimization(model_code: str) -> str:
    scaler_row = baseline_best_scalers_df.loc[baseline_best_scalers_df["Model"] == model_code]
    if scaler_row.empty:
        raise KeyError(f"No baseline scaler found for {model_code}")
    return scaler_row.iloc[0]["Optimal_Scaler"]


METHOD_CONFIG = {
    "TPE": {
        "runner": run_tpe_for_model,
        "history_step_col": "Trial",
        "best_step_col": "Best_Trial",
        "search_label": "trials",
        "step_count": N_TRIALS_PER_MODEL,
    },
    "GWO": {
        "runner": run_gwo_for_model,
        "history_step_col": "Iteration",
        "best_step_col": "Best_Iteration",
        "search_label": "evaluations",
        "step_count": GWO_POPULATION_SIZE * (GWO_ITERATIONS + 1),
    },
}


def run_single_model_optimization(method_name: str, model_code: str, progress_log: Dict[str, Dict[str, str]]) -> Dict[str, Any]:
    config = METHOD_CONFIG[method_name]
    status_key = method_name.lower()
    scaler_name = select_scaler_for_optimization(model_code)
    memory_before = refresh_memory_snapshot()

    print(f"\n{model_code:10s} | Scaler: {scaler_name:10s} | Available RAM: {memory_before['available_gb']:.2f} GB | Kernel RSS: {memory_before['process_mb']:.1f} MB")

    if progress_log.get(model_code, {}).get(status_key) == "completed":
        print(f"       Skipping: {method_name} already completed")
        return {"status": "skipped"}

    enforce_fair_resource_policy()
    collect_runtime_garbage()
    model_start = time.perf_counter()

    try:
        print(f"       Running {config['step_count']} {config['search_label']} with n_jobs_cv={N_JOBS_CV}, n_jobs_opt={N_JOBS_OPT}")
        with ResourceMonitor(f"{method_name} {model_code}"):
            search_start = time.perf_counter()
            best_row, history_df = config["runner"](model_code, scaler_name)
            search_time = time.perf_counter() - search_start

        with ResourceMonitor(f"{method_name} Eval {model_code}"):
            eval_start = time.perf_counter()
            _, summary_df, _ = evaluate_on_split(
                method_name=method_name,
                model_code=model_code,
                scaler_name=scaler_name,
                params={key: value for key, value in best_row.items() if key not in {"Model", "Optimal_Scaler", "Best_CV_Mean", config['best_step_col']}},
                X_train_input=X_train,
                y_train_input=y_train,
                X_test_input=X_test,
                y_test_input=y_test,
            )
            eval_time = time.perf_counter() - eval_start

        total_time = time.perf_counter() - model_start
        timing_row = {
            "Model": model_code,
            f"{method_name}_Search_Sec": float(search_time),
            f"{method_name}_Evaluation_Sec": float(eval_time),
            f"{method_name}_Total_Sec": float(total_time),
            "Best_CV_Mean": float(best_row["Best_CV_Mean"]),
        }

        progress_log.setdefault(model_code, {})[status_key] = "completed"
        save_progress_log(progress_log)
        save_model_checkpoint(
            method_name,
            model_code,
            {
                "best": best_row,
                "timing": timing_row,
                "memory_before": memory_before,
                "memory_after": refresh_memory_snapshot(),
            },
        )

        collect_runtime_garbage()
        return {
            "status": "completed",
            "best": pd.DataFrame([best_row]),
            "history": history_df,
            "summary": summary_df,
            "timing": pd.DataFrame([timing_row]),
        }
    except Exception as exc:
        progress_log.setdefault(model_code, {})[status_key] = f"failed: {str(exc)[:200]}"
        save_progress_log(progress_log)
        collect_runtime_garbage()
        print(f"       FAILED: {str(exc)[:120]}")
        return {"status": "failed", "error": str(exc)}


def run_method_sequentially(method_name: str, model_order: List[str] = MODEL_ORDER) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    config = METHOD_CONFIG[method_name]
    progress_log = load_progress_log()
    best_df, history_df, results_df, timing_df = load_existing_method_outputs(method_name)
    completed = 0
    failed = 0

    print("\n" + "=" * 80)
    print(f"{method_name} optimization (sequential, publication mode)")
    print(f"Fixed resources: n_jobs_cv={FIXED_N_JOBS_CV}, n_jobs_opt={FIXED_N_JOBS_OPT}")
    print("=" * 80)

    eligible_models = [model_code for model_code in model_order if model_code in SEARCH_SPACES]
    method_start = time.perf_counter()

    for index, model_code in enumerate(eligible_models, start=1):
        print(f"\n[{index:2d}/{len(eligible_models)}] {method_name} :: {model_code}")
        result = run_single_model_optimization(method_name, model_code, progress_log)

        if result["status"] == "completed":
            best_df = deduplicate_rows(pd.concat([best_df, result["best"]], ignore_index=True), ["Model"])
            history_df = deduplicate_rows(pd.concat([history_df, result["history"]], ignore_index=True), ["Model", config["history_step_col"]])
            results_df = deduplicate_rows(pd.concat([results_df, result["summary"]], ignore_index=True), ["Method", "Model", "Split"])
            timing_df = deduplicate_rows(pd.concat([timing_df, result["timing"]], ignore_index=True), ["Model"])
            export_method_outputs(method_name, best_df, history_df, results_df, timing_df, print_status=True)
            completed += 1
        elif result["status"] == "failed":
            failed += 1

    elapsed = time.perf_counter() - method_start
    print("\n" + "=" * 80)
    print(f"{method_name} summary: {completed} completed, {failed} failed, elapsed {elapsed:7.2f}s ({elapsed/60:.2f} min)")
    print("=" * 80)

    if not timing_df.empty:
        display(timing_df.sort_values(f"{method_name}_Total_Sec", ascending=False))

    return best_df, history_df, results_df, timing_df


print("Optimization helpers ready: sequential model-by-model workflow with fixed resources.")

Optimization helpers ready: sequential model-by-model workflow with fixed resources.

In [34]:
# =====================================================================
# CELL 8: TPE Optimization - Explicit Single-Model Runner
# =====================================================================

if "tpe_best_df" not in globals():
    tpe_best_df, tpe_history_df, tpe_results_df, tpe_timing_df = load_existing_method_outputs("TPE")


def run_tpe_model(model_code: str) -> Dict[str, Any]:
    """Run TPE for exactly one model and persist outputs incrementally."""
    global tpe_best_df, tpe_history_df, tpe_results_df, tpe_timing_df
    config = METHOD_CONFIG["TPE"]
    progress_log = load_progress_log()

    result = run_single_model_optimization("TPE", model_code, progress_log)

    if result["status"] == "completed":
        tpe_best_df = deduplicate_rows(pd.concat([tpe_best_df, result["best"]], ignore_index=True), ["Model"])
        tpe_history_df = deduplicate_rows(
            pd.concat([tpe_history_df, result["history"]], ignore_index=True),
            ["Model", config["history_step_col"]],
        )
        tpe_results_df = deduplicate_rows(
            pd.concat([tpe_results_df, result["summary"]], ignore_index=True),
            ["Method", "Model", "Split"],
        )
        tpe_timing_df = deduplicate_rows(pd.concat([tpe_timing_df, result["timing"]], ignore_index=True), ["Model"])
        export_method_outputs("TPE", tpe_best_df, tpe_history_df, tpe_results_df, tpe_timing_df, print_status=True)

    return result


print("TPE single-model runner ready.")
print("Call run_tpe_model('<MODEL_CODE>') one model at a time.")
print(f"Allowed models: {', '.join([m for m in MODEL_ORDER if m in SEARCH_SPACES])}")

TPE single-model runner ready.
Call run_tpe_model('<MODEL_CODE>') one model at a time.
Allowed models: LR, LDA, QDA, NB, KNN, LinearSVC, SVM, AdaBoost, RF, GB, XGB, LGBM, CB, SGD

In [35]:
# =====================================================================
# CELL 8B: GWO Optimization - Explicit Single-Model Runner
# =====================================================================

if "gwo_best_df" not in globals():
    gwo_best_df, gwo_history_df, gwo_results_df, gwo_timing_df = load_existing_method_outputs("GWO")


def run_gwo_model(model_code: str) -> Dict[str, Any]:
    """Run GWO for exactly one model and persist outputs incrementally."""
    global gwo_best_df, gwo_history_df, gwo_results_df, gwo_timing_df
    config = METHOD_CONFIG["GWO"]
    progress_log = load_progress_log()

    result = run_single_model_optimization("GWO", model_code, progress_log)

    if result["status"] == "completed":
        gwo_best_df = deduplicate_rows(pd.concat([gwo_best_df, result["best"]], ignore_index=True), ["Model"])
        gwo_history_df = deduplicate_rows(
            pd.concat([gwo_history_df, result["history"]], ignore_index=True),
            ["Model", config["history_step_col"]],
        )
        gwo_results_df = deduplicate_rows(
            pd.concat([gwo_results_df, result["summary"]], ignore_index=True),
            ["Method", "Model", "Split"],
        )
        gwo_timing_df = deduplicate_rows(pd.concat([gwo_timing_df, result["timing"]], ignore_index=True), ["Model"])
        export_method_outputs("GWO", gwo_best_df, gwo_history_df, gwo_results_df, gwo_timing_df, print_status=True)

    return result


print("GWO single-model runner ready.")
print("Call run_gwo_model('<MODEL_CODE>') one model at a time.")
print(f"Allowed models: {', '.join([m for m in MODEL_ORDER if m in SEARCH_SPACES])}")

GWO single-model runner ready.
Call run_gwo_model('<MODEL_CODE>') one model at a time.
Allowed models: LR, LDA, QDA, NB, KNN, LinearSVC, SVM, AdaBoost, RF, GB, XGB, LGBM, CB, SGD

In [68]:
# =====================================================================
# CELL 8C: Live Progress Enhancements (TPE/GWO)
# =====================================================================

TPE_PROGRESS_EVERY = 5
GWO_PROGRESS_EVERY = 5


def run_gwo_for_model(model_code: str, scaler_name: str) -> Tuple[Dict[str, Any], pd.DataFrame]:
    rng = np.random.default_rng(RANDOM_STATE)
    dim = len(SEARCH_SPACES[model_code])

    # ── FIX 1: initialize wolves as uniform [0,1] positions (unchanged, correct) ──
    wolves = rng.random((GWO_POPULATION_SIZE, dim))

    alpha_pos = np.zeros(dim)
    beta_pos  = np.zeros(dim)
    delta_pos = np.zeros(dim)
    alpha_score = -np.inf
    beta_score  = -np.inf
    delta_score = -np.inf
    alpha_params: Dict[str, Any] = {}
    history_rows = []
    evaluation_counter = 0
    best_iteration = 0
    total_evals = GWO_POPULATION_SIZE * (GWO_ITERATIONS + 1)  # 10 init + 4*10 = 50

    # Reset shared early-stop state for this model's run.
    _CURRENT_BEST_SCORE[0] = -np.inf
    _EVAL_COUNTER[0] = 0

    print(f"       GWO progress for {model_code}: 0/{total_evals} evaluations", flush=True)

    # ── FIX 2: evaluate the entire initial population BEFORE any position updates ──
    # Paper Section 3.1: "Calculate the fitness of each search agent"
    # This establishes a valid alpha/beta/delta BEFORE the first iteration begins.
    # Current code skips this — wolves[0] in iter 0 updates using alpha=zeros.
    print(f"       GWO {model_code}: initializing population ({GWO_POPULATION_SIZE} wolves)...", flush=True)
    for wolf_idx in range(GWO_POPULATION_SIZE):
        # Expose current best to objective_from_params for early stopping.
        _CURRENT_BEST_SCORE[0] = alpha_score

        position = wolves[wolf_idx].copy()
        params = decode_gwo_position(position, model_code)
        start_time = time.perf_counter()
        score = objective_from_params(model_code, scaler_name, params)
        runtime_sec = float(time.perf_counter() - start_time)
        evaluation_counter += 1

        # Update leaders from initial population
        if score > alpha_score:
            delta_score, delta_pos = beta_score, beta_pos.copy()
            beta_score,  beta_pos  = alpha_score, alpha_pos.copy()
            alpha_score, alpha_pos = score, position.copy()
            alpha_params = dict(params)
            best_iteration = evaluation_counter
        elif score > beta_score:
            delta_score, delta_pos = beta_score, beta_pos.copy()
            beta_score,  beta_pos  = score, position.copy()
        elif score > delta_score:
            delta_score, delta_pos = score, position.copy()

        history_rows.append({
            "Model": model_code,
            "Iteration": evaluation_counter,
            "CV_Mean": float(score),
            "Best_Score_So_Far": float(alpha_score),
            "Iteration_Runtime_Sec": runtime_sec,
        })

        if evaluation_counter == 1 or evaluation_counter % GWO_PROGRESS_EVERY == 0:
            print(
                f"       GWO {model_code}: init {wolf_idx+1}/{GWO_POPULATION_SIZE} | "
                f"last={score:.5f} | best={alpha_score:.5f}",
                flush=True,
            )

    print(
        f"       GWO {model_code}: init done → "
        f"α={alpha_score:.5f} β={beta_score:.5f} δ={delta_score:.5f}",
        flush=True,
    )

    # ── Main GWO loop ──────────────────────────────────────────────────────────────
    for outer_iter in range(GWO_ITERATIONS):

        # ── FIX 3: a decays from 2→0 over iterations (already correct in current code) ──
        # Paper eq. 3.5: a decreases linearly from 2 to 0
        a_value = 2.0 - 2.0 * (outer_iter / max(GWO_ITERATIONS - 1, 1))

        # ── FIX 4: separate evaluation pass and position-update pass ──────────────
        # Pass A: evaluate ALL wolves, collect scores
        scores = np.full(GWO_POPULATION_SIZE, -np.inf)
        runtimes = np.zeros(GWO_POPULATION_SIZE)
        params_list = []
        for wolf_idx in range(GWO_POPULATION_SIZE):
            # Expose current best to objective_from_params for early stopping.
            _CURRENT_BEST_SCORE[0] = alpha_score

            position = wolves[wolf_idx].copy()
            params = decode_gwo_position(position, model_code)
            start_time = time.perf_counter()
            score = objective_from_params(model_code, scaler_name, params)
            runtimes[wolf_idx] = float(time.perf_counter() - start_time)
            scores[wolf_idx] = score
            params_list.append(params)
            evaluation_counter += 1

            history_rows.append({
                "Model": model_code,
                "Iteration": evaluation_counter,
                "CV_Mean": float(score),
                "Best_Score_So_Far": float(alpha_score),   # best known so far (from prev iters)
                "Iteration_Runtime_Sec": runtimes[wolf_idx],
            })

            if evaluation_counter % GWO_PROGRESS_EVERY == 0 or evaluation_counter == total_evals:
                print(
                    f"       GWO {model_code}: {evaluation_counter:2d}/{total_evals} | "
                    f"iter={outer_iter + 1}/{GWO_ITERATIONS} | last={score:.5f} | best={alpha_score:.5f}",
                    flush=True,
                )

        # Pass B: update α, β, δ from ALL scores of this iteration
        for wolf_idx in range(GWO_POPULATION_SIZE):
            score    = scores[wolf_idx]
            position = wolves[wolf_idx].copy()
            params   = params_list[wolf_idx]
            if score > alpha_score:
                delta_score, delta_pos = beta_score, beta_pos.copy()
                beta_score,  beta_pos  = alpha_score, alpha_pos.copy()
                alpha_score, alpha_pos = score, position.copy()
                alpha_params = dict(params)
                best_iteration = evaluation_counter - (GWO_POPULATION_SIZE - wolf_idx - 1)
            elif score > beta_score:
                delta_score, delta_pos = beta_score, beta_pos.copy()
                beta_score,  beta_pos  = score, position.copy()
            elif score > delta_score:
                delta_score, delta_pos = score, position.copy()

        # Update Best_Score_So_Far retroactively for this iteration's history rows
        # (rows were written before leader update, so patch them now)
        for i in range(GWO_POPULATION_SIZE):
            history_rows[-(GWO_POPULATION_SIZE - i)]["Best_Score_So_Far"] = float(alpha_score)

        print(
            f"       GWO {model_code}: iter {outer_iter+1}/{GWO_ITERATIONS} done → "
            f"α={alpha_score:.5f} β={beta_score:.5f} δ={delta_score:.5f}",
            flush=True,
        )

        # Pass C: update ALL positions using the SAME α, β, δ
        new_wolves = np.zeros_like(wolves)
        for wolf_idx in range(GWO_POPULATION_SIZE):
            position = wolves[wolf_idx].copy()

            r1 = rng.random(dim);  r2 = rng.random(dim)
            A1 = 2.0 * a_value * r1 - a_value
            C1 = 2.0 * r2
            D_alpha = np.abs(C1 * alpha_pos - position)
            X1 = alpha_pos - A1 * D_alpha

            r1 = rng.random(dim);  r2 = rng.random(dim)
            A2 = 2.0 * a_value * r1 - a_value
            C2 = 2.0 * r2
            D_beta = np.abs(C2 * beta_pos - position)
            X2 = beta_pos - A2 * D_beta

            r1 = rng.random(dim);  r2 = rng.random(dim)
            A3 = 2.0 * a_value * r1 - a_value
            C3 = 2.0 * r2
            D_delta = np.abs(C3 * delta_pos - position)
            X3 = delta_pos - A3 * D_delta

            new_wolves[wolf_idx] = np.clip((X1 + X2 + X3) / 3.0, 0.0, 1.0)

        wolves = new_wolves

    return {
        "Model": model_code,
        "Optimal_Scaler": scaler_name,
        "Best_CV_Mean": float(alpha_score),
        "Best_Iteration": int(best_iteration),
        **alpha_params,
    }, pd.DataFrame(history_rows)


# Ensure single-model runners use the enhanced progress versions.
METHOD_CONFIG["TPE"]["runner"] = run_tpe_for_model
METHOD_CONFIG["GWO"]["runner"] = run_gwo_for_model

print("Live progress enhancements enabled.")
print(f"TPE update frequency: every {TPE_PROGRESS_EVERY} trials")
print(f"GWO update frequency: every {GWO_PROGRESS_EVERY} evaluations")

Live progress enhancements enabled.
TPE update frequency: every 5 trials
GWO update frequency: every 5 evaluations

In [78]:
# =====================================================================
# CELL 8C2: Free Memory Before Each Model Run
# =====================================================================


def collect_runtime_garbage() -> None:
    """Aggressive memory cleanup with visibility before/after optimization runs."""
    collected = gc.collect()
    vm = psutil.virtual_memory()
    process_mb = psutil.Process(os.getpid()).memory_info().rss / (1024**2)

    print(
        f"       Memory cleanup -> gc_collected={collected}, "
        f"available={vm.available / (1024**3):.2f} GB, "
        f"used={vm.percent:.1f}%, rss={process_mb:.1f} MB",
        flush=True,
    )


print("Free-memory hook enabled: cleanup runs automatically before each model optimization.")

Free-memory hook enabled: cleanup runs automatically before each model optimization.

In [69]:
# =====================================================================
# CELL 8C3: Full-Core Mode + Fold-Level Live Progress + Early Stopping
# =====================================================================

FORCE_FULL_CORE_MODE = True
SHOW_FOLD_PROGRESS = True
TPE_PROGRESS_EVERY = 1
GWO_PROGRESS_EVERY = 1

# ── Early stopping: abandon remaining folds on clearly losing wolves ──────────
# Applied after EARLY_STOP_MIN_FOLD folds; only kicks in once a valid best exists.
EARLY_STOP_MIN_FOLD = 2      # earliest fold index at which we can stop
EARLY_STOP_GAP      = 0.045  # stop if running_mean is >4.5% below current best

# Shared state: GWO/TPE loop writes current best here before each wolf call.
# objective_from_params reads it for early stopping without changing its signature.
_CURRENT_BEST_SCORE: List[float] = [-np.inf]

# Per-run evaluation counter for periodic RAM re-poll (mutable list = shared ref).
_EVAL_COUNTER: List[int] = [0]

if FORCE_FULL_CORE_MODE:
    # Threads per model fit are controlled via OMP/MKL env vars (N_JOBS_OPT).
    # The manual fold loop is inherently serial, so N_JOBS_CV stays 1.
    N_JOBS_CV = 1
    N_JOBS_OPT = max(1, CPU_COUNT)
    FIXED_N_JOBS_CV = N_JOBS_CV
    FIXED_N_JOBS_OPT = N_JOBS_OPT


def _repoll_resources(model_code: str) -> None:
    """Silently refresh thread-count env vars based on current available RAM.
    Called every 10 evaluations to adapt to memory changes mid-run."""
    global N_JOBS_OPT, FIXED_N_JOBS_OPT
    new_jobs = choose_n_jobs_opt(model_code, CPU_COUNT)
    if new_jobs != N_JOBS_OPT:
        N_JOBS_OPT = new_jobs
        FIXED_N_JOBS_OPT = new_jobs
        os.environ["OMP_NUM_THREADS"]     = str(new_jobs)
        os.environ["MKL_NUM_THREADS"]     = str(new_jobs)
        os.environ["OPENBLAS_NUM_THREADS"] = str(new_jobs)
        avail_gb = psutil.virtual_memory().available / (1024 ** 3)
        print(f"          [RAM repoll] free={avail_gb:.2f} GB → n_jobs_opt updated to {new_jobs}", flush=True)


def objective_from_params(model_code: str, scaler_name: str, params: Dict[str, Any]) -> float:
    """Manual CV objective with fold-level progress output and early stopping."""
    _EVAL_COUNTER[0] += 1
    if _EVAL_COUNTER[0] % 10 == 0:
        _repoll_resources(model_code)
    else:
        enforce_fair_resource_policy()

    fold_scores: List[float] = []

    for fold_idx, (fit_idx, val_idx) in enumerate(CV.split(X_train, y_train), start=1):
        fold_start = time.perf_counter()

        pipeline = make_pipeline(model_code, params, scaler_name)
        X_fit = X_train.iloc[fit_idx]
        y_fit = y_train.iloc[fit_idx]
        X_val = X_train.iloc[val_idx]
        y_val = y_train.iloc[val_idx]

        pipeline.fit(X_fit, y_fit)
        y_pred = pipeline.predict(X_val)
        fold_acc = float(accuracy_score(y_val, y_pred))
        fold_scores.append(fold_acc)

        if SHOW_FOLD_PROGRESS:
            elapsed = time.perf_counter() - fold_start
            print(
                f"          fold {fold_idx}/{N_SPLITS} | "
                f"acc={fold_acc:.5f} | running_mean={np.mean(fold_scores):.5f} | "
                f"time={elapsed:.2f}s",
                flush=True,
            )

        # ── Early stopping ──────────────────────────────────────────────────────
        # Skip remaining folds if this wolf is clearly not competitive.
        # Condition: after EARLY_STOP_MIN_FOLD folds and a valid best exists,
        # abandon if the gap to current best exceeds EARLY_STOP_GAP.
        if fold_idx >= EARLY_STOP_MIN_FOLD and _CURRENT_BEST_SCORE[0] > -np.inf:
            gap = _CURRENT_BEST_SCORE[0] - float(np.mean(fold_scores))
            if gap > EARLY_STOP_GAP:
                if SHOW_FOLD_PROGRESS:
                    print(
                        f"          [EarlyStop] running_mean={np.mean(fold_scores):.5f} | "
                        f"gap={gap:.4f} > {EARLY_STOP_GAP} | best={_CURRENT_BEST_SCORE[0]:.5f} "
                        f"→ skip folds {fold_idx + 1}-{N_SPLITS}",
                        flush=True,
                    )
                break

    return float(np.mean(fold_scores))


print("Full-core mode enabled for optimization.")
print(f"n_jobs_cv={N_JOBS_CV}, n_jobs_opt={N_JOBS_OPT} (all logical cores)")
print("Live fold-level progress enabled.")
print(f"Early stopping: gap > {EARLY_STOP_GAP} after fold {EARLY_STOP_MIN_FOLD}+")
print(f"RAM re-poll: every 10 evaluations")

Full-core mode enabled for optimization.
n_jobs_cv=1, n_jobs_opt=8 (all logical cores)
Live fold-level progress enabled.
Early stopping: gap > 0.045 after fold 2+
RAM re-poll: every 10 evaluations

In [70]:
# ============================================================
# Adaptive resource policy: heavy models run one-at-a-time with
# RAM-friendly thread limits
# ============================================================
import os
import psutil

MODEL_ORDER = ["LR", "LDA", "QDA", "NB", "KNN", "LinearSVC", "SVM", "AdaBoost", "RF", "GB", "XGB", "LGBM", "CB", "SGD"]

HEAVY_MODELS = {"KNN", "SVM", "RF", "GB", "XGB", "LGBM", "CB"}
MEDIUM_MODELS = {"AdaBoost", "LinearSVC", "SGD"}
LIGHT_MODELS = {"LR", "LDA", "QDA", "NB"}

MODEL_THREAD_CAP = {
    "CB": 2,
    "XGB": 2,
    "LGBM": 2,
    "RF": 3,
    "GB": 2,
    "KNN": 2,
    "SVM": 2,
    "AdaBoost": 3,
    "LinearSVC": 3,
    "SGD": 3,
    "LR": 4,
    "LDA": 4,
    "QDA": 4,
    "NB": 4,
}

def _ram_based_cap(avail_gb: float) -> int:
    if avail_gb < 2.5:
        return 1
    if avail_gb < 4.0:
        return 2
    if avail_gb < 5.5:   # was 6.0 — lowered to avoid cliff-edge at ~5.9 GB
        return 3
    return 4

def choose_n_jobs_opt(model_code: str, cpu_count: int) -> int:
    avail_gb = psutil.virtual_memory().available / (1024 ** 3)
    ram_cap = _ram_based_cap(avail_gb)
    cpu_cap = max(1, cpu_count - 1)  # keep one core free for OS/kernel
    model_cap = MODEL_THREAD_CAP.get(model_code, 2)

    if model_code in HEAVY_MODELS:
        return max(1, min(model_cap, ram_cap, cpu_cap))
    if model_code in MEDIUM_MODELS:
        return max(1, min(model_cap, ram_cap + 1, cpu_cap))
    return max(1, min(model_cap, ram_cap + 2, cpu_cap))

def apply_resource_policy_for_model(model_code: str):
    global N_JOBS_CV, N_JOBS_OPT, FIXED_N_JOBS_CV, FIXED_N_JOBS_OPT

    # Keep outer CV serial to avoid nested oversubscription.
    # Thread parallelism is handled via OMP/MKL env vars (N_JOBS_OPT).
    N_JOBS_CV = 1
    N_JOBS_OPT = choose_n_jobs_opt(model_code, CPU_COUNT)

    FIXED_N_JOBS_CV = N_JOBS_CV
    FIXED_N_JOBS_OPT = N_JOBS_OPT

    # Align threaded math backends with chosen n_jobs
    os.environ["OMP_NUM_THREADS"] = str(N_JOBS_OPT)
    os.environ["MKL_NUM_THREADS"] = str(N_JOBS_OPT)
    os.environ["OPENBLAS_NUM_THREADS"] = str(N_JOBS_OPT)

    avail_gb = psutil.virtual_memory().available / (1024 ** 3)
    group = "HEAVY" if model_code in HEAVY_MODELS else ("MEDIUM" if model_code in MEDIUM_MODELS else "LIGHT")
    print(
        f"[ResourcePolicy] model={model_code} ({group}) | free_ram={avail_gb:.2f} GB | "
        f"n_jobs_cv={N_JOBS_CV} | n_jobs_opt={N_JOBS_OPT}",
        flush=True,
    )

# Optional wrappers (use these instead of run_*_model directly)
def run_gwo_model_with_policy(model_code: str):
    apply_resource_policy_for_model(model_code)
    return run_gwo_model(model_code)

def run_tpe_model_with_policy(model_code: str):
    apply_resource_policy_for_model(model_code)
    return run_tpe_model(model_code)

## Cell 8A: Explicit TPE Per-Model Calls

Run each code cell below manually to execute one model at a time.

In [25]:
run_tpe_model("LGBM")

LGBM       | Scaler: Raw        | Available RAM: 4.38 GB | Kernel RSS: 228.2 MB
       Memory cleanup -> gc_collected=67, available=4.37 GB, used=72.2%, rss=228.2 MB
       Running 50 trials with n_jobs_cv=2, n_jobs_opt=2
       TPE progress for LGBM: 0/50 trials
       TPE LGBM:  1/50 | last=0.99148 | best=0.99148
       TPE LGBM:  5/50 | last=0.93225 | best=0.99148
       TPE LGBM: 10/50 | last=0.92915 | best=0.99265
       TPE LGBM: 15/50 | last=0.99375 | best=0.99375
       TPE LGBM: 20/50 | last=0.99517 | best=0.99517
       TPE LGBM: 25/50 | last=0.99656 | best=0.99656
       TPE LGBM: 30/50 | last=0.96560 | best=0.99667
       TPE LGBM: 35/50 | last=0.99769 | best=0.99769
       TPE LGBM: 40/50 | last=0.99712 | best=0.99769
       TPE LGBM: 45/50 | last=0.92529 | best=0.99769
       TPE LGBM: 50/50 | last=0.99406 | best=0.99769
  [TPE LGBM] Time: 2572.02s | Memory Δ:  -142.7MB | Peak:    85.6MB
  [TPE Eval LGBM] Time:  212.04s | Memory Δ:    +1.5MB | Peak:   218.9MB
       Memory cleanup -> gc_collected=64, available=3.13 GB, used=80.1%, rss=219.1 MB
       Exported TPE artifacts

{'status': 'completed',
 'best':   Model Optimal_Scaler  Best_CV_Mean  Best_Trial  n_estimators  learning_rate  \
 0  LGBM            Raw      0.997687          34           361       0.426536

    max_depth  num_leaves  min_child_samples  subsample  colsample_bytree  \
 0         15          41                 25   0.824208          0.912309

       reg_alpha  reg_lambda
 0  1.336780e-07    0.000708  ,
 'history':    Model  Trial   CV_Mean  Best_Score_So_Far  Trial_Runtime_Sec
 0   LGBM      1  0.991479           0.991479        1375.108143
 1   LGBM      2  0.957854           0.991479          51.380237
 2   LGBM      3  0.961104           0.991479          10.438176
 3   LGBM      4  0.955854           0.991479           4.676073
 4   LGBM      5  0.932250           0.991479          10.678451
 5   LGBM      6  0.978021           0.991479          26.943868
 6   LGBM      7  0.992646           0.992646           6.293340
 7   LGBM      8  0.956063           0.992646           9.268698
 8   LGBM      9  0.979271           0.992646           5.437053
 9   LGBM     10  0.929146           0.992646           6.320298
 10  LGBM     11  0.993042           0.993042          12.629217
 11  LGBM     12  0.993750           0.993750          13.026552
 12  LGBM     13  0.992208           0.993750          11.673401
 13  LGBM     14  0.992771           0.993750          12.938919
 14  LGBM     15  0.993750           0.993750          24.678805
 15  LGBM     16  0.992000           0.993750          28.908947
 16  LGBM     17  0.985250           0.993750          12.461613
 17  LGBM     18  0.995021           0.995021          31.211028
 18  LGBM     19  0.966687           0.995021           8.152053
 19  LGBM     20  0.995167           0.995167          23.953456
 20  LGBM     21  0.994208           0.995167          37.673778
 21  LGBM     22  0.994583           0.995167          38.645768
 22  LGBM     23  0.994521           0.995167          56.377043
 23  LGBM     24  0.995208           0.995208          31.823282
 24  LGBM     25  0.996562           0.996562          24.891071
 25  LGBM     26  0.996333           0.996562          22.181594
 26  LGBM     27  0.996667           0.996667          19.517818
 27  LGBM     28  0.996438           0.996667          13.722130
 28  LGBM     29  0.989354           0.996667          11.420672
 29  LGBM     30  0.965604           0.996667           7.229882
 30  LGBM     31  0.968021           0.996667           2.331076
 31  LGBM     32  0.996125           0.996667          30.018760
 32  LGBM     33  0.996604           0.996667          86.171089
 33  LGBM     34  0.997625           0.997625          36.019754
 34  LGBM     35  0.997687           0.997687          32.776016
 35  LGBM     36  0.995271           0.997687          35.504663
 36  LGBM     37  0.995688           0.997687          20.166615
 37  LGBM     38  0.996292           0.997687          38.942571
 38  LGBM     39  0.961271           0.997687          36.708952
 39  LGBM     40  0.997125           0.997687          24.139755
 40  LGBM     41  0.994083           0.997687          16.889866
 41  LGBM     42  0.997312           0.997687          47.989007
 42  LGBM     43  0.997083           0.997687          44.773583
 43  LGBM     44  0.996708           0.997687          47.160579
 44  LGBM     45  0.925292           0.997687          14.521618
 45  LGBM     46  0.996125           0.997687          16.005903
 46  LGBM     47  0.995667           0.997687          26.058093
 47  LGBM     48  0.995250           0.997687          22.654207
 48  LGBM     49  0.994667           0.997687          34.381901
 49  LGBM     50  0.994063           0.997687           9.071904,
 'summary':   Method Model Optimal_Scaler      Split  Accuracy  Precision    Recall  \
 0    TPE  LGBM            Raw  Train_OOF  0.997687   0.997944  0.998433
 1    TPE  LGBM            Raw       Test  0.999500   0.999478  0.999739

          F1     Kappa       MCC  ...  F1_CI_Lower  F1_CI_Upper  AUC_CI_Lower  \
 0  0.998188  0.994993  0.994993  ...     0.997859      0.99852      0.999907
 1  0.999608  0.998917  0.998917  ...     0.999279      0.99987      0.999994

    AUC_CI_Upper  LogLoss_CI_Lower  LogLoss_CI_Upper  Kappa_CI_Lower  \
 0      0.999962          0.006490          0.009109        0.994086
 1      1.000000          0.001323          0.003149        0.998013

    Kappa_CI_Upper  MCC_CI_Lower  MCC_CI_Upper
 0        0.995905      0.994086      0.995905
 1        0.999641      0.998014      0.999641

 [2 rows x 28 columns],
 'timing':   Model  TPE_Search_Sec  TPE_Evaluation_Sec  TPE_Total_Sec  Best_CV_Mean
 0  LGBM     2572.021975          212.042785    2784.903378      0.997687}

In [14]:
run_tpe_model("LR")

LR         | Scaler: Power      | Available RAM: 2.18 GB | Kernel RSS: 23.0 MB
       Memory cleanup -> gc_collected=76, available=2.03 GB, used=87.1%, rss=143.5 MB
       Running 50 trials with n_jobs_cv=1, n_jobs_opt=8
          fold 1/5 | acc=0.87573 | running_mean=0.87573 | time=1.14s
          fold 2/5 | acc=0.87885 | running_mean=0.87729 | time=0.68s
          fold 3/5 | acc=0.87479 | running_mean=0.87646 | time=0.68s
          fold 4/5 | acc=0.87792 | running_mean=0.87682 | time=0.78s
          fold 5/5 | acc=0.87750 | running_mean=0.87696 | time=0.73s
          fold 1/5 | acc=0.89479 | running_mean=0.89479 | time=1.18s
          fold 2/5 | acc=0.89594 | running_mean=0.89536 | time=1.66s
          fold 3/5 | acc=0.89292 | running_mean=0.89455 | time=2.97s
          fold 4/5 | acc=0.89792 | running_mean=0.89539 | time=3.14s
          fold 5/5 | acc=0.90083 | running_mean=0.89648 | time=2.57s
          fold 1/5 | acc=0.78052 | running_mean=0.78052 | time=1.14s
          fold 2/5 | acc=0.78323 | running_mean=0.78187 | time=1.21s
          fold 3/5 | acc=0.77906 | running_mean=0.78094 | time=1.73s
          fold 4/5 | acc=0.78500 | running_mean=0.78195 | time=1.68s
          fold 5/5 | acc=0.78208 | running_mean=0.78198 | time=1.05s
          fold 1/5 | acc=0.89333 | running_mean=0.89333 | time=1.61s
          fold 2/5 | acc=0.89510 | running_mean=0.89422 | time=1.84s
          fold 3/5 | acc=0.89156 | running_mean=0.89333 | time=1.32s
          fold 4/5 | acc=0.89698 | running_mean=0.89424 | time=1.10s
          fold 5/5 | acc=0.89979 | running_mean=0.89535 | time=1.50s
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=2.21s
          fold 2/5 | acc=0.89615 | running_mean=0.89651 | time=2.80s
          fold 3/5 | acc=0.89417 | running_mean=0.89573 | time=1.65s
          fold 4/5 | acc=0.89771 | running_mean=0.89622 | time=1.91s
          fold 5/5 | acc=0.90146 | running_mean=0.89727 | time=2.33s
          fold 1/5 | acc=0.84927 | running_mean=0.84927 | time=1.12s
          fold 2/5 | acc=0.85521 | running_mean=0.85224 | time=0.86s
          fold 3/5 | acc=0.85073 | running_mean=0.85174 | time=0.91s
          fold 4/5 | acc=0.85354 | running_mean=0.85219 | time=1.47s
          fold 5/5 | acc=0.84792 | running_mean=0.85133 | time=1.16s
          fold 1/5 | acc=0.88010 | running_mean=0.88010 | time=0.90s
          fold 2/5 | acc=0.88542 | running_mean=0.88276 | time=0.78s
          fold 3/5 | acc=0.87938 | running_mean=0.88163 | time=0.91s
          fold 4/5 | acc=0.88167 | running_mean=0.88164 | time=0.81s
          fold 5/5 | acc=0.88198 | running_mean=0.88171 | time=1.49s
          fold 1/5 | acc=0.84510 | running_mean=0.84510 | time=3.33s
          fold 2/5 | acc=0.85104 | running_mean=0.84807 | time=1.32s
          fold 3/5 | acc=0.84552 | running_mean=0.84722 | time=1.23s
          fold 4/5 | acc=0.84719 | running_mean=0.84721 | time=1.46s
          fold 5/5 | acc=0.84365 | running_mean=0.84650 | time=1.12s
          fold 1/5 | acc=0.89208 | running_mean=0.89208 | time=1.99s
          fold 2/5 | acc=0.89573 | running_mean=0.89391 | time=1.62s
          fold 3/5 | acc=0.89000 | running_mean=0.89260 | time=1.93s
          fold 4/5 | acc=0.89354 | running_mean=0.89284 | time=1.89s
          fold 5/5 | acc=0.89750 | running_mean=0.89377 | time=1.87s
          fold 1/5 | acc=0.89312 | running_mean=0.89312 | time=2.41s
          fold 2/5 | acc=0.89563 | running_mean=0.89437 | time=1.73s
          fold 3/5 | acc=0.89146 | running_mean=0.89340 | time=1.94s
          fold 4/5 | acc=0.89698 | running_mean=0.89430 | time=1.73s
          fold 5/5 | acc=0.90052 | running_mean=0.89554 | time=1.71s
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=1.81s
          fold 2/5 | acc=0.89604 | running_mean=0.89646 | time=1.79s
          fold 3/5 | acc=0.89406 | running_mean=0.89566 | time=2.38s
          fold 4/5 | acc=0.89781 | running_mean=0.89620 | time=2.27s
          fold 5/5 | acc=0.90146 | running_mean=0.89725 | time=1.62s
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=1.47s
          fold 2/5 | acc=0.89604 | running_mean=0.89646 | time=2.03s
          fold 3/5 | acc=0.89406 | running_mean=0.89566 | time=1.43s
          fold 4/5 | acc=0.89781 | running_mean=0.89620 | time=1.47s
          fold 5/5 | acc=0.90146 | running_mean=0.89725 | time=1.27s
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=1.61s
          fold 2/5 | acc=0.89604 | running_mean=0.89646 | time=1.36s
          fold 3/5 | acc=0.89406 | running_mean=0.89566 | time=1.17s
          fold 4/5 | acc=0.89781 | running_mean=0.89620 | time=1.50s
          fold 5/5 | acc=0.90146 | running_mean=0.89725 | time=1.85s
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=2.10s
          fold 2/5 | acc=0.89615 | running_mean=0.89651 | time=2.64s
          fold 3/5 | acc=0.89417 | running_mean=0.89573 | time=1.58s
          fold 4/5 | acc=0.89760 | running_mean=0.89620 | time=1.70s
          fold 5/5 | acc=0.90146 | running_mean=0.89725 | time=2.07s
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=1.49s
          fold 2/5 | acc=0.89615 | running_mean=0.89651 | time=1.67s
          fold 3/5 | acc=0.89417 | running_mean=0.89573 | time=1.87s
          fold 4/5 | acc=0.89760 | running_mean=0.89620 | time=2.08s
          fold 5/5 | acc=0.90135 | running_mean=0.89723 | time=1.83s
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=1.97s
          fold 2/5 | acc=0.89604 | running_mean=0.89646 | time=2.15s
          fold 3/5 | acc=0.89406 | running_mean=0.89566 | time=1.25s
          fold 4/5 | acc=0.89771 | running_mean=0.89617 | time=1.56s
          fold 5/5 | acc=0.90146 | running_mean=0.89723 | time=1.39s
          fold 1/5 | acc=0.89698 | running_mean=0.89698 | time=1.36s
          fold 2/5 | acc=0.89594 | running_mean=0.89646 | time=1.58s
          fold 3/5 | acc=0.89344 | running_mean=0.89545 | time=1.92s
          fold 4/5 | acc=0.89781 | running_mean=0.89604 | time=1.49s
          fold 5/5 | acc=0.90115 | running_mean=0.89706 | time=1.60s
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=2.10s
          fold 2/5 | acc=0.89604 | running_mean=0.89646 | time=1.76s
          fold 3/5 | acc=0.89406 | running_mean=0.89566 | time=1.64s
          fold 4/5 | acc=0.89781 | running_mean=0.89620 | time=1.75s
          fold 5/5 | acc=0.90146 | running_mean=0.89725 | time=1.28s
          fold 1/5 | acc=0.89292 | running_mean=0.89292 | time=0.94s
          fold 2/5 | acc=0.89563 | running_mean=0.89427 | time=1.13s
          fold 3/5 | acc=0.89198 | running_mean=0.89351 | time=1.24s
          fold 4/5 | acc=0.89687 | running_mean=0.89435 | time=0.96s
          fold 5/5 | acc=0.90021 | running_mean=0.89552 | time=0.90s
          fold 1/5 | acc=0.87156 | running_mean=0.87156 | time=0.70s
          fold 2/5 | acc=0.87594 | running_mean=0.87375 | time=0.65s
          fold 3/5 | acc=0.87135 | running_mean=0.87295 | time=0.78s
          fold 4/5 | acc=0.87594 | running_mean=0.87370 | time=0.74s
          fold 5/5 | acc=0.87469 | running_mean=0.87390 | time=0.90s
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=1.36s
          fold 2/5 | acc=0.89615 | running_mean=0.89651 | time=1.30s
          fold 3/5 | acc=0.89427 | running_mean=0.89576 | time=1.51s
          fold 4/5 | acc=0.89771 | running_mean=0.89625 | time=1.58s
          fold 5/5 | acc=0.90156 | running_mean=0.89731 | time=1.39s
          fold 1/5 | acc=0.89677 | running_mean=0.89677 | time=2.20s
          fold 2/5 | acc=0.89615 | running_mean=0.89646 | time=3.02s
          fold 3/5 | acc=0.89417 | running_mean=0.89569 | time=2.12s
          fold 4/5 | acc=0.89760 | running_mean=0.89617 | time=2.21s
          fold 5/5 | acc=0.90146 | running_mean=0.89723 | time=1.32s
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=1.34s
          fold 2/5 | acc=0.89604 | running_mean=0.89646 | time=1.40s
          fold 3/5 | acc=0.89406 | running_mean=0.89566 | time=1.38s
          fold 4/5 | acc=0.89781 | running_mean=0.89620 | time=1.31s
          fold 5/5 | acc=0.90146 | running_mean=0.89725 | time=1.29s
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=1.26s
          fold 2/5 | acc=0.89604 | running_mean=0.89646 | time=1.47s
          fold 3/5 | acc=0.89406 | running_mean=0.89566 | time=1.11s
          fold 4/5 | acc=0.89781 | running_mean=0.89620 | time=1.17s
          fold 5/5 | acc=0.90146 | running_mean=0.89725 | time=1.19s
          fold 1/5 | acc=0.89479 | running_mean=0.89479 | time=1.45s
          fold 2/5 | acc=0.89573 | running_mean=0.89526 | time=1.25s
          fold 3/5 | acc=0.89292 | running_mean=0.89448 | time=1.27s
          fold 4/5 | acc=0.89781 | running_mean=0.89531 | time=1.39s
          fold 5/5 | acc=0.90073 | running_mean=0.89640 | time=1.55s
          fold 1/5 | acc=0.89677 | running_mean=0.89677 | time=1.44s
          fold 2/5 | acc=0.89625 | running_mean=0.89651 | time=1.35s
          fold 3/5 | acc=0.89406 | running_mean=0.89569 | time=1.64s
          fold 4/5 | acc=0.89760 | running_mean=0.89617 | time=1.60s
          fold 5/5 | acc=0.90167 | running_mean=0.89727 | time=1.80s
          fold 1/5 | acc=0.89417 | running_mean=0.89417 | time=1.17s
          fold 2/5 | acc=0.89583 | running_mean=0.89500 | time=1.33s
          fold 3/5 | acc=0.89260 | running_mean=0.89420 | time=1.15s
          fold 4/5 | acc=0.89729 | running_mean=0.89497 | time=1.05s
          fold 5/5 | acc=0.90094 | running_mean=0.89617 | time=1.19s
          fold 1/5 | acc=0.89552 | running_mean=0.89552 | time=1.23s
          fold 2/5 | acc=0.89646 | running_mean=0.89599 | time=1.23s
          fold 3/5 | acc=0.89333 | running_mean=0.89510 | time=1.22s
          fold 4/5 | acc=0.89812 | running_mean=0.89586 | time=1.34s
          fold 5/5 | acc=0.90104 | running_mean=0.89690 | time=1.33s
          fold 1/5 | acc=0.89344 | running_mean=0.89344 | time=1.33s
          fold 2/5 | acc=0.89469 | running_mean=0.89406 | time=1.23s
          fold 3/5 | acc=0.89229 | running_mean=0.89347 | time=1.49s
          fold 4/5 | acc=0.89698 | running_mean=0.89435 | time=1.26s
          fold 5/5 | acc=0.90115 | running_mean=0.89571 | time=1.43s
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=1.44s
          fold 2/5 | acc=0.89604 | running_mean=0.89646 | time=1.63s
          fold 3/5 | acc=0.89406 | running_mean=0.89566 | time=1.77s
          fold 4/5 | acc=0.89771 | running_mean=0.89617 | time=1.45s
          fold 5/5 | acc=0.90146 | running_mean=0.89723 | time=1.41s
          fold 1/5 | acc=0.87167 | running_mean=0.87167 | time=0.81s
          fold 2/5 | acc=0.87667 | running_mean=0.87417 | time=0.74s
          fold 3/5 | acc=0.87146 | running_mean=0.87326 | time=0.82s
          fold 4/5 | acc=0.87646 | running_mean=0.87406 | time=0.87s
          fold 5/5 | acc=0.87448 | running_mean=0.87415 | time=0.73s
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=1.46s
          fold 2/5 | acc=0.89604 | running_mean=0.89646 | time=1.41s
          fold 3/5 | acc=0.89406 | running_mean=0.89566 | time=1.78s
          fold 4/5 | acc=0.89781 | running_mean=0.89620 | time=1.31s
          fold 5/5 | acc=0.90146 | running_mean=0.89725 | time=1.58s
          fold 1/5 | acc=0.89677 | running_mean=0.89677 | time=1.65s
          fold 2/5 | acc=0.89615 | running_mean=0.89646 | time=1.36s
          fold 3/5 | acc=0.89417 | running_mean=0.89569 | time=1.36s
          fold 4/5 | acc=0.89760 | running_mean=0.89617 | time=1.33s
          fold 5/5 | acc=0.90167 | running_mean=0.89727 | time=1.56s
          fold 1/5 | acc=0.89635 | running_mean=0.89635 | time=1.37s
          fold 2/5 | acc=0.89604 | running_mean=0.89620 | time=1.36s
          fold 3/5 | acc=0.89312 | running_mean=0.89517 | time=1.45s
          fold 4/5 | acc=0.89802 | running_mean=0.89589 | time=1.44s
          fold 5/5 | acc=0.90104 | running_mean=0.89692 | time=1.41s
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=1.25s
          fold 2/5 | acc=0.89615 | running_mean=0.89651 | time=1.58s
          fold 3/5 | acc=0.89417 | running_mean=0.89573 | time=1.59s
          fold 4/5 | acc=0.89771 | running_mean=0.89622 | time=1.48s
          fold 5/5 | acc=0.90146 | running_mean=0.89727 | time=1.40s
          fold 1/5 | acc=0.89677 | running_mean=0.89677 | time=1.63s
          fold 2/5 | acc=0.89615 | running_mean=0.89646 | time=1.37s
          fold 3/5 | acc=0.89396 | running_mean=0.89563 | time=1.34s
          fold 4/5 | acc=0.89760 | running_mean=0.89612 | time=1.20s
          fold 5/5 | acc=0.90156 | running_mean=0.89721 | time=1.67s
          fold 1/5 | acc=0.89260 | running_mean=0.89260 | time=0.99s
          fold 2/5 | acc=0.89656 | running_mean=0.89458 | time=1.05s
          fold 3/5 | acc=0.89094 | running_mean=0.89337 | time=0.94s
          fold 4/5 | acc=0.89635 | running_mean=0.89411 | time=1.05s
          fold 5/5 | acc=0.89990 | running_mean=0.89527 | time=1.11s
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=1.66s
          fold 2/5 | acc=0.89615 | running_mean=0.89651 | time=1.50s
          fold 3/5 | acc=0.89417 | running_mean=0.89573 | time=1.45s
          fold 4/5 | acc=0.89760 | running_mean=0.89620 | time=1.41s
          fold 5/5 | acc=0.90146 | running_mean=0.89725 | time=1.31s
          fold 1/5 | acc=0.89156 | running_mean=0.89156 | time=1.01s
          fold 2/5 | acc=0.89542 | running_mean=0.89349 | time=1.01s
          fold 3/5 | acc=0.88844 | running_mean=0.89181 | time=1.09s
          fold 4/5 | acc=0.89115 | running_mean=0.89164 | time=0.92s
          fold 5/5 | acc=0.89479 | running_mean=0.89227 | time=0.95s
          fold 1/5 | acc=0.89677 | running_mean=0.89677 | time=1.41s
          fold 2/5 | acc=0.89615 | running_mean=0.89646 | time=1.62s
          fold 3/5 | acc=0.89396 | running_mean=0.89563 | time=1.39s
          fold 4/5 | acc=0.89760 | running_mean=0.89612 | time=1.23s
          fold 5/5 | acc=0.90156 | running_mean=0.89721 | time=1.27s
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=1.59s
          fold 2/5 | acc=0.89604 | running_mean=0.89646 | time=1.38s
          fold 3/5 | acc=0.89406 | running_mean=0.89566 | time=1.23s
          fold 4/5 | acc=0.89781 | running_mean=0.89620 | time=1.29s
          fold 5/5 | acc=0.90146 | running_mean=0.89725 | time=1.55s
          fold 1/5 | acc=0.89677 | running_mean=0.89677 | time=1.51s
          fold 2/5 | acc=0.89615 | running_mean=0.89646 | time=1.53s
          fold 3/5 | acc=0.89417 | running_mean=0.89569 | time=1.37s
          fold 4/5 | acc=0.89760 | running_mean=0.89617 | time=1.63s
          fold 5/5 | acc=0.90135 | running_mean=0.89721 | time=1.38s
          fold 1/5 | acc=0.63792 | running_mean=0.63792 | time=0.91s
          fold 2/5 | acc=0.63802 | running_mean=0.63797 | time=0.69s
          fold 3/5 | acc=0.63802 | running_mean=0.63799 | time=0.68s
          fold 4/5 | acc=0.63802 | running_mean=0.63799 | time=0.78s
          fold 5/5 | acc=0.63802 | running_mean=0.63800 | time=0.87s
          fold 1/5 | acc=0.89656 | running_mean=0.89656 | time=1.24s
          fold 2/5 | acc=0.89583 | running_mean=0.89620 | time=1.27s
          fold 3/5 | acc=0.89323 | running_mean=0.89521 | time=1.21s
          fold 4/5 | acc=0.89781 | running_mean=0.89586 | time=1.76s
          fold 5/5 | acc=0.90104 | running_mean=0.89690 | time=1.43s
          fold 1/5 | acc=0.89677 | running_mean=0.89677 | time=1.39s
          fold 2/5 | acc=0.89615 | running_mean=0.89646 | time=1.65s
          fold 3/5 | acc=0.89417 | running_mean=0.89569 | time=1.50s
          fold 4/5 | acc=0.89760 | running_mean=0.89617 | time=1.40s
          fold 5/5 | acc=0.90135 | running_mean=0.89721 | time=1.52s
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=1.75s
          fold 2/5 | acc=0.89615 | running_mean=0.89651 | time=1.47s
          fold 3/5 | acc=0.89417 | running_mean=0.89573 | time=1.29s
          fold 4/5 | acc=0.89760 | running_mean=0.89620 | time=1.39s
          fold 5/5 | acc=0.90146 | running_mean=0.89725 | time=1.61s
          fold 1/5 | acc=0.88646 | running_mean=0.88646 | time=0.91s
          fold 2/5 | acc=0.89198 | running_mean=0.88922 | time=0.84s
          fold 3/5 | acc=0.88469 | running_mean=0.88771 | time=0.78s
          fold 4/5 | acc=0.88885 | running_mean=0.88799 | time=0.88s
          fold 5/5 | acc=0.88687 | running_mean=0.88777 | time=1.16s
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=2.13s
          fold 2/5 | acc=0.89604 | running_mean=0.89646 | time=1.65s
          fold 3/5 | acc=0.89406 | running_mean=0.89566 | time=1.55s
          fold 4/5 | acc=0.89781 | running_mean=0.89620 | time=1.87s
          fold 5/5 | acc=0.90146 | running_mean=0.89725 | time=1.69s
          fold 1/5 | acc=0.86000 | running_mean=0.86000 | time=0.72s
          fold 2/5 | acc=0.86687 | running_mean=0.86344 | time=0.89s
          fold 3/5 | acc=0.86073 | running_mean=0.86253 | time=0.80s
          fold 4/5 | acc=0.86271 | running_mean=0.86258 | time=0.67s
          fold 5/5 | acc=0.86135 | running_mean=0.86233 | time=0.91s
          fold 1/5 | acc=0.89677 | running_mean=0.89677 | time=1.60s
          fold 2/5 | acc=0.89615 | running_mean=0.89646 | time=1.54s
          fold 3/5 | acc=0.89396 | running_mean=0.89563 | time=1.34s
          fold 4/5 | acc=0.89760 | running_mean=0.89612 | time=1.26s
          fold 5/5 | acc=0.90156 | running_mean=0.89721 | time=1.35s
  [TPE LR] Time:  359.33s | Memory Δ:   +22.9MB | Peak:   166.4MB
  [TPE Eval LR] Time:  136.34s | Memory Δ:    -3.5MB | Peak:   162.9MB
       Memory cleanup -> gc_collected=64, available=2.31 GB, used=85.3%, rss=163.1 MB
       Exported TPE artifacts

{'status': 'completed',
 'best':   Model Optimal_Scaler  Best_CV_Mean  Best_Trial         C penalty
 0    LR          Power      0.897312          20  3.703326      l1,
 'history':    Model  Trial   CV_Mean  Best_Score_So_Far  Trial_Runtime_Sec
 0     LR      1  0.876958           0.876958           4.057603
 1     LR      2  0.896479           0.896479          11.549645
 2     LR      3  0.781979           0.896479           6.856394
 3     LR      4  0.895354           0.896479           7.396691
 4     LR      5  0.897271           0.897271          10.931673
 5     LR      6  0.851333           0.897271           5.551862
 6     LR      7  0.881708           0.897271           4.912265
 7     LR      8  0.846500           0.897271           8.488905
 8     LR      9  0.893771           0.897271           9.344094
 9     LR     10  0.895542           0.897271           9.560997
 10    LR     11  0.897250           0.897271           9.910697
 11    LR     12  0.897250           0.897271           7.699699
 12    LR     13  0.897250           0.897271           7.511322
 13    LR     14  0.897250           0.897271          10.114095
 14    LR     15  0.897229           0.897271           8.964289
 15    LR     16  0.897229           0.897271           8.342126
 16    LR     17  0.897062           0.897271           7.967979
 17    LR     18  0.897250           0.897271           8.555176
 18    LR     19  0.895521           0.897271           5.200054
 19    LR     20  0.873896           0.897271           3.797251
 20    LR     21  0.897312           0.897312           7.187747
 21    LR     22  0.897229           0.897312          10.883843
 22    LR     23  0.897250           0.897312           6.759633
 23    LR     24  0.897250           0.897312           6.221409
 24    LR     25  0.896396           0.897312           6.930070
 25    LR     26  0.897271           0.897312           7.852747
 26    LR     27  0.896167           0.897312           5.904735
 27    LR     28  0.896896           0.897312           6.381885
 28    LR     29  0.895708           0.897312           6.775252
 29    LR     30  0.897229           0.897312           7.740479
 30    LR     31  0.874146           0.897312           3.991887
 31    LR     32  0.897250           0.897312           7.562711
 32    LR     33  0.897271           0.897312           7.270588
 33    LR     34  0.896917           0.897312           7.051856
 34    LR     35  0.897271           0.897312           7.315137
 35    LR     36  0.897208           0.897312           7.232991
 36    LR     37  0.895271           0.897312           5.161316
 37    LR     38  0.897250           0.897312           7.359157
 38    LR     39  0.892271           0.897312           5.007378
 39    LR     40  0.897208           0.897312           6.947229
 40    LR     41  0.897250           0.897312           7.057193
 41    LR     42  0.897208           0.897312           7.443488
 42    LR     43  0.638000           0.897312           3.947139
 43    LR     44  0.896896           0.897312           6.942033
 44    LR     45  0.897208           0.897312           7.484755
 45    LR     46  0.897250           0.897312           7.539051
 46    LR     47  0.887771           0.897312           4.583916
 47    LR     48  0.897250           0.897312           8.919942
 48    LR     49  0.862333           0.897312           4.016459
 49    LR     50  0.897208           0.897312           7.113398,
 'summary':   Method Model Optimal_Scaler      Split  Accuracy  Precision    Recall  \
 0    TPE    LR          Power  Train_OOF  0.897312   0.914422  0.925679
 1    TPE    LR          Power       Test  0.905583   0.918624  0.934822

          F1     Kappa       MCC  ...  F1_CI_Lower  F1_CI_Upper  AUC_CI_Lower  \
 0  0.920016  0.776642  0.776755  ...     0.917731     0.922294      0.964746
 1  0.926652  0.794213  0.794452  ...     0.922375     0.930931      0.966107

    AUC_CI_Upper  LogLoss_CI_Lower  LogLoss_CI_Upper  Kappa_CI_Lower  \
 0      0.967347          0.222023          0.230605        0.770821
 1      0.971115          0.209943          0.226864        0.782780

    Kappa_CI_Upper  MCC_CI_Lower  MCC_CI_Upper
 0        0.782738      0.770953      0.782852
 1        0.805900      0.783014      0.806201

 [2 rows x 28 columns],
 'timing':   Model  TPE_Search_Sec  TPE_Evaluation_Sec  TPE_Total_Sec  Best_CV_Mean
 0    LR      359.330465          136.335596     495.857042      0.897312}

In [47]:
run_tpe_model("LDA")

LDA        | Scaler: Power      | Available RAM: 3.56 GB | Kernel RSS: 222.0 MB
       Memory cleanup -> gc_collected=0, available=3.53 GB, used=77.6%, rss=222.0 MB
       Running 50 trials with n_jobs_cv=1, n_jobs_opt=8
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.76s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.47s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.57s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.50s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.40s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.66s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.46s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.46s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.39s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.50s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.50s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.47s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.43s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.58s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.51s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.48s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.47s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.46s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.46s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.50s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.45s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.48s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.41s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.39s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.53s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.48s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.56s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.44s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.47s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.50s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.40s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.47s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.40s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.43s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.48s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.46s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.51s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.54s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.45s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.39s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.47s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.47s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.44s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.46s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.44s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.43s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.45s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.42s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.49s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.53s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.44s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.40s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.42s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.41s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.55s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.55s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.49s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.44s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.44s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.52s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.49s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.54s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.58s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.47s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.51s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.39s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.55s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.49s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.47s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.63s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.51s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.55s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.57s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.45s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.52s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.46s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.57s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.47s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.43s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.46s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.45s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.51s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.57s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.52s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.52s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.47s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.54s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.49s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.56s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.43s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.47s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.59s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.60s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.54s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.49s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.59s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.55s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.40s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.49s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.53s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.52s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.51s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.44s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.53s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.45s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.45s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.58s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.59s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.46s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.45s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.50s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.63s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.44s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.47s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.50s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.53s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.49s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.45s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.51s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.42s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.54s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.56s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.43s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.50s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.54s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.56s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.51s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.39s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.53s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.47s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.47s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.43s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.40s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.46s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.46s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.45s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.49s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.57s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.42s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.46s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.41s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.42s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.45s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.47s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.41s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.47s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.42s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.50s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.50s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.44s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.39s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.49s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.46s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.47s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.39s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.51s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.46s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.39s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.49s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.56s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.46s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.44s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.53s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.43s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.58s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.50s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.39s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.56s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.52s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.57s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.37s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.48s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.57s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.51s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.53s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.54s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.52s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.50s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.49s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.53s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.46s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.52s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.50s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.48s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.58s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.61s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.68s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.63s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.65s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.66s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.69s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.63s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.62s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.59s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.60s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.61s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.61s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.56s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.58s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.53s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.66s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.62s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.68s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.61s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.68s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.70s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.69s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.55s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.64s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.58s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.49s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.61s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.69s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.63s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.60s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.63s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.68s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.61s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.49s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.66s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.46s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.52s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.51s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.55s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.52s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.50s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.64s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.54s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.49s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.55s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.48s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.51s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.58s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.58s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.43s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.55s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.50s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.49s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.45s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.53s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.73s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.54s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.58s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.52s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.54s
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.53s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.60s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.55s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.43s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.55s
  [TPE LDA] Time:  128.84s | Memory Δ:   +10.1MB | Peak:   232.0MB
  [TPE Eval LDA] Time:  123.84s | Memory Δ:   -10.8MB | Peak:   221.3MB
       Memory cleanup -> gc_collected=64, available=3.48 GB, used=77.9%, rss=221.3 MB
       Exported TPE artifacts

{'status': 'completed',
 'best':   Model Optimal_Scaler  Best_CV_Mean  Best_Trial solver
 0   LDA          Power      0.895312           0   lsqr,
 'history':    Model  Trial   CV_Mean  Best_Score_So_Far  Trial_Runtime_Sec
 0    LDA      1  0.895312           0.895312           2.734593
 1    LDA      2  0.895312           0.895312           2.494715
 2    LDA      3  0.895312           0.895312           2.495437
 3    LDA      4  0.895312           0.895312           2.377044
 4    LDA      5  0.895312           0.895312           2.280556
 5    LDA      6  0.895312           0.895312           2.470868
 6    LDA      7  0.895312           0.895312           2.200756
 7    LDA      8  0.895312           0.895312           2.369751
 8    LDA      9  0.895312           0.895312           2.296578
 9    LDA     10  0.895312           0.895312           2.343263
 10   LDA     11  0.895312           0.895312           2.236792
 11   LDA     12  0.895312           0.895312           2.461179
 12   LDA     13  0.895312           0.895312           2.602641
 13   LDA     14  0.895312           0.895312           2.547923
 14   LDA     15  0.895312           0.895312           2.617258
 15   LDA     16  0.895312           0.895312           2.411725
 16   LDA     17  0.895312           0.895312           2.579438
 17   LDA     18  0.895312           0.895312           2.509978
 18   LDA     19  0.895312           0.895312           2.715930
 19   LDA     20  0.895312           0.895312           2.582376
 20   LDA     21  0.895312           0.895312           2.466048
 21   LDA     22  0.895312           0.895312           2.547791
 22   LDA     23  0.895312           0.895312           2.558828
 23   LDA     24  0.895312           0.895312           2.409890
 24   LDA     25  0.895312           0.895312           2.591938
 25   LDA     26  0.895312           0.895312           2.489081
 26   LDA     27  0.895312           0.895312           2.243348
 27   LDA     28  0.895312           0.895312           2.407792
 28   LDA     29  0.895312           0.895312           2.192011
 29   LDA     30  0.895312           0.895312           2.367560
 30   LDA     31  0.895312           0.895312           2.221199
 31   LDA     32  0.895312           0.895312           2.414524
 32   LDA     33  0.895312           0.895312           2.449665
 33   LDA     34  0.895312           0.895312           2.564441
 34   LDA     35  0.895312           0.895312           2.487159
 35   LDA     36  0.895312           0.895312           2.596680
 36   LDA     37  0.895312           0.895312           2.542193
 37   LDA     38  0.895312           0.895312           3.233257
 38   LDA     39  0.895312           0.895312           3.156286
 39   LDA     40  0.895312           0.895312           2.902821
 40   LDA     41  0.895312           0.895312           3.268159
 41   LDA     42  0.895312           0.895312           3.183468
 42   LDA     43  0.895312           0.895312           3.038268
 43   LDA     44  0.895312           0.895312           3.082021
 44   LDA     45  0.895312           0.895312           2.579129
 45   LDA     46  0.895312           0.895312           2.755818
 46   LDA     47  0.895312           0.895312           2.602234
 47   LDA     48  0.895312           0.895312           2.540551
 48   LDA     49  0.895312           0.895312           2.922056
 49   LDA     50  0.895312           0.895312           2.678135,
 'summary':   Method Model Optimal_Scaler      Split  Accuracy  Precision    Recall  \
 0    TPE   LDA          Power  Train_OOF  0.895312   0.913942  0.922806
 1    TPE   LDA          Power       Test  0.903500   0.917287  0.932863

          F1     Kappa       MCC  ...  F1_CI_Lower  F1_CI_Upper  AUC_CI_Lower  \
 0  0.918352  0.772519  0.772589  ...     0.916054     0.920509      0.963686
 1  0.925010  0.789725  0.789945  ...     0.920641     0.929264      0.964983

    AUC_CI_Upper  LogLoss_CI_Lower  LogLoss_CI_Upper  Kappa_CI_Lower  \
 0      0.966319          0.236391          0.243283        0.766605
 1      0.970034          0.227418          0.241073        0.778190

    Kappa_CI_Upper  MCC_CI_Lower  MCC_CI_Upper
 0        0.778447      0.766659      0.778541
 1        0.801377      0.778555      0.801650

 [2 rows x 28 columns],
 'timing':   Model  TPE_Search_Sec  TPE_Evaluation_Sec  TPE_Total_Sec  Best_CV_Mean
 0   LDA      128.843351          123.840054     252.947322      0.895312}

In [13]:
run_tpe_model("QDA")

QDA        | Scaler: Power      | Available RAM: 2.22 GB | Kernel RSS: 21.1 MB
       Skipping: TPE already completed

{'status': 'skipped'}

In [49]:
run_tpe_model("NB")

NB         | Scaler: Power      | Available RAM: 3.63 GB | Kernel RSS: 222.2 MB
       Memory cleanup -> gc_collected=0, available=3.61 GB, used=77.1%, rss=222.2 MB
       Running 50 trials with n_jobs_cv=1, n_jobs_opt=8
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.54s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.42s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.60s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.46s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.43s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.48s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.39s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.41s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.47s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.32s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.35s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.44s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.49s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.41s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.45s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.46s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.36s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.43s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.43s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.37s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.45s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.42s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.53s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.52s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.46s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.49s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.45s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.38s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.55s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.48s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.51s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.57s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.47s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.47s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.66s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.38s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.39s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.32s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.32s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.30s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.31s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.28s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.28s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.27s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.29s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.30s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.28s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.27s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.29s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.37s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.29s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.38s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.30s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.32s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.29s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.33s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.31s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.37s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.30s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.32s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.29s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.30s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.31s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.28s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.29s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.33s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.38s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.36s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.38s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.39s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.41s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.39s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.38s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.40s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.41s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.39s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.40s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.37s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.37s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.37s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.40s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.39s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.38s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.38s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.39s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.36s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.37s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.38s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.37s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.36s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.36s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.38s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.38s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.37s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.38s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.38s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.37s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.34s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.38s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.37s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.36s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.37s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.37s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.35s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.37s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.37s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.37s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.34s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.35s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.36s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.38s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.37s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.35s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.36s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.37s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.35s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.35s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.35s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.34s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.34s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.34s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.36s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.35s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.34s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.34s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.36s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.35s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.35s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.39s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.39s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.36s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.35s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.34s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.36s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.35s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.37s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.40s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.39s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.40s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.48s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.45s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.40s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.37s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.37s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.35s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.36s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.36s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.35s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.35s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.34s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.34s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.36s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.34s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.34s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.35s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.35s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.34s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.33s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.37s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.39s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.36s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.35s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.36s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.35s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.34s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.35s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.36s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.34s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.33s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.34s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.37s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.35s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.33s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.33s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.35s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.34s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.35s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.34s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.37s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.35s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.34s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.34s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.37s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.35s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.35s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.35s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.36s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.33s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.34s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.34s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.35s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.38s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.35s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.35s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.37s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.35s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.36s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.35s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.34s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.38s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.45s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.50s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.54s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.41s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.40s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.38s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.36s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.35s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.36s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.35s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.34s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.36s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.35s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.34s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.33s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.35s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.34s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.37s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.38s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.39s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.37s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.35s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.33s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.38s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.35s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.35s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.35s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.35s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.33s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.35s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.35s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.37s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.34s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.34s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.34s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.37s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.35s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.35s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.36s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.36s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.35s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.35s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.35s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.35s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.34s
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.34s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.35s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.35s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.34s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.34s
  [TPE NB] Time:   93.15s | Memory Δ:    +8.3MB | Peak:   230.6MB
  [TPE Eval NB] Time:   90.95s | Memory Δ:    -8.3MB | Peak:   222.3MB
       Memory cleanup -> gc_collected=64, available=3.48 GB, used=77.9%, rss=222.3 MB
       Exported TPE artifacts

{'status': 'completed',
 'best':   Model Optimal_Scaler  Best_CV_Mean  Best_Trial  var_smoothing
 0    NB          Power      0.843042           0   1.767017e-10,
 'history':    Model  Trial   CV_Mean  Best_Score_So_Far  Trial_Runtime_Sec
 0     NB      1  0.843042           0.843042           2.461328
 1     NB      2  0.843042           0.843042           2.084999
 2     NB      3  0.843042           0.843042           2.154166
 3     NB      4  0.843042           0.843042           2.060119
 4     NB      5  0.843042           0.843042           2.389869
 5     NB      6  0.843042           0.843042           2.373777
 6     NB      7  0.843042           0.843042           2.703418
 7     NB      8  0.843042           0.843042           1.714193
 8     NB      9  0.843042           0.843042           1.435204
 9     NB     10  0.843042           0.843042           1.522638
 10    NB     11  0.843042           0.843042           1.589957
 11    NB     12  0.843042           0.843042           1.629456
 12    NB     13  0.843042           0.843042           1.481412
 13    NB     14  0.843042           0.843042           1.839362
 14    NB     15  0.843042           0.843042           1.993067
 15    NB     16  0.843042           0.843042           1.920613
 16    NB     17  0.843042           0.843042           1.948884
 17    NB     18  0.843042           0.843042           1.843783
 18    NB     19  0.843042           0.843042           1.889390
 19    NB     20  0.843042           0.843042           1.841773
 20    NB     21  0.843042           0.843042           1.833657
 21    NB     22  0.843042           0.843042           1.802572
 22    NB     23  0.843042           0.843042           1.835053
 23    NB     24  0.843042           0.843042           1.756877
 24    NB     25  0.843042           0.843042           1.736982
 25    NB     26  0.843042           0.843042           1.845504
 26    NB     27  0.843042           0.843042           1.769186
 27    NB     28  0.843042           0.843042           2.039116
 28    NB     29  0.843042           0.843042           1.959389
 29    NB     30  0.843042           0.843042           1.767239
 30    NB     31  0.843042           0.843042           1.745776
 31    NB     32  0.843042           0.843042           1.791623
 32    NB     33  0.843042           0.843042           1.772841
 33    NB     34  0.843042           0.843042           1.725469
 34    NB     35  0.843042           0.843042           1.753801
 35    NB     36  0.843042           0.843042           1.750850
 36    NB     37  0.843042           0.843042           1.765876
 37    NB     38  0.843042           0.843042           1.736330
 38    NB     39  0.843042           0.843042           1.822677
 39    NB     40  0.843042           0.843042           1.797932
 40    NB     41  0.843042           0.843042           2.309222
 41    NB     42  0.843042           0.843042           1.805224
 42    NB     43  0.843042           0.843042           1.746367
 43    NB     44  0.843042           0.843042           1.837342
 44    NB     45  0.843042           0.843042           1.801998
 45    NB     46  0.843042           0.843042           1.736401
 46    NB     47  0.843042           0.843042           1.736220
 47    NB     48  0.843042           0.843042           1.798710
 48    NB     49  0.843042           0.843042           1.750853
 49    NB     50  0.843042           0.843042           1.731871,
 'summary':   Method Model Optimal_Scaler      Split  Accuracy  Precision    Recall  \
 0    TPE    NB          Power  Train_OOF  0.843042   0.885553  0.865889
 1    TPE    NB          Power       Test  0.847500   0.887986  0.870820

          F1     Kappa       MCC  ...  F1_CI_Lower  F1_CI_Upper  AUC_CI_Lower  \
 0  0.875611  0.663051  0.663358  ...     0.872867     0.878583      0.921513
 1  0.879319  0.672266  0.672502  ...     0.873910     0.884685      0.923027

    AUC_CI_Upper  LogLoss_CI_Lower  LogLoss_CI_Upper  Kappa_CI_Lower  \
 0      0.926109          0.355062          0.369135        0.656142
 1      0.931695          0.336669          0.363145        0.658546

    Kappa_CI_Upper  MCC_CI_Lower  MCC_CI_Upper
 0        0.670433      0.656403      0.670681
 1        0.686017      0.658863      0.686177

 [2 rows x 28 columns],
 'timing':   Model  TPE_Search_Sec  TPE_Evaluation_Sec  TPE_Total_Sec  Best_CV_Mean
 0    NB       93.151698           90.946592     184.286861      0.843042}

In [39]:
run_tpe_model("KNN")

KNN        | Scaler: Raw        | Available RAM: 2.72 GB | Kernel RSS: 242.3 MB
       Memory cleanup -> gc_collected=419, available=2.71 GB, used=82.8%, rss=242.3 MB
       Running 50 trials with n_jobs_cv=1, n_jobs_opt=8
          fold 1/5 | acc=0.93750 | running_mean=0.93750 | time=2.85s
          fold 2/5 | acc=0.94094 | running_mean=0.93922 | time=2.98s
          fold 3/5 | acc=0.93937 | running_mean=0.93927 | time=5.46s
          fold 4/5 | acc=0.93656 | running_mean=0.93859 | time=6.71s
          fold 5/5 | acc=0.93677 | running_mean=0.93823 | time=4.13s
          fold 1/5 | acc=0.94573 | running_mean=0.94573 | time=9.45s
          fold 2/5 | acc=0.94479 | running_mean=0.94526 | time=8.64s
          fold 3/5 | acc=0.94531 | running_mean=0.94528 | time=7.45s
          fold 4/5 | acc=0.94312 | running_mean=0.94474 | time=7.36s
          fold 5/5 | acc=0.94333 | running_mean=0.94446 | time=7.49s
          fold 1/5 | acc=0.93771 | running_mean=0.93771 | time=2.51s
          fold 2/5 | acc=0.94167 | running_mean=0.93969 | time=2.78s
          fold 3/5 | acc=0.94271 | running_mean=0.94069 | time=2.80s
          fold 4/5 | acc=0.94073 | running_mean=0.94070 | time=2.64s
          fold 5/5 | acc=0.94104 | running_mean=0.94077 | time=3.24s
          fold 1/5 | acc=0.94427 | running_mean=0.94427 | time=5.10s
          fold 2/5 | acc=0.94542 | running_mean=0.94484 | time=4.59s
          fold 3/5 | acc=0.94365 | running_mean=0.94444 | time=4.91s
          fold 4/5 | acc=0.94406 | running_mean=0.94435 | time=6.48s
          fold 5/5 | acc=0.94656 | running_mean=0.94479 | time=3.90s
          fold 1/5 | acc=0.93677 | running_mean=0.93677 | time=9.34s
          fold 2/5 | acc=0.93740 | running_mean=0.93708 | time=12.74s
          fold 3/5 | acc=0.93698 | running_mean=0.93705 | time=13.00s
          fold 4/5 | acc=0.93563 | running_mean=0.93669 | time=9.84s
          fold 5/5 | acc=0.93635 | running_mean=0.93662 | time=13.99s
          fold 1/5 | acc=0.93781 | running_mean=0.93781 | time=3.46s
          fold 2/5 | acc=0.93844 | running_mean=0.93813 | time=3.26s
          fold 3/5 | acc=0.93750 | running_mean=0.93792 | time=3.86s
          fold 4/5 | acc=0.93698 | running_mean=0.93768 | time=3.51s
          fold 5/5 | acc=0.93781 | running_mean=0.93771 | time=5.37s
          fold 1/5 | acc=0.90563 | running_mean=0.90563 | time=2.27s
          fold 2/5 | acc=0.90229 | running_mean=0.90396 | time=2.49s
          fold 3/5 | acc=0.90323 | running_mean=0.90372 | time=1.73s
          fold 4/5 | acc=0.90469 | running_mean=0.90396 | time=1.61s
          fold 5/5 | acc=0.90542 | running_mean=0.90425 | time=1.40s
          fold 1/5 | acc=0.93479 | running_mean=0.93479 | time=2.12s
          fold 2/5 | acc=0.93677 | running_mean=0.93578 | time=1.90s
          fold 3/5 | acc=0.93615 | running_mean=0.93590 | time=2.00s
          fold 4/5 | acc=0.93521 | running_mean=0.93573 | time=2.02s
          fold 5/5 | acc=0.93417 | running_mean=0.93542 | time=2.28s
          fold 1/5 | acc=0.93906 | running_mean=0.93906 | time=4.36s
          fold 2/5 | acc=0.94010 | running_mean=0.93958 | time=5.37s
          fold 3/5 | acc=0.93833 | running_mean=0.93917 | time=5.33s
          fold 4/5 | acc=0.93750 | running_mean=0.93875 | time=5.55s
          fold 5/5 | acc=0.94021 | running_mean=0.93904 | time=4.43s
          fold 1/5 | acc=0.94885 | running_mean=0.94885 | time=5.70s
          fold 2/5 | acc=0.94708 | running_mean=0.94797 | time=4.99s
          fold 3/5 | acc=0.94917 | running_mean=0.94837 | time=5.20s
          fold 4/5 | acc=0.94750 | running_mean=0.94815 | time=6.24s
          fold 5/5 | acc=0.94740 | running_mean=0.94800 | time=5.94s
          fold 1/5 | acc=0.93937 | running_mean=0.93937 | time=10.29s
          fold 2/5 | acc=0.93750 | running_mean=0.93844 | time=12.44s
          fold 3/5 | acc=0.93958 | running_mean=0.93882 | time=11.05s
          fold 4/5 | acc=0.93812 | running_mean=0.93865 | time=10.72s
          fold 5/5 | acc=0.93656 | running_mean=0.93823 | time=11.42s
          fold 1/5 | acc=0.94958 | running_mean=0.94958 | time=5.38s
          fold 2/5 | acc=0.94635 | running_mean=0.94797 | time=7.60s
          fold 3/5 | acc=0.94969 | running_mean=0.94854 | time=6.33s
          fold 4/5 | acc=0.94771 | running_mean=0.94833 | time=4.88s
          fold 5/5 | acc=0.94719 | running_mean=0.94810 | time=5.07s
          fold 1/5 | acc=0.94958 | running_mean=0.94958 | time=4.56s
          fold 2/5 | acc=0.94635 | running_mean=0.94797 | time=6.14s
          fold 3/5 | acc=0.94969 | running_mean=0.94854 | time=5.33s
          fold 4/5 | acc=0.94771 | running_mean=0.94833 | time=8.57s
          fold 5/5 | acc=0.94719 | running_mean=0.94810 | time=6.65s
          fold 1/5 | acc=0.94885 | running_mean=0.94885 | time=17.39s
          fold 2/5 | acc=0.94708 | running_mean=0.94797 | time=11.22s
          fold 3/5 | acc=0.94917 | running_mean=0.94837 | time=5.40s
          fold 4/5 | acc=0.94750 | running_mean=0.94815 | time=6.15s
          fold 5/5 | acc=0.94740 | running_mean=0.94800 | time=4.31s
          fold 1/5 | acc=0.94552 | running_mean=0.94552 | time=7.00s
          fold 2/5 | acc=0.94479 | running_mean=0.94516 | time=7.67s
          fold 3/5 | acc=0.94531 | running_mean=0.94521 | time=5.68s
          fold 4/5 | acc=0.94281 | running_mean=0.94461 | time=6.14s
          fold 5/5 | acc=0.94604 | running_mean=0.94490 | time=9.87s
          fold 1/5 | acc=0.94990 | running_mean=0.94990 | time=6.46s
          fold 2/5 | acc=0.94719 | running_mean=0.94854 | time=4.94s
          fold 3/5 | acc=0.94937 | running_mean=0.94882 | time=5.42s
          fold 4/5 | acc=0.94802 | running_mean=0.94862 | time=4.44s
          fold 5/5 | acc=0.94948 | running_mean=0.94879 | time=4.67s
          fold 1/5 | acc=0.94229 | running_mean=0.94229 | time=2.84s
          fold 2/5 | acc=0.94177 | running_mean=0.94203 | time=3.42s
          fold 3/5 | acc=0.94354 | running_mean=0.94253 | time=2.65s
          fold 4/5 | acc=0.93906 | running_mean=0.94167 | time=3.36s
          fold 5/5 | acc=0.94094 | running_mean=0.94152 | time=2.69s
          fold 1/5 | acc=0.94865 | running_mean=0.94865 | time=5.78s
          fold 2/5 | acc=0.94698 | running_mean=0.94781 | time=5.43s
          fold 3/5 | acc=0.94760 | running_mean=0.94774 | time=5.85s
          fold 4/5 | acc=0.94688 | running_mean=0.94753 | time=6.92s
          fold 5/5 | acc=0.94781 | running_mean=0.94758 | time=6.36s
          fold 1/5 | acc=0.94812 | running_mean=0.94812 | time=7.23s
          fold 2/5 | acc=0.94625 | running_mean=0.94719 | time=6.20s
          fold 3/5 | acc=0.94823 | running_mean=0.94753 | time=5.91s
          fold 4/5 | acc=0.94427 | running_mean=0.94672 | time=7.00s
          fold 5/5 | acc=0.94542 | running_mean=0.94646 | time=5.80s
          fold 1/5 | acc=0.94667 | running_mean=0.94667 | time=7.71s
          fold 2/5 | acc=0.94521 | running_mean=0.94594 | time=6.40s
          fold 3/5 | acc=0.94490 | running_mean=0.94559 | time=6.09s
          fold 4/5 | acc=0.94333 | running_mean=0.94503 | time=6.14s
          fold 5/5 | acc=0.94563 | running_mean=0.94515 | time=7.96s
          fold 1/5 | acc=0.93708 | running_mean=0.93708 | time=11.62s
          fold 2/5 | acc=0.93667 | running_mean=0.93688 | time=9.98s
          fold 3/5 | acc=0.93937 | running_mean=0.93771 | time=11.43s
          fold 4/5 | acc=0.93906 | running_mean=0.93805 | time=12.23s
          fold 5/5 | acc=0.93646 | running_mean=0.93773 | time=13.44s
          fold 1/5 | acc=0.94948 | running_mean=0.94948 | time=6.98s
          fold 2/5 | acc=0.94635 | running_mean=0.94792 | time=6.51s
          fold 3/5 | acc=0.95021 | running_mean=0.94868 | time=4.11s
          fold 4/5 | acc=0.94708 | running_mean=0.94828 | time=4.82s
          fold 5/5 | acc=0.94792 | running_mean=0.94821 | time=4.20s
          fold 1/5 | acc=0.94792 | running_mean=0.94792 | time=4.28s
          fold 2/5 | acc=0.94708 | running_mean=0.94750 | time=4.66s
          fold 3/5 | acc=0.94927 | running_mean=0.94809 | time=4.51s
          fold 4/5 | acc=0.94490 | running_mean=0.94729 | time=4.85s
          fold 5/5 | acc=0.94604 | running_mean=0.94704 | time=4.37s
          fold 1/5 | acc=0.94802 | running_mean=0.94802 | time=3.73s
          fold 2/5 | acc=0.94698 | running_mean=0.94750 | time=3.74s
          fold 3/5 | acc=0.94760 | running_mean=0.94753 | time=3.74s
          fold 4/5 | acc=0.94708 | running_mean=0.94742 | time=4.03s
          fold 5/5 | acc=0.94771 | running_mean=0.94748 | time=3.75s
          fold 1/5 | acc=0.94677 | running_mean=0.94677 | time=5.10s
          fold 2/5 | acc=0.94604 | running_mean=0.94641 | time=8.13s
          fold 3/5 | acc=0.94625 | running_mean=0.94635 | time=5.13s
          fold 4/5 | acc=0.94437 | running_mean=0.94586 | time=4.70s
          fold 5/5 | acc=0.94542 | running_mean=0.94577 | time=5.30s
          fold 1/5 | acc=0.94458 | running_mean=0.94458 | time=9.09s
          fold 2/5 | acc=0.94458 | running_mean=0.94458 | time=7.03s
          fold 3/5 | acc=0.94479 | running_mean=0.94465 | time=6.13s
          fold 4/5 | acc=0.94250 | running_mean=0.94411 | time=8.36s
          fold 5/5 | acc=0.94312 | running_mean=0.94392 | time=7.69s
          fold 1/5 | acc=0.92208 | running_mean=0.92208 | time=3.24s
          fold 2/5 | acc=0.92323 | running_mean=0.92266 | time=3.28s
          fold 3/5 | acc=0.92688 | running_mean=0.92406 | time=3.19s
          fold 4/5 | acc=0.92656 | running_mean=0.92469 | time=2.56s
          fold 5/5 | acc=0.92771 | running_mean=0.92529 | time=2.41s
          fold 1/5 | acc=0.94781 | running_mean=0.94781 | time=5.41s
          fold 2/5 | acc=0.94812 | running_mean=0.94797 | time=4.91s
          fold 3/5 | acc=0.94885 | running_mean=0.94826 | time=5.93s
          fold 4/5 | acc=0.94500 | running_mean=0.94745 | time=5.72s
          fold 5/5 | acc=0.94667 | running_mean=0.94729 | time=5.65s
          fold 1/5 | acc=0.94802 | running_mean=0.94802 | time=4.44s
          fold 2/5 | acc=0.94698 | running_mean=0.94750 | time=4.76s
          fold 3/5 | acc=0.94990 | running_mean=0.94830 | time=4.91s
          fold 4/5 | acc=0.94771 | running_mean=0.94815 | time=5.13s
          fold 5/5 | acc=0.94719 | running_mean=0.94796 | time=4.60s
          fold 1/5 | acc=0.93958 | running_mean=0.93958 | time=4.26s
          fold 2/5 | acc=0.94104 | running_mean=0.94031 | time=4.23s
          fold 3/5 | acc=0.93865 | running_mean=0.93976 | time=4.39s
          fold 4/5 | acc=0.94052 | running_mean=0.93995 | time=4.98s
          fold 5/5 | acc=0.94188 | running_mean=0.94033 | time=5.54s
          fold 1/5 | acc=0.94177 | running_mean=0.94177 | time=2.85s
          fold 2/5 | acc=0.94167 | running_mean=0.94172 | time=2.56s
          fold 3/5 | acc=0.94271 | running_mean=0.94205 | time=2.30s
          fold 4/5 | acc=0.93885 | running_mean=0.94125 | time=2.81s
          fold 5/5 | acc=0.94146 | running_mean=0.94129 | time=2.43s
          fold 1/5 | acc=0.94948 | running_mean=0.94948 | time=6.30s
          fold 2/5 | acc=0.94635 | running_mean=0.94792 | time=5.58s
          fold 3/5 | acc=0.95021 | running_mean=0.94868 | time=5.85s
          fold 4/5 | acc=0.94708 | running_mean=0.94828 | time=6.99s
          fold 5/5 | acc=0.94792 | running_mean=0.94821 | time=8.52s
          fold 1/5 | acc=0.94802 | running_mean=0.94802 | time=9.43s
          fold 2/5 | acc=0.94698 | running_mean=0.94750 | time=5.74s
          fold 3/5 | acc=0.94990 | running_mean=0.94830 | time=4.22s
          fold 4/5 | acc=0.94771 | running_mean=0.94815 | time=4.29s
          fold 5/5 | acc=0.94719 | running_mean=0.94796 | time=4.51s
          fold 1/5 | acc=0.94594 | running_mean=0.94594 | time=4.22s
          fold 2/5 | acc=0.94542 | running_mean=0.94568 | time=3.94s
          fold 3/5 | acc=0.94531 | running_mean=0.94556 | time=3.35s
          fold 4/5 | acc=0.94646 | running_mean=0.94578 | time=3.75s
          fold 5/5 | acc=0.94625 | running_mean=0.94588 | time=4.07s
          fold 1/5 | acc=0.94750 | running_mean=0.94750 | time=4.37s
          fold 2/5 | acc=0.94656 | running_mean=0.94703 | time=5.48s
          fold 3/5 | acc=0.94656 | running_mean=0.94688 | time=4.50s
          fold 4/5 | acc=0.94750 | running_mean=0.94703 | time=4.79s
          fold 5/5 | acc=0.94646 | running_mean=0.94692 | time=3.84s
          fold 1/5 | acc=0.94948 | running_mean=0.94948 | time=4.40s
          fold 2/5 | acc=0.94635 | running_mean=0.94792 | time=4.31s
          fold 3/5 | acc=0.95021 | running_mean=0.94868 | time=3.98s
          fold 4/5 | acc=0.94708 | running_mean=0.94828 | time=4.30s
          fold 5/5 | acc=0.94792 | running_mean=0.94821 | time=4.19s
          fold 1/5 | acc=0.94396 | running_mean=0.94396 | time=3.24s
          fold 2/5 | acc=0.94552 | running_mean=0.94474 | time=3.04s
          fold 3/5 | acc=0.94563 | running_mean=0.94503 | time=3.10s
          fold 4/5 | acc=0.94365 | running_mean=0.94469 | time=3.13s
          fold 5/5 | acc=0.94563 | running_mean=0.94488 | time=3.05s
          fold 1/5 | acc=0.94219 | running_mean=0.94219 | time=2.13s
          fold 2/5 | acc=0.94302 | running_mean=0.94260 | time=2.13s
          fold 3/5 | acc=0.94281 | running_mean=0.94267 | time=2.59s
          fold 4/5 | acc=0.93906 | running_mean=0.94177 | time=2.31s
          fold 5/5 | acc=0.94031 | running_mean=0.94148 | time=2.14s
          fold 1/5 | acc=0.93969 | running_mean=0.93969 | time=6.27s
          fold 2/5 | acc=0.93990 | running_mean=0.93979 | time=5.56s
          fold 3/5 | acc=0.94125 | running_mean=0.94028 | time=6.09s
          fold 4/5 | acc=0.94031 | running_mean=0.94029 | time=5.30s
          fold 5/5 | acc=0.94021 | running_mean=0.94027 | time=5.11s
          fold 1/5 | acc=0.92885 | running_mean=0.92885 | time=1.05s
          fold 2/5 | acc=0.92917 | running_mean=0.92901 | time=1.12s
          fold 3/5 | acc=0.93229 | running_mean=0.93010 | time=1.19s
          fold 4/5 | acc=0.93198 | running_mean=0.93057 | time=1.06s
          fold 5/5 | acc=0.93354 | running_mean=0.93117 | time=1.03s
          fold 1/5 | acc=0.94333 | running_mean=0.94333 | time=4.93s
          fold 2/5 | acc=0.94073 | running_mean=0.94203 | time=5.00s
          fold 3/5 | acc=0.94552 | running_mean=0.94319 | time=5.88s
          fold 4/5 | acc=0.94198 | running_mean=0.94289 | time=5.66s
          fold 5/5 | acc=0.94042 | running_mean=0.94240 | time=4.98s
          fold 1/5 | acc=0.94948 | running_mean=0.94948 | time=3.77s
          fold 2/5 | acc=0.94635 | running_mean=0.94792 | time=3.61s
          fold 3/5 | acc=0.95021 | running_mean=0.94868 | time=3.45s
          fold 4/5 | acc=0.94708 | running_mean=0.94828 | time=3.49s
          fold 5/5 | acc=0.94792 | running_mean=0.94821 | time=3.43s
          fold 1/5 | acc=0.94594 | running_mean=0.94594 | time=4.17s
          fold 2/5 | acc=0.94542 | running_mean=0.94568 | time=3.51s
          fold 3/5 | acc=0.94531 | running_mean=0.94556 | time=3.13s
          fold 4/5 | acc=0.94646 | running_mean=0.94578 | time=3.34s
          fold 5/5 | acc=0.94625 | running_mean=0.94588 | time=3.15s
          fold 1/5 | acc=0.94948 | running_mean=0.94948 | time=3.52s
          fold 2/5 | acc=0.94635 | running_mean=0.94792 | time=3.42s
          fold 3/5 | acc=0.95021 | running_mean=0.94868 | time=3.87s
          fold 4/5 | acc=0.94708 | running_mean=0.94828 | time=3.46s
          fold 5/5 | acc=0.94792 | running_mean=0.94821 | time=3.37s
          fold 1/5 | acc=0.94927 | running_mean=0.94927 | time=3.95s
          fold 2/5 | acc=0.94719 | running_mean=0.94823 | time=3.68s
          fold 3/5 | acc=0.94958 | running_mean=0.94868 | time=3.75s
          fold 4/5 | acc=0.94635 | running_mean=0.94810 | time=3.71s
          fold 5/5 | acc=0.94635 | running_mean=0.94775 | time=3.67s
          fold 1/5 | acc=0.94865 | running_mean=0.94865 | time=4.17s
          fold 2/5 | acc=0.94698 | running_mean=0.94781 | time=5.72s
          fold 3/5 | acc=0.94760 | running_mean=0.94774 | time=4.38s
          fold 4/5 | acc=0.94688 | running_mean=0.94753 | time=3.60s
          fold 5/5 | acc=0.94781 | running_mean=0.94758 | time=4.85s
          fold 1/5 | acc=0.94865 | running_mean=0.94865 | time=13.01s
          fold 2/5 | acc=0.94708 | running_mean=0.94786 | time=14.23s
          fold 3/5 | acc=0.94844 | running_mean=0.94806 | time=14.68s
          fold 4/5 | acc=0.94406 | running_mean=0.94706 | time=14.51s
          fold 5/5 | acc=0.94646 | running_mean=0.94694 | time=14.43s
          fold 1/5 | acc=0.94927 | running_mean=0.94927 | time=14.06s
          fold 2/5 | acc=0.94719 | running_mean=0.94823 | time=12.61s
          fold 3/5 | acc=0.94958 | running_mean=0.94868 | time=14.23s
          fold 4/5 | acc=0.94635 | running_mean=0.94810 | time=16.49s
          fold 5/5 | acc=0.94635 | running_mean=0.94775 | time=15.86s
          fold 1/5 | acc=0.93573 | running_mean=0.93573 | time=5.16s
          fold 2/5 | acc=0.93792 | running_mean=0.93682 | time=5.38s
          fold 3/5 | acc=0.94052 | running_mean=0.93806 | time=5.50s
          fold 4/5 | acc=0.93906 | running_mean=0.93831 | time=6.23s
          fold 5/5 | acc=0.94063 | running_mean=0.93877 | time=5.47s
          fold 1/5 | acc=0.94260 | running_mean=0.94260 | time=18.07s
          fold 2/5 | acc=0.94219 | running_mean=0.94240 | time=17.99s
          fold 3/5 | acc=0.94177 | running_mean=0.94219 | time=8.08s
          fold 4/5 | acc=0.94354 | running_mean=0.94253 | time=4.78s
          fold 5/5 | acc=0.94125 | running_mean=0.94227 | time=4.87s
  [TPE KNN] Time: 1417.12s | Memory Δ:    -5.8MB | Peak:   236.5MB
  [TPE Eval KNN] Time:  302.90s | Memory Δ:    +5.4MB | Peak:   241.9MB
       Memory cleanup -> gc_collected=64, available=2.18 GB, used=86.1%, rss=241.9 MB
       Exported TPE artifacts

{'status': 'completed',
 'best':   Model Optimal_Scaler  Best_CV_Mean  Best_Trial  n_neighbors   weights     metric  p
 0   KNN            Raw      0.948792          15           14  distance  manhattan  2,
 'history':    Model  Trial   CV_Mean  Best_Score_So_Far  Trial_Runtime_Sec
 0    KNN      1  0.938229           0.938229          22.141844
 1    KNN      2  0.944458           0.944458          40.416381
 2    KNN      3  0.940771           0.944458          13.994381
 3    KNN      4  0.944792           0.944792          25.011768
 4    KNN      5  0.936625           0.944792          58.935730
 5    KNN      6  0.937708           0.944792          19.460663
 6    KNN      7  0.904250           0.944792           9.520929
 7    KNN      8  0.935417           0.944792          10.341043
 8    KNN      9  0.939042           0.944792          25.084353
 9    KNN     10  0.948000           0.948000          28.097034
 10   KNN     11  0.938229           0.948000          55.948703
 11   KNN     12  0.948104           0.948104          29.275149
 12   KNN     13  0.948104           0.948104          31.294019
 13   KNN     14  0.948000           0.948104          44.524841
 14   KNN     15  0.944896           0.948104          36.389819
 15   KNN     16  0.948792           0.948792          25.974081
 16   KNN     17  0.941521           0.948792          14.992030
 17   KNN     18  0.947583           0.948792          30.367909
 18   KNN     19  0.946458           0.948792          32.169312
 19   KNN     20  0.945146           0.948792          34.336022
 20   KNN     21  0.937729           0.948792          58.741329
 21   KNN     22  0.948208           0.948792          26.660894
 22   KNN     23  0.947042           0.948792          22.691491
 23   KNN     24  0.947479           0.948792          19.007422
 24   KNN     25  0.945771           0.948792          28.385881
 25   KNN     26  0.943917           0.948792          38.317638
 26   KNN     27  0.925292           0.948792          14.725006
 27   KNN     28  0.947292           0.948792          27.639940
 28   KNN     29  0.947958           0.948792          23.864082
 29   KNN     30  0.940333           0.948792          23.427079
 30   KNN     31  0.941292           0.948792          12.980324
 31   KNN     32  0.948208           0.948792          33.269314
 32   KNN     33  0.947958           0.948792          28.217726
 33   KNN     34  0.945875           0.948792          19.349435
 34   KNN     35  0.946917           0.948792          22.991820
 35   KNN     36  0.948208           0.948792          21.196132
 36   KNN     37  0.944875           0.948792          15.584162
 37   KNN     38  0.941479           0.948792          11.326933
 38   KNN     39  0.940271           0.948792          28.349233
 39   KNN     40  0.931167           0.948792           5.479256
 40   KNN     41  0.942396           0.948792          26.467636
 41   KNN     42  0.948208           0.948792          17.764552
 42   KNN     43  0.945875           0.948792          17.319557
 43   KNN     44  0.948208           0.948792          17.657538
 44   KNN     45  0.947750           0.948792          18.777603
 45   KNN     46  0.947583           0.948792          22.742151
 46   KNN     47  0.946937           0.948792          70.880752
 47   KNN     48  0.947750           0.948792          73.305189
 48   KNN     49  0.938771           0.948792          27.808931
 49   KNN     50  0.942271           0.948792          53.890244,
 'summary':   Method Model Optimal_Scaler      Split  Accuracy  Precision    Recall        F1     Kappa       MCC       AUC   LogLoss  Accuracy_CI_Lower  Accuracy_CI_Upper  Precision_CI_Lower  Precision_CI_Upper  Recall_CI_Lower  Recall_CI_Upper  F1_CI_Lower  F1_CI_Upper  AUC_CI_Lower  AUC_CI_Upper  LogLoss_CI_Lower  LogLoss_CI_Upper  Kappa_CI_Lower  Kappa_CI_Upper  MCC_CI_Lower  MCC_CI_Upper
 0    TPE   KNN            Raw  Train_OOF  0.948792   0.954848  0.965387  0.960088  0.888670  0.888774  0.989347  0.165914           0.946729           0.950751            0.952365            0.957239         0.963275         0.967325     0.958441     0.961646      0.988698      0.989979          0.161283          0.170649        0.884242        0.893008      0.884382      0.893109
 1    TPE   KNN            Raw       Test  0.954167   0.958097  0.970611  0.964314  0.900278  0.900426  0.991358  0.154924           0.950415           0.957833            0.953728            0.962418         0.966811         0.974262     0.961318     0.967174      0.990149      0.992418          0.146934          0.164491        0.892164        0.908336      0.892237      0.908465,
 'timing':   Model  TPE_Search_Sec  TPE_Evaluation_Sec  TPE_Total_Sec  Best_CV_Mean
 0   KNN     1417.116819          302.902124    1720.238873      0.948792}

In [40]:
run_tpe_model("LinearSVC")

LinearSVC  | Scaler: Power      | Available RAM: 2.19 GB | Kernel RSS: 237.5 MB
       Memory cleanup -> gc_collected=0, available=2.19 GB, used=86.1%, rss=237.5 MB
       Running 50 trials with n_jobs_cv=1, n_jobs_opt=8
          fold 1/5 | acc=0.88156 | running_mean=0.88156 | time=0.43s
          fold 2/5 | acc=0.88562 | running_mean=0.88359 | time=0.52s
          fold 3/5 | acc=0.88094 | running_mean=0.88271 | time=0.48s
          fold 4/5 | acc=0.88313 | running_mean=0.88281 | time=0.56s
          fold 5/5 | acc=0.88177 | running_mean=0.88260 | time=0.55s
          fold 1/5 | acc=0.89219 | running_mean=0.89219 | time=0.55s
          fold 2/5 | acc=0.89635 | running_mean=0.89427 | time=0.51s
          fold 3/5 | acc=0.89042 | running_mean=0.89299 | time=0.53s
          fold 4/5 | acc=0.89531 | running_mean=0.89357 | time=0.54s
          fold 5/5 | acc=0.89927 | running_mean=0.89471 | time=0.56s
          fold 1/5 | acc=0.84375 | running_mean=0.84375 | time=0.49s
          fold 2/5 | acc=0.84635 | running_mean=0.84505 | time=0.48s
          fold 3/5 | acc=0.84365 | running_mean=0.84458 | time=0.49s
          fold 4/5 | acc=0.84656 | running_mean=0.84508 | time=0.45s
          fold 5/5 | acc=0.84396 | running_mean=0.84485 | time=0.47s
          fold 1/5 | acc=0.89656 | running_mean=0.89656 | time=0.58s
          fold 2/5 | acc=0.89604 | running_mean=0.89630 | time=0.63s
          fold 3/5 | acc=0.89333 | running_mean=0.89531 | time=0.67s
          fold 4/5 | acc=0.89771 | running_mean=0.89591 | time=0.69s
          fold 5/5 | acc=0.90156 | running_mean=0.89704 | time=0.85s
          fold 1/5 | acc=0.89708 | running_mean=0.89708 | time=1.70s
          fold 2/5 | acc=0.89635 | running_mean=0.89672 | time=2.16s
          fold 3/5 | acc=0.89312 | running_mean=0.89552 | time=2.38s
          fold 4/5 | acc=0.89708 | running_mean=0.89591 | time=1.71s
          fold 5/5 | acc=0.90115 | running_mean=0.89696 | time=1.74s
          fold 1/5 | acc=0.87406 | running_mean=0.87406 | time=0.84s
          fold 2/5 | acc=0.87969 | running_mean=0.87687 | time=0.64s
          fold 3/5 | acc=0.87438 | running_mean=0.87604 | time=0.63s
          fold 4/5 | acc=0.87677 | running_mean=0.87622 | time=0.53s
          fold 5/5 | acc=0.87562 | running_mean=0.87610 | time=0.65s
          fold 1/5 | acc=0.89219 | running_mean=0.89219 | time=0.67s
          fold 2/5 | acc=0.89677 | running_mean=0.89448 | time=0.61s
          fold 3/5 | acc=0.88958 | running_mean=0.89285 | time=0.58s
          fold 4/5 | acc=0.89406 | running_mean=0.89315 | time=0.59s
          fold 5/5 | acc=0.89719 | running_mean=0.89396 | time=0.58s
          fold 1/5 | acc=0.87021 | running_mean=0.87021 | time=0.54s
          fold 2/5 | acc=0.87510 | running_mean=0.87266 | time=0.51s
          fold 3/5 | acc=0.86990 | running_mean=0.87174 | time=0.55s
          fold 4/5 | acc=0.87365 | running_mean=0.87221 | time=0.52s
          fold 5/5 | acc=0.87021 | running_mean=0.87181 | time=0.69s
          fold 1/5 | acc=0.89000 | running_mean=0.89000 | time=0.59s
          fold 2/5 | acc=0.89333 | running_mean=0.89167 | time=0.68s
          fold 3/5 | acc=0.88635 | running_mean=0.88990 | time=0.47s
          fold 4/5 | acc=0.89031 | running_mean=0.89000 | time=0.57s
          fold 5/5 | acc=0.89052 | running_mean=0.89010 | time=0.62s
          fold 1/5 | acc=0.89156 | running_mean=0.89156 | time=0.59s
          fold 2/5 | acc=0.89604 | running_mean=0.89380 | time=0.56s
          fold 3/5 | acc=0.88781 | running_mean=0.89181 | time=0.52s
          fold 4/5 | acc=0.89250 | running_mean=0.89198 | time=0.51s
          fold 5/5 | acc=0.89438 | running_mean=0.89246 | time=0.54s
          fold 1/5 | acc=0.89667 | running_mean=0.89667 | time=0.83s
          fold 2/5 | acc=0.89594 | running_mean=0.89630 | time=0.68s
          fold 3/5 | acc=0.89365 | running_mean=0.89542 | time=0.64s
          fold 4/5 | acc=0.89760 | running_mean=0.89596 | time=0.58s
          fold 5/5 | acc=0.90125 | running_mean=0.89702 | time=0.59s
          fold 1/5 | acc=0.89667 | running_mean=0.89667 | time=0.60s
          fold 2/5 | acc=0.89594 | running_mean=0.89630 | time=0.62s
          fold 3/5 | acc=0.89365 | running_mean=0.89542 | time=0.55s
          fold 4/5 | acc=0.89760 | running_mean=0.89596 | time=0.55s
          fold 5/5 | acc=0.90125 | running_mean=0.89702 | time=0.60s
          fold 1/5 | acc=0.89677 | running_mean=0.89677 | time=0.62s
          fold 2/5 | acc=0.89583 | running_mean=0.89630 | time=0.59s
          fold 3/5 | acc=0.89344 | running_mean=0.89535 | time=0.58s
          fold 4/5 | acc=0.89760 | running_mean=0.89591 | time=0.61s
          fold 5/5 | acc=0.90115 | running_mean=0.89696 | time=0.67s
          fold 1/5 | acc=0.89667 | running_mean=0.89667 | time=0.64s
          fold 2/5 | acc=0.89594 | running_mean=0.89630 | time=0.63s
          fold 3/5 | acc=0.89365 | running_mean=0.89542 | time=0.56s
          fold 4/5 | acc=0.89760 | running_mean=0.89596 | time=0.57s
          fold 5/5 | acc=0.90125 | running_mean=0.89702 | time=0.59s
          fold 1/5 | acc=0.89677 | running_mean=0.89677 | time=0.61s
          fold 2/5 | acc=0.89573 | running_mean=0.89625 | time=0.62s
          fold 3/5 | acc=0.89344 | running_mean=0.89531 | time=0.57s
          fold 4/5 | acc=0.89771 | running_mean=0.89591 | time=0.58s
          fold 5/5 | acc=0.90115 | running_mean=0.89696 | time=0.62s
          fold 1/5 | acc=0.89677 | running_mean=0.89677 | time=0.68s
          fold 2/5 | acc=0.89573 | running_mean=0.89625 | time=0.63s
          fold 3/5 | acc=0.89365 | running_mean=0.89538 | time=0.66s
          fold 4/5 | acc=0.89760 | running_mean=0.89594 | time=0.68s
          fold 5/5 | acc=0.90125 | running_mean=0.89700 | time=0.72s
          fold 1/5 | acc=0.89667 | running_mean=0.89667 | time=0.69s
          fold 2/5 | acc=0.89604 | running_mean=0.89635 | time=0.79s
          fold 3/5 | acc=0.89354 | running_mean=0.89542 | time=0.69s
          fold 4/5 | acc=0.89760 | running_mean=0.89596 | time=0.67s
          fold 5/5 | acc=0.90104 | running_mean=0.89698 | time=0.69s
          fold 1/5 | acc=0.89677 | running_mean=0.89677 | time=0.76s
          fold 2/5 | acc=0.89594 | running_mean=0.89635 | time=0.69s
          fold 3/5 | acc=0.89365 | running_mean=0.89545 | time=0.68s
          fold 4/5 | acc=0.89771 | running_mean=0.89602 | time=0.63s
          fold 5/5 | acc=0.90125 | running_mean=0.89706 | time=0.71s
          fold 1/5 | acc=0.89677 | running_mean=0.89677 | time=0.64s
          fold 2/5 | acc=0.89594 | running_mean=0.89635 | time=0.64s
          fold 3/5 | acc=0.89365 | running_mean=0.89545 | time=0.77s
          fold 4/5 | acc=0.89760 | running_mean=0.89599 | time=0.76s
          fold 5/5 | acc=0.90125 | running_mean=0.89704 | time=0.81s
          fold 1/5 | acc=0.89667 | running_mean=0.89667 | time=0.84s
          fold 2/5 | acc=0.89594 | running_mean=0.89630 | time=1.10s
          fold 3/5 | acc=0.89365 | running_mean=0.89542 | time=0.75s
          fold 4/5 | acc=0.89771 | running_mean=0.89599 | time=0.89s
          fold 5/5 | acc=0.90125 | running_mean=0.89704 | time=0.91s
          fold 1/5 | acc=0.89333 | running_mean=0.89333 | time=1.16s
          fold 2/5 | acc=0.89458 | running_mean=0.89396 | time=0.96s
          fold 3/5 | acc=0.89167 | running_mean=0.89319 | time=0.85s
          fold 4/5 | acc=0.89729 | running_mean=0.89422 | time=0.75s
          fold 5/5 | acc=0.90083 | running_mean=0.89554 | time=0.94s
          fold 1/5 | acc=0.89667 | running_mean=0.89667 | time=0.86s
          fold 2/5 | acc=0.89563 | running_mean=0.89615 | time=0.71s
          fold 3/5 | acc=0.89365 | running_mean=0.89531 | time=0.64s
          fold 4/5 | acc=0.89771 | running_mean=0.89591 | time=0.63s
          fold 5/5 | acc=0.90125 | running_mean=0.89698 | time=0.62s
          fold 1/5 | acc=0.89667 | running_mean=0.89667 | time=0.60s
          fold 2/5 | acc=0.89563 | running_mean=0.89615 | time=0.70s
          fold 3/5 | acc=0.89365 | running_mean=0.89531 | time=0.74s
          fold 4/5 | acc=0.89771 | running_mean=0.89591 | time=0.94s
          fold 5/5 | acc=0.90125 | running_mean=0.89698 | time=1.00s
          fold 1/5 | acc=0.89677 | running_mean=0.89677 | time=0.88s
          fold 2/5 | acc=0.89573 | running_mean=0.89625 | time=0.71s
          fold 3/5 | acc=0.89354 | running_mean=0.89535 | time=0.65s
          fold 4/5 | acc=0.89760 | running_mean=0.89591 | time=0.69s
          fold 5/5 | acc=0.90125 | running_mean=0.89698 | time=0.81s
          fold 1/5 | acc=0.89667 | running_mean=0.89667 | time=0.68s
          fold 2/5 | acc=0.89583 | running_mean=0.89625 | time=0.62s
          fold 3/5 | acc=0.89365 | running_mean=0.89538 | time=0.69s
          fold 4/5 | acc=0.89760 | running_mean=0.89594 | time=0.83s
          fold 5/5 | acc=0.90125 | running_mean=0.89700 | time=0.65s
          fold 1/5 | acc=0.89656 | running_mean=0.89656 | time=0.68s
          fold 2/5 | acc=0.89604 | running_mean=0.89630 | time=0.69s
          fold 3/5 | acc=0.89333 | running_mean=0.89531 | time=0.65s
          fold 4/5 | acc=0.89760 | running_mean=0.89589 | time=0.67s
          fold 5/5 | acc=0.90115 | running_mean=0.89694 | time=0.68s
          fold 1/5 | acc=0.89677 | running_mean=0.89677 | time=0.68s
          fold 2/5 | acc=0.89573 | running_mean=0.89625 | time=0.75s
          fold 3/5 | acc=0.89354 | running_mean=0.89535 | time=0.82s
          fold 4/5 | acc=0.89760 | running_mean=0.89591 | time=0.68s
          fold 5/5 | acc=0.90125 | running_mean=0.89698 | time=0.74s
          fold 1/5 | acc=0.88615 | running_mean=0.88615 | time=0.87s
          fold 2/5 | acc=0.89219 | running_mean=0.88917 | time=0.64s
          fold 3/5 | acc=0.88438 | running_mean=0.88757 | time=0.71s
          fold 4/5 | acc=0.88896 | running_mean=0.88792 | time=0.73s
          fold 5/5 | acc=0.88667 | running_mean=0.88767 | time=0.64s
          fold 1/5 | acc=0.89667 | running_mean=0.89667 | time=0.63s
          fold 2/5 | acc=0.89583 | running_mean=0.89625 | time=0.73s
          fold 3/5 | acc=0.89365 | running_mean=0.89538 | time=0.68s
          fold 4/5 | acc=0.89760 | running_mean=0.89594 | time=0.63s
          fold 5/5 | acc=0.90125 | running_mean=0.89700 | time=0.67s
          fold 1/5 | acc=0.89542 | running_mean=0.89542 | time=0.61s
          fold 2/5 | acc=0.89667 | running_mean=0.89604 | time=0.62s
          fold 3/5 | acc=0.89208 | running_mean=0.89472 | time=0.60s
          fold 4/5 | acc=0.89667 | running_mean=0.89521 | time=1.01s
          fold 5/5 | acc=0.90115 | running_mean=0.89640 | time=0.90s
          fold 1/5 | acc=0.88917 | running_mean=0.88917 | time=0.64s
          fold 2/5 | acc=0.89406 | running_mean=0.89161 | time=0.67s
          fold 3/5 | acc=0.88604 | running_mean=0.88976 | time=0.61s
          fold 4/5 | acc=0.88969 | running_mean=0.88974 | time=0.60s
          fold 5/5 | acc=0.88938 | running_mean=0.88967 | time=0.58s
          fold 1/5 | acc=0.89667 | running_mean=0.89667 | time=0.62s
          fold 2/5 | acc=0.89594 | running_mean=0.89630 | time=0.87s
          fold 3/5 | acc=0.89333 | running_mean=0.89531 | time=1.29s
          fold 4/5 | acc=0.89771 | running_mean=0.89591 | time=1.21s
          fold 5/5 | acc=0.90156 | running_mean=0.89704 | time=1.15s
          fold 1/5 | acc=0.89677 | running_mean=0.89677 | time=0.92s
          fold 2/5 | acc=0.89583 | running_mean=0.89630 | time=0.71s
          fold 3/5 | acc=0.89344 | running_mean=0.89535 | time=0.68s
          fold 4/5 | acc=0.89760 | running_mean=0.89591 | time=0.67s
          fold 5/5 | acc=0.90125 | running_mean=0.89698 | time=0.66s
          fold 1/5 | acc=0.89490 | running_mean=0.89490 | time=0.70s
          fold 2/5 | acc=0.89563 | running_mean=0.89526 | time=0.60s
          fold 3/5 | acc=0.89271 | running_mean=0.89441 | time=0.64s
          fold 4/5 | acc=0.89687 | running_mean=0.89503 | time=0.58s
          fold 5/5 | acc=0.90094 | running_mean=0.89621 | time=0.60s
          fold 1/5 | acc=0.89729 | running_mean=0.89729 | time=2.67s
          fold 2/5 | acc=0.89573 | running_mean=0.89651 | time=2.50s
          fold 3/5 | acc=0.89365 | running_mean=0.89556 | time=2.33s
          fold 4/5 | acc=0.89760 | running_mean=0.89607 | time=2.58s
          fold 5/5 | acc=0.90177 | running_mean=0.89721 | time=4.59s
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=4.43s
          fold 2/5 | acc=0.89698 | running_mean=0.89693 | time=3.22s
          fold 3/5 | acc=0.89375 | running_mean=0.89587 | time=2.79s
          fold 4/5 | acc=0.89687 | running_mean=0.89612 | time=2.76s
          fold 5/5 | acc=0.90208 | running_mean=0.89731 | time=4.12s
          fold 1/5 | acc=0.89635 | running_mean=0.89635 | time=4.79s
          fold 2/5 | acc=0.89667 | running_mean=0.89651 | time=3.93s
          fold 3/5 | acc=0.89344 | running_mean=0.89549 | time=3.88s
          fold 4/5 | acc=0.89677 | running_mean=0.89581 | time=3.65s
          fold 5/5 | acc=0.90240 | running_mean=0.89712 | time=3.89s
          fold 1/5 | acc=0.89677 | running_mean=0.89677 | time=5.13s
          fold 2/5 | acc=0.89646 | running_mean=0.89661 | time=4.07s
          fold 3/5 | acc=0.89365 | running_mean=0.89563 | time=6.36s
          fold 4/5 | acc=0.89750 | running_mean=0.89609 | time=4.79s
          fold 5/5 | acc=0.90125 | running_mean=0.89712 | time=4.84s
          fold 1/5 | acc=0.89719 | running_mean=0.89719 | time=6.63s
          fold 2/5 | acc=0.89615 | running_mean=0.89667 | time=4.82s
          fold 3/5 | acc=0.89354 | running_mean=0.89563 | time=4.42s
          fold 4/5 | acc=0.89677 | running_mean=0.89591 | time=4.97s
          fold 5/5 | acc=0.90177 | running_mean=0.89708 | time=5.46s
          fold 1/5 | acc=0.89740 | running_mean=0.89740 | time=7.20s
          fold 2/5 | acc=0.89635 | running_mean=0.89687 | time=5.79s
          fold 3/5 | acc=0.89385 | running_mean=0.89587 | time=5.64s
          fold 4/5 | acc=0.89750 | running_mean=0.89628 | time=5.64s
          fold 5/5 | acc=0.90052 | running_mean=0.89712 | time=5.59s
          fold 1/5 | acc=0.89635 | running_mean=0.89635 | time=5.46s
          fold 2/5 | acc=0.89542 | running_mean=0.89589 | time=4.89s
          fold 3/5 | acc=0.89281 | running_mean=0.89486 | time=6.86s
          fold 4/5 | acc=0.89854 | running_mean=0.89578 | time=9.62s
          fold 5/5 | acc=0.89948 | running_mean=0.89652 | time=9.16s
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=4.60s
          fold 2/5 | acc=0.89604 | running_mean=0.89646 | time=3.78s
          fold 3/5 | acc=0.89365 | running_mean=0.89552 | time=4.14s
          fold 4/5 | acc=0.89698 | running_mean=0.89589 | time=4.47s
          fold 5/5 | acc=0.90083 | running_mean=0.89687 | time=3.33s
          fold 1/5 | acc=0.83875 | running_mean=0.83875 | time=0.55s
          fold 2/5 | acc=0.84167 | running_mean=0.84021 | time=0.53s
          fold 3/5 | acc=0.83979 | running_mean=0.84007 | time=0.98s
          fold 4/5 | acc=0.84135 | running_mean=0.84039 | time=0.75s
          fold 5/5 | acc=0.83885 | running_mean=0.84008 | time=0.66s
          fold 1/5 | acc=0.89760 | running_mean=0.89760 | time=1.49s
          fold 2/5 | acc=0.89646 | running_mean=0.89703 | time=1.61s
          fold 3/5 | acc=0.89354 | running_mean=0.89587 | time=1.56s
          fold 4/5 | acc=0.89729 | running_mean=0.89622 | time=1.58s
          fold 5/5 | acc=0.90104 | running_mean=0.89719 | time=1.32s
          fold 1/5 | acc=0.89719 | running_mean=0.89719 | time=1.27s
          fold 2/5 | acc=0.89646 | running_mean=0.89682 | time=1.24s
          fold 3/5 | acc=0.89292 | running_mean=0.89552 | time=1.14s
          fold 4/5 | acc=0.89719 | running_mean=0.89594 | time=1.11s
          fold 5/5 | acc=0.90094 | running_mean=0.89694 | time=1.29s
          fold 1/5 | acc=0.89698 | running_mean=0.89698 | time=8.11s
          fold 2/5 | acc=0.89656 | running_mean=0.89677 | time=11.68s
          fold 3/5 | acc=0.89417 | running_mean=0.89590 | time=6.25s
          fold 4/5 | acc=0.89583 | running_mean=0.89589 | time=7.03s
          fold 5/5 | acc=0.90229 | running_mean=0.89717 | time=6.74s
          fold 1/5 | acc=0.89719 | running_mean=0.89719 | time=6.62s
          fold 2/5 | acc=0.89281 | running_mean=0.89500 | time=7.70s
          fold 3/5 | acc=0.89406 | running_mean=0.89469 | time=11.81s
          fold 4/5 | acc=0.89635 | running_mean=0.89510 | time=23.63s
          fold 5/5 | acc=0.90094 | running_mean=0.89627 | time=31.38s
          fold 1/5 | acc=0.89625 | running_mean=0.89625 | time=2.96s
          fold 2/5 | acc=0.89635 | running_mean=0.89630 | time=2.63s
          fold 3/5 | acc=0.89323 | running_mean=0.89528 | time=2.87s
          fold 4/5 | acc=0.89687 | running_mean=0.89568 | time=3.25s
          fold 5/5 | acc=0.90104 | running_mean=0.89675 | time=2.98s
          fold 1/5 | acc=0.89750 | running_mean=0.89750 | time=4.71s
          fold 2/5 | acc=0.89698 | running_mean=0.89724 | time=4.90s
          fold 3/5 | acc=0.89365 | running_mean=0.89604 | time=4.34s
          fold 4/5 | acc=0.89729 | running_mean=0.89635 | time=7.11s
          fold 5/5 | acc=0.90083 | running_mean=0.89725 | time=5.64s
          fold 1/5 | acc=0.89719 | running_mean=0.89719 | time=5.45s
          fold 2/5 | acc=0.89656 | running_mean=0.89688 | time=5.34s
          fold 3/5 | acc=0.89344 | running_mean=0.89573 | time=6.87s
          fold 4/5 | acc=0.89677 | running_mean=0.89599 | time=7.04s
          fold 5/5 | acc=0.90135 | running_mean=0.89706 | time=6.28s
  [TPE LinearSVC] Time:  522.68s | Memory Δ:   -34.6MB | Peak:   202.9MB
  [TPE Eval LinearSVC] Time:  203.29s | Memory Δ:    +0.6MB | Peak:   203.6MB
       Memory cleanup -> gc_collected=64, available=2.11 GB, used=86.6%, rss=203.7 MB
       Exported TPE artifacts

{'status': 'completed',
 'best':        Model Optimal_Scaler  Best_CV_Mean  Best_Trial          C   loss
 0  LinearSVC          Power      0.897312          35  31.523392  hinge,
 'history':         Model  Trial   CV_Mean  Best_Score_So_Far  Trial_Runtime_Sec
 0   LinearSVC      1  0.882604           0.882604           2.554715
 1   LinearSVC      2  0.894708           0.894708           2.705660
 2   LinearSVC      3  0.844854           0.894708           2.408250
 3   LinearSVC      4  0.897042           0.897042           3.438370
 4   LinearSVC      5  0.896958           0.897042           9.717074
 5   LinearSVC      6  0.876104           0.897042           3.306910
 6   LinearSVC      7  0.893958           0.897042           3.048569
 7   LinearSVC      8  0.871813           0.897042           2.832639
 8   LinearSVC      9  0.890104           0.897042           2.952895
 9   LinearSVC     10  0.892458           0.897042           2.740367
 10  LinearSVC     11  0.897021           0.897042           3.334190
 11  LinearSVC     12  0.897021           0.897042           2.948311
 12  LinearSVC     13  0.896958           0.897042           3.093072
 13  LinearSVC     14  0.897021           0.897042           3.012145
 14  LinearSVC     15  0.896958           0.897042           3.018281
 15  LinearSVC     16  0.897000           0.897042           3.401046
 16  LinearSVC     17  0.896979           0.897042           3.554833
 17  LinearSVC     18  0.897062           0.897062           3.503968
 18  LinearSVC     19  0.897042           0.897062           3.644989
 19  LinearSVC     20  0.897042           0.897062           4.511291
 20  LinearSVC     21  0.895542           0.897062           4.689122
 21  LinearSVC     22  0.896979           0.897062           3.479559
 22  LinearSVC     23  0.896979           0.897062           3.992529
 23  LinearSVC     24  0.896979           0.897062           3.783054
 24  LinearSVC     25  0.897000           0.897062           3.493498
 25  LinearSVC     26  0.896937           0.897062           3.384461
 26  LinearSVC     27  0.896979           0.897062           3.690862
 27  LinearSVC     28  0.887667           0.897062           3.607755
 28  LinearSVC     29  0.897000           0.897062           3.359788
 29  LinearSVC     30  0.896396           0.897062           3.767414
 30  LinearSVC     31  0.889667           0.897062           3.119886
 31  LinearSVC     32  0.897042           0.897062           5.160998
 32  LinearSVC     33  0.896979           0.897062           3.669852
 33  LinearSVC     34  0.896208           0.897062           3.133965
 34  LinearSVC     35  0.897208           0.897208          14.685967
 35  LinearSVC     36  0.897312           0.897312          17.348958
 36  LinearSVC     37  0.897125           0.897312          20.163857
 37  LinearSVC     38  0.897125           0.897312          25.216752
 38  LinearSVC     39  0.897083           0.897312          26.318246
 39  LinearSVC     40  0.897125           0.897312          29.882093
 40  LinearSVC     41  0.896521           0.897312          36.011309
 41  LinearSVC     42  0.896875           0.897312          20.339152
 42  LinearSVC     43  0.840083           0.897312           3.486093
 43  LinearSVC     44  0.897188           0.897312           7.585824
 44  LinearSVC     45  0.896937           0.897312           6.077100
 45  LinearSVC     46  0.897167           0.897312          39.825596
 46  LinearSVC     47  0.896271           0.897312          81.181672
 47  LinearSVC     48  0.896750           0.897312          14.719336
 48  LinearSVC     49  0.897250           0.897312          26.739736
 49  LinearSVC     50  0.897062           0.897312          31.019745,
 'summary':   Method      Model Optimal_Scaler      Split  Accuracy  Precision    Recall        F1     Kappa       MCC       AUC  LogLoss  Accuracy_CI_Lower  Accuracy_CI_Upper  Precision_CI_Lower  Precision_CI_Upper  Recall_CI_Lower  Recall_CI_Upper  F1_CI_Lower  F1_CI_Upper  AUC_CI_Lower  AUC_CI_Upper  LogLoss_CI_Lower  LogLoss_CI_Upper  Kappa_CI_Lower  Kappa_CI_Upper  MCC_CI_Lower  MCC_CI_Upper
 0    TPE  LinearSVC          Power  Train_OOF  0.897312   0.916356  0.923328  0.919829  0.777044  0.777087  0.965966      NaN           0.894625           0.900146            0.913219            0.919614         0.920349         0.926345     0.917546     0.922147      0.964718      0.967305               NaN               NaN        0.771274        0.783100      0.771305      0.783152
 1    TPE  LinearSVC          Power       Test  0.904917   0.919835  0.932210  0.925981  0.793092  0.793230  0.968480      NaN           0.899583           0.910250            0.913692            0.925736         0.926558         0.937795     0.921642     0.930314      0.965987      0.971014               NaN               NaN        0.781779        0.804618      0.781893      0.804754,
 'timing':        Model  TPE_Search_Sec  TPE_Evaluation_Sec  TPE_Total_Sec  Best_CV_Mean
 0  LinearSVC      522.683788          203.284943     726.566456      0.897312}

In [46]:
run_tpe_model("SVM")

SVM        | Scaler: Standard   | Available RAM: 6.03 GB | Kernel RSS: 217.7 MB
       Memory cleanup -> gc_collected=67, available=6.03 GB, used=61.7%, rss=217.7 MB
       Running 50 trials with n_jobs_cv=1, n_jobs_opt=8
          fold 1/5 | acc=0.97969 | running_mean=0.97969 | time=46.62s
          fold 2/5 | acc=0.97708 | running_mean=0.97839 | time=44.79s
          fold 3/5 | acc=0.97573 | running_mean=0.97750 | time=44.58s
          fold 4/5 | acc=0.97844 | running_mean=0.97773 | time=45.44s
          fold 5/5 | acc=0.97917 | running_mean=0.97802 | time=45.17s
          fold 1/5 | acc=0.98427 | running_mean=0.98427 | time=296.68s
          fold 2/5 | acc=0.98375 | running_mean=0.98401 | time=344.14s
          fold 3/5 | acc=0.98104 | running_mean=0.98302 | time=285.99s
          fold 4/5 | acc=0.98104 | running_mean=0.98253 | time=297.49s
          fold 5/5 | acc=0.98281 | running_mean=0.98258 | time=337.51s
          fold 1/5 | acc=0.96281 | running_mean=0.96281 | time=91.78s
          fold 2/5 | acc=0.96302 | running_mean=0.96292 | time=89.86s
          fold 3/5 | acc=0.96417 | running_mean=0.96333 | time=91.27s
          fold 4/5 | acc=0.96396 | running_mean=0.96349 | time=91.70s
          fold 5/5 | acc=0.96115 | running_mean=0.96302 | time=91.43s
          fold 1/5 | acc=0.98010 | running_mean=0.98010 | time=60.24s
          fold 2/5 | acc=0.97698 | running_mean=0.97854 | time=61.82s
          fold 3/5 | acc=0.97937 | running_mean=0.97882 | time=59.48s
          fold 4/5 | acc=0.98281 | running_mean=0.97982 | time=62.13s
          fold 5/5 | acc=0.97917 | running_mean=0.97969 | time=60.07s
          fold 1/5 | acc=0.74083 | running_mean=0.74083 | time=138.49s
          fold 2/5 | acc=0.73635 | running_mean=0.73859 | time=129.86s
          fold 3/5 | acc=0.74281 | running_mean=0.74000 | time=125.39s
          fold 4/5 | acc=0.73948 | running_mean=0.73987 | time=136.43s
          fold 5/5 | acc=0.73729 | running_mean=0.73935 | time=138.19s
          fold 1/5 | acc=0.99542 | running_mean=0.99542 | time=129.07s
          fold 2/5 | acc=0.99385 | running_mean=0.99464 | time=114.38s
          fold 3/5 | acc=0.99333 | running_mean=0.99420 | time=102.42s
          fold 4/5 | acc=0.99406 | running_mean=0.99417 | time=117.15s
          fold 5/5 | acc=0.99510 | running_mean=0.99435 | time=110.91s
          fold 1/5 | acc=0.72167 | running_mean=0.72167 | time=181.08s
          fold 2/5 | acc=0.71604 | running_mean=0.71885 | time=173.99s
          fold 3/5 | acc=0.71927 | running_mean=0.71899 | time=174.46s
          fold 4/5 | acc=0.72146 | running_mean=0.71961 | time=177.05s
          fold 5/5 | acc=0.72000 | running_mean=0.71969 | time=174.38s
          fold 1/5 | acc=0.96521 | running_mean=0.96521 | time=83.33s
          fold 2/5 | acc=0.96615 | running_mean=0.96568 | time=83.74s
          fold 3/5 | acc=0.96719 | running_mean=0.96618 | time=83.05s
          fold 4/5 | acc=0.96802 | running_mean=0.96664 | time=82.75s
          fold 5/5 | acc=0.96562 | running_mean=0.96644 | time=83.63s
          fold 1/5 | acc=0.98792 | running_mean=0.98792 | time=80.84s
          fold 2/5 | acc=0.98750 | running_mean=0.98771 | time=72.99s
          fold 3/5 | acc=0.98875 | running_mean=0.98806 | time=71.86s
          fold 4/5 | acc=0.98521 | running_mean=0.98734 | time=74.36s
          fold 5/5 | acc=0.98854 | running_mean=0.98758 | time=70.32s
          fold 1/5 | acc=0.98615 | running_mean=0.98615 | time=49.26s
          fold 2/5 | acc=0.98781 | running_mean=0.98698 | time=50.49s
          fold 3/5 | acc=0.98781 | running_mean=0.98726 | time=49.79s
          fold 4/5 | acc=0.98813 | running_mean=0.98747 | time=51.22s
          fold 5/5 | acc=0.98708 | running_mean=0.98740 | time=49.61s
          fold 1/5 | acc=0.80750 | running_mean=0.80750 | time=369.25s
          fold 2/5 | acc=0.81281 | running_mean=0.81016 | time=377.03s
          fold 3/5 | acc=0.81042 | running_mean=0.81024 | time=371.03s
          fold 4/5 | acc=0.81396 | running_mean=0.81117 | time=372.75s
          fold 5/5 | acc=0.80646 | running_mean=0.81023 | time=366.70s
          fold 1/5 | acc=0.99313 | running_mean=0.99313 | time=51.45s
          fold 2/5 | acc=0.99365 | running_mean=0.99339 | time=50.74s
          fold 3/5 | acc=0.99438 | running_mean=0.99372 | time=49.06s
          fold 4/5 | acc=0.99104 | running_mean=0.99305 | time=48.25s
          fold 5/5 | acc=0.99396 | running_mean=0.99323 | time=49.51s
          fold 1/5 | acc=0.99302 | running_mean=0.99302 | time=52.76s
          fold 2/5 | acc=0.99323 | running_mean=0.99313 | time=50.73s
          fold 3/5 | acc=0.99427 | running_mean=0.99351 | time=49.41s
          fold 4/5 | acc=0.99135 | running_mean=0.99297 | time=49.41s
          fold 5/5 | acc=0.99396 | running_mean=0.99317 | time=49.09s
          fold 1/5 | acc=0.99323 | running_mean=0.99323 | time=53.07s
          fold 2/5 | acc=0.99354 | running_mean=0.99339 | time=49.67s
          fold 3/5 | acc=0.99448 | running_mean=0.99375 | time=49.95s
          fold 4/5 | acc=0.99135 | running_mean=0.99315 | time=49.19s
          fold 5/5 | acc=0.99396 | running_mean=0.99331 | time=50.02s
          fold 1/5 | acc=0.98667 | running_mean=0.98667 | time=61.66s
          fold 2/5 | acc=0.98365 | running_mean=0.98516 | time=61.70s
          fold 3/5 | acc=0.98583 | running_mean=0.98538 | time=60.74s
          fold 4/5 | acc=0.98802 | running_mean=0.98604 | time=62.03s
          fold 5/5 | acc=0.98583 | running_mean=0.98600 | time=61.79s
          fold 1/5 | acc=0.99250 | running_mean=0.99250 | time=49.07s
          fold 2/5 | acc=0.99219 | running_mean=0.99234 | time=46.90s
          fold 3/5 | acc=0.99302 | running_mean=0.99257 | time=47.12s
          fold 4/5 | acc=0.99135 | running_mean=0.99227 | time=46.55s
          fold 5/5 | acc=0.99375 | running_mean=0.99256 | time=46.90s
          fold 1/5 | acc=0.74187 | running_mean=0.74187 | time=171.20s
          fold 2/5 | acc=0.73813 | running_mean=0.74000 | time=138.15s
          fold 3/5 | acc=0.74385 | running_mean=0.74128 | time=139.41s
          fold 4/5 | acc=0.73958 | running_mean=0.74086 | time=139.97s
          fold 5/5 | acc=0.73687 | running_mean=0.74006 | time=142.25s
          fold 1/5 | acc=0.99010 | running_mean=0.99010 | time=53.33s
          fold 2/5 | acc=0.98583 | running_mean=0.98797 | time=54.02s
          fold 3/5 | acc=0.98844 | running_mean=0.98813 | time=53.21s
          fold 4/5 | acc=0.98906 | running_mean=0.98836 | time=53.82s
          fold 5/5 | acc=0.98750 | running_mean=0.98819 | time=54.33s
          fold 1/5 | acc=0.99250 | running_mean=0.99250 | time=50.02s
          fold 2/5 | acc=0.99302 | running_mean=0.99276 | time=49.34s
          fold 3/5 | acc=0.99344 | running_mean=0.99299 | time=47.46s
          fold 4/5 | acc=0.99135 | running_mean=0.99258 | time=46.97s
          fold 5/5 | acc=0.99448 | running_mean=0.99296 | time=48.21s
          fold 1/5 | acc=0.82760 | running_mean=0.82760 | time=248.22s
          fold 2/5 | acc=0.83010 | running_mean=0.82885 | time=246.73s
          fold 3/5 | acc=0.82583 | running_mean=0.82785 | time=247.40s
          fold 4/5 | acc=0.82760 | running_mean=0.82779 | time=247.27s
          fold 5/5 | acc=0.82708 | running_mean=0.82765 | time=247.99s
          fold 1/5 | acc=0.97385 | running_mean=0.97385 | time=110.60s
          fold 2/5 | acc=0.97437 | running_mean=0.97411 | time=107.35s
          fold 3/5 | acc=0.97500 | running_mean=0.97441 | time=105.24s
          fold 4/5 | acc=0.97562 | running_mean=0.97471 | time=104.50s
          fold 5/5 | acc=0.97354 | running_mean=0.97448 | time=103.82s
          fold 1/5 | acc=0.99323 | running_mean=0.99323 | time=51.53s
          fold 2/5 | acc=0.99354 | running_mean=0.99339 | time=49.73s
          fold 3/5 | acc=0.99448 | running_mean=0.99375 | time=51.29s
          fold 4/5 | acc=0.99135 | running_mean=0.99315 | time=50.77s
          fold 5/5 | acc=0.99406 | running_mean=0.99333 | time=51.22s
          fold 1/5 | acc=0.99271 | running_mean=0.99271 | time=53.20s
          fold 2/5 | acc=0.99323 | running_mean=0.99297 | time=57.93s
          fold 3/5 | acc=0.99354 | running_mean=0.99316 | time=53.60s
          fold 4/5 | acc=0.99073 | running_mean=0.99255 | time=49.65s
          fold 5/5 | acc=0.99375 | running_mean=0.99279 | time=49.27s
          fold 1/5 | acc=0.99323 | running_mean=0.99323 | time=49.65s
          fold 2/5 | acc=0.99313 | running_mean=0.99318 | time=48.59s
          fold 3/5 | acc=0.99385 | running_mean=0.99340 | time=48.05s
          fold 4/5 | acc=0.99146 | running_mean=0.99292 | time=47.37s
          fold 5/5 | acc=0.99469 | running_mean=0.99327 | time=48.00s
          fold 1/5 | acc=0.99313 | running_mean=0.99313 | time=51.92s
          fold 2/5 | acc=0.99344 | running_mean=0.99328 | time=50.75s
          fold 3/5 | acc=0.99458 | running_mean=0.99372 | time=50.00s
          fold 4/5 | acc=0.99125 | running_mean=0.99310 | time=49.69s
          fold 5/5 | acc=0.99396 | running_mean=0.99327 | time=49.46s
          fold 1/5 | acc=0.99062 | running_mean=0.99062 | time=45.71s
          fold 2/5 | acc=0.99156 | running_mean=0.99109 | time=44.74s
          fold 3/5 | acc=0.99000 | running_mean=0.99073 | time=42.49s
          fold 4/5 | acc=0.99208 | running_mean=0.99107 | time=44.18s
          fold 5/5 | acc=0.99021 | running_mean=0.99090 | time=47.19s
          fold 1/5 | acc=0.99250 | running_mean=0.99250 | time=51.61s
          fold 2/5 | acc=0.99323 | running_mean=0.99286 | time=47.42s
          fold 3/5 | acc=0.99323 | running_mean=0.99299 | time=47.31s
          fold 4/5 | acc=0.99062 | running_mean=0.99240 | time=47.37s
          fold 5/5 | acc=0.99396 | running_mean=0.99271 | time=46.88s
          fold 1/5 | acc=0.99156 | running_mean=0.99156 | time=47.88s
          fold 2/5 | acc=0.99177 | running_mean=0.99167 | time=46.16s
          fold 3/5 | acc=0.99313 | running_mean=0.99215 | time=45.45s
          fold 4/5 | acc=0.99156 | running_mean=0.99201 | time=46.72s
          fold 5/5 | acc=0.99323 | running_mean=0.99225 | time=45.98s
          fold 1/5 | acc=0.73906 | running_mean=0.73906 | time=177.04s
          fold 2/5 | acc=0.73813 | running_mean=0.73859 | time=175.67s
          fold 3/5 | acc=0.74427 | running_mean=0.74049 | time=153.42s
          fold 4/5 | acc=0.74094 | running_mean=0.74060 | time=150.07s
          fold 5/5 | acc=0.73698 | running_mean=0.73987 | time=198.34s
          fold 1/5 | acc=0.98010 | running_mean=0.98010 | time=57.63s
          fold 2/5 | acc=0.97802 | running_mean=0.97906 | time=58.00s
          fold 3/5 | acc=0.97698 | running_mean=0.97837 | time=57.56s
          fold 4/5 | acc=0.97865 | running_mean=0.97844 | time=59.52s
          fold 5/5 | acc=0.97906 | running_mean=0.97856 | time=60.96s
          fold 1/5 | acc=0.99469 | running_mean=0.99469 | time=140.09s
          fold 2/5 | acc=0.99333 | running_mean=0.99401 | time=135.34s
          fold 3/5 | acc=0.99260 | running_mean=0.99354 | time=125.38s
          fold 4/5 | acc=0.99354 | running_mean=0.99354 | time=134.07s
          fold 5/5 | acc=0.99458 | running_mean=0.99375 | time=133.33s
          fold 1/5 | acc=0.99510 | running_mean=0.99510 | time=156.53s
          fold 2/5 | acc=0.99396 | running_mean=0.99453 | time=145.64s
          fold 3/5 | acc=0.99323 | running_mean=0.99410 | time=125.97s
          fold 4/5 | acc=0.99438 | running_mean=0.99417 | time=133.15s
          fold 5/5 | acc=0.99500 | running_mean=0.99433 | time=131.46s
          fold 1/5 | acc=0.99438 | running_mean=0.99438 | time=129.28s
          fold 2/5 | acc=0.99344 | running_mean=0.99391 | time=125.89s
          fold 3/5 | acc=0.99281 | running_mean=0.99354 | time=120.48s
          fold 4/5 | acc=0.99365 | running_mean=0.99357 | time=131.63s
          fold 5/5 | acc=0.99427 | running_mean=0.99371 | time=198.25s
          fold 1/5 | acc=0.99010 | running_mean=0.99010 | time=102.73s
          fold 2/5 | acc=0.99167 | running_mean=0.99089 | time=93.31s
          fold 3/5 | acc=0.99021 | running_mean=0.99066 | time=65.75s
          fold 4/5 | acc=0.99229 | running_mean=0.99107 | time=131.61s
          fold 5/5 | acc=0.99042 | running_mean=0.99094 | time=126.65s
          fold 1/5 | acc=0.98385 | running_mean=0.98385 | time=325.42s
          fold 2/5 | acc=0.98323 | running_mean=0.98354 | time=209.08s
          fold 3/5 | acc=0.98083 | running_mean=0.98264 | time=226.89s
          fold 4/5 | acc=0.98156 | running_mean=0.98237 | time=235.30s
          fold 5/5 | acc=0.98271 | running_mean=0.98244 | time=303.12s
          fold 1/5 | acc=0.99240 | running_mean=0.99240 | time=69.96s
          fold 2/5 | acc=0.99240 | running_mean=0.99240 | time=64.40s
          fold 3/5 | acc=0.99135 | running_mean=0.99205 | time=60.06s
          fold 4/5 | acc=0.99323 | running_mean=0.99234 | time=65.05s
          fold 5/5 | acc=0.99302 | running_mean=0.99248 | time=64.08s
          fold 1/5 | acc=0.98750 | running_mean=0.98750 | time=45.84s
          fold 2/5 | acc=0.98510 | running_mean=0.98630 | time=46.50s
          fold 3/5 | acc=0.98531 | running_mean=0.98597 | time=46.10s
          fold 4/5 | acc=0.98885 | running_mean=0.98669 | time=45.57s
          fold 5/5 | acc=0.98615 | running_mean=0.98658 | time=45.89s
          fold 1/5 | acc=0.98917 | running_mean=0.98917 | time=42.98s
          fold 2/5 | acc=0.99031 | running_mean=0.98974 | time=42.85s
          fold 3/5 | acc=0.98917 | running_mean=0.98955 | time=41.56s
          fold 4/5 | acc=0.99135 | running_mean=0.99000 | time=43.37s
          fold 5/5 | acc=0.98927 | running_mean=0.98985 | time=43.91s
          fold 1/5 | acc=0.99198 | running_mean=0.99198 | time=125.74s
          fold 2/5 | acc=0.99115 | running_mean=0.99156 | time=118.07s
          fold 3/5 | acc=0.98969 | running_mean=0.99094 | time=120.46s
          fold 4/5 | acc=0.98885 | running_mean=0.99042 | time=124.19s
          fold 5/5 | acc=0.99094 | running_mean=0.99052 | time=120.52s
          fold 1/5 | acc=0.99167 | running_mean=0.99167 | time=50.26s
          fold 2/5 | acc=0.99187 | running_mean=0.99177 | time=50.71s
          fold 3/5 | acc=0.99083 | running_mean=0.99146 | time=48.24s
          fold 4/5 | acc=0.99271 | running_mean=0.99177 | time=51.49s
          fold 5/5 | acc=0.99073 | running_mean=0.99156 | time=48.85s
          fold 1/5 | acc=0.92437 | running_mean=0.92437 | time=130.10s
          fold 2/5 | acc=0.93031 | running_mean=0.92734 | time=132.37s
          fold 3/5 | acc=0.92740 | running_mean=0.92736 | time=129.85s
          fold 4/5 | acc=0.92792 | running_mean=0.92750 | time=130.91s
          fold 5/5 | acc=0.92729 | running_mean=0.92746 | time=132.24s
          fold 1/5 | acc=0.99521 | running_mean=0.99521 | time=154.68s
          fold 2/5 | acc=0.99406 | running_mean=0.99464 | time=142.27s
          fold 3/5 | acc=0.99323 | running_mean=0.99417 | time=126.44s
          fold 4/5 | acc=0.99385 | running_mean=0.99409 | time=150.30s
          fold 5/5 | acc=0.99490 | running_mean=0.99425 | time=131.69s
          fold 1/5 | acc=0.99333 | running_mean=0.99333 | time=63.53s
          fold 2/5 | acc=0.99198 | running_mean=0.99266 | time=60.74s
          fold 3/5 | acc=0.99177 | running_mean=0.99236 | time=55.20s
          fold 4/5 | acc=0.99260 | running_mean=0.99242 | time=63.51s
          fold 5/5 | acc=0.99260 | running_mean=0.99246 | time=59.55s
          fold 1/5 | acc=0.99542 | running_mean=0.99542 | time=146.63s
          fold 2/5 | acc=0.99385 | running_mean=0.99464 | time=138.07s
          fold 3/5 | acc=0.99271 | running_mean=0.99399 | time=118.39s
          fold 4/5 | acc=0.99375 | running_mean=0.99393 | time=131.77s
          fold 5/5 | acc=0.99521 | running_mean=0.99419 | time=137.19s
          fold 1/5 | acc=0.99552 | running_mean=0.99552 | time=151.24s
          fold 2/5 | acc=0.99427 | running_mean=0.99490 | time=138.14s
          fold 3/5 | acc=0.99281 | running_mean=0.99420 | time=136.22s
          fold 4/5 | acc=0.99365 | running_mean=0.99406 | time=152.47s
          fold 5/5 | acc=0.99490 | running_mean=0.99423 | time=144.21s
          fold 1/5 | acc=0.99365 | running_mean=0.99365 | time=76.53s
          fold 2/5 | acc=0.99281 | running_mean=0.99323 | time=71.90s
          fold 3/5 | acc=0.99229 | running_mean=0.99292 | time=70.34s
          fold 4/5 | acc=0.99385 | running_mean=0.99315 | time=69.35s
          fold 5/5 | acc=0.99354 | running_mean=0.99323 | time=81.80s
          fold 1/5 | acc=0.99531 | running_mean=0.99531 | time=177.32s
          fold 2/5 | acc=0.99375 | running_mean=0.99453 | time=161.33s
          fold 3/5 | acc=0.99354 | running_mean=0.99420 | time=166.63s
          fold 4/5 | acc=0.99375 | running_mean=0.99409 | time=193.42s
          fold 5/5 | acc=0.99479 | running_mean=0.99423 | time=184.16s
          fold 1/5 | acc=0.98271 | running_mean=0.98271 | time=82.23s
          fold 2/5 | acc=0.98271 | running_mean=0.98271 | time=80.44s
          fold 3/5 | acc=0.98052 | running_mean=0.98198 | time=79.25s
          fold 4/5 | acc=0.98083 | running_mean=0.98169 | time=81.49s
          fold 5/5 | acc=0.98104 | running_mean=0.98156 | time=82.31s
          fold 1/5 | acc=0.99490 | running_mean=0.99490 | time=241.76s
          fold 2/5 | acc=0.99365 | running_mean=0.99427 | time=323.72s
          fold 3/5 | acc=0.99427 | running_mean=0.99427 | time=308.66s
          fold 4/5 | acc=0.99385 | running_mean=0.99417 | time=201.89s
          fold 5/5 | acc=0.99500 | running_mean=0.99433 | time=343.51s
          fold 1/5 | acc=0.99417 | running_mean=0.99417 | time=154.02s
          fold 2/5 | acc=0.99354 | running_mean=0.99385 | time=135.62s
          fold 3/5 | acc=0.99240 | running_mean=0.99337 | time=152.41s
          fold 4/5 | acc=0.99000 | running_mean=0.99253 | time=139.93s
          fold 5/5 | acc=0.99281 | running_mean=0.99258 | time=130.55s
  [TPE SVM] Time: 27093.00s | Memory Δ:  -176.1MB | Peak:    41.6MB
  [TPE Eval SVM] Time: 1322.29s | Memory Δ:    +6.7MB | Peak:   191.1MB
       Memory cleanup -> gc_collected=64, available=4.87 GB, used=69.1%, rss=191.6 MB
       Exported TPE artifacts

{'status': 'completed',
 'best':   Model Optimal_Scaler  Best_CV_Mean  Best_Trial kernel           C gamma  degree     coef0
 0   SVM       Standard      0.994354           5   poly  285.708008  auto       3  0.520068,
 'history':    Model  Trial   CV_Mean  Best_Score_So_Far  Trial_Runtime_Sec
 0    SVM      1  0.978021           0.978021         226.624020
 1    SVM      2  0.982583           0.982583        1561.825985
 2    SVM      3  0.963021           0.982583         456.067668
 3    SVM      4  0.979688           0.982583         303.766006
 4    SVM      5  0.739354           0.982583         668.378727
 5    SVM      6  0.994354           0.994354         573.958113
 6    SVM      7  0.719688           0.994354         880.973791
 7    SVM      8  0.966437           0.994354         416.505895
 8    SVM      9  0.987583           0.994354         370.393064
 9    SVM     10  0.987396           0.994354         250.399447
 10   SVM     11  0.810229           0.994354        1856.791692
 11   SVM     12  0.993229           0.994354         249.061108
 12   SVM     13  0.993167           0.994354         251.427838
 13   SVM     14  0.993313           0.994354         251.928661
 14   SVM     15  0.986000           0.994354         307.974098
 15   SVM     16  0.992563           0.994354         236.578012
 16   SVM     17  0.740062           0.994354         731.008004
 17   SVM     18  0.988187           0.994354         268.765240
 18   SVM     19  0.992958           0.994354         242.037945
 19   SVM     20  0.827646           0.994354        1237.638783
 20   SVM     21  0.974479           0.994354         531.537387
 21   SVM     22  0.993333           0.994354         254.593566
 22   SVM     23  0.992792           0.994354         263.676883
 23   SVM     24  0.993271           0.994354         241.702151
 24   SVM     25  0.993271           0.994354         251.865301
 25   SVM     26  0.990896           0.994354         224.330796
 26   SVM     27  0.992708           0.994354         240.614990
 27   SVM     28  0.992250           0.994354         232.211205
 28   SVM     29  0.739875           0.994354         854.561995
 29   SVM     30  0.978563           0.994354         293.696807
 30   SVM     31  0.993750           0.994354         668.233687
 31   SVM     32  0.994333           0.994354         692.776109
 32   SVM     33  0.993708           0.994354         705.585993
 33   SVM     34  0.990938           0.994354         520.109178
 34   SVM     35  0.982437           0.994354        1299.872247
 35   SVM     36  0.992479           0.994354         323.611515
 36   SVM     37  0.986583           0.994354         229.938638
 37   SVM     38  0.989854           0.994354         214.721338
 38   SVM     39  0.990521           0.994354         608.998020
 39   SVM     40  0.991562           0.994354         249.567160
 40   SVM     41  0.927458           0.994354         655.501305
 41   SVM     42  0.994250           0.994354         705.406518
 42   SVM     43  0.992458           0.994354         302.551085
 43   SVM     44  0.994188           0.994354         672.073049
 44   SVM     45  0.994229           0.994354         722.319757
 45   SVM     46  0.993229           0.994354         369.971880
 46   SVM     47  0.994229           0.994354         882.887380
 47   SVM     48  0.981563           0.994354         405.737762
 48   SVM     49  0.994333           0.994354        1419.582660
 49   SVM     50  0.992583           0.994354         712.605374,
 'summary':   Method Model Optimal_Scaler      Split  Accuracy  Precision    Recall        F1     Kappa       MCC       AUC   LogLoss  Accuracy_CI_Lower  Accuracy_CI_Upper  Precision_CI_Lower  Precision_CI_Upper  Recall_CI_Lower  Recall_CI_Upper  F1_CI_Lower  F1_CI_Upper  AUC_CI_Lower  AUC_CI_Upper  LogLoss_CI_Lower  LogLoss_CI_Upper  Kappa_CI_Lower  Kappa_CI_Upper  MCC_CI_Lower  MCC_CI_Upper
 0    TPE   SVM       Standard  Train_OOF  0.994354   0.994526  0.996637  0.995580  0.987767  0.987772  0.999709  0.019103           0.993646           0.995000            0.993689            0.995313         0.995952         0.997257     0.995027     0.996089      0.999604      0.999805          0.017249          0.021111        0.986229        0.989188      0.986244      0.989192
 1    TPE   SVM       Standard       Test  0.996250   0.996089  0.998041  0.997064  0.991876  0.991879  0.999788  0.015304           0.995083           0.997333            0.994540            0.997424         0.996989         0.998953     0.996144     0.997914      0.999583      0.999914          0.012223          0.019235        0.989373        0.994225      0.989379      0.994226,
 'timing':   Model  TPE_Search_Sec  TPE_Evaluation_Sec  TPE_Total_Sec  Best_CV_Mean
 0   SVM    27093.003589         1322.292179    28416.02478      0.994354}

In [50]:
run_tpe_model("AdaBoost")

AdaBoost   | Scaler: Raw        | Available RAM: 3.51 GB | Kernel RSS: 222.5 MB
       Memory cleanup -> gc_collected=0, available=3.51 GB, used=77.7%, rss=222.5 MB
       Running 50 trials with n_jobs_cv=1, n_jobs_opt=8
          fold 1/5 | acc=0.93802 | running_mean=0.93802 | time=16.32s
          fold 2/5 | acc=0.93854 | running_mean=0.93828 | time=13.30s
          fold 3/5 | acc=0.94104 | running_mean=0.93920 | time=13.18s
          fold 4/5 | acc=0.93854 | running_mean=0.93904 | time=13.13s
          fold 5/5 | acc=0.93896 | running_mean=0.93902 | time=14.09s
          fold 1/5 | acc=0.83281 | running_mean=0.83281 | time=7.82s
          fold 2/5 | acc=0.84021 | running_mean=0.83651 | time=7.34s
          fold 3/5 | acc=0.83698 | running_mean=0.83667 | time=7.35s
          fold 4/5 | acc=0.83760 | running_mean=0.83690 | time=9.75s
          fold 5/5 | acc=0.83177 | running_mean=0.83588 | time=10.05s
          fold 1/5 | acc=0.91240 | running_mean=0.91240 | time=21.72s
          fold 2/5 | acc=0.91438 | running_mean=0.91339 | time=23.25s
          fold 3/5 | acc=0.91135 | running_mean=0.91271 | time=21.93s
          fold 4/5 | acc=0.91521 | running_mean=0.91333 | time=23.13s
          fold 5/5 | acc=0.91073 | running_mean=0.91281 | time=21.61s
          fold 1/5 | acc=0.86010 | running_mean=0.86010 | time=29.81s
          fold 2/5 | acc=0.86885 | running_mean=0.86448 | time=29.33s
          fold 3/5 | acc=0.86448 | running_mean=0.86448 | time=33.36s
          fold 4/5 | acc=0.86313 | running_mean=0.86414 | time=47.09s
          fold 5/5 | acc=0.86031 | running_mean=0.86338 | time=47.99s
          fold 1/5 | acc=0.87396 | running_mean=0.87396 | time=17.58s
          fold 2/5 | acc=0.87219 | running_mean=0.87307 | time=16.57s
          fold 3/5 | acc=0.87521 | running_mean=0.87378 | time=17.51s
          fold 4/5 | acc=0.87302 | running_mean=0.87359 | time=17.45s
          fold 5/5 | acc=0.86990 | running_mean=0.87285 | time=17.07s
          fold 1/5 | acc=0.84750 | running_mean=0.84750 | time=30.66s
          fold 2/5 | acc=0.85594 | running_mean=0.85172 | time=30.68s
          fold 3/5 | acc=0.85250 | running_mean=0.85198 | time=30.08s
          fold 4/5 | acc=0.84854 | running_mean=0.85112 | time=30.34s
          fold 5/5 | acc=0.84396 | running_mean=0.84969 | time=31.50s
          fold 1/5 | acc=0.91458 | running_mean=0.91458 | time=23.24s
          fold 2/5 | acc=0.91552 | running_mean=0.91505 | time=22.59s
          fold 3/5 | acc=0.91240 | running_mean=0.91417 | time=23.36s
          fold 4/5 | acc=0.91604 | running_mean=0.91464 | time=20.28s
          fold 5/5 | acc=0.91198 | running_mean=0.91410 | time=21.35s
          fold 1/5 | acc=0.84167 | running_mean=0.84167 | time=27.98s
          fold 2/5 | acc=0.84625 | running_mean=0.84396 | time=29.22s
          fold 3/5 | acc=0.84615 | running_mean=0.84469 | time=22.78s
          fold 4/5 | acc=0.84219 | running_mean=0.84406 | time=21.76s
          fold 5/5 | acc=0.83844 | running_mean=0.84294 | time=21.72s
          fold 1/5 | acc=0.92135 | running_mean=0.92135 | time=5.83s
          fold 2/5 | acc=0.91375 | running_mean=0.91755 | time=5.57s
          fold 3/5 | acc=0.92031 | running_mean=0.91847 | time=5.60s
          fold 4/5 | acc=0.92375 | running_mean=0.91979 | time=5.36s
          fold 5/5 | acc=0.91854 | running_mean=0.91954 | time=6.77s
          fold 1/5 | acc=0.83708 | running_mean=0.83708 | time=12.42s
          fold 2/5 | acc=0.84302 | running_mean=0.84005 | time=11.41s
          fold 3/5 | acc=0.84052 | running_mean=0.84021 | time=14.22s
          fold 4/5 | acc=0.83708 | running_mean=0.83943 | time=15.89s
          fold 5/5 | acc=0.83469 | running_mean=0.83848 | time=12.62s
          fold 1/5 | acc=0.88365 | running_mean=0.88365 | time=30.12s
          fold 2/5 | acc=0.88698 | running_mean=0.88531 | time=31.73s
          fold 3/5 | acc=0.88604 | running_mean=0.88556 | time=39.97s
          fold 4/5 | acc=0.88396 | running_mean=0.88516 | time=37.77s
          fold 5/5 | acc=0.88021 | running_mean=0.88417 | time=43.26s
          fold 1/5 | acc=0.87958 | running_mean=0.87958 | time=4.74s
          fold 2/5 | acc=0.86594 | running_mean=0.87276 | time=4.84s
          fold 3/5 | acc=0.87979 | running_mean=0.87510 | time=4.77s
          fold 4/5 | acc=0.88052 | running_mean=0.87646 | time=4.99s
          fold 5/5 | acc=0.87740 | running_mean=0.87665 | time=4.84s
          fold 1/5 | acc=0.89885 | running_mean=0.89885 | time=5.27s
          fold 2/5 | acc=0.89031 | running_mean=0.89458 | time=5.35s
          fold 3/5 | acc=0.89406 | running_mean=0.89441 | time=5.39s
          fold 4/5 | acc=0.89719 | running_mean=0.89510 | time=5.02s
          fold 5/5 | acc=0.89052 | running_mean=0.89419 | time=4.94s
          fold 1/5 | acc=0.91125 | running_mean=0.91125 | time=14.61s
          fold 2/5 | acc=0.91167 | running_mean=0.91146 | time=14.29s
          fold 3/5 | acc=0.90531 | running_mean=0.90941 | time=15.25s
          fold 4/5 | acc=0.91281 | running_mean=0.91026 | time=15.26s
          fold 5/5 | acc=0.90146 | running_mean=0.90850 | time=15.04s
          fold 1/5 | acc=0.88479 | running_mean=0.88479 | time=22.47s
          fold 2/5 | acc=0.88896 | running_mean=0.88687 | time=22.90s
          fold 3/5 | acc=0.88875 | running_mean=0.88750 | time=22.94s
          fold 4/5 | acc=0.88615 | running_mean=0.88716 | time=22.17s
          fold 5/5 | acc=0.88562 | running_mean=0.88685 | time=22.39s
          fold 1/5 | acc=0.91365 | running_mean=0.91365 | time=10.02s
          fold 2/5 | acc=0.90833 | running_mean=0.91099 | time=15.58s
          fold 3/5 | acc=0.90156 | running_mean=0.90785 | time=10.25s
          fold 4/5 | acc=0.90865 | running_mean=0.90805 | time=10.34s
          fold 5/5 | acc=0.90938 | running_mean=0.90831 | time=10.61s
          fold 1/5 | acc=0.86719 | running_mean=0.86719 | time=36.66s
          fold 2/5 | acc=0.87167 | running_mean=0.86943 | time=34.92s
          fold 3/5 | acc=0.86948 | running_mean=0.86944 | time=36.16s
          fold 4/5 | acc=0.86844 | running_mean=0.86919 | time=34.08s
          fold 5/5 | acc=0.86687 | running_mean=0.86873 | time=35.41s
          fold 1/5 | acc=0.93698 | running_mean=0.93698 | time=19.74s
          fold 2/5 | acc=0.93156 | running_mean=0.93427 | time=20.09s
          fold 3/5 | acc=0.93698 | running_mean=0.93517 | time=20.51s
          fold 4/5 | acc=0.93688 | running_mean=0.93560 | time=19.70s
          fold 5/5 | acc=0.92958 | running_mean=0.93440 | time=20.22s
          fold 1/5 | acc=0.89906 | running_mean=0.89906 | time=25.36s
          fold 2/5 | acc=0.89792 | running_mean=0.89849 | time=24.08s
          fold 3/5 | acc=0.89885 | running_mean=0.89861 | time=20.26s
          fold 4/5 | acc=0.90323 | running_mean=0.89977 | time=22.95s
          fold 5/5 | acc=0.89823 | running_mean=0.89946 | time=28.80s
          fold 1/5 | acc=0.93125 | running_mean=0.93125 | time=45.10s
          fold 2/5 | acc=0.92896 | running_mean=0.93010 | time=35.92s
          fold 3/5 | acc=0.92427 | running_mean=0.92816 | time=38.91s
          fold 4/5 | acc=0.92740 | running_mean=0.92797 | time=37.34s
          fold 5/5 | acc=0.92615 | running_mean=0.92760 | time=35.57s
          fold 1/5 | acc=0.87615 | running_mean=0.87615 | time=48.43s
          fold 2/5 | acc=0.87719 | running_mean=0.87667 | time=44.78s
          fold 3/5 | acc=0.87594 | running_mean=0.87642 | time=40.44s
          fold 4/5 | acc=0.87438 | running_mean=0.87591 | time=38.57s
          fold 5/5 | acc=0.87177 | running_mean=0.87508 | time=39.03s
          fold 1/5 | acc=0.92896 | running_mean=0.92896 | time=31.32s
          fold 2/5 | acc=0.92948 | running_mean=0.92922 | time=31.61s
          fold 3/5 | acc=0.93000 | running_mean=0.92948 | time=29.44s
          fold 4/5 | acc=0.92937 | running_mean=0.92945 | time=27.66s
          fold 5/5 | acc=0.93146 | running_mean=0.92985 | time=27.68s
          fold 1/5 | acc=0.92635 | running_mean=0.92635 | time=23.68s
          fold 2/5 | acc=0.92833 | running_mean=0.92734 | time=22.17s
          fold 3/5 | acc=0.92552 | running_mean=0.92674 | time=39.85s
          fold 4/5 | acc=0.92667 | running_mean=0.92672 | time=40.73s
          fold 5/5 | acc=0.93010 | running_mean=0.92740 | time=39.86s
          fold 1/5 | acc=0.89187 | running_mean=0.89187 | time=27.82s
          fold 2/5 | acc=0.89687 | running_mean=0.89437 | time=28.30s
          fold 3/5 | acc=0.89208 | running_mean=0.89361 | time=26.35s
          fold 4/5 | acc=0.89531 | running_mean=0.89404 | time=25.88s
          fold 5/5 | acc=0.88875 | running_mean=0.89298 | time=21.83s
          fold 1/5 | acc=0.91396 | running_mean=0.91396 | time=36.28s
          fold 2/5 | acc=0.91917 | running_mean=0.91656 | time=24.55s
          fold 3/5 | acc=0.91469 | running_mean=0.91594 | time=36.42s
          fold 4/5 | acc=0.91552 | running_mean=0.91583 | time=31.42s
          fold 5/5 | acc=0.91115 | running_mean=0.91490 | time=27.76s
          fold 1/5 | acc=0.94344 | running_mean=0.94344 | time=30.97s
          fold 2/5 | acc=0.93875 | running_mean=0.94109 | time=31.39s
          fold 3/5 | acc=0.93885 | running_mean=0.94035 | time=31.39s
          fold 4/5 | acc=0.93688 | running_mean=0.93948 | time=44.78s
          fold 5/5 | acc=0.93573 | running_mean=0.93873 | time=43.60s
          fold 1/5 | acc=0.93375 | running_mean=0.93375 | time=22.83s
          fold 2/5 | acc=0.93146 | running_mean=0.93260 | time=19.93s
          fold 3/5 | acc=0.93115 | running_mean=0.93212 | time=23.56s
          fold 4/5 | acc=0.93510 | running_mean=0.93286 | time=22.77s
          fold 5/5 | acc=0.93417 | running_mean=0.93313 | time=27.95s
          fold 1/5 | acc=0.90573 | running_mean=0.90573 | time=42.03s
          fold 2/5 | acc=0.90260 | running_mean=0.90417 | time=32.07s
          fold 3/5 | acc=0.90615 | running_mean=0.90483 | time=36.00s
          fold 4/5 | acc=0.90479 | running_mean=0.90482 | time=28.16s
          fold 5/5 | acc=0.90323 | running_mean=0.90450 | time=38.46s
          fold 1/5 | acc=0.89625 | running_mean=0.89625 | time=63.20s
          fold 2/5 | acc=0.89615 | running_mean=0.89620 | time=54.62s
          fold 3/5 | acc=0.89615 | running_mean=0.89618 | time=51.20s
          fold 4/5 | acc=0.89990 | running_mean=0.89711 | time=50.64s
          fold 5/5 | acc=0.89396 | running_mean=0.89648 | time=50.59s
          fold 1/5 | acc=0.89240 | running_mean=0.89240 | time=14.30s
          fold 2/5 | acc=0.89990 | running_mean=0.89615 | time=16.92s
          fold 3/5 | acc=0.89719 | running_mean=0.89649 | time=17.83s
          fold 4/5 | acc=0.89802 | running_mean=0.89687 | time=19.52s
          fold 5/5 | acc=0.89208 | running_mean=0.89592 | time=20.44s
          fold 1/5 | acc=0.93698 | running_mean=0.93698 | time=42.22s
          fold 2/5 | acc=0.93458 | running_mean=0.93578 | time=35.58s
          fold 3/5 | acc=0.93490 | running_mean=0.93549 | time=33.11s
          fold 4/5 | acc=0.93812 | running_mean=0.93615 | time=34.10s
          fold 5/5 | acc=0.93969 | running_mean=0.93685 | time=29.55s
          fold 1/5 | acc=0.93573 | running_mean=0.93573 | time=32.91s
          fold 2/5 | acc=0.93583 | running_mean=0.93578 | time=26.30s
          fold 3/5 | acc=0.93875 | running_mean=0.93677 | time=30.97s
          fold 4/5 | acc=0.93719 | running_mean=0.93688 | time=37.54s
          fold 5/5 | acc=0.93375 | running_mean=0.93625 | time=28.42s
          fold 1/5 | acc=0.92146 | running_mean=0.92146 | time=32.87s
          fold 2/5 | acc=0.92510 | running_mean=0.92328 | time=25.97s
          fold 3/5 | acc=0.91823 | running_mean=0.92160 | time=21.72s
          fold 4/5 | acc=0.92521 | running_mean=0.92250 | time=21.28s
          fold 5/5 | acc=0.92156 | running_mean=0.92231 | time=22.28s
          fold 1/5 | acc=0.75333 | running_mean=0.75333 | time=17.16s
          fold 2/5 | acc=0.75948 | running_mean=0.75641 | time=17.48s
          fold 3/5 | acc=0.75938 | running_mean=0.75740 | time=16.41s
          fold 4/5 | acc=0.74958 | running_mean=0.75544 | time=16.91s
          fold 5/5 | acc=0.74135 | running_mean=0.75262 | time=25.43s
          fold 1/5 | acc=0.94281 | running_mean=0.94281 | time=38.04s
          fold 2/5 | acc=0.94365 | running_mean=0.94323 | time=33.31s
          fold 3/5 | acc=0.94177 | running_mean=0.94274 | time=45.48s
          fold 4/5 | acc=0.94198 | running_mean=0.94255 | time=56.27s
          fold 5/5 | acc=0.94094 | running_mean=0.94223 | time=48.41s
          fold 1/5 | acc=0.91917 | running_mean=0.91917 | time=56.99s
          fold 2/5 | acc=0.91844 | running_mean=0.91880 | time=61.34s
          fold 3/5 | acc=0.91760 | running_mean=0.91840 | time=58.62s
          fold 4/5 | acc=0.91979 | running_mean=0.91875 | time=60.31s
          fold 5/5 | acc=0.91604 | running_mean=0.91821 | time=69.43s
          fold 1/5 | acc=0.92594 | running_mean=0.92594 | time=52.45s
          fold 2/5 | acc=0.92844 | running_mean=0.92719 | time=47.25s
          fold 3/5 | acc=0.92417 | running_mean=0.92618 | time=39.16s
          fold 4/5 | acc=0.92823 | running_mean=0.92669 | time=55.59s
          fold 5/5 | acc=0.92573 | running_mean=0.92650 | time=59.65s
          fold 1/5 | acc=0.94406 | running_mean=0.94406 | time=41.18s
          fold 2/5 | acc=0.94135 | running_mean=0.94271 | time=42.17s
          fold 3/5 | acc=0.94354 | running_mean=0.94299 | time=38.72s
          fold 4/5 | acc=0.94198 | running_mean=0.94273 | time=36.61s
          fold 5/5 | acc=0.94021 | running_mean=0.94223 | time=37.37s
          fold 1/5 | acc=0.90865 | running_mean=0.90865 | time=58.00s
          fold 2/5 | acc=0.90833 | running_mean=0.90849 | time=61.27s
          fold 3/5 | acc=0.90917 | running_mean=0.90872 | time=60.93s
          fold 4/5 | acc=0.90740 | running_mean=0.90839 | time=59.96s
          fold 5/5 | acc=0.90729 | running_mean=0.90817 | time=52.95s
          fold 1/5 | acc=0.91365 | running_mean=0.91365 | time=32.91s
          fold 2/5 | acc=0.91396 | running_mean=0.91380 | time=32.95s
          fold 3/5 | acc=0.91448 | running_mean=0.91403 | time=32.35s
          fold 4/5 | acc=0.91708 | running_mean=0.91479 | time=32.27s
          fold 5/5 | acc=0.91063 | running_mean=0.91396 | time=33.22s
          fold 1/5 | acc=0.85844 | running_mean=0.85844 | time=30.31s
          fold 2/5 | acc=0.86813 | running_mean=0.86328 | time=29.85s
          fold 3/5 | acc=0.86500 | running_mean=0.86385 | time=29.76s
          fold 4/5 | acc=0.86281 | running_mean=0.86359 | time=30.82s
          fold 5/5 | acc=0.86083 | running_mean=0.86304 | time=30.01s
          fold 1/5 | acc=0.94771 | running_mean=0.94771 | time=34.76s
          fold 2/5 | acc=0.94323 | running_mean=0.94547 | time=33.65s
          fold 3/5 | acc=0.94677 | running_mean=0.94590 | time=32.98s
          fold 4/5 | acc=0.94604 | running_mean=0.94594 | time=34.35s
          fold 5/5 | acc=0.94510 | running_mean=0.94577 | time=33.69s
          fold 1/5 | acc=0.94698 | running_mean=0.94698 | time=33.99s
          fold 2/5 | acc=0.94760 | running_mean=0.94729 | time=33.88s
          fold 3/5 | acc=0.94833 | running_mean=0.94764 | time=34.63s
          fold 4/5 | acc=0.94802 | running_mean=0.94773 | time=35.67s
          fold 5/5 | acc=0.94708 | running_mean=0.94760 | time=36.34s
          fold 1/5 | acc=0.94729 | running_mean=0.94729 | time=38.10s
          fold 2/5 | acc=0.94531 | running_mean=0.94630 | time=35.21s
          fold 3/5 | acc=0.94500 | running_mean=0.94587 | time=38.10s
          fold 4/5 | acc=0.94656 | running_mean=0.94604 | time=33.35s
          fold 5/5 | acc=0.94240 | running_mean=0.94531 | time=33.27s
          fold 1/5 | acc=0.95073 | running_mean=0.95073 | time=40.94s
          fold 2/5 | acc=0.95052 | running_mean=0.95063 | time=38.59s
          fold 3/5 | acc=0.94667 | running_mean=0.94931 | time=40.14s
          fold 4/5 | acc=0.95073 | running_mean=0.94966 | time=39.48s
          fold 5/5 | acc=0.94958 | running_mean=0.94965 | time=38.48s
          fold 1/5 | acc=0.95188 | running_mean=0.95188 | time=41.17s
          fold 2/5 | acc=0.94833 | running_mean=0.95010 | time=41.06s
          fold 3/5 | acc=0.95156 | running_mean=0.95059 | time=49.67s
          fold 4/5 | acc=0.95240 | running_mean=0.95104 | time=42.48s
          fold 5/5 | acc=0.95073 | running_mean=0.95098 | time=56.00s
          fold 1/5 | acc=0.95219 | running_mean=0.95219 | time=56.35s
          fold 2/5 | acc=0.95021 | running_mean=0.95120 | time=61.79s
          fold 3/5 | acc=0.94979 | running_mean=0.95073 | time=63.69s
          fold 4/5 | acc=0.95104 | running_mean=0.95081 | time=47.85s
          fold 5/5 | acc=0.95010 | running_mean=0.95067 | time=36.40s
          fold 1/5 | acc=0.93917 | running_mean=0.93917 | time=29.19s
          fold 2/5 | acc=0.93250 | running_mean=0.93583 | time=34.69s
          fold 3/5 | acc=0.93594 | running_mean=0.93587 | time=30.81s
          fold 4/5 | acc=0.93906 | running_mean=0.93667 | time=32.55s
          fold 5/5 | acc=0.93781 | running_mean=0.93690 | time=34.06s
          fold 1/5 | acc=0.92698 | running_mean=0.92698 | time=42.61s
          fold 2/5 | acc=0.92594 | running_mean=0.92646 | time=39.92s
          fold 3/5 | acc=0.92437 | running_mean=0.92576 | time=38.50s
          fold 4/5 | acc=0.92708 | running_mean=0.92609 | time=36.84s
          fold 5/5 | acc=0.92583 | running_mean=0.92604 | time=38.91s
          fold 1/5 | acc=0.94802 | running_mean=0.94802 | time=39.41s
          fold 2/5 | acc=0.94812 | running_mean=0.94807 | time=33.57s
          fold 3/5 | acc=0.95021 | running_mean=0.94878 | time=38.95s
          fold 4/5 | acc=0.94948 | running_mean=0.94896 | time=42.48s
          fold 5/5 | acc=0.94854 | running_mean=0.94887 | time=48.69s
  [TPE AdaBoost] Time: 7610.11s | Memory Δ:  -174.0MB | Peak:    48.4MB
  [TPE Eval AdaBoost] Time:  471.18s | Memory Δ:    -4.6MB | Peak:   190.0MB
       Memory cleanup -> gc_collected=64, available=1.89 GB, used=88.0%, rss=190.6 MB
       Exported TPE artifacts

{'status': 'completed',
 'best':       Model Optimal_Scaler  Best_CV_Mean  Best_Trial  n_estimators  \
 0  AdaBoost            Raw      0.950979          45           401

    learning_rate algorithm
 0       1.809305   SAMME.R  ,
 'history':        Model  Trial   CV_Mean  Best_Score_So_Far  Trial_Runtime_Sec
 0   AdaBoost      1  0.939021           0.939021          70.041766
 1   AdaBoost      2  0.835875           0.939021          42.316324
 2   AdaBoost      3  0.912813           0.939021         111.654005
 3   AdaBoost      4  0.863375           0.939021         187.595616
 4   AdaBoost      5  0.872854           0.939021          86.195142
 5   AdaBoost      6  0.849688           0.939021         153.276545
 6   AdaBoost      7  0.914104           0.939021         110.832179
 7   AdaBoost      8  0.842938           0.939021         123.464680
 8   AdaBoost      9  0.919542           0.939021          29.148242
 9   AdaBoost     10  0.838479           0.939021          66.587078
 10  AdaBoost     11  0.884167           0.939021         182.870919
 11  AdaBoost     12  0.876646           0.939021          24.211489
 12  AdaBoost     13  0.894187           0.939021          25.996762
 13  AdaBoost     14  0.908500           0.939021          74.480838
 14  AdaBoost     15  0.886854           0.939021         112.899416
 15  AdaBoost     16  0.908313           0.939021          56.824845
 16  AdaBoost     17  0.868729           0.939021         177.249922
 17  AdaBoost     18  0.934396           0.939021         100.277241
 18  AdaBoost     19  0.899458           0.939021         121.490887
 19  AdaBoost     20  0.927604           0.939021         192.881018
 20  AdaBoost     21  0.875083           0.939021         211.290174
 21  AdaBoost     22  0.929854           0.939021         147.756714
 22  AdaBoost     23  0.927396           0.939021         166.323361
 23  AdaBoost     24  0.892979           0.939021         130.227994
 24  AdaBoost     25  0.914896           0.939021         156.473352
 25  AdaBoost     26  0.938729           0.939021         182.140289
 26  AdaBoost     27  0.933125           0.939021         117.103444
 27  AdaBoost     28  0.904500           0.939021         176.743025
 28  AdaBoost     29  0.896479           0.939021         270.294457
 29  AdaBoost     30  0.895917           0.939021          89.056453
 30  AdaBoost     31  0.936854           0.939021         174.620775
 31  AdaBoost     32  0.936250           0.939021         156.194571
 32  AdaBoost     33  0.922312           0.939021         124.177299
 33  AdaBoost     34  0.752625           0.939021          93.426219
 34  AdaBoost     35  0.942229           0.942229         221.556090
 35  AdaBoost     36  0.918208           0.942229         306.750775
 36  AdaBoost     37  0.926500           0.942229         254.171842
 37  AdaBoost     38  0.942229           0.942229         196.098978
 38  AdaBoost     39  0.908167           0.942229         293.149935
 39  AdaBoost     40  0.913958           0.942229         163.746640
 40  AdaBoost     41  0.863042           0.942229         150.794814
 41  AdaBoost     42  0.945771           0.945771         169.469346
 42  AdaBoost     43  0.947604           0.947604         174.568972
 43  AdaBoost     44  0.945312           0.947604         178.046519
 44  AdaBoost     45  0.949646           0.949646         197.660706
 45  AdaBoost     46  0.950979           0.950979         230.426710
 46  AdaBoost     47  0.950667           0.950979         266.147061
 47  AdaBoost     48  0.936896           0.950979         161.318009
 48  AdaBoost     49  0.926042           0.950979         196.813611
 49  AdaBoost     50  0.948875           0.950979         203.168372,
 'summary':   Method     Model Optimal_Scaler      Split  Accuracy  Precision    Recall  \
 0    TPE  AdaBoost            Raw  Train_OOF  0.950979   0.961326  0.961860
 1    TPE  AdaBoost            Raw       Test  0.950667   0.960255  0.962513

          F1     Kappa       MCC  ...  F1_CI_Lower  F1_CI_Upper  AUC_CI_Lower  \
 0  0.961593  0.893852  0.893852  ...     0.960112     0.963103      0.990771
 1  0.961383  0.893102  0.893106  ...     0.958325     0.964417      0.990555

    AUC_CI_Upper  LogLoss_CI_Lower  LogLoss_CI_Upper  Kappa_CI_Lower  \
 0      0.991767          0.646047          0.646687        0.889906
 1      0.992589          0.644744          0.646063        0.884853

    Kappa_CI_Upper  MCC_CI_Lower  MCC_CI_Upper
 0        0.897883      0.889906      0.897886
 1        0.901594      0.884861      0.901645

 [2 rows x 28 columns],
 'timing':       Model  TPE_Search_Sec  TPE_Evaluation_Sec  TPE_Total_Sec  Best_CV_Mean
 0  AdaBoost     7610.104852          471.181954    8083.071238      0.950979}

In [41]:
run_tpe_model("RF")

RF         | Scaler: MinMax     | Available RAM: 2.11 GB | Kernel RSS: 203.9 MB
       Memory cleanup -> gc_collected=0, available=2.12 GB, used=86.5%, rss=203.9 MB
       Running 50 trials with n_jobs_cv=1, n_jobs_opt=8
          fold 1/5 | acc=0.94052 | running_mean=0.94052 | time=10.58s
          fold 2/5 | acc=0.94490 | running_mean=0.94271 | time=9.53s
          fold 3/5 | acc=0.94510 | running_mean=0.94351 | time=8.76s
          fold 4/5 | acc=0.94125 | running_mean=0.94294 | time=9.87s
          fold 5/5 | acc=0.94146 | running_mean=0.94265 | time=9.08s
          fold 1/5 | acc=0.95021 | running_mean=0.95021 | time=22.02s
          fold 2/5 | acc=0.95344 | running_mean=0.95182 | time=25.14s
          fold 3/5 | acc=0.95260 | running_mean=0.95208 | time=28.98s
          fold 4/5 | acc=0.94979 | running_mean=0.95151 | time=27.77s
          fold 5/5 | acc=0.94948 | running_mean=0.95110 | time=24.19s
          fold 1/5 | acc=0.90146 | running_mean=0.90146 | time=18.09s
          fold 2/5 | acc=0.90812 | running_mean=0.90479 | time=18.11s
          fold 3/5 | acc=0.90542 | running_mean=0.90500 | time=17.27s
          fold 4/5 | acc=0.89917 | running_mean=0.90354 | time=16.35s
          fold 5/5 | acc=0.90729 | running_mean=0.90429 | time=16.84s
          fold 1/5 | acc=0.93156 | running_mean=0.93156 | time=5.41s
          fold 2/5 | acc=0.93344 | running_mean=0.93250 | time=5.38s
          fold 3/5 | acc=0.93292 | running_mean=0.93264 | time=5.64s
          fold 4/5 | acc=0.92958 | running_mean=0.93188 | time=6.38s
          fold 5/5 | acc=0.92969 | running_mean=0.93144 | time=5.31s
          fold 1/5 | acc=0.82104 | running_mean=0.82104 | time=23.06s
          fold 2/5 | acc=0.82552 | running_mean=0.82328 | time=23.41s
          fold 3/5 | acc=0.83313 | running_mean=0.82656 | time=26.54s
          fold 4/5 | acc=0.82135 | running_mean=0.82526 | time=24.66s
          fold 5/5 | acc=0.82177 | running_mean=0.82456 | time=21.44s
          fold 1/5 | acc=0.94010 | running_mean=0.94010 | time=61.05s
          fold 2/5 | acc=0.94698 | running_mean=0.94354 | time=74.09s
          fold 3/5 | acc=0.94396 | running_mean=0.94368 | time=89.43s
          fold 4/5 | acc=0.93844 | running_mean=0.94237 | time=56.63s
          fold 5/5 | acc=0.94281 | running_mean=0.94246 | time=65.55s
          fold 1/5 | acc=0.95250 | running_mean=0.95250 | time=13.63s
          fold 2/5 | acc=0.95875 | running_mean=0.95562 | time=14.25s
          fold 3/5 | acc=0.95562 | running_mean=0.95562 | time=16.24s
          fold 4/5 | acc=0.95312 | running_mean=0.95500 | time=14.54s
          fold 5/5 | acc=0.95844 | running_mean=0.95569 | time=13.09s
          fold 1/5 | acc=0.94865 | running_mean=0.94865 | time=30.68s
          fold 2/5 | acc=0.95427 | running_mean=0.95146 | time=27.83s
          fold 3/5 | acc=0.95240 | running_mean=0.95177 | time=26.87s
          fold 4/5 | acc=0.94781 | running_mean=0.95078 | time=24.13s
          fold 5/5 | acc=0.95073 | running_mean=0.95077 | time=24.01s
          fold 1/5 | acc=0.90365 | running_mean=0.90365 | time=11.62s
          fold 2/5 | acc=0.90854 | running_mean=0.90609 | time=11.08s
          fold 3/5 | acc=0.90573 | running_mean=0.90597 | time=10.94s
          fold 4/5 | acc=0.89948 | running_mean=0.90435 | time=10.95s
          fold 5/5 | acc=0.90615 | running_mean=0.90471 | time=11.66s
          fold 1/5 | acc=0.93448 | running_mean=0.93448 | time=28.78s
          fold 2/5 | acc=0.93875 | running_mean=0.93661 | time=31.74s
          fold 3/5 | acc=0.93583 | running_mean=0.93635 | time=40.53s
          fold 4/5 | acc=0.93073 | running_mean=0.93495 | time=42.24s
          fold 5/5 | acc=0.93500 | running_mean=0.93496 | time=46.91s
          fold 1/5 | acc=0.93656 | running_mean=0.93656 | time=19.80s
          fold 2/5 | acc=0.94010 | running_mean=0.93833 | time=14.64s
          fold 3/5 | acc=0.93917 | running_mean=0.93861 | time=12.49s
          fold 4/5 | acc=0.93510 | running_mean=0.93773 | time=12.30s
          fold 5/5 | acc=0.93469 | running_mean=0.93712 | time=11.21s
          fold 1/5 | acc=0.95510 | running_mean=0.95510 | time=19.43s
          fold 2/5 | acc=0.95896 | running_mean=0.95703 | time=21.11s
          fold 3/5 | acc=0.95833 | running_mean=0.95747 | time=20.02s
          fold 4/5 | acc=0.95677 | running_mean=0.95729 | time=21.93s
          fold 5/5 | acc=0.95667 | running_mean=0.95717 | time=22.72s
          fold 1/5 | acc=0.94021 | running_mean=0.94021 | time=22.25s
          fold 2/5 | acc=0.94385 | running_mean=0.94203 | time=20.60s
          fold 3/5 | acc=0.94156 | running_mean=0.94188 | time=21.81s
          fold 4/5 | acc=0.93948 | running_mean=0.94128 | time=20.42s
          fold 5/5 | acc=0.93812 | running_mean=0.94065 | time=19.42s
          fold 1/5 | acc=0.94760 | running_mean=0.94760 | time=16.08s
          fold 2/5 | acc=0.95021 | running_mean=0.94891 | time=15.27s
          fold 3/5 | acc=0.95250 | running_mean=0.95010 | time=14.88s
          fold 4/5 | acc=0.94708 | running_mean=0.94935 | time=15.02s
          fold 5/5 | acc=0.94927 | running_mean=0.94933 | time=16.24s
          fold 1/5 | acc=0.93958 | running_mean=0.93958 | time=8.03s
          fold 2/5 | acc=0.94156 | running_mean=0.94057 | time=8.28s
          fold 3/5 | acc=0.94198 | running_mean=0.94104 | time=8.15s
          fold 4/5 | acc=0.93906 | running_mean=0.94055 | time=8.97s
          fold 5/5 | acc=0.93740 | running_mean=0.93992 | time=8.91s
          fold 1/5 | acc=0.94844 | running_mean=0.94844 | time=17.23s
          fold 2/5 | acc=0.95146 | running_mean=0.94995 | time=14.54s
          fold 3/5 | acc=0.94937 | running_mean=0.94976 | time=14.46s
          fold 4/5 | acc=0.94583 | running_mean=0.94878 | time=15.95s
          fold 5/5 | acc=0.94802 | running_mean=0.94863 | time=15.59s
          fold 1/5 | acc=0.93948 | running_mean=0.93948 | time=3.42s
          fold 2/5 | acc=0.94427 | running_mean=0.94188 | time=2.56s
          fold 3/5 | acc=0.94146 | running_mean=0.94174 | time=2.92s
          fold 4/5 | acc=0.93781 | running_mean=0.94076 | time=3.40s
          fold 5/5 | acc=0.93854 | running_mean=0.94031 | time=3.46s
          fold 1/5 | acc=0.95823 | running_mean=0.95823 | time=23.16s
          fold 2/5 | acc=0.96135 | running_mean=0.95979 | time=30.31s
          fold 3/5 | acc=0.96250 | running_mean=0.96069 | time=31.74s
          fold 4/5 | acc=0.95865 | running_mean=0.96018 | time=23.77s
          fold 5/5 | acc=0.96042 | running_mean=0.96023 | time=23.80s
          fold 1/5 | acc=0.95302 | running_mean=0.95302 | time=21.57s
          fold 2/5 | acc=0.95615 | running_mean=0.95458 | time=25.03s
          fold 3/5 | acc=0.95583 | running_mean=0.95500 | time=20.81s
          fold 4/5 | acc=0.95396 | running_mean=0.95474 | time=23.10s
          fold 5/5 | acc=0.95271 | running_mean=0.95433 | time=22.78s
          fold 1/5 | acc=0.95437 | running_mean=0.95437 | time=28.27s
          fold 2/5 | acc=0.95833 | running_mean=0.95635 | time=28.15s
          fold 3/5 | acc=0.95906 | running_mean=0.95726 | time=21.45s
          fold 4/5 | acc=0.95604 | running_mean=0.95695 | time=21.19s
          fold 5/5 | acc=0.95667 | running_mean=0.95690 | time=22.10s
          fold 1/5 | acc=0.94812 | running_mean=0.94812 | time=24.66s
          fold 2/5 | acc=0.95198 | running_mean=0.95005 | time=27.83s
          fold 3/5 | acc=0.95094 | running_mean=0.95035 | time=23.49s
          fold 4/5 | acc=0.94854 | running_mean=0.94990 | time=22.89s
          fold 5/5 | acc=0.94792 | running_mean=0.94950 | time=21.14s
          fold 1/5 | acc=0.95875 | running_mean=0.95875 | time=18.37s
          fold 2/5 | acc=0.96260 | running_mean=0.96068 | time=21.12s
          fold 3/5 | acc=0.96240 | running_mean=0.96125 | time=20.23s
          fold 4/5 | acc=0.95917 | running_mean=0.96073 | time=20.09s
          fold 5/5 | acc=0.96073 | running_mean=0.96073 | time=22.00s
          fold 1/5 | acc=0.95604 | running_mean=0.95604 | time=20.22s
          fold 2/5 | acc=0.95844 | running_mean=0.95724 | time=18.71s
          fold 3/5 | acc=0.95854 | running_mean=0.95767 | time=18.21s
          fold 4/5 | acc=0.95583 | running_mean=0.95721 | time=17.46s
          fold 5/5 | acc=0.95823 | running_mean=0.95742 | time=17.78s
          fold 1/5 | acc=0.95198 | running_mean=0.95198 | time=17.23s
          fold 2/5 | acc=0.95490 | running_mean=0.95344 | time=17.66s
          fold 3/5 | acc=0.95667 | running_mean=0.95451 | time=16.95s
          fold 4/5 | acc=0.95115 | running_mean=0.95367 | time=18.77s
          fold 5/5 | acc=0.95167 | running_mean=0.95327 | time=20.96s
          fold 1/5 | acc=0.95990 | running_mean=0.95990 | time=17.41s
          fold 2/5 | acc=0.96313 | running_mean=0.96151 | time=17.83s
          fold 3/5 | acc=0.96323 | running_mean=0.96208 | time=20.02s
          fold 4/5 | acc=0.95917 | running_mean=0.96135 | time=17.36s
          fold 5/5 | acc=0.96135 | running_mean=0.96135 | time=15.70s
          fold 1/5 | acc=0.95417 | running_mean=0.95417 | time=16.04s
          fold 2/5 | acc=0.95854 | running_mean=0.95635 | time=15.88s
          fold 3/5 | acc=0.95854 | running_mean=0.95708 | time=15.07s
          fold 4/5 | acc=0.95542 | running_mean=0.95667 | time=14.85s
          fold 5/5 | acc=0.95667 | running_mean=0.95667 | time=15.40s
          fold 1/5 | acc=0.94833 | running_mean=0.94833 | time=11.90s
          fold 2/5 | acc=0.95198 | running_mean=0.95016 | time=11.20s
          fold 3/5 | acc=0.95167 | running_mean=0.95066 | time=11.21s
          fold 4/5 | acc=0.94823 | running_mean=0.95005 | time=11.31s
          fold 5/5 | acc=0.94969 | running_mean=0.94998 | time=11.18s
          fold 1/5 | acc=0.95844 | running_mean=0.95844 | time=14.24s
          fold 2/5 | acc=0.96198 | running_mean=0.96021 | time=13.26s
          fold 3/5 | acc=0.96208 | running_mean=0.96083 | time=13.29s
          fold 4/5 | acc=0.95937 | running_mean=0.96047 | time=13.61s
          fold 5/5 | acc=0.96104 | running_mean=0.96058 | time=14.97s
          fold 1/5 | acc=0.95583 | running_mean=0.95583 | time=16.78s
          fold 2/5 | acc=0.95875 | running_mean=0.95729 | time=15.29s
          fold 3/5 | acc=0.95896 | running_mean=0.95785 | time=15.52s
          fold 4/5 | acc=0.95490 | running_mean=0.95711 | time=16.75s
          fold 5/5 | acc=0.95552 | running_mean=0.95679 | time=16.03s
          fold 1/5 | acc=0.94271 | running_mean=0.94271 | time=12.44s
          fold 2/5 | acc=0.94760 | running_mean=0.94516 | time=12.48s
          fold 3/5 | acc=0.94708 | running_mean=0.94580 | time=13.29s
          fold 4/5 | acc=0.94396 | running_mean=0.94534 | time=13.81s
          fold 5/5 | acc=0.94448 | running_mean=0.94517 | time=12.73s
          fold 1/5 | acc=0.93917 | running_mean=0.93917 | time=7.48s
          fold 2/5 | acc=0.94323 | running_mean=0.94120 | time=8.01s
          fold 3/5 | acc=0.94385 | running_mean=0.94208 | time=7.56s
          fold 4/5 | acc=0.93771 | running_mean=0.94099 | time=7.15s
          fold 5/5 | acc=0.93948 | running_mean=0.94069 | time=7.50s
          fold 1/5 | acc=0.95833 | running_mean=0.95833 | time=12.44s
          fold 2/5 | acc=0.96208 | running_mean=0.96021 | time=12.38s
          fold 3/5 | acc=0.96292 | running_mean=0.96111 | time=12.08s
          fold 4/5 | acc=0.95833 | running_mean=0.96042 | time=13.91s
          fold 5/5 | acc=0.95969 | running_mean=0.96027 | time=14.00s
          fold 1/5 | acc=0.95854 | running_mean=0.95854 | time=19.63s
          fold 2/5 | acc=0.96292 | running_mean=0.96073 | time=14.75s
          fold 3/5 | acc=0.96344 | running_mean=0.96163 | time=15.08s
          fold 4/5 | acc=0.95885 | running_mean=0.96094 | time=18.70s
          fold 5/5 | acc=0.96021 | running_mean=0.96079 | time=14.58s
          fold 1/5 | acc=0.95927 | running_mean=0.95927 | time=23.07s
          fold 2/5 | acc=0.96292 | running_mean=0.96109 | time=20.53s
          fold 3/5 | acc=0.96417 | running_mean=0.96212 | time=17.82s
          fold 4/5 | acc=0.95969 | running_mean=0.96151 | time=18.24s
          fold 5/5 | acc=0.96042 | running_mean=0.96129 | time=19.27s
          fold 1/5 | acc=0.95396 | running_mean=0.95396 | time=24.72s
          fold 2/5 | acc=0.95719 | running_mean=0.95557 | time=14.72s
          fold 3/5 | acc=0.95750 | running_mean=0.95622 | time=14.76s
          fold 4/5 | acc=0.95323 | running_mean=0.95547 | time=15.33s
          fold 5/5 | acc=0.95458 | running_mean=0.95529 | time=14.31s
          fold 1/5 | acc=0.95979 | running_mean=0.95979 | time=14.21s
          fold 2/5 | acc=0.96156 | running_mean=0.96068 | time=13.67s
          fold 3/5 | acc=0.96385 | running_mean=0.96174 | time=14.69s
          fold 4/5 | acc=0.96010 | running_mean=0.96133 | time=14.48s
          fold 5/5 | acc=0.95927 | running_mean=0.96092 | time=15.77s
          fold 1/5 | acc=0.95479 | running_mean=0.95479 | time=10.92s
          fold 2/5 | acc=0.95792 | running_mean=0.95635 | time=12.90s
          fold 3/5 | acc=0.95854 | running_mean=0.95708 | time=16.12s
          fold 4/5 | acc=0.95531 | running_mean=0.95664 | time=13.58s
          fold 5/5 | acc=0.95510 | running_mean=0.95633 | time=11.05s
          fold 1/5 | acc=0.84688 | running_mean=0.84688 | time=4.35s
          fold 2/5 | acc=0.85188 | running_mean=0.84937 | time=5.79s
          fold 3/5 | acc=0.84740 | running_mean=0.84872 | time=4.52s
          fold 4/5 | acc=0.84802 | running_mean=0.84854 | time=6.24s
          fold 5/5 | acc=0.84594 | running_mean=0.84802 | time=5.52s
          fold 1/5 | acc=0.95323 | running_mean=0.95323 | time=16.21s
          fold 2/5 | acc=0.95781 | running_mean=0.95552 | time=16.73s
          fold 3/5 | acc=0.95885 | running_mean=0.95663 | time=18.19s
          fold 4/5 | acc=0.95531 | running_mean=0.95630 | time=16.38s
          fold 5/5 | acc=0.95781 | running_mean=0.95660 | time=17.84s
          fold 1/5 | acc=0.95146 | running_mean=0.95146 | time=20.83s
          fold 2/5 | acc=0.95417 | running_mean=0.95281 | time=17.61s
          fold 3/5 | acc=0.95437 | running_mean=0.95333 | time=16.63s
          fold 4/5 | acc=0.94969 | running_mean=0.95242 | time=16.12s
          fold 5/5 | acc=0.95156 | running_mean=0.95225 | time=16.36s
          fold 1/5 | acc=0.95250 | running_mean=0.95250 | time=56.41s
          fold 2/5 | acc=0.95792 | running_mean=0.95521 | time=62.16s
          fold 3/5 | acc=0.95688 | running_mean=0.95576 | time=67.67s
          fold 4/5 | acc=0.95229 | running_mean=0.95490 | time=66.28s
          fold 5/5 | acc=0.95583 | running_mean=0.95508 | time=59.24s
          fold 1/5 | acc=0.95781 | running_mean=0.95781 | time=24.05s
          fold 2/5 | acc=0.96198 | running_mean=0.95990 | time=29.91s
          fold 3/5 | acc=0.96271 | running_mean=0.96083 | time=26.79s
          fold 4/5 | acc=0.95990 | running_mean=0.96060 | time=25.34s
          fold 5/5 | acc=0.96062 | running_mean=0.96060 | time=22.56s
          fold 1/5 | acc=0.96000 | running_mean=0.96000 | time=20.41s
          fold 2/5 | acc=0.96250 | running_mean=0.96125 | time=18.61s
          fold 3/5 | acc=0.96375 | running_mean=0.96208 | time=20.57s
          fold 4/5 | acc=0.95948 | running_mean=0.96143 | time=18.05s
          fold 5/5 | acc=0.96104 | running_mean=0.96135 | time=18.96s
          fold 1/5 | acc=0.95427 | running_mean=0.95427 | time=17.43s
          fold 2/5 | acc=0.95792 | running_mean=0.95609 | time=16.95s
          fold 3/5 | acc=0.95854 | running_mean=0.95691 | time=17.23s
          fold 4/5 | acc=0.95500 | running_mean=0.95643 | time=16.64s
          fold 5/5 | acc=0.95771 | running_mean=0.95669 | time=20.26s
          fold 1/5 | acc=0.95906 | running_mean=0.95906 | time=13.37s
          fold 2/5 | acc=0.96250 | running_mean=0.96078 | time=13.21s
          fold 3/5 | acc=0.96281 | running_mean=0.96146 | time=14.13s
          fold 4/5 | acc=0.95906 | running_mean=0.96086 | time=14.30s
          fold 5/5 | acc=0.95979 | running_mean=0.96065 | time=14.68s
          fold 1/5 | acc=0.96875 | running_mean=0.96875 | time=42.73s
          fold 2/5 | acc=0.97229 | running_mean=0.97052 | time=41.81s
          fold 3/5 | acc=0.97062 | running_mean=0.97056 | time=39.94s
          fold 4/5 | acc=0.96937 | running_mean=0.97026 | time=52.73s
          fold 5/5 | acc=0.97198 | running_mean=0.97060 | time=56.02s
          fold 1/5 | acc=0.96927 | running_mean=0.96927 | time=46.33s
          fold 2/5 | acc=0.97229 | running_mean=0.97078 | time=48.39s
          fold 3/5 | acc=0.97042 | running_mean=0.97066 | time=53.24s
          fold 4/5 | acc=0.96885 | running_mean=0.97021 | time=41.96s
          fold 5/5 | acc=0.97219 | running_mean=0.97060 | time=41.29s
          fold 1/5 | acc=0.95937 | running_mean=0.95937 | time=39.44s
          fold 2/5 | acc=0.96396 | running_mean=0.96167 | time=40.73s
          fold 3/5 | acc=0.96229 | running_mean=0.96188 | time=38.02s
          fold 4/5 | acc=0.95833 | running_mean=0.96099 | time=40.29s
          fold 5/5 | acc=0.96365 | running_mean=0.96152 | time=39.36s
          fold 1/5 | acc=0.96156 | running_mean=0.96156 | time=30.47s
          fold 2/5 | acc=0.96490 | running_mean=0.96323 | time=30.59s
          fold 3/5 | acc=0.96479 | running_mean=0.96375 | time=28.85s
          fold 4/5 | acc=0.96094 | running_mean=0.96305 | time=30.33s
          fold 5/5 | acc=0.96469 | running_mean=0.96337 | time=29.41s
          fold 1/5 | acc=0.95937 | running_mean=0.95937 | time=31.97s
          fold 2/5 | acc=0.96458 | running_mean=0.96198 | time=30.81s
          fold 3/5 | acc=0.96146 | running_mean=0.96181 | time=32.03s
          fold 4/5 | acc=0.95781 | running_mean=0.96081 | time=32.22s
          fold 5/5 | acc=0.96302 | running_mean=0.96125 | time=43.82s
  [TPE RF] Time: 5297.96s | Memory Δ:   -90.5MB | Peak:   113.4MB
  [TPE Eval RF] Time:  394.22s | Memory Δ:  -145.2MB | Peak:   103.7MB
       Memory cleanup -> gc_collected=64, available=4.71 GB, used=70.1%, rss=242.9 MB
       Exported TPE artifacts

{'status': 'completed',
 'best':   Model Optimal_Scaler  Best_CV_Mean  Best_Trial  n_estimators  max_depth  min_samples_split  min_samples_leaf max_features
 0    RF         MinMax      0.970604          46           233         18                  2                 2         None,
 'history':    Model  Trial   CV_Mean  Best_Score_So_Far  Trial_Runtime_Sec
 0     RF      1  0.942646           0.942646          47.843787
 1     RF      2  0.951104           0.951104         128.170631
 2     RF      3  0.904292           0.951104          86.693251
 3     RF      4  0.931438           0.951104          28.158073
 4     RF      5  0.824563           0.951104         119.131775
 5     RF      6  0.942458           0.951104         346.789984
 6     RF      7  0.955688           0.955688          71.780327
 7     RF      8  0.950771           0.955688         133.568251
 8     RF      9  0.904708           0.955688          56.279376
 9     RF     10  0.934958           0.955688         190.240988
 10    RF     11  0.937125           0.955688          70.530700
 11    RF     12  0.957167           0.957167         105.300113
 12    RF     13  0.940646           0.957167         104.561876
 13    RF     14  0.949333           0.957167          77.572676
 14    RF     15  0.939917           0.957167          42.382389
 15    RF     16  0.948625           0.957167          77.848075
 16    RF     17  0.940313           0.957167          15.829892
 17    RF     18  0.960229           0.960229         132.855467
 18    RF     19  0.954333           0.960229         113.389173
 19    RF     20  0.956896           0.960229         121.262846
 20    RF     21  0.949500           0.960229         120.097669
 21    RF     22  0.960729           0.960729         101.915552
 22    RF     23  0.957417           0.960729          92.479148
 23    RF     24  0.953271           0.960729          91.663790
 24    RF     25  0.961354           0.961354          88.423613
 25    RF     26  0.956667           0.961354          77.319306
 26    RF     27  0.949979           0.961354          56.875565
 27    RF     28  0.960583           0.961354          69.464207
 28    RF     29  0.956792           0.961354          80.423172
 29    RF     30  0.945167           0.961354          64.810529
 30    RF     31  0.940687           0.961354          37.768049
 31    RF     32  0.960271           0.961354          64.881522
 32    RF     33  0.960792           0.961354          82.809932
 33    RF     34  0.961292           0.961354          99.024479
 34    RF     35  0.955292           0.961354          83.918556
 35    RF     36  0.960917           0.961354          72.894990
 36    RF     37  0.956333           0.961354          64.632850
 37    RF     38  0.848021           0.961354          26.483531
 38    RF     39  0.956604           0.961354          85.420897
 39    RF     40  0.952250           0.961354          87.628359
 40    RF     41  0.955083           0.961354         311.830772
 41    RF     42  0.960604           0.961354         128.725221
 42    RF     43  0.961354           0.961354          96.710172
 43    RF     44  0.956687           0.961354          88.596562
 44    RF     45  0.960646           0.961354          69.777821
 45    RF     46  0.970604           0.970604         233.314593
 46    RF     47  0.970604           0.970604         231.286751
 47    RF     48  0.961521           0.970604         197.900164
 48    RF     49  0.963375           0.970604         149.719920
 49    RF     50  0.961250           0.970604         170.909212,
 'summary':   Method Model Optimal_Scaler      Split  Accuracy  Precision    Recall        F1     Kappa       MCC       AUC   LogLoss  Accuracy_CI_Lower  Accuracy_CI_Upper  Precision_CI_Lower  Precision_CI_Upper  Recall_CI_Lower  Recall_CI_Upper  F1_CI_Lower  F1_CI_Upper  AUC_CI_Lower  AUC_CI_Upper  LogLoss_CI_Lower  LogLoss_CI_Upper  Kappa_CI_Lower  Kappa_CI_Upper  MCC_CI_Lower  MCC_CI_Upper
 0    TPE    RF         MinMax  Train_OOF  0.970604   0.970404  0.983934  0.977122  0.936020  0.936196  0.996158  0.121002           0.969145           0.972104            0.968525            0.972291         0.982521         0.985377     0.975982     0.978288      0.995836      0.996470          0.119005          0.123016        0.932780        0.939269      0.932944      0.939410
 1    TPE    RF         MinMax       Test  0.979250   0.978427  0.989289  0.983828  0.954887  0.955000  0.997863  0.100170           0.976833           0.981667            0.975291            0.981563         0.986883         0.991461     0.981889     0.985743      0.997419      0.998269          0.096740          0.103617        0.949571        0.960241      0.949755      0.960344,
 'timing':   Model  TPE_Search_Sec  TPE_Evaluation_Sec  TPE_Total_Sec  Best_CV_Mean
 0    RF     5297.961511          394.217436    5693.333136      0.970604}

In [42]:
run_tpe_model("GB")

GB         | Scaler: Raw        | Available RAM: 4.75 GB | Kernel RSS: 189.4 MB
       Memory cleanup -> gc_collected=0, available=4.71 GB, used=70.1%, rss=189.4 MB
       Running 50 trials with n_jobs_cv=1, n_jobs_opt=8
          fold 1/5 | acc=0.99083 | running_mean=0.99083 | time=135.65s
          fold 2/5 | acc=0.98927 | running_mean=0.99005 | time=215.46s
          fold 3/5 | acc=0.99125 | running_mean=0.99045 | time=184.83s
          fold 4/5 | acc=0.98938 | running_mean=0.99018 | time=159.06s
          fold 5/5 | acc=0.99062 | running_mean=0.99027 | time=198.35s
          fold 1/5 | acc=0.98313 | running_mean=0.98313 | time=56.74s
          fold 2/5 | acc=0.98604 | running_mean=0.98458 | time=67.59s
          fold 3/5 | acc=0.98625 | running_mean=0.98514 | time=71.88s
          fold 4/5 | acc=0.98719 | running_mean=0.98565 | time=106.99s
          fold 5/5 | acc=0.98531 | running_mean=0.98558 | time=85.17s
          fold 1/5 | acc=0.96240 | running_mean=0.96240 | time=255.49s
          fold 2/5 | acc=0.96271 | running_mean=0.96255 | time=221.18s
          fold 3/5 | acc=0.96427 | running_mean=0.96313 | time=247.00s
          fold 4/5 | acc=0.96042 | running_mean=0.96245 | time=256.18s
          fold 5/5 | acc=0.95958 | running_mean=0.96188 | time=237.93s
          fold 1/5 | acc=0.97969 | running_mean=0.97969 | time=247.54s
          fold 2/5 | acc=0.98031 | running_mean=0.98000 | time=251.07s
          fold 3/5 | acc=0.98260 | running_mean=0.98087 | time=279.76s
          fold 4/5 | acc=0.98062 | running_mean=0.98081 | time=257.26s
          fold 5/5 | acc=0.98031 | running_mean=0.98071 | time=197.60s
          fold 1/5 | acc=0.99010 | running_mean=0.99010 | time=73.48s
          fold 2/5 | acc=0.98875 | running_mean=0.98943 | time=88.97s
          fold 3/5 | acc=0.98990 | running_mean=0.98958 | time=103.63s
          fold 4/5 | acc=0.98885 | running_mean=0.98940 | time=103.00s
          fold 5/5 | acc=0.99010 | running_mean=0.98954 | time=91.91s
          fold 1/5 | acc=0.89865 | running_mean=0.89865 | time=126.63s
          fold 2/5 | acc=0.90687 | running_mean=0.90276 | time=92.58s
          fold 3/5 | acc=0.90521 | running_mean=0.90358 | time=98.96s
          fold 4/5 | acc=0.90198 | running_mean=0.90318 | time=95.14s
          fold 5/5 | acc=0.89885 | running_mean=0.90231 | time=86.50s
          fold 1/5 | acc=0.97104 | running_mean=0.97104 | time=149.34s
          fold 2/5 | acc=0.97396 | running_mean=0.97250 | time=193.37s
          fold 3/5 | acc=0.97365 | running_mean=0.97288 | time=208.27s
          fold 4/5 | acc=0.97052 | running_mean=0.97229 | time=212.88s
          fold 5/5 | acc=0.97292 | running_mean=0.97242 | time=178.63s
          fold 1/5 | acc=0.97865 | running_mean=0.97865 | time=33.82s
          fold 2/5 | acc=0.97958 | running_mean=0.97911 | time=32.79s
          fold 3/5 | acc=0.97990 | running_mean=0.97937 | time=35.74s
          fold 4/5 | acc=0.98042 | running_mean=0.97964 | time=42.23s
          fold 5/5 | acc=0.97760 | running_mean=0.97923 | time=27.80s
          fold 1/5 | acc=0.98396 | running_mean=0.98396 | time=432.42s
          fold 2/5 | acc=0.98583 | running_mean=0.98490 | time=465.59s
          fold 3/5 | acc=0.98562 | running_mean=0.98514 | time=510.97s
          fold 4/5 | acc=0.98458 | running_mean=0.98500 | time=448.13s
          fold 5/5 | acc=0.98573 | running_mean=0.98515 | time=368.56s
          fold 1/5 | acc=0.99344 | running_mean=0.99344 | time=133.32s
          fold 2/5 | acc=0.99135 | running_mean=0.99240 | time=127.83s
          fold 3/5 | acc=0.99156 | running_mean=0.99212 | time=116.01s
          fold 4/5 | acc=0.99219 | running_mean=0.99214 | time=127.01s
          fold 5/5 | acc=0.99146 | running_mean=0.99200 | time=131.35s
          fold 1/5 | acc=0.99438 | running_mean=0.99438 | time=310.13s
          fold 2/5 | acc=0.99156 | running_mean=0.99297 | time=307.65s
          fold 3/5 | acc=0.99187 | running_mean=0.99260 | time=334.20s
          fold 4/5 | acc=0.99385 | running_mean=0.99292 | time=219.20s
          fold 5/5 | acc=0.99292 | running_mean=0.99292 | time=260.48s
          fold 1/5 | acc=0.99448 | running_mean=0.99448 | time=183.91s
          fold 2/5 | acc=0.99292 | running_mean=0.99370 | time=200.70s
          fold 3/5 | acc=0.99281 | running_mean=0.99340 | time=231.89s
          fold 4/5 | acc=0.99323 | running_mean=0.99336 | time=322.63s
          fold 5/5 | acc=0.99385 | running_mean=0.99346 | time=290.40s
          fold 1/5 | acc=0.99365 | running_mean=0.99365 | time=254.95s
          fold 2/5 | acc=0.99292 | running_mean=0.99328 | time=325.43s
          fold 3/5 | acc=0.99375 | running_mean=0.99344 | time=288.87s
          fold 4/5 | acc=0.99344 | running_mean=0.99344 | time=182.46s
          fold 5/5 | acc=0.99396 | running_mean=0.99354 | time=171.22s
          fold 1/5 | acc=0.99281 | running_mean=0.99281 | time=159.73s
          fold 2/5 | acc=0.99229 | running_mean=0.99255 | time=160.40s
          fold 3/5 | acc=0.99208 | running_mean=0.99240 | time=158.91s
          fold 4/5 | acc=0.99260 | running_mean=0.99245 | time=157.27s
          fold 5/5 | acc=0.99260 | running_mean=0.99248 | time=154.72s
          fold 1/5 | acc=0.99031 | running_mean=0.99031 | time=164.02s
          fold 2/5 | acc=0.98948 | running_mean=0.98990 | time=165.20s
          fold 3/5 | acc=0.99042 | running_mean=0.99007 | time=166.23s
          fold 4/5 | acc=0.99010 | running_mean=0.99008 | time=165.89s
          fold 5/5 | acc=0.99021 | running_mean=0.99010 | time=165.25s
          fold 1/5 | acc=0.98938 | running_mean=0.98938 | time=199.25s
          fold 2/5 | acc=0.98771 | running_mean=0.98854 | time=190.62s
          fold 3/5 | acc=0.98917 | running_mean=0.98875 | time=182.79s
          fold 4/5 | acc=0.98625 | running_mean=0.98813 | time=312.97s
          fold 5/5 | acc=0.98667 | running_mean=0.98783 | time=250.01s
          fold 1/5 | acc=0.99021 | running_mean=0.99021 | time=215.72s
          fold 2/5 | acc=0.99156 | running_mean=0.99089 | time=303.65s
          fold 3/5 | acc=0.99187 | running_mean=0.99122 | time=322.41s
          fold 4/5 | acc=0.99021 | running_mean=0.99096 | time=292.91s
          fold 5/5 | acc=0.99042 | running_mean=0.99085 | time=333.35s
          fold 1/5 | acc=0.98365 | running_mean=0.98365 | time=133.66s
          fold 2/5 | acc=0.98292 | running_mean=0.98328 | time=159.56s
          fold 3/5 | acc=0.98469 | running_mean=0.98375 | time=110.48s
          fold 4/5 | acc=0.98427 | running_mean=0.98388 | time=102.88s
          fold 5/5 | acc=0.98250 | running_mean=0.98360 | time=116.76s
          fold 1/5 | acc=0.98823 | running_mean=0.98823 | time=83.06s
          fold 2/5 | acc=0.98781 | running_mean=0.98802 | time=90.79s
          fold 3/5 | acc=0.98865 | running_mean=0.98823 | time=85.46s
          fold 4/5 | acc=0.98885 | running_mean=0.98839 | time=80.61s
          fold 5/5 | acc=0.98750 | running_mean=0.98821 | time=81.70s
          fold 1/5 | acc=0.96156 | running_mean=0.96156 | time=117.67s
          fold 2/5 | acc=0.96208 | running_mean=0.96182 | time=111.57s
          fold 3/5 | acc=0.96313 | running_mean=0.96226 | time=61.56s
          fold 4/5 | acc=0.96510 | running_mean=0.96297 | time=61.44s
          fold 5/5 | acc=0.96333 | running_mean=0.96304 | time=108.62s
          fold 1/5 | acc=0.99281 | running_mean=0.99281 | time=204.14s
          fold 2/5 | acc=0.99292 | running_mean=0.99286 | time=201.05s
          fold 3/5 | acc=0.99313 | running_mean=0.99295 | time=165.28s
          fold 4/5 | acc=0.99313 | running_mean=0.99299 | time=192.94s
          fold 5/5 | acc=0.99292 | running_mean=0.99298 | time=162.42s
          fold 1/5 | acc=0.99427 | running_mean=0.99427 | time=253.16s
          fold 2/5 | acc=0.99250 | running_mean=0.99339 | time=261.69s
          fold 3/5 | acc=0.99313 | running_mean=0.99330 | time=244.14s
          fold 4/5 | acc=0.99365 | running_mean=0.99339 | time=207.34s
          fold 5/5 | acc=0.99219 | running_mean=0.99315 | time=247.73s
          fold 1/5 | acc=0.99490 | running_mean=0.99490 | time=258.22s
          fold 2/5 | acc=0.99417 | running_mean=0.99453 | time=230.61s
          fold 3/5 | acc=0.99469 | running_mean=0.99458 | time=256.70s
          fold 4/5 | acc=0.99458 | running_mean=0.99458 | time=180.48s
          fold 5/5 | acc=0.99490 | running_mean=0.99465 | time=287.48s
          fold 1/5 | acc=0.99458 | running_mean=0.99458 | time=233.64s
          fold 2/5 | acc=0.99250 | running_mean=0.99354 | time=178.39s
          fold 3/5 | acc=0.99469 | running_mean=0.99392 | time=243.58s
          fold 4/5 | acc=0.99583 | running_mean=0.99440 | time=259.47s
          fold 5/5 | acc=0.99531 | running_mean=0.99458 | time=197.48s
          fold 1/5 | acc=0.99458 | running_mean=0.99458 | time=212.39s
          fold 2/5 | acc=0.99313 | running_mean=0.99385 | time=213.46s
          fold 3/5 | acc=0.99479 | running_mean=0.99417 | time=206.12s
          fold 4/5 | acc=0.99510 | running_mean=0.99440 | time=212.36s
          fold 5/5 | acc=0.99406 | running_mean=0.99433 | time=226.50s
          fold 1/5 | acc=0.99281 | running_mean=0.99281 | time=186.04s
          fold 2/5 | acc=0.99198 | running_mean=0.99240 | time=97.58s
          fold 3/5 | acc=0.99167 | running_mean=0.99215 | time=171.93s
          fold 4/5 | acc=0.99292 | running_mean=0.99234 | time=179.92s
          fold 5/5 | acc=0.99344 | running_mean=0.99256 | time=182.65s
          fold 1/5 | acc=0.99500 | running_mean=0.99500 | time=155.41s
          fold 2/5 | acc=0.99406 | running_mean=0.99453 | time=155.19s
          fold 3/5 | acc=0.99417 | running_mean=0.99441 | time=158.06s
          fold 4/5 | acc=0.99521 | running_mean=0.99461 | time=132.12s
          fold 5/5 | acc=0.99500 | running_mean=0.99469 | time=194.48s
          fold 1/5 | acc=0.99302 | running_mean=0.99302 | time=95.98s
          fold 2/5 | acc=0.99229 | running_mean=0.99266 | time=143.37s
          fold 3/5 | acc=0.99281 | running_mean=0.99271 | time=126.89s
          fold 4/5 | acc=0.99344 | running_mean=0.99289 | time=122.76s
          fold 5/5 | acc=0.99344 | running_mean=0.99300 | time=106.58s
          fold 1/5 | acc=0.99365 | running_mean=0.99365 | time=217.24s
          fold 2/5 | acc=0.99271 | running_mean=0.99318 | time=251.09s
          fold 3/5 | acc=0.99385 | running_mean=0.99340 | time=251.18s
          fold 4/5 | acc=0.99438 | running_mean=0.99365 | time=180.05s
          fold 5/5 | acc=0.99448 | running_mean=0.99381 | time=163.24s
          fold 1/5 | acc=0.98948 | running_mean=0.98948 | time=39.55s
          fold 2/5 | acc=0.98938 | running_mean=0.98943 | time=39.22s
          fold 3/5 | acc=0.98771 | running_mean=0.98885 | time=43.31s
          fold 4/5 | acc=0.99115 | running_mean=0.98943 | time=39.92s
          fold 5/5 | acc=0.98917 | running_mean=0.98938 | time=41.46s
          fold 1/5 | acc=0.99260 | running_mean=0.99260 | time=66.21s
          fold 2/5 | acc=0.99187 | running_mean=0.99224 | time=74.22s
          fold 3/5 | acc=0.99354 | running_mean=0.99267 | time=78.38s
          fold 4/5 | acc=0.99354 | running_mean=0.99289 | time=83.09s
          fold 5/5 | acc=0.99333 | running_mean=0.99298 | time=126.20s
          fold 1/5 | acc=0.99573 | running_mean=0.99573 | time=190.84s
          fold 2/5 | acc=0.99313 | running_mean=0.99443 | time=192.16s
          fold 3/5 | acc=0.99490 | running_mean=0.99458 | time=183.60s
          fold 4/5 | acc=0.99490 | running_mean=0.99466 | time=191.48s
          fold 5/5 | acc=0.99438 | running_mean=0.99460 | time=179.04s
          fold 1/5 | acc=0.99385 | running_mean=0.99385 | time=180.92s
          fold 2/5 | acc=0.99521 | running_mean=0.99453 | time=159.03s
          fold 3/5 | acc=0.99323 | running_mean=0.99410 | time=136.22s
          fold 4/5 | acc=0.99510 | running_mean=0.99435 | time=130.83s
          fold 5/5 | acc=0.99333 | running_mean=0.99415 | time=131.18s
          fold 1/5 | acc=0.99490 | running_mean=0.99490 | time=157.25s
          fold 2/5 | acc=0.99292 | running_mean=0.99391 | time=160.55s
          fold 3/5 | acc=0.99427 | running_mean=0.99403 | time=192.86s
          fold 4/5 | acc=0.99469 | running_mean=0.99419 | time=147.04s
          fold 5/5 | acc=0.99448 | running_mean=0.99425 | time=204.77s
          fold 1/5 | acc=0.99625 | running_mean=0.99625 | time=161.36s
          fold 2/5 | acc=0.99469 | running_mean=0.99547 | time=230.03s
          fold 3/5 | acc=0.99542 | running_mean=0.99545 | time=210.78s
          fold 4/5 | acc=0.99687 | running_mean=0.99581 | time=202.83s
          fold 5/5 | acc=0.99583 | running_mean=0.99581 | time=189.98s
          fold 1/5 | acc=0.99323 | running_mean=0.99323 | time=106.35s
          fold 2/5 | acc=0.99302 | running_mean=0.99313 | time=136.19s
          fold 3/5 | acc=0.99365 | running_mean=0.99330 | time=102.15s
          fold 4/5 | acc=0.99479 | running_mean=0.99367 | time=154.09s
          fold 5/5 | acc=0.99406 | running_mean=0.99375 | time=130.62s
          fold 1/5 | acc=0.98125 | running_mean=0.98125 | time=43.57s
          fold 2/5 | acc=0.97802 | running_mean=0.97964 | time=51.54s
          fold 3/5 | acc=0.98146 | running_mean=0.98024 | time=50.59s
          fold 4/5 | acc=0.98104 | running_mean=0.98044 | time=42.57s
          fold 5/5 | acc=0.98042 | running_mean=0.98044 | time=34.56s
          fold 1/5 | acc=0.99313 | running_mean=0.99313 | time=259.28s
          fold 2/5 | acc=0.99260 | running_mean=0.99286 | time=281.41s
          fold 3/5 | acc=0.99448 | running_mean=0.99340 | time=276.16s
          fold 4/5 | acc=0.99354 | running_mean=0.99344 | time=285.95s
          fold 5/5 | acc=0.99344 | running_mean=0.99344 | time=310.45s
          fold 1/5 | acc=0.99469 | running_mean=0.99469 | time=178.57s
          fold 2/5 | acc=0.99438 | running_mean=0.99453 | time=195.94s
          fold 3/5 | acc=0.99417 | running_mean=0.99441 | time=159.10s
          fold 4/5 | acc=0.99552 | running_mean=0.99469 | time=187.39s
          fold 5/5 | acc=0.99531 | running_mean=0.99481 | time=125.37s
          fold 1/5 | acc=0.99385 | running_mean=0.99385 | time=106.09s
          fold 2/5 | acc=0.99271 | running_mean=0.99328 | time=112.44s
          fold 3/5 | acc=0.99396 | running_mean=0.99351 | time=155.35s
          fold 4/5 | acc=0.99417 | running_mean=0.99367 | time=109.37s
          fold 5/5 | acc=0.99229 | running_mean=0.99340 | time=147.73s
          fold 1/5 | acc=0.99000 | running_mean=0.99000 | time=172.22s
          fold 2/5 | acc=0.98771 | running_mean=0.98885 | time=171.78s
          fold 3/5 | acc=0.98990 | running_mean=0.98920 | time=181.01s
          fold 4/5 | acc=0.98771 | running_mean=0.98883 | time=179.98s
          fold 5/5 | acc=0.98896 | running_mean=0.98885 | time=153.89s
          fold 1/5 | acc=0.99510 | running_mean=0.99510 | time=163.32s
          fold 2/5 | acc=0.99469 | running_mean=0.99490 | time=148.30s
          fold 3/5 | acc=0.99323 | running_mean=0.99434 | time=215.84s
          fold 4/5 | acc=0.99427 | running_mean=0.99432 | time=220.85s
          fold 5/5 | acc=0.99458 | running_mean=0.99438 | time=210.91s
          fold 1/5 | acc=0.97229 | running_mean=0.97229 | time=100.27s
          fold 2/5 | acc=0.97042 | running_mean=0.97135 | time=98.01s
          fold 3/5 | acc=0.97437 | running_mean=0.97236 | time=87.47s
          fold 4/5 | acc=0.97198 | running_mean=0.97227 | time=83.19s
          fold 5/5 | acc=0.97083 | running_mean=0.97198 | time=84.97s
          fold 1/5 | acc=0.99187 | running_mean=0.99187 | time=119.55s
          fold 2/5 | acc=0.99083 | running_mean=0.99135 | time=140.63s
          fold 3/5 | acc=0.99281 | running_mean=0.99184 | time=136.56s
          fold 4/5 | acc=0.99177 | running_mean=0.99182 | time=129.80s
          fold 5/5 | acc=0.99125 | running_mean=0.99171 | time=133.11s
          fold 1/5 | acc=0.90781 | running_mean=0.90781 | time=176.15s
          fold 2/5 | acc=0.91635 | running_mean=0.91208 | time=206.82s
          fold 3/5 | acc=0.91563 | running_mean=0.91326 | time=164.52s
          fold 4/5 | acc=0.91312 | running_mean=0.91323 | time=199.73s
          fold 5/5 | acc=0.90917 | running_mean=0.91242 | time=149.27s
          fold 1/5 | acc=0.99396 | running_mean=0.99396 | time=167.14s
          fold 2/5 | acc=0.99135 | running_mean=0.99266 | time=164.03s
          fold 3/5 | acc=0.99187 | running_mean=0.99240 | time=167.20s
          fold 4/5 | acc=0.99417 | running_mean=0.99284 | time=143.85s
          fold 5/5 | acc=0.99104 | running_mean=0.99248 | time=144.44s
          fold 1/5 | acc=0.99479 | running_mean=0.99479 | time=363.13s
          fold 2/5 | acc=0.99323 | running_mean=0.99401 | time=447.65s
          fold 3/5 | acc=0.99354 | running_mean=0.99385 | time=259.14s
          fold 4/5 | acc=0.99396 | running_mean=0.99388 | time=272.01s
          fold 5/5 | acc=0.99438 | running_mean=0.99398 | time=336.79s
          fold 1/5 | acc=0.99615 | running_mean=0.99615 | time=178.23s
          fold 2/5 | acc=0.99292 | running_mean=0.99453 | time=200.63s
          fold 3/5 | acc=0.99365 | running_mean=0.99424 | time=183.04s
          fold 4/5 | acc=0.99344 | running_mean=0.99404 | time=207.51s
          fold 5/5 | acc=0.99635 | running_mean=0.99450 | time=212.52s
          fold 1/5 | acc=0.98719 | running_mean=0.98719 | time=76.43s
          fold 2/5 | acc=0.98875 | running_mean=0.98797 | time=72.41s
          fold 3/5 | acc=0.98719 | running_mean=0.98771 | time=118.10s
          fold 4/5 | acc=0.98813 | running_mean=0.98781 | time=93.04s
          fold 5/5 | acc=0.98510 | running_mean=0.98727 | time=86.68s
          fold 1/5 | acc=0.99302 | running_mean=0.99302 | time=140.28s
          fold 2/5 | acc=0.99146 | running_mean=0.99224 | time=139.90s
          fold 3/5 | acc=0.99208 | running_mean=0.99219 | time=137.97s
          fold 4/5 | acc=0.99250 | running_mean=0.99227 | time=137.32s
          fold 5/5 | acc=0.99333 | running_mean=0.99248 | time=142.38s
  [TPE GB] Time: 43420.38s | Memory Δ:  -144.2MB | Peak:    45.3MB
  [TPE Eval GB] Time:  793.89s | Memory Δ:  -140.7MB | Peak:    44.8MB
       Memory cleanup -> gc_collected=64, available=6.40 GB, used=59.3%, rss=186.9 MB
       Exported TPE artifacts

{'status': 'completed',
 'best':   Model Optimal_Scaler  Best_CV_Mean  Best_Trial  n_estimators  learning_rate  max_depth  min_samples_split  min_samples_leaf  subsample
 0    GB            Raw      0.995813          34           447        0.40012          5                  4                 8   0.728487,
 'history':    Model  Trial   CV_Mean  Best_Score_So_Far  Trial_Runtime_Sec
 0     GB      1  0.990271           0.990271         893.379563
 1     GB      2  0.985583           0.990271         388.390858
 2     GB      3  0.961875           0.990271        1217.823000
 3     GB      4  0.980708           0.990271        1233.276206
 4     GB      5  0.989542           0.990271         461.036835
 5     GB      6  0.902313           0.990271         499.855642
 6     GB      7  0.972417           0.990271         942.538571
 7     GB      8  0.979229           0.990271         172.412765
 8     GB      9  0.985146           0.990271        2225.706093
 9     GB     10  0.992000           0.992000         635.557444
 10    GB     11  0.992917           0.992917        1431.855026
 11    GB     12  0.993458           0.993458        1229.629987
 12    GB     13  0.993542           0.993542        1222.983617
 13    GB     14  0.992479           0.993542         791.104923
 14    GB     15  0.990104           0.993542         826.625243
 15    GB     16  0.987833           0.993542        1135.720805
 16    GB     17  0.990854           0.993542        1468.111840
 17    GB     18  0.983604           0.993542         623.383954
 18    GB     19  0.988208           0.993542         421.668088
 19    GB     20  0.963042           0.993542         460.891371
 20    GB     21  0.992979           0.993542         925.882790
 21    GB     22  0.993146           0.993542        1214.128799
 22    GB     23  0.994646           0.994646        1213.595203
 23    GB     24  0.994583           0.994646        1112.713636
 24    GB     25  0.994333           0.994646        1070.910644
 25    GB     26  0.992563           0.994646         818.199685
 26    GB     27  0.994688           0.994688         795.337711
 27    GB     28  0.993000           0.994688         595.686606
 28    GB     29  0.993812           0.994688        1062.912283
 29    GB     30  0.989375           0.994688         203.519219
 30    GB     31  0.992979           0.994688         428.141986
 31    GB     32  0.994604           0.994688         937.223880
 32    GB     33  0.994146           0.994688         738.359683
 33    GB     34  0.994250           0.994688         862.561667
 34    GB     35  0.995813           0.995813         995.072026
 35    GB     36  0.993750           0.995813         629.503833
 36    GB     37  0.980438           0.995813         222.919775
 37    GB     38  0.993438           0.995813        1413.342202
 38    GB     39  0.994813           0.995813         846.474714
 39    GB     40  0.993396           0.995813         631.034810
 40    GB     41  0.988854           0.995813         858.954642
 41    GB     42  0.994375           0.995813         959.277714
 42    GB     43  0.971979           0.995813         453.973524
 43    GB     44  0.991708           0.995813         659.712845
 44    GB     45  0.912417           0.995813         896.554823
 45    GB     46  0.992479           0.995813         786.713433
 46    GB     47  0.993979           0.995813        1678.797130
 47    GB     48  0.994500           0.995813         982.039893
 48    GB     49  0.987271           0.995813         446.702022
 49    GB     50  0.992479           0.995813         697.891773,
 'summary':   Method Model Optimal_Scaler      Split  Accuracy  Precision    Recall        F1     Kappa       MCC       AUC   LogLoss  Accuracy_CI_Lower  Accuracy_CI_Upper  Precision_CI_Lower  Precision_CI_Upper  Recall_CI_Lower  Recall_CI_Upper  F1_CI_Lower  F1_CI_Upper  AUC_CI_Lower  AUC_CI_Upper  LogLoss_CI_Lower  LogLoss_CI_Upper  Kappa_CI_Lower  Kappa_CI_Upper  MCC_CI_Lower  MCC_CI_Upper
 0    TPE    GB            Raw  Train_OOF  0.995812   0.995860  0.997584  0.996721  0.990928  0.990931  0.999828  0.014684           0.995229           0.996375            0.995156            0.996569         0.997030         0.998104     0.996269     0.997160      0.999767      0.999882          0.013382          0.016039        0.989670        0.992142      0.989675      0.992145
 1    TPE    GB            Raw       Test  0.998000   0.997782  0.999086  0.998434  0.995668  0.995670  0.999937  0.009615           0.997167           0.998750            0.996698            0.998819         0.998417         0.999738     0.997780     0.999023      0.999863      0.999987          0.008025          0.011480        0.993895        0.997311      0.993897      0.997313,
 'timing':   Model  TPE_Search_Sec  TPE_Evaluation_Sec  TPE_Total_Sec  Best_CV_Mean
 0    GB    43420.378867          793.890236   44215.377276      0.995813}

In [43]:
run_tpe_model("XGB")

XGB        | Scaler: MinMax     | Available RAM: 6.32 GB | Kernel RSS: 196.9 MB
       Memory cleanup -> gc_collected=64, available=6.31 GB, used=59.9%, rss=197.4 MB
       Running 50 trials with n_jobs_cv=1, n_jobs_opt=8
          fold 1/5 | acc=0.98594 | running_mean=0.98594 | time=1.62s
          fold 2/5 | acc=0.98667 | running_mean=0.98630 | time=1.82s
          fold 3/5 | acc=0.98646 | running_mean=0.98635 | time=4.27s
          fold 4/5 | acc=0.98719 | running_mean=0.98656 | time=5.43s
          fold 5/5 | acc=0.98656 | running_mean=0.98656 | time=4.24s
          fold 1/5 | acc=0.95531 | running_mean=0.95531 | time=10.42s
          fold 2/5 | acc=0.95813 | running_mean=0.95672 | time=9.17s
          fold 3/5 | acc=0.95917 | running_mean=0.95753 | time=5.82s
          fold 4/5 | acc=0.95490 | running_mean=0.95688 | time=6.30s
          fold 5/5 | acc=0.95583 | running_mean=0.95667 | time=6.21s
          fold 1/5 | acc=0.97042 | running_mean=0.97042 | time=3.35s
          fold 2/5 | acc=0.97344 | running_mean=0.97193 | time=3.61s
          fold 3/5 | acc=0.97510 | running_mean=0.97299 | time=4.47s
          fold 4/5 | acc=0.97333 | running_mean=0.97307 | time=6.80s
          fold 5/5 | acc=0.97240 | running_mean=0.97294 | time=6.23s
          fold 1/5 | acc=0.95125 | running_mean=0.95125 | time=1.77s
          fold 2/5 | acc=0.95281 | running_mean=0.95203 | time=1.72s
          fold 3/5 | acc=0.95667 | running_mean=0.95358 | time=1.69s
          fold 4/5 | acc=0.95323 | running_mean=0.95349 | time=2.60s
          fold 5/5 | acc=0.95271 | running_mean=0.95333 | time=1.20s
          fold 1/5 | acc=0.94469 | running_mean=0.94469 | time=4.14s
          fold 2/5 | acc=0.94937 | running_mean=0.94703 | time=6.38s
          fold 3/5 | acc=0.95063 | running_mean=0.94823 | time=4.48s
          fold 4/5 | acc=0.94594 | running_mean=0.94766 | time=3.98s
          fold 5/5 | acc=0.94698 | running_mean=0.94752 | time=3.92s
          fold 1/5 | acc=0.96833 | running_mean=0.96833 | time=4.66s
          fold 2/5 | acc=0.97010 | running_mean=0.96922 | time=4.09s
          fold 3/5 | acc=0.97083 | running_mean=0.96976 | time=4.36s
          fold 4/5 | acc=0.96865 | running_mean=0.96948 | time=3.83s
          fold 5/5 | acc=0.97010 | running_mean=0.96960 | time=4.43s
          fold 1/5 | acc=0.98750 | running_mean=0.98750 | time=1.79s
          fold 2/5 | acc=0.98562 | running_mean=0.98656 | time=1.85s
          fold 3/5 | acc=0.98656 | running_mean=0.98656 | time=6.08s
          fold 4/5 | acc=0.98667 | running_mean=0.98659 | time=3.94s
          fold 5/5 | acc=0.98656 | running_mean=0.98658 | time=2.21s
          fold 1/5 | acc=0.96177 | running_mean=0.96177 | time=3.85s
          fold 2/5 | acc=0.96500 | running_mean=0.96339 | time=3.19s
          fold 3/5 | acc=0.96677 | running_mean=0.96451 | time=3.21s
          fold 4/5 | acc=0.96385 | running_mean=0.96435 | time=3.17s
          fold 5/5 | acc=0.96448 | running_mean=0.96438 | time=3.40s
          fold 1/5 | acc=0.97688 | running_mean=0.97688 | time=1.05s
          fold 2/5 | acc=0.97646 | running_mean=0.97667 | time=0.82s
          fold 3/5 | acc=0.97469 | running_mean=0.97601 | time=0.91s
          fold 4/5 | acc=0.97583 | running_mean=0.97596 | time=1.12s
          fold 5/5 | acc=0.97625 | running_mean=0.97602 | time=1.53s
          fold 1/5 | acc=0.92917 | running_mean=0.92917 | time=1.77s
          fold 2/5 | acc=0.93354 | running_mean=0.93135 | time=2.17s
          fold 3/5 | acc=0.93406 | running_mean=0.93226 | time=2.10s
          fold 4/5 | acc=0.92885 | running_mean=0.93141 | time=1.83s
          fold 5/5 | acc=0.92927 | running_mean=0.93098 | time=1.77s
          fold 1/5 | acc=0.98729 | running_mean=0.98729 | time=3.30s
          fold 2/5 | acc=0.98969 | running_mean=0.98849 | time=3.08s
          fold 3/5 | acc=0.98781 | running_mean=0.98826 | time=2.43s
          fold 4/5 | acc=0.98885 | running_mean=0.98841 | time=3.07s
          fold 5/5 | acc=0.98969 | running_mean=0.98867 | time=2.59s
          fold 1/5 | acc=0.98813 | running_mean=0.98813 | time=2.57s
          fold 2/5 | acc=0.98781 | running_mean=0.98797 | time=2.60s
          fold 3/5 | acc=0.98813 | running_mean=0.98802 | time=2.84s
          fold 4/5 | acc=0.98885 | running_mean=0.98823 | time=2.52s
          fold 5/5 | acc=0.98938 | running_mean=0.98846 | time=2.53s
          fold 1/5 | acc=0.98792 | running_mean=0.98792 | time=2.58s
          fold 2/5 | acc=0.98844 | running_mean=0.98818 | time=2.96s
          fold 3/5 | acc=0.99021 | running_mean=0.98885 | time=2.91s
          fold 4/5 | acc=0.99146 | running_mean=0.98951 | time=2.91s
          fold 5/5 | acc=0.99031 | running_mean=0.98967 | time=3.12s
          fold 1/5 | acc=0.98802 | running_mean=0.98802 | time=4.17s
          fold 2/5 | acc=0.98802 | running_mean=0.98802 | time=3.26s
          fold 3/5 | acc=0.98802 | running_mean=0.98802 | time=3.55s
          fold 4/5 | acc=0.98781 | running_mean=0.98797 | time=3.96s
          fold 5/5 | acc=0.98969 | running_mean=0.98831 | time=3.45s
          fold 1/5 | acc=0.98000 | running_mean=0.98000 | time=1.86s
          fold 2/5 | acc=0.98156 | running_mean=0.98078 | time=3.88s
          fold 3/5 | acc=0.98271 | running_mean=0.98142 | time=2.19s
          fold 4/5 | acc=0.98156 | running_mean=0.98146 | time=2.28s
          fold 5/5 | acc=0.98177 | running_mean=0.98152 | time=2.11s
          fold 1/5 | acc=0.98042 | running_mean=0.98042 | time=3.32s
          fold 2/5 | acc=0.97958 | running_mean=0.98000 | time=2.99s
          fold 3/5 | acc=0.98073 | running_mean=0.98024 | time=2.76s
          fold 4/5 | acc=0.98219 | running_mean=0.98073 | time=2.78s
          fold 5/5 | acc=0.98031 | running_mean=0.98065 | time=2.88s
          fold 1/5 | acc=0.98771 | running_mean=0.98771 | time=2.73s
          fold 2/5 | acc=0.98823 | running_mean=0.98797 | time=3.00s
          fold 3/5 | acc=0.98865 | running_mean=0.98819 | time=2.94s
          fold 4/5 | acc=0.98979 | running_mean=0.98859 | time=2.91s
          fold 5/5 | acc=0.98906 | running_mean=0.98869 | time=2.68s
          fold 1/5 | acc=0.98667 | running_mean=0.98667 | time=4.05s
          fold 2/5 | acc=0.98687 | running_mean=0.98677 | time=4.03s
          fold 3/5 | acc=0.98708 | running_mean=0.98688 | time=4.86s
          fold 4/5 | acc=0.98781 | running_mean=0.98711 | time=4.94s
          fold 5/5 | acc=0.98656 | running_mean=0.98700 | time=3.87s
          fold 1/5 | acc=0.98458 | running_mean=0.98458 | time=1.67s
          fold 2/5 | acc=0.98604 | running_mean=0.98531 | time=1.67s
          fold 3/5 | acc=0.98521 | running_mean=0.98528 | time=2.50s
          fold 4/5 | acc=0.98615 | running_mean=0.98549 | time=1.35s
          fold 5/5 | acc=0.98698 | running_mean=0.98579 | time=1.34s
          fold 1/5 | acc=0.98781 | running_mean=0.98781 | time=3.46s
          fold 2/5 | acc=0.98802 | running_mean=0.98792 | time=3.32s
          fold 3/5 | acc=0.98844 | running_mean=0.98809 | time=3.78s
          fold 4/5 | acc=0.99021 | running_mean=0.98862 | time=3.36s
          fold 5/5 | acc=0.98781 | running_mean=0.98846 | time=3.37s
          fold 1/5 | acc=0.97510 | running_mean=0.97510 | time=2.48s
          fold 2/5 | acc=0.97688 | running_mean=0.97599 | time=2.20s
          fold 3/5 | acc=0.97719 | running_mean=0.97639 | time=2.72s
          fold 4/5 | acc=0.97927 | running_mean=0.97711 | time=2.62s
          fold 5/5 | acc=0.97521 | running_mean=0.97673 | time=2.70s
          fold 1/5 | acc=0.98844 | running_mean=0.98844 | time=2.30s
          fold 2/5 | acc=0.98813 | running_mean=0.98828 | time=2.51s
          fold 3/5 | acc=0.98885 | running_mean=0.98847 | time=2.43s
          fold 4/5 | acc=0.98885 | running_mean=0.98857 | time=2.28s
          fold 5/5 | acc=0.98938 | running_mean=0.98873 | time=2.88s
          fold 1/5 | acc=0.98531 | running_mean=0.98531 | time=2.09s
          fold 2/5 | acc=0.98667 | running_mean=0.98599 | time=2.39s
          fold 3/5 | acc=0.98510 | running_mean=0.98569 | time=1.79s
          fold 4/5 | acc=0.98448 | running_mean=0.98539 | time=2.42s
          fold 5/5 | acc=0.98781 | running_mean=0.98588 | time=1.92s
          fold 1/5 | acc=0.99156 | running_mean=0.99156 | time=2.40s
          fold 2/5 | acc=0.99135 | running_mean=0.99146 | time=3.01s
          fold 3/5 | acc=0.99344 | running_mean=0.99212 | time=2.53s
          fold 4/5 | acc=0.99208 | running_mean=0.99211 | time=3.01s
          fold 5/5 | acc=0.99323 | running_mean=0.99233 | time=2.43s
          fold 1/5 | acc=0.98500 | running_mean=0.98500 | time=1.91s
          fold 2/5 | acc=0.98687 | running_mean=0.98594 | time=1.58s
          fold 3/5 | acc=0.98531 | running_mean=0.98573 | time=2.52s
          fold 4/5 | acc=0.98583 | running_mean=0.98576 | time=1.46s
          fold 5/5 | acc=0.98719 | running_mean=0.98604 | time=1.47s
          fold 1/5 | acc=0.98927 | running_mean=0.98927 | time=3.19s
          fold 2/5 | acc=0.98979 | running_mean=0.98953 | time=2.35s
          fold 3/5 | acc=0.99031 | running_mean=0.98979 | time=2.49s
          fold 4/5 | acc=0.99187 | running_mean=0.99031 | time=2.31s
          fold 5/5 | acc=0.99052 | running_mean=0.99035 | time=2.67s
          fold 1/5 | acc=0.98219 | running_mean=0.98219 | time=2.25s
          fold 2/5 | acc=0.98375 | running_mean=0.98297 | time=2.38s
          fold 3/5 | acc=0.98385 | running_mean=0.98326 | time=3.31s
          fold 4/5 | acc=0.98458 | running_mean=0.98359 | time=3.56s
          fold 5/5 | acc=0.98406 | running_mean=0.98369 | time=2.79s
          fold 1/5 | acc=0.99198 | running_mean=0.99198 | time=2.33s
          fold 2/5 | acc=0.98979 | running_mean=0.99089 | time=3.11s
          fold 3/5 | acc=0.98979 | running_mean=0.99052 | time=2.35s
          fold 4/5 | acc=0.99219 | running_mean=0.99094 | time=1.99s
          fold 5/5 | acc=0.99292 | running_mean=0.99133 | time=2.08s
          fold 1/5 | acc=0.98823 | running_mean=0.98823 | time=1.76s
          fold 2/5 | acc=0.98896 | running_mean=0.98859 | time=1.36s
          fold 3/5 | acc=0.98969 | running_mean=0.98896 | time=1.77s
          fold 4/5 | acc=0.99000 | running_mean=0.98922 | time=1.90s
          fold 5/5 | acc=0.99010 | running_mean=0.98940 | time=1.71s
          fold 1/5 | acc=0.97708 | running_mean=0.97708 | time=1.58s
          fold 2/5 | acc=0.98073 | running_mean=0.97891 | time=1.93s
          fold 3/5 | acc=0.98125 | running_mean=0.97969 | time=1.82s
          fold 4/5 | acc=0.98073 | running_mean=0.97995 | time=1.75s
          fold 5/5 | acc=0.98271 | running_mean=0.98050 | time=2.38s
          fold 1/5 | acc=0.99052 | running_mean=0.99052 | time=2.15s
          fold 2/5 | acc=0.99292 | running_mean=0.99172 | time=2.15s
          fold 3/5 | acc=0.98938 | running_mean=0.99094 | time=1.87s
          fold 4/5 | acc=0.99208 | running_mean=0.99122 | time=1.72s
          fold 5/5 | acc=0.99260 | running_mean=0.99150 | time=2.44s
          fold 1/5 | acc=0.99198 | running_mean=0.99198 | time=2.03s
          fold 2/5 | acc=0.99167 | running_mean=0.99182 | time=1.66s
          fold 3/5 | acc=0.99313 | running_mean=0.99226 | time=2.27s
          fold 4/5 | acc=0.99375 | running_mean=0.99263 | time=1.69s
          fold 5/5 | acc=0.99229 | running_mean=0.99256 | time=1.92s
          fold 1/5 | acc=0.99281 | running_mean=0.99281 | time=2.59s
          fold 2/5 | acc=0.99365 | running_mean=0.99323 | time=2.64s
          fold 3/5 | acc=0.99313 | running_mean=0.99319 | time=2.55s
          fold 4/5 | acc=0.99344 | running_mean=0.99326 | time=2.55s
          fold 5/5 | acc=0.99479 | running_mean=0.99356 | time=2.60s
          fold 1/5 | acc=0.99250 | running_mean=0.99250 | time=2.11s
          fold 2/5 | acc=0.99271 | running_mean=0.99260 | time=2.41s
          fold 3/5 | acc=0.99250 | running_mean=0.99257 | time=2.20s
          fold 4/5 | acc=0.99156 | running_mean=0.99232 | time=2.61s
          fold 5/5 | acc=0.99323 | running_mean=0.99250 | time=2.91s
          fold 1/5 | acc=0.99146 | running_mean=0.99146 | time=2.29s
          fold 2/5 | acc=0.99021 | running_mean=0.99083 | time=1.95s
          fold 3/5 | acc=0.99187 | running_mean=0.99118 | time=2.02s
          fold 4/5 | acc=0.99281 | running_mean=0.99159 | time=2.53s
          fold 5/5 | acc=0.99302 | running_mean=0.99187 | time=1.94s
          fold 1/5 | acc=0.97917 | running_mean=0.97917 | time=1.07s
          fold 2/5 | acc=0.98073 | running_mean=0.97995 | time=1.38s
          fold 3/5 | acc=0.97948 | running_mean=0.97979 | time=1.14s
          fold 4/5 | acc=0.98146 | running_mean=0.98021 | time=1.20s
          fold 5/5 | acc=0.98052 | running_mean=0.98027 | time=1.10s
          fold 1/5 | acc=0.98125 | running_mean=0.98125 | time=2.06s
          fold 2/5 | acc=0.98323 | running_mean=0.98224 | time=1.75s
          fold 3/5 | acc=0.98344 | running_mean=0.98264 | time=1.76s
          fold 4/5 | acc=0.98333 | running_mean=0.98281 | time=1.92s
          fold 5/5 | acc=0.98323 | running_mean=0.98290 | time=1.57s
          fold 1/5 | acc=0.97115 | running_mean=0.97115 | time=1.90s
          fold 2/5 | acc=0.97552 | running_mean=0.97333 | time=1.84s
          fold 3/5 | acc=0.97354 | running_mean=0.97340 | time=1.42s
          fold 4/5 | acc=0.97260 | running_mean=0.97320 | time=1.27s
          fold 5/5 | acc=0.97656 | running_mean=0.97387 | time=1.38s
          fold 1/5 | acc=0.98531 | running_mean=0.98531 | time=2.02s
          fold 2/5 | acc=0.98458 | running_mean=0.98495 | time=2.00s
          fold 3/5 | acc=0.98573 | running_mean=0.98521 | time=2.06s
          fold 4/5 | acc=0.98740 | running_mean=0.98576 | time=1.79s
          fold 5/5 | acc=0.98750 | running_mean=0.98610 | time=1.85s
          fold 1/5 | acc=0.98156 | running_mean=0.98156 | time=1.73s
          fold 2/5 | acc=0.98125 | running_mean=0.98141 | time=1.34s
          fold 3/5 | acc=0.98198 | running_mean=0.98160 | time=1.17s
          fold 4/5 | acc=0.98365 | running_mean=0.98211 | time=1.24s
          fold 5/5 | acc=0.98438 | running_mean=0.98256 | time=1.42s
          fold 1/5 | acc=0.97625 | running_mean=0.97625 | time=1.61s
          fold 2/5 | acc=0.97365 | running_mean=0.97495 | time=1.67s
          fold 3/5 | acc=0.97719 | running_mean=0.97569 | time=2.22s
          fold 4/5 | acc=0.97990 | running_mean=0.97674 | time=1.65s
          fold 5/5 | acc=0.97937 | running_mean=0.97727 | time=1.79s
          fold 1/5 | acc=0.99177 | running_mean=0.99177 | time=2.48s
          fold 2/5 | acc=0.99302 | running_mean=0.99240 | time=1.96s
          fold 3/5 | acc=0.99385 | running_mean=0.99288 | time=1.82s
          fold 4/5 | acc=0.99240 | running_mean=0.99276 | time=2.27s
          fold 5/5 | acc=0.99219 | running_mean=0.99265 | time=2.04s
          fold 1/5 | acc=0.99021 | running_mean=0.99021 | time=2.39s
          fold 2/5 | acc=0.99000 | running_mean=0.99010 | time=2.28s
          fold 3/5 | acc=0.98917 | running_mean=0.98979 | time=2.41s
          fold 4/5 | acc=0.99104 | running_mean=0.99010 | time=2.58s
          fold 5/5 | acc=0.99073 | running_mean=0.99023 | time=2.25s
          fold 1/5 | acc=0.93677 | running_mean=0.93677 | time=2.23s
          fold 2/5 | acc=0.94198 | running_mean=0.93938 | time=1.79s
          fold 3/5 | acc=0.94396 | running_mean=0.94090 | time=2.54s
          fold 4/5 | acc=0.93719 | running_mean=0.93997 | time=3.26s
          fold 5/5 | acc=0.93719 | running_mean=0.93942 | time=3.48s
          fold 1/5 | acc=0.98667 | running_mean=0.98667 | time=1.60s
          fold 2/5 | acc=0.98562 | running_mean=0.98615 | time=1.58s
          fold 3/5 | acc=0.98615 | running_mean=0.98615 | time=2.04s
          fold 4/5 | acc=0.98646 | running_mean=0.98622 | time=1.62s
          fold 5/5 | acc=0.98844 | running_mean=0.98667 | time=2.18s
          fold 1/5 | acc=0.98667 | running_mean=0.98667 | time=2.19s
          fold 2/5 | acc=0.98781 | running_mean=0.98724 | time=1.91s
          fold 3/5 | acc=0.98906 | running_mean=0.98785 | time=3.12s
          fold 4/5 | acc=0.98896 | running_mean=0.98813 | time=2.85s
          fold 5/5 | acc=0.98781 | running_mean=0.98806 | time=2.92s
          fold 1/5 | acc=0.97688 | running_mean=0.97688 | time=1.83s
          fold 2/5 | acc=0.97719 | running_mean=0.97703 | time=2.00s
          fold 3/5 | acc=0.97937 | running_mean=0.97781 | time=1.60s
          fold 4/5 | acc=0.97854 | running_mean=0.97799 | time=2.11s
          fold 5/5 | acc=0.97760 | running_mean=0.97792 | time=3.74s
          fold 1/5 | acc=0.98677 | running_mean=0.98677 | time=2.75s
          fold 2/5 | acc=0.98823 | running_mean=0.98750 | time=2.79s
          fold 3/5 | acc=0.98667 | running_mean=0.98722 | time=1.84s
          fold 4/5 | acc=0.98885 | running_mean=0.98763 | time=1.91s
          fold 5/5 | acc=0.98844 | running_mean=0.98779 | time=1.54s
          fold 1/5 | acc=0.99021 | running_mean=0.99021 | time=2.42s
          fold 2/5 | acc=0.99219 | running_mean=0.99120 | time=2.59s
          fold 3/5 | acc=0.99031 | running_mean=0.99090 | time=2.41s
          fold 4/5 | acc=0.99052 | running_mean=0.99081 | time=3.83s
          fold 5/5 | acc=0.99260 | running_mean=0.99117 | time=3.07s
          fold 1/5 | acc=0.98115 | running_mean=0.98115 | time=2.48s
          fold 2/5 | acc=0.98260 | running_mean=0.98188 | time=3.55s
          fold 3/5 | acc=0.98021 | running_mean=0.98132 | time=2.70s
          fold 4/5 | acc=0.98333 | running_mean=0.98182 | time=4.59s
          fold 5/5 | acc=0.98146 | running_mean=0.98175 | time=2.55s
  [TPE XGB] Time:  662.38s | Memory Δ:  -111.7MB | Peak:    85.7MB
  [TPE Eval XGB] Time:  139.34s | Memory Δ:   -23.4MB | Peak:   198.5MB
       Memory cleanup -> gc_collected=64, available=4.77 GB, used=69.7%, rss=199.0 MB
       Exported TPE artifacts

{'status': 'completed',
 'best':   Model Optimal_Scaler  Best_CV_Mean  Best_Trial  n_estimators  learning_rate  max_depth  min_child_weight  subsample  colsample_bytree     gamma  reg_alpha  reg_lambda
 0   XGB         MinMax      0.993563          32           363       0.397021          5                 2   0.639592          0.850623  0.080977    0.00072    0.000004,
 'history':    Model  Trial   CV_Mean  Best_Score_So_Far  Trial_Runtime_Sec
 0    XGB      1  0.986563           0.986563          17.417580
 1    XGB      2  0.956667           0.986563          37.945979
 2    XGB      3  0.972938           0.986563          24.485854
 3    XGB      4  0.953333           0.986563           9.013771
 4    XGB      5  0.947521           0.986563          22.938708
 5    XGB      6  0.969604           0.986563          21.394929
 6    XGB      7  0.986583           0.986583          15.892393
 7    XGB      8  0.964375           0.986583          16.845733
 8    XGB      9  0.976021           0.986583           5.460080
 9    XGB     10  0.930979           0.986583           9.673441
 10   XGB     11  0.988667           0.988667          14.533880
 11   XGB     12  0.988458           0.988667          13.125624
 12   XGB     13  0.989667           0.989667          14.535232
 13   XGB     14  0.988312           0.989667          18.450193
 14   XGB     15  0.981521           0.989667          12.372115
 15   XGB     16  0.980646           0.989667          14.778986
 16   XGB     17  0.988687           0.989667          14.312833
 17   XGB     18  0.987000           0.989667          21.802610
 18   XGB     19  0.985792           0.989667           8.599629
 19   XGB     20  0.988458           0.989667          17.367615
 20   XGB     21  0.976729           0.989667          12.786980
 21   XGB     22  0.988729           0.989667          12.472501
 22   XGB     23  0.985875           0.989667          10.669658
 23   XGB     24  0.992333           0.992333          13.434985
 24   XGB     25  0.986042           0.992333           9.008970
 25   XGB     26  0.990354           0.992333          13.066019
 26   XGB     27  0.983688           0.992333          14.354656
 27   XGB     28  0.991333           0.992333          11.911957
 28   XGB     29  0.989396           0.992333           8.556758
 29   XGB     30  0.980500           0.992333           9.521737
 30   XGB     31  0.991500           0.992333          10.391933
 31   XGB     32  0.992563           0.992563           9.636260
 32   XGB     33  0.993563           0.993563          12.989738
 33   XGB     34  0.992500           0.993563          12.299752
 34   XGB     35  0.991875           0.993563          10.789420
 35   XGB     36  0.980271           0.993563           5.944286
 36   XGB     37  0.982896           0.993563           9.129412
 37   XGB     38  0.973875           0.993563           7.877027
 38   XGB     39  0.986104           0.993563           9.767574
 39   XGB     40  0.982563           0.993563           6.962860
 40   XGB     41  0.977271           0.993563           8.999876
 41   XGB     42  0.992646           0.993563          10.651938
 42   XGB     43  0.990229           0.993563          11.988418
 43   XGB     44  0.939417           0.993563          13.367517
 44   XGB     45  0.986667           0.993563           9.099743
 45   XGB     46  0.988063           0.993563          13.055702
 46   XGB     47  0.977917           0.993563          11.342053
 47   XGB     48  0.987792           0.993563          10.918460
 48   XGB     49  0.991167           0.993563          14.459024
 49   XGB     50  0.981750           0.993563          15.932323,
 'summary':   Method Model Optimal_Scaler      Split  Accuracy  Precision    Recall        F1     Kappa       MCC       AUC   LogLoss  Accuracy_CI_Lower  Accuracy_CI_Upper  Precision_CI_Lower  Precision_CI_Upper  Recall_CI_Lower  Recall_CI_Upper  F1_CI_Lower  F1_CI_Upper  AUC_CI_Lower  AUC_CI_Upper  LogLoss_CI_Lower  LogLoss_CI_Upper  Kappa_CI_Lower  Kappa_CI_Upper  MCC_CI_Lower  MCC_CI_Upper
 0    TPE   XGB         MinMax  Train_OOF  0.993563   0.994325  0.995592  0.994958  0.986057  0.986058  0.999706  0.021769           0.992833           0.994229            0.993435            0.995116         0.994842         0.996290     0.994382     0.995479      0.999633      0.999767          0.020396          0.023295        0.984441        0.987532      0.984444      0.987532
 1    TPE   XGB         MinMax       Test  0.995417   0.995567  0.997257  0.996411  0.990071  0.990074  0.999882  0.015672           0.994167           0.996583            0.993958            0.996979         0.996096         0.998422     0.995400     0.997319      0.999813      0.999935          0.013798          0.017846        0.987340        0.992601      0.987358      0.992606,
 'timing':   Model  TPE_Search_Sec  TPE_Evaluation_Sec  TPE_Total_Sec  Best_CV_Mean
 0   XGB      662.375989          139.344475     802.204165      0.993563}

In [44]:
run_tpe_model("CB")

CB         | Scaler: MinMax     | Available RAM: 4.74 GB | Kernel RSS: 219.8 MB
       Memory cleanup -> gc_collected=119, available=4.73 GB, used=69.9%, rss=219.8 MB
       Running 50 trials with n_jobs_cv=1, n_jobs_opt=8
          fold 1/5 | acc=0.98260 | running_mean=0.98260 | time=5.76s
          fold 2/5 | acc=0.98479 | running_mean=0.98370 | time=5.92s
          fold 3/5 | acc=0.98375 | running_mean=0.98372 | time=4.64s
          fold 4/5 | acc=0.98500 | running_mean=0.98404 | time=4.94s
          fold 5/5 | acc=0.98646 | running_mean=0.98452 | time=4.63s
          fold 1/5 | acc=0.96573 | running_mean=0.96573 | time=0.72s
          fold 2/5 | acc=0.97198 | running_mean=0.96885 | time=0.66s
          fold 3/5 | acc=0.97167 | running_mean=0.96979 | time=0.78s
          fold 4/5 | acc=0.97073 | running_mean=0.97003 | time=0.76s
          fold 5/5 | acc=0.96958 | running_mean=0.96994 | time=0.74s
          fold 1/5 | acc=0.92635 | running_mean=0.92635 | time=5.79s
          fold 2/5 | acc=0.93167 | running_mean=0.92901 | time=5.93s
          fold 3/5 | acc=0.93219 | running_mean=0.93007 | time=5.51s
          fold 4/5 | acc=0.92927 | running_mean=0.92987 | time=5.89s
          fold 5/5 | acc=0.92854 | running_mean=0.92960 | time=5.59s
          fold 1/5 | acc=0.95219 | running_mean=0.95219 | time=4.86s
          fold 2/5 | acc=0.95552 | running_mean=0.95385 | time=5.04s
          fold 3/5 | acc=0.95510 | running_mean=0.95427 | time=5.50s
          fold 4/5 | acc=0.95208 | running_mean=0.95372 | time=5.60s
          fold 5/5 | acc=0.95406 | running_mean=0.95379 | time=4.87s
          fold 1/5 | acc=0.97719 | running_mean=0.97719 | time=3.40s
          fold 2/5 | acc=0.97437 | running_mean=0.97578 | time=3.36s
          fold 3/5 | acc=0.97604 | running_mean=0.97587 | time=3.56s
          fold 4/5 | acc=0.97708 | running_mean=0.97617 | time=3.84s
          fold 5/5 | acc=0.97750 | running_mean=0.97644 | time=3.28s
          fold 1/5 | acc=0.89281 | running_mean=0.89281 | time=4.17s
          fold 2/5 | acc=0.89812 | running_mean=0.89547 | time=4.36s
          fold 3/5 | acc=0.89781 | running_mean=0.89625 | time=4.26s
          fold 4/5 | acc=0.89573 | running_mean=0.89612 | time=4.18s
          fold 5/5 | acc=0.89458 | running_mean=0.89581 | time=4.22s
          fold 1/5 | acc=0.90281 | running_mean=0.90281 | time=2.35s
          fold 2/5 | acc=0.91010 | running_mean=0.90646 | time=2.22s
          fold 3/5 | acc=0.91042 | running_mean=0.90778 | time=2.07s
          fold 4/5 | acc=0.90812 | running_mean=0.90786 | time=2.31s
          fold 5/5 | acc=0.90094 | running_mean=0.90648 | time=2.25s
          fold 1/5 | acc=0.95719 | running_mean=0.95719 | time=0.49s
          fold 2/5 | acc=0.96031 | running_mean=0.95875 | time=0.76s
          fold 3/5 | acc=0.96010 | running_mean=0.95920 | time=0.47s
          fold 4/5 | acc=0.95979 | running_mean=0.95935 | time=0.57s
          fold 5/5 | acc=0.95583 | running_mean=0.95865 | time=0.45s
          fold 1/5 | acc=0.96333 | running_mean=0.96333 | time=23.55s
          fold 2/5 | acc=0.96469 | running_mean=0.96401 | time=23.81s
          fold 3/5 | acc=0.96437 | running_mean=0.96413 | time=23.02s
          fold 4/5 | acc=0.96396 | running_mean=0.96409 | time=23.30s
          fold 5/5 | acc=0.96365 | running_mean=0.96400 | time=23.26s
          fold 1/5 | acc=0.97562 | running_mean=0.97562 | time=3.93s
          fold 2/5 | acc=0.97490 | running_mean=0.97526 | time=4.21s
          fold 3/5 | acc=0.97573 | running_mean=0.97542 | time=3.65s
          fold 4/5 | acc=0.97698 | running_mean=0.97581 | time=3.83s
          fold 5/5 | acc=0.97667 | running_mean=0.97598 | time=3.75s
          fold 1/5 | acc=0.98771 | running_mean=0.98771 | time=29.55s
          fold 2/5 | acc=0.98760 | running_mean=0.98766 | time=29.82s
          fold 3/5 | acc=0.98729 | running_mean=0.98753 | time=29.97s
          fold 4/5 | acc=0.98760 | running_mean=0.98755 | time=29.89s
          fold 5/5 | acc=0.98635 | running_mean=0.98731 | time=40.21s
          fold 1/5 | acc=0.98479 | running_mean=0.98479 | time=34.15s
          fold 2/5 | acc=0.98396 | running_mean=0.98438 | time=32.32s
          fold 3/5 | acc=0.98562 | running_mean=0.98479 | time=33.95s
          fold 4/5 | acc=0.98677 | running_mean=0.98529 | time=31.56s
          fold 5/5 | acc=0.98604 | running_mean=0.98544 | time=31.74s
          fold 1/5 | acc=0.98667 | running_mean=0.98667 | time=37.05s
          fold 2/5 | acc=0.98469 | running_mean=0.98568 | time=31.96s
          fold 3/5 | acc=0.98792 | running_mean=0.98642 | time=31.09s
          fold 4/5 | acc=0.98750 | running_mean=0.98669 | time=32.06s
          fold 5/5 | acc=0.98729 | running_mean=0.98681 | time=28.84s
          fold 1/5 | acc=0.98833 | running_mean=0.98833 | time=15.64s
          fold 2/5 | acc=0.98417 | running_mean=0.98625 | time=15.85s
          fold 3/5 | acc=0.98896 | running_mean=0.98715 | time=15.26s
          fold 4/5 | acc=0.98802 | running_mean=0.98737 | time=15.24s
          fold 5/5 | acc=0.98635 | running_mean=0.98717 | time=15.62s
          fold 1/5 | acc=0.98167 | running_mean=0.98167 | time=15.45s
          fold 2/5 | acc=0.98156 | running_mean=0.98161 | time=15.20s
          fold 3/5 | acc=0.98458 | running_mean=0.98260 | time=15.56s
          fold 4/5 | acc=0.98552 | running_mean=0.98333 | time=15.41s
          fold 5/5 | acc=0.98281 | running_mean=0.98323 | time=15.22s
          fold 1/5 | acc=0.98583 | running_mean=0.98583 | time=14.79s
          fold 2/5 | acc=0.98583 | running_mean=0.98583 | time=14.86s
          fold 3/5 | acc=0.98833 | running_mean=0.98667 | time=14.40s
          fold 4/5 | acc=0.98677 | running_mean=0.98669 | time=15.31s
          fold 5/5 | acc=0.98771 | running_mean=0.98690 | time=14.73s
          fold 1/5 | acc=0.98844 | running_mean=0.98844 | time=14.41s
          fold 2/5 | acc=0.98792 | running_mean=0.98818 | time=14.37s
          fold 3/5 | acc=0.98885 | running_mean=0.98840 | time=13.66s
          fold 4/5 | acc=0.99073 | running_mean=0.98898 | time=13.97s
          fold 5/5 | acc=0.99083 | running_mean=0.98935 | time=14.31s
          fold 1/5 | acc=0.99094 | running_mean=0.99094 | time=8.14s
          fold 2/5 | acc=0.98990 | running_mean=0.99042 | time=12.51s
          fold 3/5 | acc=0.99260 | running_mean=0.99115 | time=8.98s
          fold 4/5 | acc=0.99240 | running_mean=0.99146 | time=8.13s
          fold 5/5 | acc=0.99135 | running_mean=0.99144 | time=7.95s
          fold 1/5 | acc=0.98896 | running_mean=0.98896 | time=6.08s
          fold 2/5 | acc=0.98729 | running_mean=0.98813 | time=6.04s
          fold 3/5 | acc=0.98917 | running_mean=0.98847 | time=7.38s
          fold 4/5 | acc=0.99198 | running_mean=0.98935 | time=6.26s
          fold 5/5 | acc=0.98708 | running_mean=0.98890 | time=5.92s
          fold 1/5 | acc=0.98906 | running_mean=0.98906 | time=6.33s
          fold 2/5 | acc=0.98583 | running_mean=0.98745 | time=6.61s
          fold 3/5 | acc=0.98906 | running_mean=0.98799 | time=6.21s
          fold 4/5 | acc=0.98823 | running_mean=0.98805 | time=6.30s
          fold 5/5 | acc=0.98844 | running_mean=0.98812 | time=6.22s
          fold 1/5 | acc=0.96427 | running_mean=0.96427 | time=6.77s
          fold 2/5 | acc=0.96583 | running_mean=0.96505 | time=6.94s
          fold 3/5 | acc=0.96625 | running_mean=0.96545 | time=7.05s
          fold 4/5 | acc=0.96677 | running_mean=0.96578 | time=6.85s
          fold 5/5 | acc=0.96479 | running_mean=0.96558 | time=6.85s
          fold 1/5 | acc=0.98906 | running_mean=0.98906 | time=6.07s
          fold 2/5 | acc=0.98813 | running_mean=0.98859 | time=6.17s
          fold 3/5 | acc=0.99031 | running_mean=0.98917 | time=6.27s
          fold 4/5 | acc=0.99083 | running_mean=0.98958 | time=6.39s
          fold 5/5 | acc=0.99156 | running_mean=0.98998 | time=6.16s
          fold 1/5 | acc=0.99448 | running_mean=0.99448 | time=7.60s
          fold 2/5 | acc=0.99250 | running_mean=0.99349 | time=8.18s
          fold 3/5 | acc=0.99333 | running_mean=0.99344 | time=7.76s
          fold 4/5 | acc=0.99521 | running_mean=0.99388 | time=7.74s
          fold 5/5 | acc=0.99333 | running_mean=0.99377 | time=7.66s
          fold 1/5 | acc=0.99052 | running_mean=0.99052 | time=6.19s
          fold 2/5 | acc=0.98823 | running_mean=0.98938 | time=6.02s
          fold 3/5 | acc=0.99073 | running_mean=0.98983 | time=6.42s
          fold 4/5 | acc=0.99260 | running_mean=0.99052 | time=6.66s
          fold 5/5 | acc=0.99042 | running_mean=0.99050 | time=5.96s
          fold 1/5 | acc=0.99021 | running_mean=0.99021 | time=6.49s
          fold 2/5 | acc=0.99094 | running_mean=0.99057 | time=6.17s
          fold 3/5 | acc=0.99177 | running_mean=0.99097 | time=6.18s
          fold 4/5 | acc=0.99219 | running_mean=0.99128 | time=6.72s
          fold 5/5 | acc=0.99167 | running_mean=0.99135 | time=6.40s
          fold 1/5 | acc=0.99333 | running_mean=0.99333 | time=6.57s
          fold 2/5 | acc=0.99250 | running_mean=0.99292 | time=6.39s
          fold 3/5 | acc=0.99219 | running_mean=0.99267 | time=6.43s
          fold 4/5 | acc=0.99333 | running_mean=0.99284 | time=6.40s
          fold 5/5 | acc=0.99333 | running_mean=0.99294 | time=6.87s
          fold 1/5 | acc=0.99313 | running_mean=0.99313 | time=6.38s
          fold 2/5 | acc=0.99042 | running_mean=0.99177 | time=6.50s
          fold 3/5 | acc=0.99198 | running_mean=0.99184 | time=6.80s
          fold 4/5 | acc=0.99375 | running_mean=0.99232 | time=6.32s
          fold 5/5 | acc=0.99260 | running_mean=0.99238 | time=6.49s
          fold 1/5 | acc=0.97333 | running_mean=0.97333 | time=1.14s
          fold 2/5 | acc=0.97573 | running_mean=0.97453 | time=0.89s
          fold 3/5 | acc=0.97677 | running_mean=0.97528 | time=0.99s
          fold 4/5 | acc=0.97906 | running_mean=0.97622 | time=1.03s
          fold 5/5 | acc=0.97708 | running_mean=0.97640 | time=0.91s
          fold 1/5 | acc=0.98813 | running_mean=0.98813 | time=6.43s
          fold 2/5 | acc=0.98687 | running_mean=0.98750 | time=5.99s
          fold 3/5 | acc=0.98750 | running_mean=0.98750 | time=6.81s
          fold 4/5 | acc=0.98844 | running_mean=0.98773 | time=6.15s
          fold 5/5 | acc=0.98729 | running_mean=0.98765 | time=5.83s
          fold 1/5 | acc=0.99302 | running_mean=0.99302 | time=5.99s
          fold 2/5 | acc=0.99156 | running_mean=0.99229 | time=5.95s
          fold 3/5 | acc=0.99427 | running_mean=0.99295 | time=5.98s
          fold 4/5 | acc=0.99427 | running_mean=0.99328 | time=5.97s
          fold 5/5 | acc=0.99073 | running_mean=0.99277 | time=5.77s
          fold 1/5 | acc=0.99167 | running_mean=0.99167 | time=7.02s
          fold 2/5 | acc=0.98979 | running_mean=0.99073 | time=6.96s
          fold 3/5 | acc=0.98927 | running_mean=0.99024 | time=6.64s
          fold 4/5 | acc=0.99052 | running_mean=0.99031 | time=6.52s
          fold 5/5 | acc=0.99115 | running_mean=0.99048 | time=6.55s
          fold 1/5 | acc=0.99240 | running_mean=0.99240 | time=5.88s
          fold 2/5 | acc=0.99010 | running_mean=0.99125 | time=6.39s
          fold 3/5 | acc=0.99302 | running_mean=0.99184 | time=6.01s
          fold 4/5 | acc=0.99385 | running_mean=0.99234 | time=6.11s
          fold 5/5 | acc=0.99219 | running_mean=0.99231 | time=6.32s
          fold 1/5 | acc=0.98583 | running_mean=0.98583 | time=5.51s
          fold 2/5 | acc=0.98521 | running_mean=0.98552 | time=5.32s
          fold 3/5 | acc=0.98552 | running_mean=0.98552 | time=6.57s
          fold 4/5 | acc=0.98708 | running_mean=0.98591 | time=5.53s
          fold 5/5 | acc=0.98719 | running_mean=0.98617 | time=5.51s
          fold 1/5 | acc=0.99375 | running_mean=0.99375 | time=8.01s
          fold 2/5 | acc=0.99302 | running_mean=0.99339 | time=8.02s
          fold 3/5 | acc=0.99365 | running_mean=0.99347 | time=8.28s
          fold 4/5 | acc=0.99469 | running_mean=0.99378 | time=7.77s
          fold 5/5 | acc=0.99479 | running_mean=0.99398 | time=8.05s
          fold 1/5 | acc=0.99292 | running_mean=0.99292 | time=8.33s
          fold 2/5 | acc=0.99083 | running_mean=0.99188 | time=7.91s
          fold 3/5 | acc=0.99365 | running_mean=0.99247 | time=8.08s
          fold 4/5 | acc=0.99313 | running_mean=0.99263 | time=7.96s
          fold 5/5 | acc=0.99313 | running_mean=0.99273 | time=8.16s
          fold 1/5 | acc=0.98021 | running_mean=0.98021 | time=1.22s
          fold 2/5 | acc=0.97927 | running_mean=0.97974 | time=1.44s
          fold 3/5 | acc=0.98115 | running_mean=0.98021 | time=1.27s
          fold 4/5 | acc=0.98302 | running_mean=0.98091 | time=1.33s
          fold 5/5 | acc=0.97792 | running_mean=0.98031 | time=1.28s
          fold 1/5 | acc=0.99250 | running_mean=0.99250 | time=8.22s
          fold 2/5 | acc=0.99198 | running_mean=0.99224 | time=7.83s
          fold 3/5 | acc=0.99260 | running_mean=0.99236 | time=8.17s
          fold 4/5 | acc=0.99396 | running_mean=0.99276 | time=8.06s
          fold 5/5 | acc=0.99313 | running_mean=0.99283 | time=8.45s
          fold 1/5 | acc=0.98938 | running_mean=0.98938 | time=4.96s
          fold 2/5 | acc=0.98760 | running_mean=0.98849 | time=4.55s
          fold 3/5 | acc=0.98958 | running_mean=0.98885 | time=4.52s
          fold 4/5 | acc=0.99021 | running_mean=0.98919 | time=4.44s
          fold 5/5 | acc=0.98813 | running_mean=0.98898 | time=4.29s
          fold 1/5 | acc=0.99313 | running_mean=0.99313 | time=6.96s
          fold 2/5 | acc=0.98958 | running_mean=0.99135 | time=6.81s
          fold 3/5 | acc=0.99104 | running_mean=0.99125 | time=7.13s
          fold 4/5 | acc=0.99260 | running_mean=0.99159 | time=6.69s
          fold 5/5 | acc=0.99135 | running_mean=0.99154 | time=6.79s
          fold 1/5 | acc=0.99083 | running_mean=0.99083 | time=8.50s
          fold 2/5 | acc=0.98875 | running_mean=0.98979 | time=8.78s
          fold 3/5 | acc=0.99104 | running_mean=0.99021 | time=8.49s
          fold 4/5 | acc=0.99021 | running_mean=0.99021 | time=8.59s
          fold 5/5 | acc=0.98917 | running_mean=0.99000 | time=8.92s
          fold 1/5 | acc=0.99250 | running_mean=0.99250 | time=6.06s
          fold 2/5 | acc=0.99042 | running_mean=0.99146 | time=5.85s
          fold 3/5 | acc=0.99292 | running_mean=0.99194 | time=6.06s
          fold 4/5 | acc=0.99313 | running_mean=0.99224 | time=6.09s
          fold 5/5 | acc=0.99094 | running_mean=0.99198 | time=6.01s
          fold 1/5 | acc=0.99052 | running_mean=0.99052 | time=8.42s
          fold 2/5 | acc=0.99052 | running_mean=0.99052 | time=8.23s
          fold 3/5 | acc=0.99146 | running_mean=0.99083 | time=8.16s
          fold 4/5 | acc=0.99281 | running_mean=0.99133 | time=8.84s
          fold 5/5 | acc=0.99177 | running_mean=0.99142 | time=8.50s
          fold 1/5 | acc=0.99365 | running_mean=0.99365 | time=6.45s
          fold 2/5 | acc=0.99083 | running_mean=0.99224 | time=6.63s
          fold 3/5 | acc=0.99250 | running_mean=0.99233 | time=6.60s
          fold 4/5 | acc=0.99469 | running_mean=0.99292 | time=7.61s
          fold 5/5 | acc=0.99333 | running_mean=0.99300 | time=7.35s
          fold 1/5 | acc=0.99333 | running_mean=0.99333 | time=11.57s
          fold 2/5 | acc=0.99115 | running_mean=0.99224 | time=8.89s
          fold 3/5 | acc=0.99302 | running_mean=0.99250 | time=6.43s
          fold 4/5 | acc=0.99448 | running_mean=0.99299 | time=6.69s
          fold 5/5 | acc=0.99292 | running_mean=0.99298 | time=5.95s
          fold 1/5 | acc=0.91208 | running_mean=0.91208 | time=7.38s
          fold 2/5 | acc=0.91792 | running_mean=0.91500 | time=7.03s
          fold 3/5 | acc=0.91833 | running_mean=0.91611 | time=9.76s
          fold 4/5 | acc=0.91500 | running_mean=0.91583 | time=11.37s
          fold 5/5 | acc=0.91458 | running_mean=0.91558 | time=7.69s
          fold 1/5 | acc=0.99323 | running_mean=0.99323 | time=5.81s
          fold 2/5 | acc=0.99021 | running_mean=0.99172 | time=6.58s
          fold 3/5 | acc=0.99260 | running_mean=0.99201 | time=5.88s
          fold 4/5 | acc=0.99229 | running_mean=0.99208 | time=6.02s
          fold 5/5 | acc=0.99385 | running_mean=0.99244 | time=6.07s
          fold 1/5 | acc=0.99302 | running_mean=0.99302 | time=6.95s
          fold 2/5 | acc=0.99146 | running_mean=0.99224 | time=6.95s
          fold 3/5 | acc=0.99385 | running_mean=0.99278 | time=7.33s
          fold 4/5 | acc=0.99542 | running_mean=0.99344 | time=6.79s
          fold 5/5 | acc=0.99479 | running_mean=0.99371 | time=6.84s
          fold 1/5 | acc=0.99448 | running_mean=0.99448 | time=6.75s
          fold 2/5 | acc=0.99271 | running_mean=0.99359 | time=6.78s
          fold 3/5 | acc=0.99365 | running_mean=0.99361 | time=6.88s
          fold 4/5 | acc=0.99542 | running_mean=0.99406 | time=6.66s
          fold 5/5 | acc=0.99385 | running_mean=0.99402 | time=6.71s
          fold 1/5 | acc=0.99333 | running_mean=0.99333 | time=6.74s
          fold 2/5 | acc=0.99260 | running_mean=0.99297 | time=7.53s
          fold 3/5 | acc=0.99260 | running_mean=0.99285 | time=6.99s
          fold 4/5 | acc=0.99385 | running_mean=0.99310 | time=6.77s
          fold 5/5 | acc=0.99302 | running_mean=0.99308 | time=6.99s
          fold 1/5 | acc=0.99344 | running_mean=0.99344 | time=7.53s
          fold 2/5 | acc=0.99052 | running_mean=0.99198 | time=7.54s
          fold 3/5 | acc=0.99187 | running_mean=0.99194 | time=7.31s
          fold 4/5 | acc=0.99313 | running_mean=0.99224 | time=7.35s
          fold 5/5 | acc=0.99271 | running_mean=0.99233 | time=7.83s
  [TPE CB] Time: 2148.68s | Memory Δ:  -156.5MB | Peak:    63.2MB
  [TPE Eval CB] Time:  142.13s | Memory Δ:    +2.0MB | Peak:   205.4MB
       Memory cleanup -> gc_collected=64, available=6.23 GB, used=60.4%, rss=205.9 MB
       Exported TPE artifacts

{'status': 'completed',
 'best':   Model Optimal_Scaler  Best_CV_Mean  Best_Trial  iterations  learning_rate  depth  l2_leaf_reg  border_count  bagging_temperature
 0    CB         MinMax      0.994021          47         441        0.39283      6     5.920924            51             6.306163,
 'history':    Model  Trial   CV_Mean  Best_Score_So_Far  Trial_Runtime_Sec
 0     CB      1  0.984521           0.984521          25.919743
 1     CB      2  0.969938           0.984521           3.683115
 2     CB      3  0.929604           0.984521          28.732418
 3     CB      4  0.953792           0.984521          25.887149
 4     CB      5  0.976438           0.984521          17.464252
 5     CB      6  0.895813           0.984521          21.211095
 6     CB      7  0.906479           0.984521          11.213913
 7     CB      8  0.958646           0.984521           2.761256
 8     CB      9  0.964000           0.984521         116.973034
 9     CB     10  0.975979           0.984521          19.391694
 10    CB     11  0.987313           0.987313         159.485394
 11    CB     12  0.985437           0.987313         163.789134
 12    CB     13  0.986813           0.987313         161.064491
 13    CB     14  0.987167           0.987313          77.656175
 14    CB     15  0.983229           0.987313          76.875420
 15    CB     16  0.986896           0.987313          74.146743
 16    CB     17  0.989354           0.989354          70.763175
 17    CB     18  0.991437           0.991437          45.768899
 18    CB     19  0.988896           0.991437          31.717746
 19    CB     20  0.988125           0.991437          31.715892
 20    CB     21  0.965583           0.991437          34.496638
 21    CB     22  0.989979           0.991437          31.106554
 22    CB     23  0.993771           0.993771          38.978849
 23    CB     24  0.990500           0.993771          31.307640
 24    CB     25  0.991354           0.993771          32.006870
 25    CB     26  0.992938           0.993771          32.696696
 26    CB     27  0.992375           0.993771          32.538312
 27    CB     28  0.976396           0.993771           5.013901
 28    CB     29  0.987646           0.993771          31.248980
 29    CB     30  0.992771           0.993771          29.689534
 30    CB     31  0.990479           0.993771          33.739535
 31    CB     32  0.992313           0.993771          30.753863
 32    CB     33  0.986167           0.993771          28.478484
 33    CB     34  0.993979           0.993979          40.176864
 34    CB     35  0.992729           0.993979          40.490871
 35    CB     36  0.980312           0.993979           6.603963
 36    CB     37  0.992833           0.993979          40.764139
 37    CB     38  0.988979           0.993979          22.799426
 38    CB     39  0.991542           0.993979          34.433097
 39    CB     40  0.990000           0.993979          43.321186
 40    CB     41  0.991979           0.993979          30.122347
 41    CB     42  0.991417           0.993979          42.197459
 42    CB     43  0.993000           0.993979          34.697220
 43    CB     44  0.992979           0.993979          39.628696
 44    CB     45  0.915583           0.993979          43.306130
 45    CB     46  0.992437           0.993979          30.428204
 46    CB     47  0.993708           0.993979          34.905468
 47    CB     48  0.994021           0.994021          33.819857
 48    CB     49  0.993083           0.994021          35.072668
 49    CB     50  0.992333           0.994021          37.605673,
 'summary':   Method Model Optimal_Scaler      Split  Accuracy  Precision    Recall        F1     Kappa       MCC       AUC   LogLoss  Accuracy_CI_Lower  Accuracy_CI_Upper  Precision_CI_Lower  Precision_CI_Upper  Recall_CI_Lower  Recall_CI_Upper  F1_CI_Lower  F1_CI_Upper  AUC_CI_Lower  AUC_CI_Upper  LogLoss_CI_Lower  LogLoss_CI_Upper  Kappa_CI_Lower  Kappa_CI_Upper  MCC_CI_Lower  MCC_CI_Upper
 0    TPE    CB         MinMax  Train_OOF  0.994021   0.994587  0.996049  0.995318  0.987048  0.987050  0.999717  0.027959           0.993292           0.994687            0.993741            0.995371         0.995340         0.996732     0.994733     0.995837      0.999647      0.999778          0.026788          0.029237        0.985490        0.988511      0.985492      0.988512
 1    TPE    CB         MinMax       Test  0.996167   0.996348  0.997649  0.996998  0.991697  0.991699  0.999906  0.021955           0.995000           0.997167            0.994903            0.997614         0.996479         0.998691     0.996070     0.997802      0.999846      0.999954          0.020283          0.023758        0.989191        0.993904      0.989198      0.993905,
 'timing':   Model  TPE_Search_Sec  TPE_Evaluation_Sec  TPE_Total_Sec  Best_CV_Mean
 0    CB     2148.680982          142.128956    2291.143637      0.994021}

In [45]:
run_tpe_model("SGD")

SGD        | Scaler: Power      | Available RAM: 6.17 GB | Kernel RSS: 219.8 MB
       Memory cleanup -> gc_collected=119, available=6.13 GB, used=61.0%, rss=219.8 MB
       Running 50 trials with n_jobs_cv=1, n_jobs_opt=8
          fold 1/5 | acc=0.84458 | running_mean=0.84458 | time=1.06s
          fold 2/5 | acc=0.88562 | running_mean=0.86510 | time=1.34s
          fold 3/5 | acc=0.87729 | running_mean=0.86917 | time=1.02s
          fold 4/5 | acc=0.88948 | running_mean=0.87424 | time=1.01s
          fold 5/5 | acc=0.86625 | running_mean=0.87265 | time=1.14s
          fold 1/5 | acc=0.85521 | running_mean=0.85521 | time=0.51s
          fold 2/5 | acc=0.86083 | running_mean=0.85802 | time=0.50s
          fold 3/5 | acc=0.85635 | running_mean=0.85747 | time=0.51s
          fold 4/5 | acc=0.85802 | running_mean=0.85760 | time=0.53s
          fold 5/5 | acc=0.85531 | running_mean=0.85715 | time=0.54s
          fold 1/5 | acc=0.88646 | running_mean=0.88646 | time=0.71s
          fold 2/5 | acc=0.87875 | running_mean=0.88260 | time=0.73s
          fold 3/5 | acc=0.88687 | running_mean=0.88403 | time=0.72s
          fold 4/5 | acc=0.88729 | running_mean=0.88484 | time=0.72s
          fold 5/5 | acc=0.89583 | running_mean=0.88704 | time=0.76s
          fold 1/5 | acc=0.86687 | running_mean=0.86687 | time=1.03s
          fold 2/5 | acc=0.87146 | running_mean=0.86917 | time=1.02s
          fold 3/5 | acc=0.86010 | running_mean=0.86615 | time=1.05s
          fold 4/5 | acc=0.89135 | running_mean=0.87245 | time=1.00s
          fold 5/5 | acc=0.88250 | running_mean=0.87446 | time=1.11s
          fold 1/5 | acc=0.84198 | running_mean=0.84198 | time=0.54s
          fold 2/5 | acc=0.82854 | running_mean=0.83526 | time=0.60s
          fold 3/5 | acc=0.82479 | running_mean=0.83177 | time=0.58s
          fold 4/5 | acc=0.83344 | running_mean=0.83219 | time=0.63s
          fold 5/5 | acc=0.83104 | running_mean=0.83196 | time=0.57s
          fold 1/5 | acc=0.89365 | running_mean=0.89365 | time=0.98s
          fold 2/5 | acc=0.88740 | running_mean=0.89052 | time=0.77s
          fold 3/5 | acc=0.88719 | running_mean=0.88941 | time=0.82s
          fold 4/5 | acc=0.88146 | running_mean=0.88742 | time=0.78s
          fold 5/5 | acc=0.88458 | running_mean=0.88685 | time=0.73s
          fold 1/5 | acc=0.88958 | running_mean=0.88958 | time=0.52s
          fold 2/5 | acc=0.89635 | running_mean=0.89297 | time=0.55s
          fold 3/5 | acc=0.88292 | running_mean=0.88962 | time=0.56s
          fold 4/5 | acc=0.89427 | running_mean=0.89078 | time=0.49s
          fold 5/5 | acc=0.89677 | running_mean=0.89198 | time=0.71s
          fold 1/5 | acc=0.89010 | running_mean=0.89010 | time=0.49s
          fold 2/5 | acc=0.89417 | running_mean=0.89214 | time=0.56s
          fold 3/5 | acc=0.89250 | running_mean=0.89226 | time=0.54s
          fold 4/5 | acc=0.89438 | running_mean=0.89279 | time=0.65s
          fold 5/5 | acc=0.89333 | running_mean=0.89290 | time=0.56s
          fold 1/5 | acc=0.88750 | running_mean=0.88750 | time=1.00s
          fold 2/5 | acc=0.89187 | running_mean=0.88969 | time=0.94s
          fold 3/5 | acc=0.88552 | running_mean=0.88830 | time=0.92s
          fold 4/5 | acc=0.88938 | running_mean=0.88857 | time=0.81s
          fold 5/5 | acc=0.89792 | running_mean=0.89044 | time=0.92s
          fold 1/5 | acc=0.88802 | running_mean=0.88802 | time=0.97s
          fold 2/5 | acc=0.88844 | running_mean=0.88823 | time=1.36s
          fold 3/5 | acc=0.89115 | running_mean=0.88920 | time=1.13s
          fold 4/5 | acc=0.88687 | running_mean=0.88862 | time=0.99s
          fold 5/5 | acc=0.89281 | running_mean=0.88946 | time=0.94s
          fold 1/5 | acc=0.89312 | running_mean=0.89312 | time=0.53s
          fold 2/5 | acc=0.89146 | running_mean=0.89229 | time=0.50s
          fold 3/5 | acc=0.88969 | running_mean=0.89142 | time=0.63s
          fold 4/5 | acc=0.89552 | running_mean=0.89245 | time=0.52s
          fold 5/5 | acc=0.89479 | running_mean=0.89292 | time=0.59s
          fold 1/5 | acc=0.88958 | running_mean=0.88958 | time=0.52s
          fold 2/5 | acc=0.89427 | running_mean=0.89193 | time=0.53s
          fold 3/5 | acc=0.89240 | running_mean=0.89208 | time=0.50s
          fold 4/5 | acc=0.89458 | running_mean=0.89271 | time=0.51s
          fold 5/5 | acc=0.89354 | running_mean=0.89288 | time=0.58s
          fold 1/5 | acc=0.88792 | running_mean=0.88792 | time=0.50s
          fold 2/5 | acc=0.89427 | running_mean=0.89109 | time=0.54s
          fold 3/5 | acc=0.88594 | running_mean=0.88937 | time=0.46s
          fold 4/5 | acc=0.88844 | running_mean=0.88914 | time=0.53s
          fold 5/5 | acc=0.89021 | running_mean=0.88935 | time=0.49s
          fold 1/5 | acc=0.88156 | running_mean=0.88156 | time=0.47s
          fold 2/5 | acc=0.88979 | running_mean=0.88568 | time=0.51s
          fold 3/5 | acc=0.88448 | running_mean=0.88528 | time=0.48s
          fold 4/5 | acc=0.88365 | running_mean=0.88487 | time=0.52s
          fold 5/5 | acc=0.88604 | running_mean=0.88510 | time=0.48s
          fold 1/5 | acc=0.89229 | running_mean=0.89229 | time=0.63s
          fold 2/5 | acc=0.89229 | running_mean=0.89229 | time=0.68s
          fold 3/5 | acc=0.88802 | running_mean=0.89087 | time=0.59s
          fold 4/5 | acc=0.88687 | running_mean=0.88987 | time=0.59s
          fold 5/5 | acc=0.89167 | running_mean=0.89023 | time=0.65s
          fold 1/5 | acc=0.89094 | running_mean=0.89094 | time=0.59s
          fold 2/5 | acc=0.89333 | running_mean=0.89214 | time=0.64s
          fold 3/5 | acc=0.88865 | running_mean=0.89097 | time=0.56s
          fold 4/5 | acc=0.88667 | running_mean=0.88990 | time=0.61s
          fold 5/5 | acc=0.89552 | running_mean=0.89102 | time=0.63s
          fold 1/5 | acc=0.87542 | running_mean=0.87542 | time=0.48s
          fold 2/5 | acc=0.87969 | running_mean=0.87755 | time=0.52s
          fold 3/5 | acc=0.87292 | running_mean=0.87601 | time=0.47s
          fold 4/5 | acc=0.87646 | running_mean=0.87612 | time=0.54s
          fold 5/5 | acc=0.87510 | running_mean=0.87592 | time=0.46s
          fold 1/5 | acc=0.89333 | running_mean=0.89333 | time=0.55s
          fold 2/5 | acc=0.89292 | running_mean=0.89312 | time=0.52s
          fold 3/5 | acc=0.88875 | running_mean=0.89167 | time=0.52s
          fold 4/5 | acc=0.89573 | running_mean=0.89268 | time=0.53s
          fold 5/5 | acc=0.89469 | running_mean=0.89308 | time=0.51s
          fold 1/5 | acc=0.88885 | running_mean=0.88885 | time=0.54s
          fold 2/5 | acc=0.89135 | running_mean=0.89010 | time=0.52s
          fold 3/5 | acc=0.88635 | running_mean=0.88885 | time=0.52s
          fold 4/5 | acc=0.88646 | running_mean=0.88826 | time=0.51s
          fold 5/5 | acc=0.89062 | running_mean=0.88873 | time=0.57s
          fold 1/5 | acc=0.85979 | running_mean=0.85979 | time=0.53s
          fold 2/5 | acc=0.86677 | running_mean=0.86328 | time=0.51s
          fold 3/5 | acc=0.86083 | running_mean=0.86247 | time=0.50s
          fold 4/5 | acc=0.86417 | running_mean=0.86289 | time=0.49s
          fold 5/5 | acc=0.86198 | running_mean=0.86271 | time=0.50s
          fold 1/5 | acc=0.89323 | running_mean=0.89323 | time=0.56s
          fold 2/5 | acc=0.89302 | running_mean=0.89312 | time=0.56s
          fold 3/5 | acc=0.88917 | running_mean=0.89181 | time=0.52s
          fold 4/5 | acc=0.89563 | running_mean=0.89276 | time=0.53s
          fold 5/5 | acc=0.89490 | running_mean=0.89319 | time=0.55s
          fold 1/5 | acc=0.89302 | running_mean=0.89302 | time=0.51s
          fold 2/5 | acc=0.89177 | running_mean=0.89240 | time=0.52s
          fold 3/5 | acc=0.88906 | running_mean=0.89128 | time=0.52s
          fold 4/5 | acc=0.89531 | running_mean=0.89229 | time=0.54s
          fold 5/5 | acc=0.89469 | running_mean=0.89277 | time=0.52s
          fold 1/5 | acc=0.88781 | running_mean=0.88781 | time=0.53s
          fold 2/5 | acc=0.89198 | running_mean=0.88990 | time=0.58s
          fold 3/5 | acc=0.88802 | running_mean=0.88927 | time=0.55s
          fold 4/5 | acc=0.89573 | running_mean=0.89089 | time=0.61s
          fold 5/5 | acc=0.89615 | running_mean=0.89194 | time=0.55s
          fold 1/5 | acc=0.88833 | running_mean=0.88833 | time=0.52s
          fold 2/5 | acc=0.89469 | running_mean=0.89151 | time=0.49s
          fold 3/5 | acc=0.88583 | running_mean=0.88962 | time=0.49s
          fold 4/5 | acc=0.88896 | running_mean=0.88945 | time=0.48s
          fold 5/5 | acc=0.88979 | running_mean=0.88952 | time=0.48s
          fold 1/5 | acc=0.88875 | running_mean=0.88875 | time=0.74s
          fold 2/5 | acc=0.88865 | running_mean=0.88870 | time=0.68s
          fold 3/5 | acc=0.88729 | running_mean=0.88823 | time=0.65s
          fold 4/5 | acc=0.89083 | running_mean=0.88888 | time=0.69s
          fold 5/5 | acc=0.88458 | running_mean=0.88802 | time=0.65s
          fold 1/5 | acc=0.88760 | running_mean=0.88760 | time=0.51s
          fold 2/5 | acc=0.89469 | running_mean=0.89115 | time=0.50s
          fold 3/5 | acc=0.88646 | running_mean=0.88958 | time=0.50s
          fold 4/5 | acc=0.88885 | running_mean=0.88940 | time=0.51s
          fold 5/5 | acc=0.88990 | running_mean=0.88950 | time=0.50s
          fold 1/5 | acc=0.88167 | running_mean=0.88167 | time=0.51s
          fold 2/5 | acc=0.89052 | running_mean=0.88609 | time=0.56s
          fold 3/5 | acc=0.88531 | running_mean=0.88583 | time=0.52s
          fold 4/5 | acc=0.88583 | running_mean=0.88583 | time=0.50s
          fold 5/5 | acc=0.88677 | running_mean=0.88602 | time=0.53s
          fold 1/5 | acc=0.87875 | running_mean=0.87875 | time=0.52s
          fold 2/5 | acc=0.88667 | running_mean=0.88271 | time=0.52s
          fold 3/5 | acc=0.88042 | running_mean=0.88194 | time=0.48s
          fold 4/5 | acc=0.88073 | running_mean=0.88164 | time=0.47s
          fold 5/5 | acc=0.88094 | running_mean=0.88150 | time=0.51s
          fold 1/5 | acc=0.88531 | running_mean=0.88531 | time=0.73s
          fold 2/5 | acc=0.88990 | running_mean=0.88760 | time=0.69s
          fold 3/5 | acc=0.88490 | running_mean=0.88670 | time=0.70s
          fold 4/5 | acc=0.88062 | running_mean=0.88518 | time=0.70s
          fold 5/5 | acc=0.89052 | running_mean=0.88625 | time=0.71s
          fold 1/5 | acc=0.89167 | running_mean=0.89167 | time=0.60s
          fold 2/5 | acc=0.89240 | running_mean=0.89203 | time=0.62s
          fold 3/5 | acc=0.89229 | running_mean=0.89212 | time=0.60s
          fold 4/5 | acc=0.89667 | running_mean=0.89326 | time=0.63s
          fold 5/5 | acc=0.89802 | running_mean=0.89421 | time=0.65s
          fold 1/5 | acc=0.85292 | running_mean=0.85292 | time=1.59s
          fold 2/5 | acc=0.88146 | running_mean=0.86719 | time=1.54s
          fold 3/5 | acc=0.88427 | running_mean=0.87288 | time=1.14s
          fold 4/5 | acc=0.85760 | running_mean=0.86906 | time=1.30s
          fold 5/5 | acc=0.84115 | running_mean=0.86348 | time=1.51s
          fold 1/5 | acc=0.89177 | running_mean=0.89177 | time=0.58s
          fold 2/5 | acc=0.89531 | running_mean=0.89354 | time=0.62s
          fold 3/5 | acc=0.88844 | running_mean=0.89184 | time=0.56s
          fold 4/5 | acc=0.89062 | running_mean=0.89154 | time=0.66s
          fold 5/5 | acc=0.89990 | running_mean=0.89321 | time=0.59s
          fold 1/5 | acc=0.89094 | running_mean=0.89094 | time=0.69s
          fold 2/5 | acc=0.88708 | running_mean=0.88901 | time=0.64s
          fold 3/5 | acc=0.88969 | running_mean=0.88924 | time=0.66s
          fold 4/5 | acc=0.89302 | running_mean=0.89018 | time=0.76s
          fold 5/5 | acc=0.89729 | running_mean=0.89160 | time=0.74s
          fold 1/5 | acc=0.89448 | running_mean=0.89448 | time=0.71s
          fold 2/5 | acc=0.89219 | running_mean=0.89333 | time=0.66s
          fold 3/5 | acc=0.89271 | running_mean=0.89312 | time=0.65s
          fold 4/5 | acc=0.89687 | running_mean=0.89406 | time=0.59s
          fold 5/5 | acc=0.89708 | running_mean=0.89467 | time=0.62s
          fold 1/5 | acc=0.89146 | running_mean=0.89146 | time=0.61s
          fold 2/5 | acc=0.89240 | running_mean=0.89193 | time=0.66s
          fold 3/5 | acc=0.89135 | running_mean=0.89174 | time=0.58s
          fold 4/5 | acc=0.89406 | running_mean=0.89232 | time=0.69s
          fold 5/5 | acc=0.89552 | running_mean=0.89296 | time=0.64s
          fold 1/5 | acc=0.87625 | running_mean=0.87625 | time=0.51s
          fold 2/5 | acc=0.87740 | running_mean=0.87682 | time=0.52s
          fold 3/5 | acc=0.87292 | running_mean=0.87552 | time=0.50s
          fold 4/5 | acc=0.87760 | running_mean=0.87604 | time=0.55s
          fold 5/5 | acc=0.87531 | running_mean=0.87590 | time=0.47s
          fold 1/5 | acc=0.88562 | running_mean=0.88562 | time=0.53s
          fold 2/5 | acc=0.88740 | running_mean=0.88651 | time=0.50s
          fold 3/5 | acc=0.87792 | running_mean=0.88365 | time=0.51s
          fold 4/5 | acc=0.88448 | running_mean=0.88385 | time=0.49s
          fold 5/5 | acc=0.87760 | running_mean=0.88260 | time=0.48s
          fold 1/5 | acc=0.88562 | running_mean=0.88562 | time=1.03s
          fold 2/5 | acc=0.89156 | running_mean=0.88859 | time=0.90s
          fold 3/5 | acc=0.88062 | running_mean=0.88594 | time=0.93s
          fold 4/5 | acc=0.88906 | running_mean=0.88672 | time=0.78s
          fold 5/5 | acc=0.89740 | running_mean=0.88885 | time=0.90s
          fold 1/5 | acc=0.89062 | running_mean=0.89062 | time=0.69s
          fold 2/5 | acc=0.89104 | running_mean=0.89083 | time=0.61s
          fold 3/5 | acc=0.89146 | running_mean=0.89104 | time=0.60s
          fold 4/5 | acc=0.89479 | running_mean=0.89198 | time=0.61s
          fold 5/5 | acc=0.89969 | running_mean=0.89352 | time=0.66s
          fold 1/5 | acc=0.88938 | running_mean=0.88938 | time=0.73s
          fold 2/5 | acc=0.88323 | running_mean=0.88630 | time=0.72s
          fold 3/5 | acc=0.88823 | running_mean=0.88694 | time=0.74s
          fold 4/5 | acc=0.88750 | running_mean=0.88708 | time=0.72s
          fold 5/5 | acc=0.89635 | running_mean=0.88894 | time=0.77s
          fold 1/5 | acc=0.89010 | running_mean=0.89010 | time=0.60s
          fold 2/5 | acc=0.89073 | running_mean=0.89042 | time=0.62s
          fold 3/5 | acc=0.89156 | running_mean=0.89080 | time=0.57s
          fold 4/5 | acc=0.89479 | running_mean=0.89180 | time=0.60s
          fold 5/5 | acc=0.89906 | running_mean=0.89325 | time=0.61s
          fold 1/5 | acc=0.88958 | running_mean=0.88958 | time=0.75s
          fold 2/5 | acc=0.88896 | running_mean=0.88927 | time=0.72s
          fold 3/5 | acc=0.89240 | running_mean=0.89031 | time=0.67s
          fold 4/5 | acc=0.88927 | running_mean=0.89005 | time=0.68s
          fold 5/5 | acc=0.89490 | running_mean=0.89102 | time=0.63s
          fold 1/5 | acc=0.89656 | running_mean=0.89656 | time=0.57s
          fold 2/5 | acc=0.89135 | running_mean=0.89396 | time=0.60s
          fold 3/5 | acc=0.89312 | running_mean=0.89368 | time=0.54s
          fold 4/5 | acc=0.89563 | running_mean=0.89417 | time=0.60s
          fold 5/5 | acc=0.89844 | running_mean=0.89502 | time=0.55s
          fold 1/5 | acc=0.88948 | running_mean=0.88948 | time=0.62s
          fold 2/5 | acc=0.89052 | running_mean=0.89000 | time=0.61s
          fold 3/5 | acc=0.88938 | running_mean=0.88979 | time=0.63s
          fold 4/5 | acc=0.89469 | running_mean=0.89102 | time=0.60s
          fold 5/5 | acc=0.89875 | running_mean=0.89256 | time=0.61s
          fold 1/5 | acc=0.88917 | running_mean=0.88917 | time=0.63s
          fold 2/5 | acc=0.89000 | running_mean=0.88958 | time=0.62s
          fold 3/5 | acc=0.88844 | running_mean=0.88920 | time=0.66s
          fold 4/5 | acc=0.89417 | running_mean=0.89044 | time=0.60s
          fold 5/5 | acc=0.89781 | running_mean=0.89192 | time=0.65s
          fold 1/5 | acc=0.89458 | running_mean=0.89458 | time=0.52s
          fold 2/5 | acc=0.89271 | running_mean=0.89365 | time=0.52s
          fold 3/5 | acc=0.89552 | running_mean=0.89427 | time=0.54s
          fold 4/5 | acc=0.89490 | running_mean=0.89443 | time=0.54s
          fold 5/5 | acc=0.90021 | running_mean=0.89558 | time=0.57s
          fold 1/5 | acc=0.89448 | running_mean=0.89448 | time=0.52s
          fold 2/5 | acc=0.89271 | running_mean=0.89359 | time=0.54s
          fold 3/5 | acc=0.89563 | running_mean=0.89427 | time=0.51s
          fold 4/5 | acc=0.89490 | running_mean=0.89443 | time=0.56s
          fold 5/5 | acc=0.90000 | running_mean=0.89554 | time=0.53s
          fold 1/5 | acc=0.89542 | running_mean=0.89542 | time=0.56s
          fold 2/5 | acc=0.89292 | running_mean=0.89417 | time=0.53s
          fold 3/5 | acc=0.89521 | running_mean=0.89451 | time=0.54s
          fold 4/5 | acc=0.89604 | running_mean=0.89490 | time=0.55s
          fold 5/5 | acc=0.90094 | running_mean=0.89610 | time=0.52s
          fold 1/5 | acc=0.88990 | running_mean=0.88990 | time=0.80s
          fold 2/5 | acc=0.89302 | running_mean=0.89146 | time=0.75s
          fold 3/5 | acc=0.88760 | running_mean=0.89017 | time=0.57s
          fold 4/5 | acc=0.88729 | running_mean=0.88945 | time=0.57s
          fold 5/5 | acc=0.89125 | running_mean=0.88981 | time=0.56s
          fold 1/5 | acc=0.89406 | running_mean=0.89406 | time=0.55s
          fold 2/5 | acc=0.89333 | running_mean=0.89370 | time=0.59s
          fold 3/5 | acc=0.89344 | running_mean=0.89361 | time=0.56s
          fold 4/5 | acc=0.89708 | running_mean=0.89448 | time=0.57s
          fold 5/5 | acc=0.89938 | running_mean=0.89546 | time=0.57s
  [TPE SGD] Time:  161.94s | Memory Δ:    +7.8MB | Peak:   227.6MB
  [TPE Eval SGD] Time:  103.45s | Memory Δ:   -12.5MB | Peak:   215.1MB
       Memory cleanup -> gc_collected=64, available=6.09 GB, used=61.3%, rss=215.1 MB
       Exported TPE artifacts

{'status': 'completed',
 'best':   Model Optimal_Scaler  Best_CV_Mean  Best_Trial      loss penalty     alpha  l1_ratio
 0   SGD          Power      0.896104          47  log_loss      l1  0.000208  0.335745,
 'history':    Model  Trial   CV_Mean  Best_Score_So_Far  Trial_Runtime_Sec
 0    SGD      1  0.872646           0.872646           5.584355
 1    SGD      2  0.857146           0.872646           2.607894
 2    SGD      3  0.887042           0.887042           3.667438
 3    SGD      4  0.874458           0.887042           5.235700
 4    SGD      5  0.831958           0.887042           2.946652
 5    SGD      6  0.886854           0.887042           4.105096
 6    SGD      7  0.891979           0.891979           2.842161
 7    SGD      8  0.892896           0.892896           2.821786
 8    SGD      9  0.890438           0.892896           4.611792
 9    SGD     10  0.889458           0.892896           5.399378
 10   SGD     11  0.892917           0.892917           2.800921
 11   SGD     12  0.892875           0.892917           2.663169
 12   SGD     13  0.889354           0.892917           2.544781
 13   SGD     14  0.885104           0.892917           2.484144
 14   SGD     15  0.890229           0.892917           3.166168
 15   SGD     16  0.891021           0.892917           3.054381
 16   SGD     17  0.875917           0.892917           2.495366
 17   SGD     18  0.893083           0.893083           2.653166
 18   SGD     19  0.888729           0.893083           2.677146
 19   SGD     20  0.862708           0.893083           2.541119
 20   SGD     21  0.893188           0.893188           2.741675
 21   SGD     22  0.892771           0.893188           2.633878
 22   SGD     23  0.891938           0.893188           2.828343
 23   SGD     24  0.889521           0.893188           2.478451
 24   SGD     25  0.888021           0.893188           3.436646
 25   SGD     26  0.889500           0.893188           2.538467
 26   SGD     27  0.886021           0.893188           2.628131
 27   SGD     28  0.881500           0.893188           2.522468
 28   SGD     29  0.886250           0.893188           3.562893
 29   SGD     30  0.894208           0.894208           3.111465
 30   SGD     31  0.863479           0.894208           7.096181
 31   SGD     32  0.893208           0.894208           3.042252
 32   SGD     33  0.891604           0.894208           3.512286
 33   SGD     34  0.894667           0.894667           3.253567
 34   SGD     35  0.892958           0.894667           3.198652
 35   SGD     36  0.875896           0.894667           2.571427
 36   SGD     37  0.882604           0.894667           2.530476
 37   SGD     38  0.888854           0.894667           4.561480
 38   SGD     39  0.893521           0.894667           3.188380
 39   SGD     40  0.888937           0.894667           3.689091
 40   SGD     41  0.893250           0.894667           3.023028
 41   SGD     42  0.891021           0.894667           3.474677
 42   SGD     43  0.895021           0.895021           2.888961
 43   SGD     44  0.892563           0.895021           3.084150
 44   SGD     45  0.891917           0.895021           3.175870
 45   SGD     46  0.895583           0.895583           2.719480
 46   SGD     47  0.895542           0.895583           2.678271
 47   SGD     48  0.896104           0.896104           2.707560
 48   SGD     49  0.889813           0.896104           3.283329
 49   SGD     50  0.895458           0.896104           2.853649,
 'summary':   Method Model Optimal_Scaler      Split  Accuracy  Precision    Recall        F1     Kappa       MCC       AUC   LogLoss  Accuracy_CI_Lower  Accuracy_CI_Upper  Precision_CI_Lower  Precision_CI_Upper  Recall_CI_Lower  Recall_CI_Upper  F1_CI_Lower  F1_CI_Upper  AUC_CI_Lower  AUC_CI_Upper  LogLoss_CI_Lower  LogLoss_CI_Upper  Kappa_CI_Lower  Kappa_CI_Upper  MCC_CI_Lower  MCC_CI_Upper
 0    TPE   SGD          Power  Train_OOF  0.896104   0.913220  0.925059  0.919101  0.773957  0.774083  0.965103  0.229262           0.893292           0.898937            0.910107            0.916592         0.921997         0.928150     0.916770     0.921437      0.963779      0.966489          0.224783          0.233451        0.768116        0.780116      0.768226      0.780295
 1    TPE   SGD          Power       Test  0.902833   0.908896  0.942137  0.925218  0.786668  0.787702  0.968284  0.222030           0.897500           0.908167            0.902706            0.915118         0.936665         0.947362     0.921034     0.929477      0.965709      0.970775          0.213843          0.230020        0.774999        0.798537      0.776110      0.799404,
 'timing':   Model  TPE_Search_Sec  TPE_Evaluation_Sec  TPE_Total_Sec  Best_CV_Mean
 0   SGD      161.936932          103.452609     265.615265      0.896104}

## Cell 8D: Explicit GWO Per-Model Calls

Run each code cell below manually to execute one model at a time.

In [45]:
run_gwo_model("LGBM")

LGBM       | Scaler: Raw        | Available RAM: 5.53 GB | Kernel RSS: 26.1 MB
       Memory cleanup -> gc_collected=20, available=5.41 GB, used=65.6%, rss=176.0 MB
       Running 50 evaluations with n_jobs_cv=1, n_jobs_opt=8
       GWO progress for LGBM: 0/50 evaluations
       GWO LGBM: initializing population (10 wolves)...
          fold 1/5 | acc=0.99031 | running_mean=0.99031 | time=3.65s
          fold 2/5 | acc=0.99104 | running_mean=0.99068 | time=3.55s
          fold 3/5 | acc=0.99208 | running_mean=0.99115 | time=3.58s
          fold 4/5 | acc=0.99156 | running_mean=0.99125 | time=4.88s
          fold 5/5 | acc=0.98969 | running_mean=0.99094 | time=7.69s
       GWO LGBM: init 1/10 | last=0.99094 | best=0.99094
          fold 1/5 | acc=0.98094 | running_mean=0.98094 | time=4.02s
          fold 2/5 | acc=0.98292 | running_mean=0.98193 | time=4.15s
          fold 3/5 | acc=0.98188 | running_mean=0.98191 | time=4.08s
          fold 4/5 | acc=0.98104 | running_mean=0.98169 | time=4.01s
          fold 5/5 | acc=0.98073 | running_mean=0.98150 | time=3.84s
       GWO LGBM: init 2/10 | last=0.98150 | best=0.99094
          fold 1/5 | acc=0.99396 | running_mean=0.99396 | time=4.91s
          fold 2/5 | acc=0.99542 | running_mean=0.99469 | time=4.46s
          fold 3/5 | acc=0.99615 | running_mean=0.99517 | time=5.69s
          fold 4/5 | acc=0.99469 | running_mean=0.99505 | time=5.24s
          fold 5/5 | acc=0.99448 | running_mean=0.99494 | time=5.97s
       GWO LGBM: init 3/10 | last=0.99494 | best=0.99494
          fold 1/5 | acc=0.91135 | running_mean=0.91135 | time=0.96s
          fold 2/5 | acc=0.92125 | running_mean=0.91630 | time=0.99s
          fold 3/5 | acc=0.91927 | running_mean=0.91729 | time=1.26s
          fold 4/5 | acc=0.91615 | running_mean=0.91701 | time=1.02s
          fold 5/5 | acc=0.91687 | running_mean=0.91698 | time=1.00s
       GWO LGBM: init 4/10 | last=0.91698 | best=0.99494
          fold 1/5 | acc=0.95073 | running_mean=0.95073 | time=0.90s
          fold 2/5 | acc=0.95719 | running_mean=0.95396 | time=1.26s
          fold 3/5 | acc=0.95760 | running_mean=0.95517 | time=1.02s
          fold 4/5 | acc=0.95271 | running_mean=0.95456 | time=0.92s
          fold 5/5 | acc=0.95333 | running_mean=0.95431 | time=1.00s
       GWO LGBM: init 5/10 | last=0.95431 | best=0.99494
          fold 1/5 | acc=0.97917 | running_mean=0.97917 | time=3.13s
          fold 2/5 | acc=0.97958 | running_mean=0.97937 | time=2.94s
          fold 3/5 | acc=0.98198 | running_mean=0.98024 | time=3.84s
          fold 4/5 | acc=0.98104 | running_mean=0.98044 | time=4.17s
          fold 5/5 | acc=0.97937 | running_mean=0.98023 | time=3.31s
       GWO LGBM: init 6/10 | last=0.98023 | best=0.99494
          fold 1/5 | acc=0.99469 | running_mean=0.99469 | time=4.76s
          fold 2/5 | acc=0.99417 | running_mean=0.99443 | time=4.96s
          fold 3/5 | acc=0.99510 | running_mean=0.99465 | time=5.63s
          fold 4/5 | acc=0.99438 | running_mean=0.99458 | time=4.91s
          fold 5/5 | acc=0.99406 | running_mean=0.99448 | time=4.78s
       GWO LGBM: init 7/10 | last=0.99448 | best=0.99494
          fold 1/5 | acc=0.99281 | running_mean=0.99281 | time=5.15s
          fold 2/5 | acc=0.99281 | running_mean=0.99281 | time=5.80s
          fold 3/5 | acc=0.99396 | running_mean=0.99319 | time=7.34s
          fold 4/5 | acc=0.99281 | running_mean=0.99310 | time=5.12s
          fold 5/5 | acc=0.99323 | running_mean=0.99313 | time=5.67s
       GWO LGBM: init 8/10 | last=0.99313 | best=0.99494
          fold 1/5 | acc=0.94396 | running_mean=0.94396 | time=1.66s
          fold 2/5 | acc=0.94906 | running_mean=0.94651 | time=1.55s
          fold 3/5 | acc=0.94927 | running_mean=0.94743 | time=1.66s
          fold 4/5 | acc=0.94500 | running_mean=0.94682 | time=1.53s
          fold 5/5 | acc=0.94521 | running_mean=0.94650 | time=2.01s
       GWO LGBM: init 9/10 | last=0.94650 | best=0.99494
          fold 1/5 | acc=0.98990 | running_mean=0.98990 | time=1.19s
          fold 2/5 | acc=0.98885 | running_mean=0.98938 | time=1.37s
          fold 3/5 | acc=0.99062 | running_mean=0.98979 | time=1.24s
          fold 4/5 | acc=0.99062 | running_mean=0.99000 | time=1.40s
          fold 5/5 | acc=0.99052 | running_mean=0.99010 | time=1.01s
       GWO LGBM: init 10/10 | last=0.99010 | best=0.99494
       GWO LGBM: init done → α=0.99494 β=0.99448 δ=0.99313
          fold 1/5 | acc=0.99031 | running_mean=0.99031 | time=6.77s
          fold 2/5 | acc=0.99104 | running_mean=0.99068 | time=6.59s
          fold 3/5 | acc=0.99208 | running_mean=0.99115 | time=6.55s
          fold 4/5 | acc=0.99156 | running_mean=0.99125 | time=6.94s
          fold 5/5 | acc=0.98969 | running_mean=0.99094 | time=8.20s
       GWO LGBM: 11/50 | iter=1/4 | last=0.99094 | best=0.99494
          fold 1/5 | acc=0.98094 | running_mean=0.98094 | time=3.37s
          fold 2/5 | acc=0.98292 | running_mean=0.98193 | time=3.71s
          fold 3/5 | acc=0.98188 | running_mean=0.98191 | time=3.45s
          fold 4/5 | acc=0.98104 | running_mean=0.98169 | time=3.68s
          fold 5/5 | acc=0.98073 | running_mean=0.98150 | time=4.45s
       GWO LGBM: 12/50 | iter=1/4 | last=0.98150 | best=0.99494
          fold 1/5 | acc=0.99396 | running_mean=0.99396 | time=4.51s
          fold 2/5 | acc=0.99542 | running_mean=0.99469 | time=4.96s
          fold 3/5 | acc=0.99615 | running_mean=0.99517 | time=4.73s
          fold 4/5 | acc=0.99469 | running_mean=0.99505 | time=4.62s
          fold 5/5 | acc=0.99448 | running_mean=0.99494 | time=4.69s
       GWO LGBM: 13/50 | iter=1/4 | last=0.99494 | best=0.99494
          fold 1/5 | acc=0.91135 | running_mean=0.91135 | time=1.03s
          fold 2/5 | acc=0.92125 | running_mean=0.91630 | time=1.12s
          fold 3/5 | acc=0.91927 | running_mean=0.91729 | time=1.30s
          fold 4/5 | acc=0.91615 | running_mean=0.91701 | time=1.38s
          fold 5/5 | acc=0.91687 | running_mean=0.91698 | time=1.11s
       GWO LGBM: 14/50 | iter=1/4 | last=0.91698 | best=0.99494
          fold 1/5 | acc=0.95073 | running_mean=0.95073 | time=1.10s
          fold 2/5 | acc=0.95719 | running_mean=0.95396 | time=1.28s
          fold 3/5 | acc=0.95760 | running_mean=0.95517 | time=1.14s
          fold 4/5 | acc=0.95271 | running_mean=0.95456 | time=1.00s
          fold 5/5 | acc=0.95333 | running_mean=0.95431 | time=0.91s
       GWO LGBM: 15/50 | iter=1/4 | last=0.95431 | best=0.99494
          fold 1/5 | acc=0.97917 | running_mean=0.97917 | time=3.36s
          fold 2/5 | acc=0.97958 | running_mean=0.97937 | time=2.77s
          fold 3/5 | acc=0.98198 | running_mean=0.98024 | time=3.24s
          fold 4/5 | acc=0.98104 | running_mean=0.98044 | time=3.33s
          fold 5/5 | acc=0.97937 | running_mean=0.98023 | time=2.80s
       GWO LGBM: 16/50 | iter=1/4 | last=0.98023 | best=0.99494
          fold 1/5 | acc=0.99469 | running_mean=0.99469 | time=4.99s
          fold 2/5 | acc=0.99417 | running_mean=0.99443 | time=4.83s
          fold 3/5 | acc=0.99510 | running_mean=0.99465 | time=5.21s
          fold 4/5 | acc=0.99438 | running_mean=0.99458 | time=5.24s
          fold 5/5 | acc=0.99406 | running_mean=0.99448 | time=4.72s
       GWO LGBM: 17/50 | iter=1/4 | last=0.99448 | best=0.99494
          fold 1/5 | acc=0.99281 | running_mean=0.99281 | time=5.09s
          fold 2/5 | acc=0.99281 | running_mean=0.99281 | time=5.14s
          fold 3/5 | acc=0.99396 | running_mean=0.99319 | time=4.98s
          fold 4/5 | acc=0.99281 | running_mean=0.99310 | time=5.07s
          fold 5/5 | acc=0.99323 | running_mean=0.99313 | time=4.98s
       GWO LGBM: 18/50 | iter=1/4 | last=0.99313 | best=0.99494
          fold 1/5 | acc=0.94396 | running_mean=0.94396 | time=1.88s
          fold 2/5 | acc=0.94906 | running_mean=0.94651 | time=1.52s
          fold 3/5 | acc=0.94927 | running_mean=0.94743 | time=1.55s
          fold 4/5 | acc=0.94500 | running_mean=0.94682 | time=2.04s
          fold 5/5 | acc=0.94521 | running_mean=0.94650 | time=1.68s
       GWO LGBM: 19/50 | iter=1/4 | last=0.94650 | best=0.99494
          fold 1/5 | acc=0.98990 | running_mean=0.98990 | time=1.10s
          fold 2/5 | acc=0.98885 | running_mean=0.98938 | time=1.26s
          fold 3/5 | acc=0.99062 | running_mean=0.98979 | time=1.12s
          fold 4/5 | acc=0.99062 | running_mean=0.99000 | time=0.94s
          fold 5/5 | acc=0.99052 | running_mean=0.99010 | time=1.18s
       GWO LGBM: 20/50 | iter=1/4 | last=0.99010 | best=0.99494
       GWO LGBM: iter 1/4 done → α=0.99494 β=0.99494 δ=0.99448
          fold 1/5 | acc=0.99542 | running_mean=0.99542 | time=4.86s
          fold 2/5 | acc=0.99573 | running_mean=0.99557 | time=4.50s
          fold 3/5 | acc=0.99635 | running_mean=0.99583 | time=5.63s
          fold 4/5 | acc=0.99656 | running_mean=0.99602 | time=4.62s
          fold 5/5 | acc=0.99635 | running_mean=0.99608 | time=5.04s
       GWO LGBM: 21/50 | iter=2/4 | last=0.99608 | best=0.99494
          fold 1/5 | acc=0.98135 | running_mean=0.98135 | time=7.03s
          fold 2/5 | acc=0.98427 | running_mean=0.98281 | time=6.89s
          fold 3/5 | acc=0.98427 | running_mean=0.98330 | time=7.40s
          fold 4/5 | acc=0.98313 | running_mean=0.98326 | time=6.62s
          fold 5/5 | acc=0.98271 | running_mean=0.98315 | time=7.25s
       GWO LGBM: 22/50 | iter=2/4 | last=0.98315 | best=0.99494
          fold 1/5 | acc=0.99594 | running_mean=0.99594 | time=4.11s
          fold 2/5 | acc=0.99740 | running_mean=0.99667 | time=4.43s
          fold 3/5 | acc=0.99708 | running_mean=0.99681 | time=4.49s
          fold 4/5 | acc=0.99646 | running_mean=0.99672 | time=4.50s
          fold 5/5 | acc=0.99594 | running_mean=0.99656 | time=4.62s
       GWO LGBM: 23/50 | iter=2/4 | last=0.99656 | best=0.99494
          fold 1/5 | acc=0.99646 | running_mean=0.99646 | time=3.92s
          fold 2/5 | acc=0.99635 | running_mean=0.99641 | time=5.09s
          fold 3/5 | acc=0.99729 | running_mean=0.99670 | time=3.82s
          fold 4/5 | acc=0.99604 | running_mean=0.99654 | time=4.50s
          fold 5/5 | acc=0.99573 | running_mean=0.99638 | time=3.72s
       GWO LGBM: 24/50 | iter=2/4 | last=0.99638 | best=0.99494
          fold 1/5 | acc=0.98052 | running_mean=0.98052 | time=2.06s
          fold 2/5 | acc=0.98417 | running_mean=0.98234 | time=1.69s
          fold 3/5 | acc=0.98198 | running_mean=0.98222 | time=2.00s
          fold 4/5 | acc=0.98219 | running_mean=0.98221 | time=1.80s
          fold 5/5 | acc=0.98198 | running_mean=0.98217 | time=1.98s
       GWO LGBM: 25/50 | iter=2/4 | last=0.98217 | best=0.99494
          fold 1/5 | acc=0.99500 | running_mean=0.99500 | time=2.76s
          fold 2/5 | acc=0.99427 | running_mean=0.99464 | time=2.50s
          fold 3/5 | acc=0.99490 | running_mean=0.99472 | time=3.02s
          fold 4/5 | acc=0.99396 | running_mean=0.99453 | time=2.34s
          fold 5/5 | acc=0.99417 | running_mean=0.99446 | time=2.76s
       GWO LGBM: 26/50 | iter=2/4 | last=0.99446 | best=0.99494
          fold 1/5 | acc=0.99375 | running_mean=0.99375 | time=6.75s
          fold 2/5 | acc=0.99292 | running_mean=0.99333 | time=7.02s
          fold 3/5 | acc=0.99510 | running_mean=0.99392 | time=7.84s
          fold 4/5 | acc=0.99292 | running_mean=0.99367 | time=7.03s
          fold 5/5 | acc=0.99219 | running_mean=0.99338 | time=7.63s
       GWO LGBM: 27/50 | iter=2/4 | last=0.99338 | best=0.99494
          fold 1/5 | acc=0.99521 | running_mean=0.99521 | time=5.00s
          fold 2/5 | acc=0.99625 | running_mean=0.99573 | time=4.82s
          fold 3/5 | acc=0.99635 | running_mean=0.99594 | time=4.89s
          fold 4/5 | acc=0.99573 | running_mean=0.99589 | time=5.07s
          fold 5/5 | acc=0.99667 | running_mean=0.99604 | time=5.01s
       GWO LGBM: 28/50 | iter=2/4 | last=0.99604 | best=0.99494
          fold 1/5 | acc=0.99313 | running_mean=0.99313 | time=4.65s
          fold 2/5 | acc=0.99333 | running_mean=0.99323 | time=4.28s
          fold 3/5 | acc=0.99302 | running_mean=0.99316 | time=4.24s
          fold 4/5 | acc=0.99229 | running_mean=0.99294 | time=4.67s
          fold 5/5 | acc=0.99219 | running_mean=0.99279 | time=5.70s
       GWO LGBM: 29/50 | iter=2/4 | last=0.99279 | best=0.99494
          fold 1/5 | acc=0.96031 | running_mean=0.96031 | time=2.09s
          fold 2/5 | acc=0.96396 | running_mean=0.96214 | time=3.17s
          fold 3/5 | acc=0.96594 | running_mean=0.96340 | time=2.47s
          fold 4/5 | acc=0.96344 | running_mean=0.96341 | time=2.71s
          fold 5/5 | acc=0.96313 | running_mean=0.96335 | time=2.15s
       GWO LGBM: 30/50 | iter=2/4 | last=0.96335 | best=0.99494
       GWO LGBM: iter 2/4 done → α=0.99656 β=0.99638 δ=0.99608
          fold 1/5 | acc=0.99260 | running_mean=0.99260 | time=3.93s
          fold 2/5 | acc=0.99240 | running_mean=0.99250 | time=3.45s
          fold 3/5 | acc=0.99292 | running_mean=0.99264 | time=3.27s
          fold 4/5 | acc=0.99271 | running_mean=0.99266 | time=3.67s
          fold 5/5 | acc=0.99219 | running_mean=0.99256 | time=3.63s
       GWO LGBM: 31/50 | iter=3/4 | last=0.99256 | best=0.99656
          fold 1/5 | acc=0.99667 | running_mean=0.99667 | time=4.13s
          fold 2/5 | acc=0.99708 | running_mean=0.99687 | time=3.59s
          fold 3/5 | acc=0.99656 | running_mean=0.99677 | time=3.38s
          fold 4/5 | acc=0.99698 | running_mean=0.99682 | time=4.01s
          fold 5/5 | acc=0.99677 | running_mean=0.99681 | time=3.25s
       GWO LGBM: 32/50 | iter=3/4 | last=0.99681 | best=0.99656
          fold 1/5 | acc=0.99427 | running_mean=0.99427 | time=8.67s
          fold 2/5 | acc=0.99427 | running_mean=0.99427 | time=12.52s
          fold 3/5 | acc=0.99625 | running_mean=0.99493 | time=10.07s
          fold 4/5 | acc=0.99375 | running_mean=0.99464 | time=10.10s
          fold 5/5 | acc=0.99438 | running_mean=0.99458 | time=9.90s
       GWO LGBM: 33/50 | iter=3/4 | last=0.99458 | best=0.99656
          fold 1/5 | acc=0.99562 | running_mean=0.99562 | time=4.82s
          fold 2/5 | acc=0.99573 | running_mean=0.99568 | time=4.65s
          fold 3/5 | acc=0.99708 | running_mean=0.99615 | time=4.37s
          fold 4/5 | acc=0.99646 | running_mean=0.99622 | time=4.80s
          fold 5/5 | acc=0.99656 | running_mean=0.99629 | time=4.27s
       GWO LGBM: 34/50 | iter=3/4 | last=0.99629 | best=0.99656
          fold 1/5 | acc=0.98875 | running_mean=0.98875 | time=3.57s
          fold 2/5 | acc=0.99000 | running_mean=0.98938 | time=3.78s
          fold 3/5 | acc=0.99052 | running_mean=0.98976 | time=3.67s
          fold 4/5 | acc=0.99083 | running_mean=0.99003 | time=3.36s
          fold 5/5 | acc=0.98865 | running_mean=0.98975 | time=3.61s
       GWO LGBM: 35/50 | iter=3/4 | last=0.98975 | best=0.99656
          fold 1/5 | acc=0.99531 | running_mean=0.99531 | time=5.93s
          fold 2/5 | acc=0.99604 | running_mean=0.99568 | time=6.95s
          fold 3/5 | acc=0.99583 | running_mean=0.99573 | time=5.50s
          fold 4/5 | acc=0.99760 | running_mean=0.99620 | time=5.08s
          fold 5/5 | acc=0.99656 | running_mean=0.99627 | time=5.09s
       GWO LGBM: 36/50 | iter=3/4 | last=0.99627 | best=0.99656
          fold 1/5 | acc=0.96510 | running_mean=0.96510 | time=8.51s
          fold 2/5 | acc=0.96896 | running_mean=0.96703 | time=6.64s
          fold 3/5 | acc=0.96937 | running_mean=0.96781 | time=7.12s
          fold 4/5 | acc=0.96729 | running_mean=0.96768 | time=6.87s
          fold 5/5 | acc=0.96781 | running_mean=0.96771 | time=7.46s
       GWO LGBM: 37/50 | iter=3/4 | last=0.96771 | best=0.99656
          fold 1/5 | acc=0.99698 | running_mean=0.99698 | time=4.12s
          fold 2/5 | acc=0.99615 | running_mean=0.99656 | time=6.03s
          fold 3/5 | acc=0.99792 | running_mean=0.99701 | time=4.43s
          fold 4/5 | acc=0.99687 | running_mean=0.99698 | time=4.37s
          fold 5/5 | acc=0.99781 | running_mean=0.99715 | time=3.97s
       GWO LGBM: 38/50 | iter=3/4 | last=0.99715 | best=0.99656
          fold 1/5 | acc=0.99615 | running_mean=0.99615 | time=4.91s
          fold 2/5 | acc=0.99562 | running_mean=0.99589 | time=5.12s
          fold 3/5 | acc=0.99750 | running_mean=0.99642 | time=5.17s
          fold 4/5 | acc=0.99615 | running_mean=0.99635 | time=4.72s
          fold 5/5 | acc=0.99667 | running_mean=0.99642 | time=4.63s
       GWO LGBM: 39/50 | iter=3/4 | last=0.99642 | best=0.99656
          fold 1/5 | acc=0.99635 | running_mean=0.99635 | time=5.27s
          fold 2/5 | acc=0.99531 | running_mean=0.99583 | time=4.23s
          fold 3/5 | acc=0.99646 | running_mean=0.99604 | time=5.51s
          fold 4/5 | acc=0.99594 | running_mean=0.99602 | time=4.08s
          fold 5/5 | acc=0.99594 | running_mean=0.99600 | time=4.59s
       GWO LGBM: 40/50 | iter=3/4 | last=0.99600 | best=0.99656
       GWO LGBM: iter 3/4 done → α=0.99715 β=0.99681 δ=0.99656
          fold 1/5 | acc=0.99667 | running_mean=0.99667 | time=4.80s
          fold 2/5 | acc=0.99615 | running_mean=0.99641 | time=4.53s
          fold 3/5 | acc=0.99687 | running_mean=0.99656 | time=5.32s
          fold 4/5 | acc=0.99698 | running_mean=0.99667 | time=4.29s
          fold 5/5 | acc=0.99698 | running_mean=0.99673 | time=4.54s
       GWO LGBM: 41/50 | iter=4/4 | last=0.99673 | best=0.99715
          fold 1/5 | acc=0.99719 | running_mean=0.99719 | time=4.77s
          fold 2/5 | acc=0.99698 | running_mean=0.99708 | time=4.48s
          fold 3/5 | acc=0.99698 | running_mean=0.99705 | time=4.47s
          fold 4/5 | acc=0.99813 | running_mean=0.99732 | time=4.41s
          fold 5/5 | acc=0.99667 | running_mean=0.99719 | time=4.75s
       GWO LGBM: 42/50 | iter=4/4 | last=0.99719 | best=0.99715
          fold 1/5 | acc=0.99594 | running_mean=0.99594 | time=5.07s
          fold 2/5 | acc=0.99583 | running_mean=0.99589 | time=5.52s
          fold 3/5 | acc=0.99750 | running_mean=0.99642 | time=5.14s
          fold 4/5 | acc=0.99635 | running_mean=0.99641 | time=5.01s
          fold 5/5 | acc=0.99625 | running_mean=0.99637 | time=5.40s
       GWO LGBM: 43/50 | iter=4/4 | last=0.99637 | best=0.99715
          fold 1/5 | acc=0.99760 | running_mean=0.99760 | time=4.47s
          fold 2/5 | acc=0.99677 | running_mean=0.99719 | time=4.61s
          fold 3/5 | acc=0.99740 | running_mean=0.99726 | time=5.28s
          fold 4/5 | acc=0.99823 | running_mean=0.99750 | time=5.29s
          fold 5/5 | acc=0.99708 | running_mean=0.99742 | time=4.73s
       GWO LGBM: 44/50 | iter=4/4 | last=0.99742 | best=0.99715
          fold 1/5 | acc=0.99635 | running_mean=0.99635 | time=3.85s
          fold 2/5 | acc=0.99677 | running_mean=0.99656 | time=3.33s
          fold 3/5 | acc=0.99625 | running_mean=0.99646 | time=3.80s
          fold 4/5 | acc=0.99698 | running_mean=0.99659 | time=4.17s
          fold 5/5 | acc=0.99677 | running_mean=0.99663 | time=3.75s
       GWO LGBM: 45/50 | iter=4/4 | last=0.99663 | best=0.99715
          fold 1/5 | acc=0.99677 | running_mean=0.99677 | time=4.58s
          fold 2/5 | acc=0.99677 | running_mean=0.99677 | time=4.25s
          fold 3/5 | acc=0.99781 | running_mean=0.99712 | time=4.48s
          fold 4/5 | acc=0.99719 | running_mean=0.99714 | time=4.63s
          fold 5/5 | acc=0.99698 | running_mean=0.99710 | time=4.42s
       GWO LGBM: 46/50 | iter=4/4 | last=0.99710 | best=0.99715
          fold 1/5 | acc=0.99583 | running_mean=0.99583 | time=4.53s
          fold 2/5 | acc=0.99687 | running_mean=0.99635 | time=4.91s
          fold 3/5 | acc=0.99740 | running_mean=0.99670 | time=5.25s
          fold 4/5 | acc=0.99760 | running_mean=0.99693 | time=4.47s
          fold 5/5 | acc=0.99740 | running_mean=0.99702 | time=5.17s
       GWO LGBM: 47/50 | iter=4/4 | last=0.99702 | best=0.99715
          fold 1/5 | acc=0.99750 | running_mean=0.99750 | time=5.00s
          fold 2/5 | acc=0.99615 | running_mean=0.99682 | time=7.39s
          fold 3/5 | acc=0.99802 | running_mean=0.99722 | time=4.54s

{'status': 'completed',
 'best':   Model Optimal_Scaler  Best_CV_Mean  Best_Iteration  n_estimators  \
 0  LGBM            Raw      0.997417              44           500

    learning_rate  max_depth  num_leaves  min_child_samples  subsample  \
 0       0.355003         14          41                 67   0.882642

    colsample_bytree     reg_alpha  reg_lambda  random_state
 0          0.804129  3.282340e-07    0.002453            42  ,
 'history':    Model  Iteration   CV_Mean  Best_Score_So_Far  Iteration_Runtime_Sec
 0   LGBM          1  0.990938           0.990938              23.387606
 1   LGBM          2  0.981500           0.990938              20.144641
 2   LGBM          3  0.994938           0.994938              26.293972
 3   LGBM          4  0.916979           0.994938               5.263392
 4   LGBM          5  0.954313           0.994938               5.139570
 5   LGBM          6  0.980229           0.994938              17.422333
 6   LGBM          7  0.994479           0.994938              25.068935
 7   LGBM          8  0.993125           0.994938              29.131606
 8   LGBM          9  0.946500           0.994938               8.465131
 9   LGBM         10  0.990104           0.994938               6.248506
 10  LGBM         11  0.990938           0.994938              35.088174
 11  LGBM         12  0.981500           0.994938              18.717273
 12  LGBM         13  0.994938           0.994938              23.586698
 13  LGBM         14  0.916979           0.994938               6.003513
 14  LGBM         15  0.954313           0.994938               5.493449
 15  LGBM         16  0.980229           0.994938              15.533357
 16  LGBM         17  0.994479           0.994938              25.024596
 17  LGBM         18  0.993125           0.994938              25.280785
 18  LGBM         19  0.946500           0.994938               8.724926
 19  LGBM         20  0.990104           0.994938               5.633470
 20  LGBM         21  0.996083           0.996562              24.692178
 21  LGBM         22  0.983146           0.996562              35.241406
 22  LGBM         23  0.996562           0.996562              22.190685
 23  LGBM         24  0.996375           0.996562              21.079011
 24  LGBM         25  0.982167           0.996562               9.592322
 25  LGBM         26  0.994458           0.996562              13.435405
 26  LGBM         27  0.993375           0.996562              36.297682
 27  LGBM         28  0.996042           0.996562              24.837613
 28  LGBM         29  0.992792           0.996562              23.597078
 29  LGBM         30  0.963354           0.996562              12.633138
 30  LGBM         31  0.992563           0.997146              18.014402
 31  LGBM         32  0.996813           0.997146              18.421891
 32  LGBM         33  0.994583           0.997146              51.334764
 33  LGBM         34  0.996292           0.997146              22.950706
 34  LGBM         35  0.989750           0.997146              18.011727
 35  LGBM         36  0.996271           0.997146              28.569807
 36  LGBM         37  0.967708           0.997146              36.631193
 37  LGBM         38  0.997146           0.997146              22.937879
 38  LGBM         39  0.996417           0.997146              24.577544
 39  LGBM         40  0.996000           0.997146              23.710054
 40  LGBM         41  0.996729           0.997417              23.517446
 41  LGBM         42  0.997188           0.997417              22.916145
 42  LGBM         43  0.996375           0.997417              26.183517
 43  LGBM         44  0.997417           0.997417              24.409564
 44  LGBM         45  0.996625           0.997417              18.923715
 45  LGBM         46  0.997104           0.997417              22.409718
 46  LGBM         47  0.997021           0.997417              24.375366
 47  LGBM         48  0.997146           0.997417              26.031490
 48  LGBM         49  0.996646           0.997417              28.642055
 49  LGBM         50  0.995583           0.997417              27.637583,
 'summary':   Method Model Optimal_Scaler      Split  Accuracy  Precision    Recall  \
 0    GWO  LGBM            Raw  Train_OOF  0.997417   0.997488  0.998465
 1    GWO  LGBM            Raw       Test  0.999000   0.998825  0.999608

          F1     Kappa       MCC  ...  F1_CI_Lower  F1_CI_Upper  AUC_CI_Lower  \
 0  0.997976  0.994405  0.994406  ...     0.997605     0.998316      0.999895
 1  0.999217  0.997834  0.997835  ...     0.998756     0.999611      0.999992

    AUC_CI_Upper  LogLoss_CI_Lower  LogLoss_CI_Upper  Kappa_CI_Lower  \
 0      0.999960          0.006804          0.009587        0.993397
 1      0.999999          0.001688          0.003934        0.996571

    Kappa_CI_Upper  MCC_CI_Lower  MCC_CI_Upper
 0        0.995346      0.993398      0.995348
 1        0.998927      0.996571      0.998927

 [2 rows x 28 columns],
 'timing':   Model  GWO_Search_Sec  GWO_Evaluation_Sec  GWO_Total_Sec  Best_CV_Mean
 0  LGBM     1069.594466           138.05214     1207.98395      0.997417}

In [47]:
run_gwo_model("LR")

LR         | Scaler: Power      | Available RAM: 4.45 GB | Kernel RSS: 219.1 MB
       Memory cleanup -> gc_collected=223, available=4.45 GB, used=71.7%, rss=219.1 MB
       Running 50 evaluations with n_jobs_cv=1, n_jobs_opt=8
       GWO progress for LR: 0/50 evaluations
       GWO LR: initializing population (10 wolves)...
          fold 1/5 | acc=0.89677 | running_mean=0.89677 | time=2.72s
          fold 2/5 | acc=0.89615 | running_mean=0.89646 | time=1.94s
          fold 3/5 | acc=0.89417 | running_mean=0.89569 | time=1.88s
          fold 4/5 | acc=0.89760 | running_mean=0.89617 | time=1.80s
          fold 5/5 | acc=0.90135 | running_mean=0.89721 | time=2.00s
       GWO LR: init 1/10 | last=0.89721 | best=0.89721
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=1.73s
          fold 2/5 | acc=0.89615 | running_mean=0.89651 | time=1.69s
          fold 3/5 | acc=0.89354 | running_mean=0.89552 | time=1.58s
          fold 4/5 | acc=0.89750 | running_mean=0.89602 | time=1.91s
          fold 5/5 | acc=0.90125 | running_mean=0.89706 | time=1.76s
       GWO LR: init 2/10 | last=0.89706 | best=0.89721
          fold 1/5 | acc=0.84198 | running_mean=0.84198 | time=1.09s
          fold 2/5 | acc=0.84635 | running_mean=0.84417 | time=1.09s
          fold 3/5 | acc=0.84031 | running_mean=0.84288 | time=1.00s
          fold 4/5 | acc=0.84448 | running_mean=0.84328 | time=0.92s
          fold 5/5 | acc=0.83906 | running_mean=0.84244 | time=1.03s
       GWO LR: init 3/10 | last=0.84244 | best=0.89721
          fold 1/5 | acc=0.89490 | running_mean=0.89490 | time=1.65s
          fold 2/5 | acc=0.89573 | running_mean=0.89531 | time=1.51s
          fold 3/5 | acc=0.89281 | running_mean=0.89448 | time=1.57s
          fold 4/5 | acc=0.89750 | running_mean=0.89523 | time=1.66s
          fold 5/5 | acc=0.90083 | running_mean=0.89635 | time=1.51s
       GWO LR: init 4/10 | last=0.89635 | best=0.89721
          fold 1/5 | acc=0.85208 | running_mean=0.85208 | time=1.02s
          fold 2/5 | acc=0.85729 | running_mean=0.85469 | time=1.03s
          fold 3/5 | acc=0.85448 | running_mean=0.85462 | time=1.08s
          fold 4/5 | acc=0.85625 | running_mean=0.85503 | time=1.10s
          fold 5/5 | acc=0.85010 | running_mean=0.85404 | time=1.18s
       GWO LR: init 5/10 | last=0.85404 | best=0.89721
          fold 1/5 | acc=0.87562 | running_mean=0.87562 | time=1.03s
          fold 2/5 | acc=0.88000 | running_mean=0.87781 | time=1.03s
          fold 3/5 | acc=0.87438 | running_mean=0.87667 | time=0.98s
          fold 4/5 | acc=0.87781 | running_mean=0.87695 | time=0.99s
          fold 5/5 | acc=0.87729 | running_mean=0.87702 | time=0.98s
       GWO LR: init 6/10 | last=0.87702 | best=0.89721
          fold 1/5 | acc=0.89250 | running_mean=0.89250 | time=1.46s
          fold 2/5 | acc=0.89625 | running_mean=0.89437 | time=1.25s
          fold 3/5 | acc=0.89031 | running_mean=0.89302 | time=1.35s
          fold 4/5 | acc=0.89510 | running_mean=0.89354 | time=1.41s
          fold 5/5 | acc=0.89906 | running_mean=0.89465 | time=1.50s
       GWO LR: init 7/10 | last=0.89465 | best=0.89721
          fold 1/5 | acc=0.89104 | running_mean=0.89104 | time=1.61s
          fold 2/5 | acc=0.89552 | running_mean=0.89328 | time=1.56s
          fold 3/5 | acc=0.88990 | running_mean=0.89215 | time=1.58s
          fold 4/5 | acc=0.89229 | running_mean=0.89219 | time=1.55s
          fold 5/5 | acc=0.89583 | running_mean=0.89292 | time=1.57s
       GWO LR: init 8/10 | last=0.89292 | best=0.89721
          fold 1/5 | acc=0.89427 | running_mean=0.89427 | time=1.81s
          fold 2/5 | acc=0.89479 | running_mean=0.89453 | time=2.00s
          fold 3/5 | acc=0.89219 | running_mean=0.89375 | time=1.94s
          fold 4/5 | acc=0.89698 | running_mean=0.89456 | time=1.83s
          fold 5/5 | acc=0.90094 | running_mean=0.89583 | time=1.82s
       GWO LR: init 9/10 | last=0.89583 | best=0.89721
          fold 1/5 | acc=0.89667 | running_mean=0.89667 | time=1.50s
          fold 2/5 | acc=0.89583 | running_mean=0.89625 | time=1.70s
          fold 3/5 | acc=0.89323 | running_mean=0.89524 | time=1.65s
          fold 4/5 | acc=0.89760 | running_mean=0.89583 | time=1.59s
          fold 5/5 | acc=0.90083 | running_mean=0.89683 | time=1.81s
       GWO LR: init 10/10 | last=0.89683 | best=0.89721
       GWO LR: init done → α=0.89721 β=0.89706 δ=0.89683
          fold 1/5 | acc=0.89677 | running_mean=0.89677 | time=1.97s
          fold 2/5 | acc=0.89615 | running_mean=0.89646 | time=1.93s
          fold 3/5 | acc=0.89417 | running_mean=0.89569 | time=1.87s
          fold 4/5 | acc=0.89760 | running_mean=0.89617 | time=1.79s
          fold 5/5 | acc=0.90135 | running_mean=0.89721 | time=1.93s
       GWO LR: 11/50 | iter=1/4 | last=0.89721 | best=0.89721
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=1.59s
          fold 2/5 | acc=0.89615 | running_mean=0.89651 | time=1.72s
          fold 3/5 | acc=0.89354 | running_mean=0.89552 | time=1.70s
          fold 4/5 | acc=0.89750 | running_mean=0.89602 | time=1.64s
          fold 5/5 | acc=0.90125 | running_mean=0.89706 | time=1.53s
       GWO LR: 12/50 | iter=1/4 | last=0.89706 | best=0.89721
          fold 1/5 | acc=0.84198 | running_mean=0.84198 | time=1.02s
          fold 2/5 | acc=0.84635 | running_mean=0.84417 | time=1.08s
          fold 3/5 | acc=0.84031 | running_mean=0.84288 | time=1.10s
          fold 4/5 | acc=0.84448 | running_mean=0.84328 | time=1.12s
          fold 5/5 | acc=0.83906 | running_mean=0.84244 | time=1.25s
       GWO LR: 13/50 | iter=1/4 | last=0.84244 | best=0.89721
          fold 1/5 | acc=0.89490 | running_mean=0.89490 | time=2.18s
          fold 2/5 | acc=0.89573 | running_mean=0.89531 | time=2.20s
          fold 3/5 | acc=0.89281 | running_mean=0.89448 | time=2.09s
          fold 4/5 | acc=0.89750 | running_mean=0.89523 | time=2.01s
          fold 5/5 | acc=0.90083 | running_mean=0.89635 | time=2.32s
       GWO LR: 14/50 | iter=1/4 | last=0.89635 | best=0.89721
          fold 1/5 | acc=0.85208 | running_mean=0.85208 | time=1.50s
          fold 2/5 | acc=0.85729 | running_mean=0.85469 | time=1.54s
          fold 3/5 | acc=0.85448 | running_mean=0.85462 | time=1.08s
          fold 4/5 | acc=0.85625 | running_mean=0.85503 | time=1.08s
          fold 5/5 | acc=0.85010 | running_mean=0.85404 | time=1.12s
       GWO LR: 15/50 | iter=1/4 | last=0.85404 | best=0.89721
          fold 1/5 | acc=0.87562 | running_mean=0.87562 | time=1.03s
          fold 2/5 | acc=0.88000 | running_mean=0.87781 | time=0.99s
          fold 3/5 | acc=0.87438 | running_mean=0.87667 | time=0.94s
          fold 4/5 | acc=0.87781 | running_mean=0.87695 | time=0.92s
          fold 5/5 | acc=0.87729 | running_mean=0.87702 | time=0.93s
       GWO LR: 16/50 | iter=1/4 | last=0.87702 | best=0.89721
          fold 1/5 | acc=0.89250 | running_mean=0.89250 | time=1.64s
          fold 2/5 | acc=0.89625 | running_mean=0.89437 | time=1.51s
          fold 3/5 | acc=0.89031 | running_mean=0.89302 | time=1.46s
          fold 4/5 | acc=0.89510 | running_mean=0.89354 | time=1.47s
          fold 5/5 | acc=0.89906 | running_mean=0.89465 | time=1.47s
       GWO LR: 17/50 | iter=1/4 | last=0.89465 | best=0.89721
          fold 1/5 | acc=0.89104 | running_mean=0.89104 | time=1.87s
          fold 2/5 | acc=0.89552 | running_mean=0.89328 | time=2.07s
          fold 3/5 | acc=0.88990 | running_mean=0.89215 | time=2.21s
          fold 4/5 | acc=0.89229 | running_mean=0.89219 | time=2.20s
          fold 5/5 | acc=0.89583 | running_mean=0.89292 | time=2.06s
       GWO LR: 18/50 | iter=1/4 | last=0.89292 | best=0.89721
          fold 1/5 | acc=0.89427 | running_mean=0.89427 | time=2.12s
          fold 2/5 | acc=0.89479 | running_mean=0.89453 | time=2.06s
          fold 3/5 | acc=0.89219 | running_mean=0.89375 | time=1.76s
          fold 4/5 | acc=0.89698 | running_mean=0.89456 | time=1.95s
          fold 5/5 | acc=0.90094 | running_mean=0.89583 | time=1.87s
       GWO LR: 19/50 | iter=1/4 | last=0.89583 | best=0.89721
          fold 1/5 | acc=0.89667 | running_mean=0.89667 | time=1.68s
          fold 2/5 | acc=0.89583 | running_mean=0.89625 | time=1.73s
          fold 3/5 | acc=0.89323 | running_mean=0.89524 | time=1.56s
          fold 4/5 | acc=0.89760 | running_mean=0.89583 | time=1.69s
          fold 5/5 | acc=0.90083 | running_mean=0.89683 | time=1.87s
       GWO LR: 20/50 | iter=1/4 | last=0.89683 | best=0.89721
       GWO LR: iter 1/4 done → α=0.89721 β=0.89721 δ=0.89706
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=2.15s
          fold 2/5 | acc=0.89573 | running_mean=0.89542 | time=1.96s
          fold 3/5 | acc=0.89292 | running_mean=0.89458 | time=1.70s
          fold 4/5 | acc=0.89740 | running_mean=0.89529 | time=1.67s
          fold 5/5 | acc=0.90094 | running_mean=0.89642 | time=1.55s
       GWO LR: 21/50 | iter=2/4 | last=0.89642 | best=0.89721
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=1.80s
          fold 2/5 | acc=0.89615 | running_mean=0.89651 | time=1.60s
          fold 3/5 | acc=0.89417 | running_mean=0.89573 | time=1.65s
          fold 4/5 | acc=0.89760 | running_mean=0.89620 | time=1.78s
          fold 5/5 | acc=0.90135 | running_mean=0.89723 | time=1.76s
       GWO LR: 22/50 | iter=2/4 | last=0.89723 | best=0.89721
          fold 1/5 | acc=0.84229 | running_mean=0.84229 | time=1.04s
          fold 2/5 | acc=0.84667 | running_mean=0.84448 | time=1.08s
          fold 3/5 | acc=0.84062 | running_mean=0.84319 | time=0.94s
          fold 4/5 | acc=0.84479 | running_mean=0.84359 | time=0.88s
          fold 5/5 | acc=0.83969 | running_mean=0.84281 | time=0.94s
       GWO LR: 23/50 | iter=2/4 | last=0.84281 | best=0.89721
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=2.36s
          fold 2/5 | acc=0.89615 | running_mean=0.89651 | time=2.22s
          fold 3/5 | acc=0.89417 | running_mean=0.89573 | time=1.88s
          fold 4/5 | acc=0.89760 | running_mean=0.89620 | time=1.97s
          fold 5/5 | acc=0.90146 | running_mean=0.89725 | time=1.90s
       GWO LR: 24/50 | iter=2/4 | last=0.89725 | best=0.89721
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=2.03s
          fold 2/5 | acc=0.89604 | running_mean=0.89646 | time=1.86s
          fold 3/5 | acc=0.89406 | running_mean=0.89566 | time=1.93s
          fold 4/5 | acc=0.89781 | running_mean=0.89620 | time=2.33s
          fold 5/5 | acc=0.90146 | running_mean=0.89725 | time=2.01s
       GWO LR: 25/50 | iter=2/4 | last=0.89725 | best=0.89721
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=1.60s
          fold 2/5 | acc=0.89615 | running_mean=0.89651 | time=1.62s
          fold 3/5 | acc=0.89417 | running_mean=0.89573 | time=1.58s
          fold 4/5 | acc=0.89760 | running_mean=0.89620 | time=1.72s
          fold 5/5 | acc=0.90135 | running_mean=0.89723 | time=1.68s
       GWO LR: 26/50 | iter=2/4 | last=0.89723 | best=0.89721
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=1.89s
          fold 2/5 | acc=0.89615 | running_mean=0.89651 | time=1.94s
          fold 3/5 | acc=0.89417 | running_mean=0.89573 | time=1.94s
          fold 4/5 | acc=0.89760 | running_mean=0.89620 | time=1.83s
          fold 5/5 | acc=0.90135 | running_mean=0.89723 | time=1.90s
       GWO LR: 27/50 | iter=2/4 | last=0.89723 | best=0.89721
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=1.91s
          fold 2/5 | acc=0.89604 | running_mean=0.89646 | time=1.81s
          fold 3/5 | acc=0.89406 | running_mean=0.89566 | time=1.84s
          fold 4/5 | acc=0.89781 | running_mean=0.89620 | time=2.96s
          fold 5/5 | acc=0.90146 | running_mean=0.89725 | time=2.28s
       GWO LR: 28/50 | iter=2/4 | last=0.89725 | best=0.89721
          fold 1/5 | acc=0.89677 | running_mean=0.89677 | time=1.94s
          fold 2/5 | acc=0.89615 | running_mean=0.89646 | time=2.01s
          fold 3/5 | acc=0.89396 | running_mean=0.89563 | time=1.79s
          fold 4/5 | acc=0.89760 | running_mean=0.89612 | time=1.88s
          fold 5/5 | acc=0.90156 | running_mean=0.89721 | time=1.71s
       GWO LR: 29/50 | iter=2/4 | last=0.89721 | best=0.89721
          fold 1/5 | acc=0.89531 | running_mean=0.89531 | time=1.55s
          fold 2/5 | acc=0.89583 | running_mean=0.89557 | time=1.61s
          fold 3/5 | acc=0.89302 | running_mean=0.89472 | time=1.87s
          fold 4/5 | acc=0.89740 | running_mean=0.89539 | time=1.58s
          fold 5/5 | acc=0.90083 | running_mean=0.89648 | time=1.69s
       GWO LR: 30/50 | iter=2/4 | last=0.89648 | best=0.89721
       GWO LR: iter 2/4 done → α=0.89725 β=0.89725 δ=0.89725
          fold 1/5 | acc=0.89677 | running_mean=0.89677 | time=1.92s
          fold 2/5 | acc=0.89625 | running_mean=0.89651 | time=2.07s
          fold 3/5 | acc=0.89417 | running_mean=0.89573 | time=2.14s
          fold 4/5 | acc=0.89760 | running_mean=0.89620 | time=1.32s
          fold 5/5 | acc=0.90167 | running_mean=0.89729 | time=1.28s
       GWO LR: 31/50 | iter=3/4 | last=0.89729 | best=0.89725
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=1.29s
          fold 2/5 | acc=0.89604 | running_mean=0.89646 | time=1.49s
          fold 3/5 | acc=0.89406 | running_mean=0.89566 | time=1.57s
          fold 4/5 | acc=0.89781 | running_mean=0.89620 | time=1.48s
          fold 5/5 | acc=0.90146 | running_mean=0.89725 | time=1.46s
       GWO LR: 32/50 | iter=3/4 | last=0.89725 | best=0.89725
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=1.58s
          fold 2/5 | acc=0.89604 | running_mean=0.89646 | time=1.56s
          fold 3/5 | acc=0.89406 | running_mean=0.89566 | time=1.32s
          fold 4/5 | acc=0.89781 | running_mean=0.89620 | time=1.46s
          fold 5/5 | acc=0.90146 | running_mean=0.89725 | time=1.46s
       GWO LR: 33/50 | iter=3/4 | last=0.89725 | best=0.89725
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=1.43s
          fold 2/5 | acc=0.89615 | running_mean=0.89651 | time=1.73s
          fold 3/5 | acc=0.89417 | running_mean=0.89573 | time=1.57s
          fold 4/5 | acc=0.89760 | running_mean=0.89620 | time=1.47s
          fold 5/5 | acc=0.90135 | running_mean=0.89723 | time=1.40s
       GWO LR: 34/50 | iter=3/4 | last=0.89723 | best=0.89725
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=1.51s
          fold 2/5 | acc=0.89604 | running_mean=0.89646 | time=1.62s
          fold 3/5 | acc=0.89406 | running_mean=0.89566 | time=1.73s
          fold 4/5 | acc=0.89781 | running_mean=0.89620 | time=1.38s
          fold 5/5 | acc=0.90146 | running_mean=0.89725 | time=1.29s
       GWO LR: 35/50 | iter=3/4 | last=0.89725 | best=0.89725
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=1.38s
          fold 2/5 | acc=0.89604 | running_mean=0.89646 | time=1.49s
          fold 3/5 | acc=0.89406 | running_mean=0.89566 | time=1.39s
          fold 4/5 | acc=0.89781 | running_mean=0.89620 | time=1.36s
          fold 5/5 | acc=0.90146 | running_mean=0.89725 | time=1.30s
       GWO LR: 36/50 | iter=3/4 | last=0.89725 | best=0.89725
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=1.29s
          fold 2/5 | acc=0.89604 | running_mean=0.89646 | time=1.22s
          fold 3/5 | acc=0.89406 | running_mean=0.89566 | time=1.37s
          fold 4/5 | acc=0.89781 | running_mean=0.89620 | time=1.36s
          fold 5/5 | acc=0.90146 | running_mean=0.89725 | time=1.55s
       GWO LR: 37/50 | iter=3/4 | last=0.89725 | best=0.89725
          fold 1/5 | acc=0.89677 | running_mean=0.89677 | time=1.22s
          fold 2/5 | acc=0.89583 | running_mean=0.89630 | time=1.33s
          fold 3/5 | acc=0.89333 | running_mean=0.89531 | time=1.61s
          fold 4/5 | acc=0.89781 | running_mean=0.89594 | time=1.47s
          fold 5/5 | acc=0.90104 | running_mean=0.89696 | time=1.37s
       GWO LR: 38/50 | iter=3/4 | last=0.89696 | best=0.89725
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=1.19s
          fold 2/5 | acc=0.89615 | running_mean=0.89651 | time=1.21s
          fold 3/5 | acc=0.89417 | running_mean=0.89573 | time=1.15s
          fold 4/5 | acc=0.89760 | running_mean=0.89620 | time=1.13s
          fold 5/5 | acc=0.90135 | running_mean=0.89723 | time=1.22s
       GWO LR: 39/50 | iter=3/4 | last=0.89723 | best=0.89725
          fold 1/5 | acc=0.89427 | running_mean=0.89427 | time=0.94s
          fold 2/5 | acc=0.89563 | running_mean=0.89495 | time=0.90s
          fold 3/5 | acc=0.89198 | running_mean=0.89396 | time=0.87s
          fold 4/5 | acc=0.89708 | running_mean=0.89474 | time=0.92s
          fold 5/5 | acc=0.90073 | running_mean=0.89594 | time=0.86s
       GWO LR: 40/50 | iter=3/4 | last=0.89594 | best=0.89725
       GWO LR: iter 3/4 done → α=0.89729 β=0.89725 δ=0.89725
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=0.98s
          fold 2/5 | acc=0.89615 | running_mean=0.89651 | time=1.05s
          fold 3/5 | acc=0.89417 | running_mean=0.89573 | time=1.05s
          fold 4/5 | acc=0.89760 | running_mean=0.89620 | time=0.92s
          fold 5/5 | acc=0.90135 | running_mean=0.89723 | time=0.94s
       GWO LR: 41/50 | iter=4/4 | last=0.89723 | best=0.89729
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=1.17s
          fold 2/5 | acc=0.89604 | running_mean=0.89646 | time=1.15s
          fold 3/5 | acc=0.89406 | running_mean=0.89566 | time=1.22s
          fold 4/5 | acc=0.89781 | running_mean=0.89620 | time=1.24s
          fold 5/5 | acc=0.90146 | running_mean=0.89725 | time=1.20s
       GWO LR: 42/50 | iter=4/4 | last=0.89725 | best=0.89729
          fold 1/5 | acc=0.89396 | running_mean=0.89396 | time=1.00s
          fold 2/5 | acc=0.89542 | running_mean=0.89469 | time=1.02s
          fold 3/5 | acc=0.89219 | running_mean=0.89385 | time=1.14s
          fold 4/5 | acc=0.89719 | running_mean=0.89469 | time=1.15s
          fold 5/5 | acc=0.90052 | running_mean=0.89585 | time=1.12s
       GWO LR: 43/50 | iter=4/4 | last=0.89585 | best=0.89729
          fold 1/5 | acc=0.89677 | running_mean=0.89677 | time=1.26s
          fold 2/5 | acc=0.89615 | running_mean=0.89646 | time=1.31s
          fold 3/5 | acc=0.89427 | running_mean=0.89573 | time=1.30s
          fold 4/5 | acc=0.89771 | running_mean=0.89622 | time=1.18s
          fold 5/5 | acc=0.90167 | running_mean=0.89731 | time=1.16s
       GWO LR: 44/50 | iter=4/4 | last=0.89731 | best=0.89729
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=1.51s
          fold 2/5 | acc=0.89604 | running_mean=0.89646 | time=1.31s
          fold 3/5 | acc=0.89406 | running_mean=0.89566 | time=1.32s
          fold 4/5 | acc=0.89781 | running_mean=0.89620 | time=1.40s
          fold 5/5 | acc=0.90146 | running_mean=0.89725 | time=1.45s
       GWO LR: 45/50 | iter=4/4 | last=0.89725 | best=0.89729
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=1.32s
          fold 2/5 | acc=0.89615 | running_mean=0.89651 | time=1.45s
          fold 3/5 | acc=0.89417 | running_mean=0.89573 | time=1.65s
          fold 4/5 | acc=0.89771 | running_mean=0.89622 | time=1.64s
          fold 5/5 | acc=0.90146 | running_mean=0.89727 | time=1.27s
       GWO LR: 46/50 | iter=4/4 | last=0.89727 | best=0.89729
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=1.32s
          fold 2/5 | acc=0.89604 | running_mean=0.89646 | time=1.36s
          fold 3/5 | acc=0.89406 | running_mean=0.89566 | time=1.46s
          fold 4/5 | acc=0.89781 | running_mean=0.89620 | time=1.32s
          fold 5/5 | acc=0.90146 | running_mean=0.89725 | time=1.25s
       GWO LR: 47/50 | iter=4/4 | last=0.89725 | best=0.89729
          fold 1/5 | acc=0.89677 | running_mean=0.89677 | time=1.19s
          fold 2/5 | acc=0.89615 | running_mean=0.89646 | time=1.22s
          fold 3/5 | acc=0.89417 | running_mean=0.89569 | time=1.42s
          fold 4/5 | acc=0.89760 | running_mean=0.89617 | time=1.15s
          fold 5/5 | acc=0.90167 | running_mean=0.89727 | time=1.13s

{'status': 'completed',
 'best':   Model Optimal_Scaler  Best_CV_Mean  Best_Iteration         C penalty solver  max_iter  random_state
 0    LR          Power      0.897312              44  3.339511      l1   saga      2000            42,
 'history':    Model  Iteration   CV_Mean  Best_Score_So_Far  Iteration_Runtime_Sec
 0     LR          1  0.897208           0.897208              10.359904
 1     LR          2  0.897062           0.897208               8.687850
 2     LR          3  0.842437           0.897208               5.141470
 3     LR          4  0.896354           0.897208               7.924488
 4     LR          5  0.854042           0.897208               5.419212
 5     LR          6  0.877021           0.897208               5.023885
 6     LR          7  0.894646           0.897208               7.002790
 7     LR          8  0.892917           0.897208               7.890523
 8     LR          9  0.895833           0.897208               9.415465
 9     LR         10  0.896833           0.897208               8.281038
 10    LR         11  0.897208           0.897208               9.500108
 11    LR         12  0.897062           0.897208               8.206607
 12    LR         13  0.842437           0.897208               5.578286
 13    LR         14  0.896354           0.897208              10.822406
 14    LR         15  0.854042           0.897208               6.346415
 15    LR         16  0.877021           0.897208               4.827138
 16    LR         17  0.894646           0.897208               7.571610
 17    LR         18  0.892917           0.897208              10.443547
 18    LR         19  0.895833           0.897208               9.777301
 19    LR         20  0.896833           0.897208               8.540038
 20    LR         21  0.896417           0.897250               9.049464
 21    LR         22  0.897229           0.897250               8.606974
 22    LR         23  0.842812           0.897250               4.898743
 23    LR         24  0.897250           0.897250              10.345550
 24    LR         25  0.897250           0.897250              10.175071
 25    LR         26  0.897229           0.897250               8.216411
 26    LR         27  0.897229           0.897250               9.514851
 27    LR         28  0.897250           0.897250              10.823947
 28    LR         29  0.897208           0.897250               9.343577
 29    LR         30  0.896479           0.897250               8.312704
 30    LR         31  0.897292           0.897292               8.751981
 31    LR         32  0.897250           0.897292               7.319033
 32    LR         33  0.897250           0.897292               7.402466
 33    LR         34  0.897229           0.897292               7.622313
 34    LR         35  0.897250           0.897292               7.539483
 35    LR         36  0.897250           0.897292               6.932963
 36    LR         37  0.897250           0.897292               6.798884
 37    LR         38  0.896958           0.897292               7.015184
 38    LR         39  0.897229           0.897292               5.903495
 39    LR         40  0.895937           0.897292               4.502379
 40    LR         41  0.897229           0.897312               4.959620
 41    LR         42  0.897250           0.897312               5.979720
 42    LR         43  0.895854           0.897312               5.442993
 43    LR         44  0.897312           0.897312               6.232579
 44    LR         45  0.897250           0.897312               7.010603
 45    LR         46  0.897271           0.897312               7.340222
 46    LR         47  0.897250           0.897312               6.728973
 47    LR         48  0.897271           0.897312               6.114925
 48    LR         49  0.897187           0.897312               6.211222
 49    LR         50  0.897250           0.897312               6.502110,
 'summary':   Method Model Optimal_Scaler      Split  Accuracy  Precision    Recall        F1     Kappa       MCC       AUC   LogLoss  Accuracy_CI_Lower  Accuracy_CI_Upper  Precision_CI_Lower  Precision_CI_Upper  Recall_CI_Lower  Recall_CI_Upper  F1_CI_Lower  F1_CI_Upper  AUC_CI_Lower  AUC_CI_Upper  LogLoss_CI_Lower  LogLoss_CI_Upper  Kappa_CI_Lower  Kappa_CI_Upper  MCC_CI_Lower  MCC_CI_Upper
 0    GWO    LR          Power  Train_OOF  0.897312   0.914449  0.925647  0.920014  0.776648  0.776760  0.966013  0.226450           0.894645           0.900125            0.911372            0.917683         0.922625         0.928621     0.917745     0.922279      0.964746      0.967346          0.222025          0.230605        0.770827        0.782741      0.770938      0.782878
 1    GWO    LR          Power       Test  0.905583   0.918624  0.934822  0.926652  0.794213  0.794452  0.968614  0.218634           0.900417           0.910835            0.912498            0.924452         0.929031         0.940401     0.922375     0.930931      0.966106      0.971114          0.209948          0.226864        0.782780        0.805900      0.783014      0.806201,
 'timing':   Model  GWO_Search_Sec  GWO_Evaluation_Sec  GWO_Total_Sec  Best_CV_Mean
 0    LR      378.413696          132.914084     511.646146      0.897312}

In [48]:
run_gwo_model("LDA")

LDA        | Scaler: Power      | Available RAM: 5.21 GB | Kernel RSS: 204.5 MB
       Memory cleanup -> gc_collected=223, available=5.21 GB, used=66.9%, rss=204.5 MB
       Running 50 evaluations with n_jobs_cv=1, n_jobs_opt=8
       GWO progress for LDA: 0/50 evaluations
       GWO LDA: initializing population (10 wolves)...
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.61s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.68s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.58s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.52s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.56s
       GWO LDA: init 1/10 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.50s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.62s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.53s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.61s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.52s
       GWO LDA: init 2/10 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.79s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.96s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=1.10s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=1.11s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=1.23s
       GWO LDA: init 3/10 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=1.29s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=1.19s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.95s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=1.05s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.95s
       GWO LDA: init 4/10 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=1.14s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=1.00s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=1.18s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=1.24s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=1.14s
       GWO LDA: init 5/10 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=1.09s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=1.17s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=1.11s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=1.21s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=1.15s
       GWO LDA: init 6/10 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=1.25s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=1.18s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=1.19s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=1.60s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=1.52s
       GWO LDA: init 7/10 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=1.35s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=1.39s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=1.42s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=1.35s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=1.38s
       GWO LDA: init 8/10 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=1.39s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=1.38s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=1.36s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=1.33s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=1.29s
       GWO LDA: init 9/10 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=1.22s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=1.23s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=1.14s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=1.17s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.89s
       GWO LDA: init 10/10 | last=0.89531 | best=0.89531
       GWO LDA: init done → α=0.89531 β=0.89531 δ=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.92s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.78s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.90s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.92s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.82s
       GWO LDA: 11/50 | iter=1/4 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.83s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.80s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.71s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.92s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.83s
       GWO LDA: 12/50 | iter=1/4 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.72s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.88s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.62s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.64s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.57s
       GWO LDA: 13/50 | iter=1/4 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.55s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.61s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.61s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.61s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.58s
       GWO LDA: 14/50 | iter=1/4 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.57s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.62s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.54s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.53s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.58s
       GWO LDA: 15/50 | iter=1/4 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.56s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.59s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.55s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.60s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.52s
       GWO LDA: 16/50 | iter=1/4 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.52s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.52s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.48s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.52s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.49s
       GWO LDA: 17/50 | iter=1/4 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.50s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.50s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.49s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.55s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.60s
       GWO LDA: 18/50 | iter=1/4 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.55s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.53s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.52s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.52s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.54s
       GWO LDA: 19/50 | iter=1/4 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.52s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.50s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.49s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.48s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.50s
       GWO LDA: 20/50 | iter=1/4 | last=0.89531 | best=0.89531
       GWO LDA: iter 1/4 done → α=0.89531 β=0.89531 δ=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.52s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.49s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.51s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.48s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.52s
       GWO LDA: 21/50 | iter=2/4 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.50s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.46s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.52s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.48s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.52s
       GWO LDA: 22/50 | iter=2/4 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.69s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.61s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.55s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.53s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.56s
       GWO LDA: 23/50 | iter=2/4 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.46s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.56s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.46s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.48s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.52s
       GWO LDA: 24/50 | iter=2/4 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.46s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.56s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.47s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.47s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.56s
       GWO LDA: 25/50 | iter=2/4 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.53s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.70s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.48s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.55s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.49s
       GWO LDA: 26/50 | iter=2/4 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.48s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.55s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.49s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.59s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.51s
       GWO LDA: 27/50 | iter=2/4 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.48s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.54s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.47s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.56s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.47s
       GWO LDA: 28/50 | iter=2/4 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.48s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.53s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.46s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.63s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.53s
       GWO LDA: 29/50 | iter=2/4 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.53s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.53s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.46s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.54s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.46s
       GWO LDA: 30/50 | iter=2/4 | last=0.89531 | best=0.89531
       GWO LDA: iter 2/4 done → α=0.89531 β=0.89531 δ=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.50s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.52s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.45s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.56s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.51s
       GWO LDA: 31/50 | iter=3/4 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.55s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.60s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.51s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.57s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.48s
       GWO LDA: 32/50 | iter=3/4 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.55s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.48s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.47s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.53s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.47s
       GWO LDA: 33/50 | iter=3/4 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.55s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.48s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.47s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.51s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.46s
       GWO LDA: 34/50 | iter=3/4 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.55s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.49s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.46s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.56s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.48s
       GWO LDA: 35/50 | iter=3/4 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.57s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.48s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.46s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.52s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.47s
       GWO LDA: 36/50 | iter=3/4 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.55s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.47s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.47s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.55s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.48s
       GWO LDA: 37/50 | iter=3/4 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.60s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.49s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.49s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.52s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.47s
       GWO LDA: 38/50 | iter=3/4 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.53s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.46s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.51s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.52s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.51s
       GWO LDA: 39/50 | iter=3/4 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.53s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.49s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.49s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.49s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.48s
       GWO LDA: 40/50 | iter=3/4 | last=0.89531 | best=0.89531
       GWO LDA: iter 3/4 done → α=0.89531 β=0.89531 δ=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.51s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.98s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=1.28s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=1.43s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=1.11s
       GWO LDA: 41/50 | iter=4/4 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.95s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.93s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.91s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.92s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.85s
       GWO LDA: 42/50 | iter=4/4 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.91s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.94s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.89s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.86s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.93s
       GWO LDA: 43/50 | iter=4/4 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=1.03s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.96s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.89s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.95s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.93s
       GWO LDA: 44/50 | iter=4/4 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.91s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.81s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.72s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.70s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.65s
       GWO LDA: 45/50 | iter=4/4 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.63s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.65s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.62s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.67s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.63s
       GWO LDA: 46/50 | iter=4/4 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.70s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.58s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.64s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.57s
          fold 5/5 | acc=0.89948 | running_mean=0.89531 | time=0.66s
       GWO LDA: 47/50 | iter=4/4 | last=0.89531 | best=0.89531
          fold 1/5 | acc=0.89510 | running_mean=0.89510 | time=0.59s
          fold 2/5 | acc=0.89427 | running_mean=0.89469 | time=0.63s
          fold 3/5 | acc=0.89271 | running_mean=0.89403 | time=0.61s
          fold 4/5 | acc=0.89500 | running_mean=0.89427 | time=0.69s

{'status': 'completed',
 'best':   Model Optimal_Scaler  Best_CV_Mean  Best_Iteration solver
 0   LDA          Power      0.895312               1  eigen,
 'history':    Model  Iteration   CV_Mean  Best_Score_So_Far  Iteration_Runtime_Sec
 0    LDA          1  0.895312           0.895312               2.971514
 1    LDA          2  0.895312           0.895312               2.794431
 2    LDA          3  0.895312           0.895312               5.209054
 3    LDA          4  0.895312           0.895312               5.474137
 4    LDA          5  0.895312           0.895312               5.732209
 5    LDA          6  0.895312           0.895312               5.761890
 6    LDA          7  0.895312           0.895312               6.771554
 7    LDA          8  0.895312           0.895312               6.925123
 8    LDA          9  0.895312           0.895312               6.774983
 9    LDA         10  0.895312           0.895312               5.670505
 10   LDA         11  0.895312           0.895312               4.361432
 11   LDA         12  0.895312           0.895312               4.116938
 12   LDA         13  0.895312           0.895312               3.457510
 13   LDA         14  0.895312           0.895312               2.965685
 14   LDA         15  0.895312           0.895312               2.861724
 15   LDA         16  0.895312           0.895312               2.844146
 16   LDA         17  0.895312           0.895312               2.542605
 17   LDA         18  0.895312           0.895312               2.655262
 18   LDA         19  0.895312           0.895312               2.682397
 19   LDA         20  0.895312           0.895312               2.509567
 20   LDA         21  0.895312           0.895312               2.537103
 21   LDA         22  0.895312           0.895312               2.502803
 22   LDA         23  0.895312           0.895312               2.959019
 23   LDA         24  0.895312           0.895312               2.492378
 24   LDA         25  0.895312           0.895312               2.521273
 25   LDA         26  0.895312           0.895312               2.762714
 26   LDA         27  0.895312           0.895312               2.628024
 27   LDA         28  0.895312           0.895312               2.523341
 28   LDA         29  0.895312           0.895312               2.647578
 29   LDA         30  0.895312           0.895312               2.535614
 30   LDA         31  0.895312           0.895312               2.554440
 31   LDA         32  0.895312           0.895312               2.730667
 32   LDA         33  0.895312           0.895312               2.518489
 33   LDA         34  0.895312           0.895312               2.489530
 34   LDA         35  0.895312           0.895312               2.554512
 35   LDA         36  0.895312           0.895312               2.505192
 36   LDA         37  0.895312           0.895312               2.529264
 37   LDA         38  0.895312           0.895312               2.577943
 38   LDA         39  0.895312           0.895312               2.540972
 39   LDA         40  0.895312           0.895312               2.499403
 40   LDA         41  0.895312           0.895312               5.327287
 41   LDA         42  0.895312           0.895312               4.589390
 42   LDA         43  0.895312           0.895312               4.550566
 43   LDA         44  0.895312           0.895312               4.784248
 44   LDA         45  0.895312           0.895312               3.819365
 45   LDA         46  0.895312           0.895312               3.203422
 46   LDA         47  0.895312           0.895312               3.175096
 47   LDA         48  0.895312           0.895312               3.440688
 48   LDA         49  0.895312           0.895312               3.606258
 49   LDA         50  0.895312           0.895312               3.219114,
 'summary':   Method Model Optimal_Scaler      Split  Accuracy  Precision    Recall        F1     Kappa       MCC       AUC   LogLoss  Accuracy_CI_Lower  Accuracy_CI_Upper  Precision_CI_Lower  Precision_CI_Upper  Recall_CI_Lower  Recall_CI_Upper  F1_CI_Lower  F1_CI_Upper  AUC_CI_Lower  AUC_CI_Upper  LogLoss_CI_Lower  LogLoss_CI_Upper  Kappa_CI_Lower  Kappa_CI_Upper  MCC_CI_Lower  MCC_CI_Upper
 0    GWO   LDA          Power  Train_OOF  0.895312   0.913942  0.922806  0.918352  0.772519  0.772589  0.964981  0.239864           0.892521           0.898042            0.910854            0.917221         0.919793         0.925820     0.916054     0.920509      0.963686      0.966319          0.236391          0.243283        0.766605        0.778447      0.766659      0.778541
 1    GWO   LDA          Power       Test  0.903500   0.917287  0.932863  0.925010  0.789725  0.789945  0.967520  0.234269           0.898250           0.908919            0.910999            0.923354         0.927239         0.938498     0.920641     0.929264      0.964983      0.970034          0.227418          0.241073        0.778190        0.801377      0.778555      0.801650,
 'timing':   Model  GWO_Search_Sec  GWO_Evaluation_Sec  GWO_Total_Sec  Best_CV_Mean
 0   LDA      176.471286          152.676832     329.576221      0.895312}

In [49]:
run_gwo_model("QDA")

QDA        | Scaler: Power      | Available RAM: 7.30 GB | Kernel RSS: 198.4 MB
       Memory cleanup -> gc_collected=67, available=7.22 GB, used=54.1%, rss=198.4 MB
       Running 50 evaluations with n_jobs_cv=1, n_jobs_opt=8
       GWO progress for QDA: 0/50 evaluations
       GWO QDA: initializing population (10 wolves)...
          fold 1/5 | acc=0.84292 | running_mean=0.84292 | time=1.33s
          fold 2/5 | acc=0.84406 | running_mean=0.84349 | time=1.41s
          fold 3/5 | acc=0.83948 | running_mean=0.84215 | time=1.25s
          fold 4/5 | acc=0.84062 | running_mean=0.84177 | time=1.21s
          fold 5/5 | acc=0.83719 | running_mean=0.84085 | time=1.37s
       GWO QDA: init 1/10 | last=0.84085 | best=0.84085
          fold 1/5 | acc=0.86333 | running_mean=0.86333 | time=1.31s
          fold 2/5 | acc=0.86521 | running_mean=0.86427 | time=1.27s
          fold 3/5 | acc=0.86052 | running_mean=0.86302 | time=1.12s
          fold 4/5 | acc=0.86521 | running_mean=0.86357 | time=1.23s
          fold 5/5 | acc=0.85792 | running_mean=0.86244 | time=1.10s
       GWO QDA: init 2/10 | last=0.86244 | best=0.86244
          fold 1/5 | acc=0.83802 | running_mean=0.83802 | time=1.06s
          fold 2/5 | acc=0.83875 | running_mean=0.83839 | time=1.12s
          fold 3/5 | acc=0.83208 | running_mean=0.83628 | time=1.06s
          fold 4/5 | acc=0.83500 | running_mean=0.83596 | time=1.06s
          fold 5/5 | acc=0.83281 | running_mean=0.83533 | time=1.16s
       GWO QDA: init 3/10 | last=0.83533 | best=0.86244
          fold 1/5 | acc=0.84635 | running_mean=0.84635 | time=1.12s
          fold 2/5 | acc=0.84833 | running_mean=0.84734 | time=1.32s
          fold 3/5 | acc=0.84406 | running_mean=0.84625 | time=1.08s
          fold 4/5 | acc=0.84594 | running_mean=0.84617 | time=1.29s
          fold 5/5 | acc=0.84219 | running_mean=0.84537 | time=1.29s
       GWO QDA: init 4/10 | last=0.84537 | best=0.86244
          fold 1/5 | acc=0.89292 | running_mean=0.89292 | time=1.42s
          fold 2/5 | acc=0.89823 | running_mean=0.89557 | time=1.40s
          fold 3/5 | acc=0.89177 | running_mean=0.89431 | time=1.20s
          fold 4/5 | acc=0.89479 | running_mean=0.89443 | time=1.35s
          fold 5/5 | acc=0.89042 | running_mean=0.89362 | time=1.10s
       GWO QDA: init 5/10 | last=0.89362 | best=0.89362
          fold 1/5 | acc=0.82896 | running_mean=0.82896 | time=1.17s
          fold 2/5 | acc=0.82969 | running_mean=0.82932 | time=1.17s
          fold 3/5 | acc=0.82323 | running_mean=0.82729 | time=0.95s
          fold 4/5 | acc=0.82615 | running_mean=0.82701 | time=0.83s
          fold 5/5 | acc=0.82375 | running_mean=0.82635 | time=0.62s
       GWO QDA: init 6/10 | last=0.82635 | best=0.89362
          fold 1/5 | acc=0.84323 | running_mean=0.84323 | time=0.55s
          fold 2/5 | acc=0.84448 | running_mean=0.84385 | time=0.58s
          fold 3/5 | acc=0.84083 | running_mean=0.84285 | time=0.64s
          fold 4/5 | acc=0.84135 | running_mean=0.84247 | time=0.80s
          fold 5/5 | acc=0.83802 | running_mean=0.84158 | time=0.64s
       GWO QDA: init 7/10 | last=0.84158 | best=0.89362
          fold 1/5 | acc=0.84146 | running_mean=0.84146 | time=0.68s
          fold 2/5 | acc=0.84344 | running_mean=0.84245 | time=0.57s
          fold 3/5 | acc=0.83823 | running_mean=0.84104 | time=0.54s
          fold 4/5 | acc=0.84000 | running_mean=0.84078 | time=0.48s
          fold 5/5 | acc=0.83635 | running_mean=0.83990 | time=0.52s
       GWO QDA: init 8/10 | last=0.83990 | best=0.89362
          fold 1/5 | acc=0.88917 | running_mean=0.88917 | time=0.51s
          fold 2/5 | acc=0.89333 | running_mean=0.89125 | time=0.59s
          fold 3/5 | acc=0.88896 | running_mean=0.89049 | time=0.50s
          fold 4/5 | acc=0.89062 | running_mean=0.89052 | time=0.54s
          fold 5/5 | acc=0.88562 | running_mean=0.88954 | time=0.52s
       GWO QDA: init 9/10 | last=0.88954 | best=0.89362
          fold 1/5 | acc=0.86250 | running_mean=0.86250 | time=0.51s
          fold 2/5 | acc=0.86396 | running_mean=0.86323 | time=0.50s
          fold 3/5 | acc=0.85990 | running_mean=0.86212 | time=0.49s
          fold 4/5 | acc=0.86438 | running_mean=0.86268 | time=0.51s
          fold 5/5 | acc=0.85698 | running_mean=0.86154 | time=0.53s
       GWO QDA: init 10/10 | last=0.86154 | best=0.89362
       GWO QDA: init done → α=0.89362 β=0.88954 δ=0.86244
          fold 1/5 | acc=0.84292 | running_mean=0.84292 | time=0.50s
          fold 2/5 | acc=0.84406 | running_mean=0.84349 | time=0.50s
          fold 3/5 | acc=0.83948 | running_mean=0.84215 | time=0.50s
          fold 4/5 | acc=0.84062 | running_mean=0.84177 | time=0.52s
          fold 5/5 | acc=0.83719 | running_mean=0.84085 | time=0.50s
       GWO QDA: 11/50 | iter=1/4 | last=0.84085 | best=0.89362
          fold 1/5 | acc=0.86333 | running_mean=0.86333 | time=0.58s
          fold 2/5 | acc=0.86521 | running_mean=0.86427 | time=0.53s
          fold 3/5 | acc=0.86052 | running_mean=0.86302 | time=0.53s
          fold 4/5 | acc=0.86521 | running_mean=0.86357 | time=0.50s
          fold 5/5 | acc=0.85792 | running_mean=0.86244 | time=0.50s
       GWO QDA: 12/50 | iter=1/4 | last=0.86244 | best=0.89362
          fold 1/5 | acc=0.83802 | running_mean=0.83802 | time=0.50s
          fold 2/5 | acc=0.83875 | running_mean=0.83839 | time=0.51s
          fold 3/5 | acc=0.83208 | running_mean=0.83628 | time=0.53s
          fold 4/5 | acc=0.83500 | running_mean=0.83596 | time=0.51s
          fold 5/5 | acc=0.83281 | running_mean=0.83533 | time=0.53s
       GWO QDA: 13/50 | iter=1/4 | last=0.83533 | best=0.89362
          fold 1/5 | acc=0.84635 | running_mean=0.84635 | time=0.52s
          fold 2/5 | acc=0.84833 | running_mean=0.84734 | time=0.49s
          fold 3/5 | acc=0.84406 | running_mean=0.84625 | time=0.49s
          fold 4/5 | acc=0.84594 | running_mean=0.84617 | time=0.52s
          fold 5/5 | acc=0.84219 | running_mean=0.84537 | time=0.52s
       GWO QDA: 14/50 | iter=1/4 | last=0.84537 | best=0.89362
          fold 1/5 | acc=0.89292 | running_mean=0.89292 | time=0.50s
          fold 2/5 | acc=0.89823 | running_mean=0.89557 | time=0.55s
          fold 3/5 | acc=0.89177 | running_mean=0.89431 | time=0.54s
          fold 4/5 | acc=0.89479 | running_mean=0.89443 | time=0.50s
          fold 5/5 | acc=0.89042 | running_mean=0.89362 | time=0.55s
       GWO QDA: 15/50 | iter=1/4 | last=0.89362 | best=0.89362
          fold 1/5 | acc=0.82896 | running_mean=0.82896 | time=0.53s
          fold 2/5 | acc=0.82969 | running_mean=0.82932 | time=0.76s
          fold 3/5 | acc=0.82323 | running_mean=0.82729 | time=0.57s
          fold 4/5 | acc=0.82615 | running_mean=0.82701 | time=0.56s
          fold 5/5 | acc=0.82375 | running_mean=0.82635 | time=0.52s
       GWO QDA: 16/50 | iter=1/4 | last=0.82635 | best=0.89362
          fold 1/5 | acc=0.84323 | running_mean=0.84323 | time=0.52s
          fold 2/5 | acc=0.84448 | running_mean=0.84385 | time=0.52s
          fold 3/5 | acc=0.84083 | running_mean=0.84285 | time=0.46s
          fold 4/5 | acc=0.84135 | running_mean=0.84247 | time=0.51s
          fold 5/5 | acc=0.83802 | running_mean=0.84158 | time=0.48s
       GWO QDA: 17/50 | iter=1/4 | last=0.84158 | best=0.89362
          fold 1/5 | acc=0.84146 | running_mean=0.84146 | time=0.50s
          fold 2/5 | acc=0.84344 | running_mean=0.84245 | time=0.53s
          fold 3/5 | acc=0.83823 | running_mean=0.84104 | time=0.47s
          fold 4/5 | acc=0.84000 | running_mean=0.84078 | time=0.55s
          fold 5/5 | acc=0.83635 | running_mean=0.83990 | time=0.52s
       GWO QDA: 18/50 | iter=1/4 | last=0.83990 | best=0.89362
          fold 1/5 | acc=0.88917 | running_mean=0.88917 | time=0.56s
          fold 2/5 | acc=0.89333 | running_mean=0.89125 | time=0.49s
          fold 3/5 | acc=0.88896 | running_mean=0.89049 | time=0.49s
          fold 4/5 | acc=0.89062 | running_mean=0.89052 | time=0.55s
          fold 5/5 | acc=0.88562 | running_mean=0.88954 | time=0.51s
       GWO QDA: 19/50 | iter=1/4 | last=0.88954 | best=0.89362
          fold 1/5 | acc=0.86250 | running_mean=0.86250 | time=0.56s
          fold 2/5 | acc=0.86396 | running_mean=0.86323 | time=0.49s
          fold 3/5 | acc=0.85990 | running_mean=0.86212 | time=0.55s
          fold 4/5 | acc=0.86438 | running_mean=0.86268 | time=0.56s
          fold 5/5 | acc=0.85698 | running_mean=0.86154 | time=0.58s
       GWO QDA: 20/50 | iter=1/4 | last=0.86154 | best=0.89362
       GWO QDA: iter 1/4 done → α=0.89362 β=0.89362 δ=0.88954
          fold 1/5 | acc=0.88729 | running_mean=0.88729 | time=0.55s
          fold 2/5 | acc=0.89198 | running_mean=0.88964 | time=0.56s
          fold 3/5 | acc=0.88573 | running_mean=0.88833 | time=0.55s
          fold 4/5 | acc=0.88885 | running_mean=0.88846 | time=0.49s
          fold 5/5 | acc=0.88375 | running_mean=0.88752 | time=0.56s
       GWO QDA: 21/50 | iter=2/4 | last=0.88752 | best=0.89362
          fold 1/5 | acc=0.89469 | running_mean=0.89469 | time=0.56s
          fold 2/5 | acc=0.89354 | running_mean=0.89411 | time=0.54s
          fold 3/5 | acc=0.88969 | running_mean=0.89264 | time=0.46s
          fold 4/5 | acc=0.89094 | running_mean=0.89221 | time=0.47s
          fold 5/5 | acc=0.89333 | running_mean=0.89244 | time=0.56s
       GWO QDA: 22/50 | iter=2/4 | last=0.89244 | best=0.89362
          fold 1/5 | acc=0.89469 | running_mean=0.89469 | time=0.49s
          fold 2/5 | acc=0.89354 | running_mean=0.89411 | time=0.57s
          fold 3/5 | acc=0.88969 | running_mean=0.89264 | time=0.49s
          fold 4/5 | acc=0.89094 | running_mean=0.89221 | time=0.57s
          fold 5/5 | acc=0.89333 | running_mean=0.89244 | time=0.53s
       GWO QDA: 23/50 | iter=2/4 | last=0.89244 | best=0.89362
          fold 1/5 | acc=0.86979 | running_mean=0.86979 | time=0.47s
          fold 2/5 | acc=0.87313 | running_mean=0.87146 | time=0.53s
          fold 3/5 | acc=0.86813 | running_mean=0.87035 | time=0.48s
          fold 4/5 | acc=0.87260 | running_mean=0.87091 | time=0.54s
          fold 5/5 | acc=0.86469 | running_mean=0.86967 | time=0.51s
       GWO QDA: 24/50 | iter=2/4 | last=0.86967 | best=0.89362
          fold 1/5 | acc=0.88802 | running_mean=0.88802 | time=0.52s
          fold 2/5 | acc=0.89260 | running_mean=0.89031 | time=0.57s
          fold 3/5 | acc=0.88719 | running_mean=0.88927 | time=0.48s
          fold 4/5 | acc=0.88979 | running_mean=0.88940 | time=0.53s
          fold 5/5 | acc=0.88406 | running_mean=0.88833 | time=0.50s
       GWO QDA: 25/50 | iter=2/4 | last=0.88833 | best=0.89362
          fold 1/5 | acc=0.89469 | running_mean=0.89469 | time=0.50s
          fold 2/5 | acc=0.89354 | running_mean=0.89411 | time=0.54s
          fold 3/5 | acc=0.88969 | running_mean=0.89264 | time=0.48s
          fold 4/5 | acc=0.89094 | running_mean=0.89221 | time=0.53s
          fold 5/5 | acc=0.89333 | running_mean=0.89244 | time=0.50s
       GWO QDA: 26/50 | iter=2/4 | last=0.89244 | best=0.89362
          fold 1/5 | acc=0.86990 | running_mean=0.86990 | time=0.57s
          fold 2/5 | acc=0.87344 | running_mean=0.87167 | time=0.55s
          fold 3/5 | acc=0.86833 | running_mean=0.87056 | time=0.55s
          fold 4/5 | acc=0.87281 | running_mean=0.87112 | time=0.55s
          fold 5/5 | acc=0.86490 | running_mean=0.86988 | time=0.55s
       GWO QDA: 27/50 | iter=2/4 | last=0.86988 | best=0.89362
          fold 1/5 | acc=0.89469 | running_mean=0.89469 | time=0.57s
          fold 2/5 | acc=0.89354 | running_mean=0.89411 | time=0.52s
          fold 3/5 | acc=0.88969 | running_mean=0.89264 | time=0.54s
          fold 4/5 | acc=0.89094 | running_mean=0.89221 | time=0.49s
          fold 5/5 | acc=0.89333 | running_mean=0.89244 | time=0.48s
       GWO QDA: 28/50 | iter=2/4 | last=0.89244 | best=0.89362
          fold 1/5 | acc=0.88750 | running_mean=0.88750 | time=0.55s
          fold 2/5 | acc=0.89250 | running_mean=0.89000 | time=0.75s
          fold 3/5 | acc=0.88615 | running_mean=0.88872 | time=0.77s
          fold 4/5 | acc=0.88938 | running_mean=0.88888 | time=0.73s
          fold 5/5 | acc=0.88406 | running_mean=0.88792 | time=0.63s
       GWO QDA: 29/50 | iter=2/4 | last=0.88792 | best=0.89362
          fold 1/5 | acc=0.87854 | running_mean=0.87854 | time=0.85s
          fold 2/5 | acc=0.88302 | running_mean=0.88078 | time=0.85s
          fold 3/5 | acc=0.87750 | running_mean=0.87969 | time=0.75s
          fold 4/5 | acc=0.88229 | running_mean=0.88034 | time=0.63s
          fold 5/5 | acc=0.87646 | running_mean=0.87956 | time=0.65s
       GWO QDA: 30/50 | iter=2/4 | last=0.87956 | best=0.89362
       GWO QDA: iter 2/4 done → α=0.89362 β=0.89362 δ=0.89244
          fold 1/5 | acc=0.89156 | running_mean=0.89156 | time=0.54s
          fold 2/5 | acc=0.89635 | running_mean=0.89396 | time=0.70s
          fold 3/5 | acc=0.89052 | running_mean=0.89281 | time=0.61s
          fold 4/5 | acc=0.89271 | running_mean=0.89279 | time=0.77s
          fold 5/5 | acc=0.88875 | running_mean=0.89198 | time=0.80s
       GWO QDA: 31/50 | iter=3/4 | last=0.89198 | best=0.89362
          fold 1/5 | acc=0.89542 | running_mean=0.89542 | time=0.68s
          fold 2/5 | acc=0.90042 | running_mean=0.89792 | time=0.75s
          fold 3/5 | acc=0.89448 | running_mean=0.89677 | time=0.62s
          fold 4/5 | acc=0.89542 | running_mean=0.89643 | time=0.82s
          fold 5/5 | acc=0.89365 | running_mean=0.89587 | time=0.83s
       GWO QDA: 32/50 | iter=3/4 | last=0.89587 | best=0.89362
          fold 1/5 | acc=0.89677 | running_mean=0.89677 | time=0.91s
          fold 2/5 | acc=0.90125 | running_mean=0.89901 | time=0.82s
          fold 3/5 | acc=0.89625 | running_mean=0.89809 | time=0.69s
          fold 4/5 | acc=0.89708 | running_mean=0.89784 | time=0.78s
          fold 5/5 | acc=0.89563 | running_mean=0.89740 | time=0.59s
       GWO QDA: 33/50 | iter=3/4 | last=0.89740 | best=0.89362
          fold 1/5 | acc=0.87927 | running_mean=0.87927 | time=0.68s
          fold 2/5 | acc=0.88333 | running_mean=0.88130 | time=0.63s
          fold 3/5 | acc=0.87813 | running_mean=0.88024 | time=0.68s
          fold 4/5 | acc=0.88208 | running_mean=0.88070 | time=0.58s
          fold 5/5 | acc=0.87698 | running_mean=0.87996 | time=0.69s
       GWO QDA: 34/50 | iter=3/4 | last=0.87996 | best=0.89362
          fold 1/5 | acc=0.88917 | running_mean=0.88917 | time=0.76s
          fold 2/5 | acc=0.89333 | running_mean=0.89125 | time=0.67s
          fold 3/5 | acc=0.88896 | running_mean=0.89049 | time=0.56s
          fold 4/5 | acc=0.89062 | running_mean=0.89052 | time=0.69s
          fold 5/5 | acc=0.88562 | running_mean=0.88954 | time=0.59s
       GWO QDA: 35/50 | iter=3/4 | last=0.88954 | best=0.89362
          fold 1/5 | acc=0.89708 | running_mean=0.89708 | time=0.67s
          fold 2/5 | acc=0.90250 | running_mean=0.89979 | time=0.65s
          fold 3/5 | acc=0.89740 | running_mean=0.89899 | time=0.68s
          fold 4/5 | acc=0.89833 | running_mean=0.89883 | time=0.60s
          fold 5/5 | acc=0.89729 | running_mean=0.89852 | time=0.73s
       GWO QDA: 36/50 | iter=3/4 | last=0.89852 | best=0.89362
          fold 1/5 | acc=0.88667 | running_mean=0.88667 | time=0.60s
          fold 2/5 | acc=0.89167 | running_mean=0.88917 | time=0.77s
          fold 3/5 | acc=0.88521 | running_mean=0.88785 | time=0.76s
          fold 4/5 | acc=0.88844 | running_mean=0.88799 | time=0.71s
          fold 5/5 | acc=0.88333 | running_mean=0.88706 | time=0.60s
       GWO QDA: 37/50 | iter=3/4 | last=0.88706 | best=0.89362
          fold 1/5 | acc=0.88917 | running_mean=0.88917 | time=0.69s
          fold 2/5 | acc=0.89333 | running_mean=0.89125 | time=0.64s
          fold 3/5 | acc=0.88896 | running_mean=0.89049 | time=0.60s
          fold 4/5 | acc=0.89073 | running_mean=0.89055 | time=0.52s
          fold 5/5 | acc=0.88562 | running_mean=0.88956 | time=0.60s
       GWO QDA: 38/50 | iter=3/4 | last=0.88956 | best=0.89362
          fold 1/5 | acc=0.89052 | running_mean=0.89052 | time=0.55s
          fold 2/5 | acc=0.89396 | running_mean=0.89224 | time=0.60s
          fold 3/5 | acc=0.89010 | running_mean=0.89153 | time=0.53s
          fold 4/5 | acc=0.89167 | running_mean=0.89156 | time=0.63s
          fold 5/5 | acc=0.88729 | running_mean=0.89071 | time=0.56s
       GWO QDA: 39/50 | iter=3/4 | last=0.89071 | best=0.89362
          fold 1/5 | acc=0.87854 | running_mean=0.87854 | time=0.63s
          fold 2/5 | acc=0.88302 | running_mean=0.88078 | time=0.56s
          fold 3/5 | acc=0.87750 | running_mean=0.87969 | time=0.59s
          fold 4/5 | acc=0.88219 | running_mean=0.88031 | time=0.55s
          fold 5/5 | acc=0.87646 | running_mean=0.87954 | time=0.51s
       GWO QDA: 40/50 | iter=3/4 | last=0.87954 | best=0.89362
       GWO QDA: iter 3/4 done → α=0.89852 β=0.89740 δ=0.89587
          fold 1/5 | acc=0.89708 | running_mean=0.89708 | time=0.60s
          fold 2/5 | acc=0.90125 | running_mean=0.89917 | time=0.56s
          fold 3/5 | acc=0.89615 | running_mean=0.89816 | time=0.58s
          fold 4/5 | acc=0.89792 | running_mean=0.89810 | time=0.52s
          fold 5/5 | acc=0.89594 | running_mean=0.89767 | time=0.62s
       GWO QDA: 41/50 | iter=4/4 | last=0.89767 | best=0.89852
          fold 1/5 | acc=0.89698 | running_mean=0.89698 | time=0.52s
          fold 2/5 | acc=0.90302 | running_mean=0.90000 | time=0.60s
          fold 3/5 | acc=0.89708 | running_mean=0.89903 | time=0.55s
          fold 4/5 | acc=0.89865 | running_mean=0.89893 | time=0.54s
          fold 5/5 | acc=0.89729 | running_mean=0.89860 | time=0.58s
       GWO QDA: 42/50 | iter=4/4 | last=0.89860 | best=0.89852
          fold 1/5 | acc=0.89615 | running_mean=0.89615 | time=0.50s
          fold 2/5 | acc=0.90115 | running_mean=0.89865 | time=0.59s
          fold 3/5 | acc=0.89542 | running_mean=0.89757 | time=0.56s
          fold 4/5 | acc=0.89635 | running_mean=0.89727 | time=0.61s
          fold 5/5 | acc=0.89510 | running_mean=0.89683 | time=0.52s
       GWO QDA: 43/50 | iter=4/4 | last=0.89683 | best=0.89852
          fold 1/5 | acc=0.89563 | running_mean=0.89563 | time=0.58s
          fold 2/5 | acc=0.90063 | running_mean=0.89813 | time=0.55s
          fold 3/5 | acc=0.89490 | running_mean=0.89705 | time=0.52s
          fold 4/5 | acc=0.89531 | running_mean=0.89661 | time=0.58s
          fold 5/5 | acc=0.89417 | running_mean=0.89613 | time=0.56s
       GWO QDA: 44/50 | iter=4/4 | last=0.89613 | best=0.89852
          fold 1/5 | acc=0.89542 | running_mean=0.89542 | time=0.75s
          fold 2/5 | acc=0.90042 | running_mean=0.89792 | time=0.57s
          fold 3/5 | acc=0.89458 | running_mean=0.89681 | time=0.60s
          fold 4/5 | acc=0.89542 | running_mean=0.89646 | time=0.55s
          fold 5/5 | acc=0.89385 | running_mean=0.89594 | time=0.63s
       GWO QDA: 45/50 | iter=4/4 | last=0.89594 | best=0.89852
          fold 1/5 | acc=0.89531 | running_mean=0.89531 | time=0.53s
          fold 2/5 | acc=0.90063 | running_mean=0.89797 | time=0.61s
          fold 3/5 | acc=0.89490 | running_mean=0.89694 | time=0.53s
          fold 4/5 | acc=0.89542 | running_mean=0.89656 | time=0.58s
          fold 5/5 | acc=0.89365 | running_mean=0.89598 | time=0.59s
       GWO QDA: 46/50 | iter=4/4 | last=0.89598 | best=0.89852
          fold 1/5 | acc=0.89635 | running_mean=0.89635 | time=0.76s
          fold 2/5 | acc=0.90135 | running_mean=0.89885 | time=0.60s
          fold 3/5 | acc=0.89615 | running_mean=0.89795 | time=0.62s
          fold 4/5 | acc=0.89656 | running_mean=0.89760 | time=0.53s
          fold 5/5 | acc=0.89521 | running_mean=0.89712 | time=0.62s
       GWO QDA: 47/50 | iter=4/4 | last=0.89712 | best=0.89852
          fold 1/5 | acc=0.89375 | running_mean=0.89375 | time=0.54s
          fold 2/5 | acc=0.89875 | running_mean=0.89625 | time=0.54s
          fold 3/5 | acc=0.89219 | running_mean=0.89490 | time=0.54s
          fold 4/5 | acc=0.89500 | running_mean=0.89492 | time=0.54s

{'status': 'completed',
 'best':   Model Optimal_Scaler  Best_CV_Mean  Best_Iteration  reg_param
 0   QDA          Power      0.898646              50   0.037184,
 'history':    Model  Iteration   CV_Mean  Best_Score_So_Far  Iteration_Runtime_Sec
 0    QDA          1  0.840854           0.840854               6.595225
 1    QDA          2  0.862438           0.862438               6.058986
 2    QDA          3  0.835333           0.862438               5.486445
 3    QDA          4  0.845375           0.862438               6.122134
 4    QDA          5  0.893625           0.893625               6.500316
 5    QDA          6  0.826354           0.893625               4.768205
 6    QDA          7  0.841583           0.893625               3.228748
 7    QDA          8  0.839896           0.893625               2.817807
 8    QDA          9  0.889542           0.893625               2.685707
 9    QDA         10  0.861542           0.893625               2.552237
 10   QDA         11  0.840854           0.893625               2.544065
 11   QDA         12  0.862438           0.893625               2.658041
 12   QDA         13  0.835333           0.893625               2.590823
 13   QDA         14  0.845375           0.893625               2.571429
 14   QDA         15  0.893625           0.893625               2.644526
 15   QDA         16  0.826354           0.893625               2.958285
 16   QDA         17  0.841583           0.893625               2.504803
 17   QDA         18  0.839896           0.893625               2.589943
 18   QDA         19  0.889542           0.893625               2.621974
 19   QDA         20  0.861542           0.893625               2.762694
 20   QDA         21  0.887521           0.893625               2.733311
 21   QDA         22  0.892437           0.893625               2.607684
 22   QDA         23  0.892437           0.893625               2.652446
 23   QDA         24  0.869667           0.893625               2.548697
 24   QDA         25  0.888333           0.893625               2.611890
 25   QDA         26  0.892437           0.893625               2.569137
 26   QDA         27  0.869875           0.893625               2.779164
 27   QDA         28  0.892437           0.893625               2.631546
 28   QDA         29  0.887917           0.893625               3.440382
 29   QDA         30  0.879563           0.893625               3.749967
 30   QDA         31  0.891979           0.898521               3.443181
 31   QDA         32  0.895875           0.898521               3.731168
 32   QDA         33  0.897396           0.898521               3.815838
 33   QDA         34  0.879958           0.898521               3.280692
 34   QDA         35  0.889542           0.898521               3.289013
 35   QDA         36  0.898521           0.898521               3.338798
 36   QDA         37  0.887063           0.898521               3.467124
 37   QDA         38  0.889562           0.898521               3.059970
 38   QDA         39  0.890708           0.898521               2.880135
 39   QDA         40  0.879542           0.898521               2.850938
 40   QDA         41  0.897667           0.898646               2.901296
 41   QDA         42  0.898604           0.898646               2.805292
 42   QDA         43  0.896833           0.898646               2.792816
 43   QDA         44  0.896125           0.898646               2.809438
 44   QDA         45  0.895937           0.898646               3.118456
 45   QDA         46  0.895979           0.898646               2.853034
 46   QDA         47  0.897125           0.898646               3.154994
 47   QDA         48  0.894458           0.898646               2.770613
 48   QDA         49  0.898250           0.898646               2.739999
 49   QDA         50  0.898646           0.898646               2.811971,
 'summary':   Method Model Optimal_Scaler      Split  Accuracy  Precision    Recall        F1     Kappa       MCC       AUC   LogLoss  Accuracy_CI_Lower  Accuracy_CI_Upper  Precision_CI_Lower  Precision_CI_Upper  Recall_CI_Lower  Recall_CI_Upper  F1_CI_Lower  F1_CI_Upper  AUC_CI_Lower  AUC_CI_Upper  LogLoss_CI_Lower  LogLoss_CI_Upper  Kappa_CI_Lower  Kappa_CI_Upper  MCC_CI_Lower  MCC_CI_Upper
 0    GWO   QDA          Power  Train_OOF  0.898646   0.896402  0.951051  0.922918  0.775356  0.778253  0.967436  0.233802           0.895938           0.901459            0.893228            0.899995         0.948806         0.953436     0.920763     0.925123      0.966163      0.968747          0.230111          0.237405        0.769251        0.781450      0.772254      0.784118
 1    GWO   QDA          Power       Test  0.905167   0.899877  0.957941  0.928002  0.789517  0.792833  0.970126  0.228459           0.900081           0.910417            0.893444            0.906313         0.953609         0.962439     0.923887     0.932118      0.967627      0.972544          0.221526          0.235477        0.778123        0.801142      0.781617      0.804217,
 'timing':   Model  GWO_Search_Sec  GWO_Evaluation_Sec  GWO_Total_Sec  Best_CV_Mean
 0   QDA      163.559562          122.482875     286.288645      0.898646}

In [50]:
run_gwo_model("NB")

NB         | Scaler: Power      | Available RAM: 6.14 GB | Kernel RSS: 205.0 MB
       Memory cleanup -> gc_collected=64, available=6.14 GB, used=61.0%, rss=205.0 MB
       Running 50 evaluations with n_jobs_cv=1, n_jobs_opt=8
       GWO progress for NB: 0/50 evaluations
       GWO NB: initializing population (10 wolves)...
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.59s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.52s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.48s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.45s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.48s
       GWO NB: init 1/10 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.44s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.44s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.45s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.43s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.42s
       GWO NB: init 2/10 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.49s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.46s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.44s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.46s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.43s
       GWO NB: init 3/10 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.48s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.44s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.42s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.51s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.46s
       GWO NB: init 4/10 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.45s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.49s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.41s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.47s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.46s
       GWO NB: init 5/10 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.44s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.49s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.41s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.43s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.49s
       GWO NB: init 6/10 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.43s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.44s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.44s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.41s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.46s
       GWO NB: init 7/10 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.45s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.43s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.45s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.42s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.43s
       GWO NB: init 8/10 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.71s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.51s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.59s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.48s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.44s
       GWO NB: init 9/10 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.48s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.43s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.43s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.45s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.49s
       GWO NB: init 10/10 | last=0.84304 | best=0.84304
       GWO NB: init done → α=0.84304 β=0.84304 δ=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=1.15s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=1.31s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=1.34s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=1.15s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=1.13s
       GWO NB: 11/50 | iter=1/4 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=1.08s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=1.06s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=1.11s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=1.03s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=1.05s
       GWO NB: 12/50 | iter=1/4 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=1.02s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.92s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.99s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=1.08s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=1.15s
       GWO NB: 13/50 | iter=1/4 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.99s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.95s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.91s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.81s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.91s
       GWO NB: 14/50 | iter=1/4 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.88s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.77s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.63s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.57s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.54s
       GWO NB: 15/50 | iter=1/4 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.48s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.50s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.47s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.49s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.49s
       GWO NB: 16/50 | iter=1/4 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.48s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.58s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.47s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.49s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.46s
       GWO NB: 17/50 | iter=1/4 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.48s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.63s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.61s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.62s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.62s
       GWO NB: 18/50 | iter=1/4 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.61s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.54s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.50s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.64s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.59s
       GWO NB: 19/50 | iter=1/4 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.58s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.60s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.58s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.55s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.53s
       GWO NB: 20/50 | iter=1/4 | last=0.84304 | best=0.84304
       GWO NB: iter 1/4 done → α=0.84304 β=0.84304 δ=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.53s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.51s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.51s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.46s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.50s
       GWO NB: 21/50 | iter=2/4 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.52s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.55s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.50s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.49s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.53s
       GWO NB: 22/50 | iter=2/4 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.51s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.55s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.49s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.58s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.52s
       GWO NB: 23/50 | iter=2/4 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.55s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.56s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.61s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.68s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.71s
       GWO NB: 24/50 | iter=2/4 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.68s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.64s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.53s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.59s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.62s
       GWO NB: 25/50 | iter=2/4 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.59s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.54s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.52s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.57s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.51s
       GWO NB: 26/50 | iter=2/4 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.51s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.50s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.58s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.76s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.56s
       GWO NB: 27/50 | iter=2/4 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.63s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.54s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.54s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.50s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.59s
       GWO NB: 28/50 | iter=2/4 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.49s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.50s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.51s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.47s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.61s
       GWO NB: 29/50 | iter=2/4 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.52s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.54s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.55s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.56s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.59s
       GWO NB: 30/50 | iter=2/4 | last=0.84304 | best=0.84304
       GWO NB: iter 2/4 done → α=0.84304 β=0.84304 δ=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.50s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.56s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.50s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.58s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.54s
       GWO NB: 31/50 | iter=3/4 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.66s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.68s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.66s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.59s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.58s
       GWO NB: 32/50 | iter=3/4 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.50s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.53s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.54s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.54s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.58s
       GWO NB: 33/50 | iter=3/4 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.51s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.60s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.51s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.54s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.64s
       GWO NB: 34/50 | iter=3/4 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.58s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.63s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.58s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.57s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.49s
       GWO NB: 35/50 | iter=3/4 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.57s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.53s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.58s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.52s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.49s
       GWO NB: 36/50 | iter=3/4 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.53s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.46s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.58s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.67s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.81s
       GWO NB: 37/50 | iter=3/4 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.80s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.66s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.68s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.55s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.50s
       GWO NB: 38/50 | iter=3/4 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.56s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.51s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.53s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.47s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.45s
       GWO NB: 39/50 | iter=3/4 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.57s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.47s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.56s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.48s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.52s
       GWO NB: 40/50 | iter=3/4 | last=0.84304 | best=0.84304
       GWO NB: iter 3/4 done → α=0.84304 β=0.84304 δ=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.53s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.45s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.48s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.47s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.47s
       GWO NB: 41/50 | iter=4/4 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.54s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.49s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.57s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.47s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.47s
       GWO NB: 42/50 | iter=4/4 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.60s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.59s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.69s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.63s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.65s
       GWO NB: 43/50 | iter=4/4 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.52s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.57s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.62s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.76s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.65s
       GWO NB: 44/50 | iter=4/4 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.67s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.53s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.52s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.61s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.70s
       GWO NB: 45/50 | iter=4/4 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.63s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.74s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.69s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.66s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.53s
       GWO NB: 46/50 | iter=4/4 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.60s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.51s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.45s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.54s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.44s
       GWO NB: 47/50 | iter=4/4 | last=0.84304 | best=0.84304
          fold 1/5 | acc=0.84448 | running_mean=0.84448 | time=0.58s
          fold 2/5 | acc=0.84521 | running_mean=0.84484 | time=0.51s
          fold 3/5 | acc=0.84292 | running_mean=0.84420 | time=0.65s
          fold 4/5 | acc=0.84292 | running_mean=0.84388 | time=0.67s
          fold 5/5 | acc=0.83969 | running_mean=0.84304 | time=0.62s

{'status': 'completed',
 'best':   Model Optimal_Scaler  Best_CV_Mean  Best_Iteration  var_smoothing
 0    NB          Power      0.843042               1   4.402874e-08,
 'history':    Model  Iteration   CV_Mean  Best_Score_So_Far  Iteration_Runtime_Sec
 0     NB          1  0.843042           0.843042               2.534995
 1     NB          2  0.843042           0.843042               2.203515
 2     NB          3  0.843042           0.843042               2.299188
 3     NB          4  0.843042           0.843042               2.326427
 4     NB          5  0.843042           0.843042               2.295911
 5     NB          6  0.843042           0.843042               2.280964
 6     NB          7  0.843042           0.843042               2.190794
 7     NB          8  0.843042           0.843042               2.202114
 8     NB          9  0.843042           0.843042               2.750561
 9     NB         10  0.843042           0.843042               2.295005
 10    NB         11  0.843042           0.843042               6.118109
 11    NB         12  0.843042           0.843042               5.344507
 12    NB         13  0.843042           0.843042               5.185711
 13    NB         14  0.843042           0.843042               4.592972
 14    NB         15  0.843042           0.843042               3.400277
 15    NB         16  0.843042           0.843042               2.454391
 16    NB         17  0.843042           0.843042               2.498396
 17    NB         18  0.843042           0.843042               2.972162
 18    NB         19  0.843042           0.843042               2.895034
 19    NB         20  0.843042           0.843042               2.861701
 20    NB         21  0.843042           0.843042               2.518071
 21    NB         22  0.843042           0.843042               2.614581
 22    NB         23  0.843042           0.843042               2.675202
 23    NB         24  0.843042           0.843042               3.113015
 24    NB         25  0.843042           0.843042               3.076263
 25    NB         26  0.843042           0.843042               2.753260
 26    NB         27  0.843042           0.843042               2.913011
 27    NB         28  0.843042           0.843042               2.816663
 28    NB         29  0.843042           0.843042               2.591352
 29    NB         30  0.843042           0.843042               2.775947
 30    NB         31  0.843042           0.843042               2.696919
 31    NB         32  0.843042           0.843042               3.183842
 32    NB         33  0.843042           0.843042               2.714720
 33    NB         34  0.843042           0.843042               2.813402
 34    NB         35  0.843042           0.843042               2.875541
 35    NB         36  0.843042           0.843042               2.710518
 36    NB         37  0.843042           0.843042               3.064331
 37    NB         38  0.843042           0.843042               3.204851
 38    NB         39  0.843042           0.843042               2.527352
 39    NB         40  0.843042           0.843042               2.599639
 40    NB         41  0.843042           0.843042               2.427954
 41    NB         42  0.843042           0.843042               2.547400
 42    NB         43  0.843042           0.843042               3.188550
 43    NB         44  0.843042           0.843042               3.132454
 44    NB         45  0.843042           0.843042               3.043652
 45    NB         46  0.843042           0.843042               3.270310
 46    NB         47  0.843042           0.843042               2.558509
 47    NB         48  0.843042           0.843042               3.033306
 48    NB         49  0.843042           0.843042               2.918394
 49    NB         50  0.843042           0.843042               3.058370,
 'summary':   Method Model Optimal_Scaler      Split  Accuracy  Precision    Recall        F1     Kappa       MCC       AUC   LogLoss  Accuracy_CI_Lower  Accuracy_CI_Upper  Precision_CI_Lower  Precision_CI_Upper  Recall_CI_Lower  Recall_CI_Upper  F1_CI_Lower  F1_CI_Upper  AUC_CI_Lower  AUC_CI_Upper  LogLoss_CI_Lower  LogLoss_CI_Upper  Kappa_CI_Lower  Kappa_CI_Upper  MCC_CI_Lower  MCC_CI_Upper
 0    GWO    NB          Power  Train_OOF  0.843042   0.885553  0.865889  0.875611  0.663051  0.663358  0.923743  0.362247           0.839770           0.846480            0.881818            0.889304         0.862158         0.869875     0.872867     0.878583      0.921513      0.926109          0.355062          0.369135        0.656142        0.670433      0.656403      0.670681
 1    GWO    NB          Power       Test  0.847500   0.887986  0.870820  0.879319  0.672266  0.672502  0.927360  0.349683           0.841167           0.853917            0.881169            0.895182         0.862932         0.878310     0.873910     0.884685      0.923027      0.931695          0.336669          0.363145        0.658546        0.686017      0.658863      0.686177,
 'timing':   Model  GWO_Search_Sec  GWO_Evaluation_Sec  GWO_Total_Sec  Best_CV_Mean
 0    NB        147.1823          138.367776     285.878493      0.843042}

In [56]:
apply_resource_policy_for_model('KNN')

[ResourcePolicy] model=KNN | free_ram=5.78 GB | n_jobs_cv=1 | n_jobs_opt=3

In [57]:
run_gwo_model("KNN")

KNN        | Scaler: Raw        | Available RAM: 5.78 GB | Kernel RSS: 251.7 MB
       Memory cleanup -> gc_collected=725, available=5.78 GB, used=63.2%, rss=244.1 MB
       Running 50 evaluations with n_jobs_cv=1, n_jobs_opt=3
       GWO progress for KNN: 0/50 evaluations
       GWO KNN: initializing population (10 wolves)...
          fold 1/5 | acc=0.93542 | running_mean=0.93542 | time=11.02s
          fold 2/5 | acc=0.93344 | running_mean=0.93443 | time=9.73s
          fold 3/5 | acc=0.93417 | running_mean=0.93434 | time=9.86s
          fold 4/5 | acc=0.93385 | running_mean=0.93422 | time=9.99s
          fold 5/5 | acc=0.93250 | running_mean=0.93388 | time=12.29s
       GWO KNN: init 1/10 | last=0.93388 | best=0.93388
          fold 1/5 | acc=0.92917 | running_mean=0.92917 | time=10.79s
          fold 2/5 | acc=0.93146 | running_mean=0.93031 | time=7.26s
          fold 3/5 | acc=0.93333 | running_mean=0.93132 | time=9.24s
          fold 4/5 | acc=0.93208 | running_mean=0.93151 | time=10.71s
          fold 5/5 | acc=0.93260 | running_mean=0.93173 | time=8.99s
       GWO KNN: init 2/10 | last=0.93173 | best=0.93388
          fold 1/5 | acc=0.93958 | running_mean=0.93958 | time=5.95s
          fold 2/5 | acc=0.94104 | running_mean=0.94031 | time=8.18s
          fold 3/5 | acc=0.93865 | running_mean=0.93976 | time=6.03s
          fold 4/5 | acc=0.94052 | running_mean=0.93995 | time=7.56s
          fold 5/5 | acc=0.94188 | running_mean=0.94033 | time=6.75s
       GWO KNN: init 3/10 | last=0.94033 | best=0.94033
          fold 1/5 | acc=0.94615 | running_mean=0.94615 | time=7.77s
          fold 2/5 | acc=0.94531 | running_mean=0.94573 | time=6.91s
          fold 3/5 | acc=0.94656 | running_mean=0.94601 | time=6.67s
          fold 4/5 | acc=0.94552 | running_mean=0.94589 | time=5.98s
          fold 5/5 | acc=0.94635 | running_mean=0.94598 | time=5.06s
       GWO KNN: init 4/10 | last=0.94598 | best=0.94598
          fold 1/5 | acc=0.93583 | running_mean=0.93583 | time=8.45s
          fold 2/5 | acc=0.93490 | running_mean=0.93536 | time=8.80s
          fold 3/5 | acc=0.93583 | running_mean=0.93552 | time=10.54s
          fold 4/5 | acc=0.93417 | running_mean=0.93518 | time=15.00s
          fold 5/5 | acc=0.93365 | running_mean=0.93487 | time=12.72s
       GWO KNN: init 5/10 | last=0.93487 | best=0.94598
          fold 1/5 | acc=0.93406 | running_mean=0.93406 | time=12.41s
          fold 2/5 | acc=0.93354 | running_mean=0.93380 | time=13.90s
          fold 3/5 | acc=0.93458 | running_mean=0.93406 | time=12.80s
          fold 4/5 | acc=0.93385 | running_mean=0.93401 | time=12.19s
          fold 5/5 | acc=0.93219 | running_mean=0.93365 | time=10.28s
       GWO KNN: init 6/10 | last=0.93365 | best=0.94598
          fold 1/5 | acc=0.94156 | running_mean=0.94156 | time=5.92s
          fold 2/5 | acc=0.94021 | running_mean=0.94089 | time=6.10s
          fold 3/5 | acc=0.94052 | running_mean=0.94076 | time=5.84s
          fold 4/5 | acc=0.93885 | running_mean=0.94029 | time=7.39s
          fold 5/5 | acc=0.93927 | running_mean=0.94008 | time=6.24s
       GWO KNN: init 7/10 | last=0.94008 | best=0.94598
          fold 1/5 | acc=0.94594 | running_mean=0.94594 | time=3.92s
          fold 2/5 | acc=0.94542 | running_mean=0.94568 | time=3.23s
          fold 3/5 | acc=0.94531 | running_mean=0.94556 | time=3.71s
          fold 4/5 | acc=0.94646 | running_mean=0.94578 | time=3.77s
          fold 5/5 | acc=0.94625 | running_mean=0.94588 | time=4.86s
       GWO KNN: init 8/10 | last=0.94588 | best=0.94598
          fold 1/5 | acc=0.94594 | running_mean=0.94594 | time=4.82s
          fold 2/5 | acc=0.94208 | running_mean=0.94401 | time=4.54s
          fold 3/5 | acc=0.94458 | running_mean=0.94420 | time=5.34s
          fold 4/5 | acc=0.94354 | running_mean=0.94404 | time=5.12s
          fold 5/5 | acc=0.94135 | running_mean=0.94350 | time=5.01s
       GWO KNN: init 9/10 | last=0.94350 | best=0.94598
          fold 1/5 | acc=0.93500 | running_mean=0.93500 | time=1.74s
          fold 2/5 | acc=0.93490 | running_mean=0.93495 | time=1.74s
          fold 3/5 | acc=0.93719 | running_mean=0.93569 | time=1.85s
          fold 4/5 | acc=0.93604 | running_mean=0.93578 | time=2.18s
          fold 5/5 | acc=0.93490 | running_mean=0.93560 | time=2.38s
       GWO KNN: init 10/10 | last=0.93560 | best=0.94598
       GWO KNN: init done → α=0.94598 β=0.94588 δ=0.94350
          fold 1/5 | acc=0.93542 | running_mean=0.93542 | time=14.29s
          fold 2/5 | acc=0.93344 | running_mean=0.93443 | time=10.41s
          fold 3/5 | acc=0.93417 | running_mean=0.93434 | time=10.76s
          fold 4/5 | acc=0.93385 | running_mean=0.93422 | time=11.72s
          fold 5/5 | acc=0.93250 | running_mean=0.93388 | time=10.28s
       GWO KNN: 11/50 | iter=1/4 | last=0.93388 | best=0.94598
          fold 1/5 | acc=0.92917 | running_mean=0.92917 | time=5.55s
          fold 2/5 | acc=0.93146 | running_mean=0.93031 | time=4.73s
          fold 3/5 | acc=0.93333 | running_mean=0.93132 | time=5.78s
          fold 4/5 | acc=0.93208 | running_mean=0.93151 | time=6.22s
          fold 5/5 | acc=0.93260 | running_mean=0.93173 | time=4.42s
       GWO KNN: 12/50 | iter=1/4 | last=0.93173 | best=0.94598
          fold 1/5 | acc=0.93958 | running_mean=0.93958 | time=3.41s
          fold 2/5 | acc=0.94104 | running_mean=0.94031 | time=3.47s
          fold 3/5 | acc=0.93865 | running_mean=0.93976 | time=4.16s
          fold 4/5 | acc=0.94052 | running_mean=0.93995 | time=4.72s
          fold 5/5 | acc=0.94188 | running_mean=0.94033 | time=6.64s
       GWO KNN: 13/50 | iter=1/4 | last=0.94033 | best=0.94598
          fold 1/5 | acc=0.94615 | running_mean=0.94615 | time=7.37s
          fold 2/5 | acc=0.94531 | running_mean=0.94573 | time=6.54s
          fold 3/5 | acc=0.94656 | running_mean=0.94601 | time=5.83s
          fold 4/5 | acc=0.94552 | running_mean=0.94589 | time=5.49s
          fold 5/5 | acc=0.94635 | running_mean=0.94598 | time=5.78s
       GWO KNN: 14/50 | iter=1/4 | last=0.94598 | best=0.94598
          fold 1/5 | acc=0.93583 | running_mean=0.93583 | time=8.20s
          fold 2/5 | acc=0.93490 | running_mean=0.93536 | time=8.11s
          fold 3/5 | acc=0.93583 | running_mean=0.93552 | time=9.10s
          fold 4/5 | acc=0.93417 | running_mean=0.93518 | time=9.22s
          fold 5/5 | acc=0.93365 | running_mean=0.93487 | time=10.26s
       GWO KNN: 15/50 | iter=1/4 | last=0.93487 | best=0.94598
          fold 1/5 | acc=0.93406 | running_mean=0.93406 | time=23.79s
          fold 2/5 | acc=0.93354 | running_mean=0.93380 | time=17.83s
          fold 3/5 | acc=0.93458 | running_mean=0.93406 | time=15.85s
          fold 4/5 | acc=0.93385 | running_mean=0.93401 | time=12.35s
          fold 5/5 | acc=0.93219 | running_mean=0.93365 | time=10.05s
       GWO KNN: 16/50 | iter=1/4 | last=0.93365 | best=0.94598
          fold 1/5 | acc=0.94156 | running_mean=0.94156 | time=6.69s
          fold 2/5 | acc=0.94021 | running_mean=0.94089 | time=9.78s
          fold 3/5 | acc=0.94052 | running_mean=0.94076 | time=9.05s
          fold 4/5 | acc=0.93885 | running_mean=0.94029 | time=6.98s
          fold 5/5 | acc=0.93927 | running_mean=0.94008 | time=11.65s
       GWO KNN: 17/50 | iter=1/4 | last=0.94008 | best=0.94598
          fold 1/5 | acc=0.94594 | running_mean=0.94594 | time=8.22s
          fold 2/5 | acc=0.94542 | running_mean=0.94568 | time=6.96s
          fold 3/5 | acc=0.94531 | running_mean=0.94556 | time=5.48s
          fold 4/5 | acc=0.94646 | running_mean=0.94578 | time=5.59s
          fold 5/5 | acc=0.94625 | running_mean=0.94588 | time=6.24s
       GWO KNN: 18/50 | iter=1/4 | last=0.94588 | best=0.94598
          fold 1/5 | acc=0.94594 | running_mean=0.94594 | time=8.17s
          fold 2/5 | acc=0.94208 | running_mean=0.94401 | time=7.38s
          fold 3/5 | acc=0.94458 | running_mean=0.94420 | time=7.59s
          fold 4/5 | acc=0.94354 | running_mean=0.94404 | time=7.36s
          fold 5/5 | acc=0.94135 | running_mean=0.94350 | time=7.18s
       GWO KNN: 19/50 | iter=1/4 | last=0.94350 | best=0.94598
          fold 1/5 | acc=0.93500 | running_mean=0.93500 | time=2.67s
          fold 2/5 | acc=0.93490 | running_mean=0.93495 | time=2.81s
          fold 3/5 | acc=0.93719 | running_mean=0.93569 | time=2.58s
          fold 4/5 | acc=0.93604 | running_mean=0.93578 | time=2.60s
          fold 5/5 | acc=0.93490 | running_mean=0.93560 | time=3.20s
       GWO KNN: 20/50 | iter=1/4 | last=0.93560 | best=0.94598
       GWO KNN: iter 1/4 done → α=0.94598 β=0.94598 δ=0.94588
          fold 1/5 | acc=0.94833 | running_mean=0.94833 | time=9.80s
          fold 2/5 | acc=0.94750 | running_mean=0.94792 | time=7.23s
          fold 3/5 | acc=0.94792 | running_mean=0.94792 | time=7.18s
          fold 4/5 | acc=0.94448 | running_mean=0.94706 | time=8.01s
          fold 5/5 | acc=0.94635 | running_mean=0.94692 | time=8.64s
       GWO KNN: 21/50 | iter=2/4 | last=0.94692 | best=0.94598
          fold 1/5 | acc=0.94958 | running_mean=0.94958 | time=5.44s
          fold 2/5 | acc=0.94635 | running_mean=0.94797 | time=4.27s
          fold 3/5 | acc=0.94969 | running_mean=0.94854 | time=5.12s
          fold 4/5 | acc=0.94771 | running_mean=0.94833 | time=4.08s
          fold 5/5 | acc=0.94719 | running_mean=0.94810 | time=4.22s
       GWO KNN: 22/50 | iter=2/4 | last=0.94810 | best=0.94598
          fold 1/5 | acc=0.94656 | running_mean=0.94656 | time=5.98s
          fold 2/5 | acc=0.94458 | running_mean=0.94557 | time=6.46s
          fold 3/5 | acc=0.94646 | running_mean=0.94587 | time=5.19s
          fold 4/5 | acc=0.94333 | running_mean=0.94523 | time=7.13s
          fold 5/5 | acc=0.94344 | running_mean=0.94488 | time=5.74s
       GWO KNN: 23/50 | iter=2/4 | last=0.94488 | best=0.94598
          fold 1/5 | acc=0.94240 | running_mean=0.94240 | time=2.22s
          fold 2/5 | acc=0.94167 | running_mean=0.94203 | time=2.33s
          fold 3/5 | acc=0.94094 | running_mean=0.94167 | time=2.45s
          fold 4/5 | acc=0.93958 | running_mean=0.94115 | time=2.31s
          fold 5/5 | acc=0.94146 | running_mean=0.94121 | time=2.48s
       GWO KNN: 24/50 | iter=2/4 | last=0.94121 | best=0.94598
          fold 1/5 | acc=0.94615 | running_mean=0.94615 | time=4.73s
          fold 2/5 | acc=0.94531 | running_mean=0.94573 | time=6.32s
          fold 3/5 | acc=0.94656 | running_mean=0.94601 | time=8.09s
          fold 4/5 | acc=0.94552 | running_mean=0.94589 | time=5.07s
          fold 5/5 | acc=0.94635 | running_mean=0.94598 | time=4.76s
       GWO KNN: 25/50 | iter=2/4 | last=0.94598 | best=0.94598
          fold 1/5 | acc=0.93396 | running_mean=0.93396 | time=10.43s
          fold 2/5 | acc=0.93521 | running_mean=0.93458 | time=11.63s
          fold 3/5 | acc=0.93437 | running_mean=0.93451 | time=11.12s
          fold 4/5 | acc=0.93458 | running_mean=0.93453 | time=11.19s
          fold 5/5 | acc=0.93302 | running_mean=0.93423 | time=12.80s
       GWO KNN: 26/50 | iter=2/4 | last=0.93423 | best=0.94598
          fold 1/5 | acc=0.93958 | running_mean=0.93958 | time=4.30s
          fold 2/5 | acc=0.94104 | running_mean=0.94031 | time=4.38s
          fold 3/5 | acc=0.93865 | running_mean=0.93976 | time=6.84s
          fold 4/5 | acc=0.94052 | running_mean=0.93995 | time=10.54s
          fold 5/5 | acc=0.94188 | running_mean=0.94033 | time=8.81s
       GWO KNN: 27/50 | iter=2/4 | last=0.94033 | best=0.94598
          fold 1/5 | acc=0.93927 | running_mean=0.93927 | time=16.57s
          fold 2/5 | acc=0.93969 | running_mean=0.93948 | time=12.32s
          fold 3/5 | acc=0.93937 | running_mean=0.93944 | time=16.44s
          fold 4/5 | acc=0.93844 | running_mean=0.93919 | time=19.14s
          fold 5/5 | acc=0.93812 | running_mean=0.93898 | time=17.68s
       GWO KNN: 28/50 | iter=2/4 | last=0.93898 | best=0.94598
          fold 1/5 | acc=0.93719 | running_mean=0.93719 | time=6.90s
          fold 2/5 | acc=0.93760 | running_mean=0.93740 | time=5.47s
          fold 3/5 | acc=0.93781 | running_mean=0.93753 | time=6.59s
          fold 4/5 | acc=0.93937 | running_mean=0.93799 | time=8.75s
          fold 5/5 | acc=0.93833 | running_mean=0.93806 | time=11.84s
       GWO KNN: 29/50 | iter=2/4 | last=0.93806 | best=0.94598
          fold 1/5 | acc=0.94833 | running_mean=0.94833 | time=9.19s
          fold 2/5 | acc=0.94750 | running_mean=0.94792 | time=7.25s
          fold 3/5 | acc=0.94792 | running_mean=0.94792 | time=7.23s
          fold 4/5 | acc=0.94448 | running_mean=0.94706 | time=6.21s
          fold 5/5 | acc=0.94635 | running_mean=0.94692 | time=4.55s
       GWO KNN: 30/50 | iter=2/4 | last=0.94692 | best=0.94598
       GWO KNN: iter 2/4 done → α=0.94810 β=0.94692 δ=0.94692
          fold 1/5 | acc=0.94885 | running_mean=0.94885 | time=4.04s
          fold 2/5 | acc=0.94708 | running_mean=0.94797 | time=4.36s
          fold 3/5 | acc=0.94917 | running_mean=0.94837 | time=3.99s
          fold 4/5 | acc=0.94750 | running_mean=0.94815 | time=4.14s
          fold 5/5 | acc=0.94740 | running_mean=0.94800 | time=4.03s
       GWO KNN: 31/50 | iter=3/4 | last=0.94800 | best=0.94810
          fold 1/5 | acc=0.94750 | running_mean=0.94750 | time=3.73s
          fold 2/5 | acc=0.94656 | running_mean=0.94703 | time=3.50s
          fold 3/5 | acc=0.94656 | running_mean=0.94688 | time=3.45s
          fold 4/5 | acc=0.94750 | running_mean=0.94703 | time=3.54s
          fold 5/5 | acc=0.94646 | running_mean=0.94692 | time=4.10s
       GWO KNN: 32/50 | iter=3/4 | last=0.94692 | best=0.94810
          fold 1/5 | acc=0.94708 | running_mean=0.94708 | time=4.74s
          fold 2/5 | acc=0.94719 | running_mean=0.94714 | time=5.48s
          fold 3/5 | acc=0.94708 | running_mean=0.94712 | time=4.50s
          fold 4/5 | acc=0.94469 | running_mean=0.94651 | time=4.37s
          fold 5/5 | acc=0.94521 | running_mean=0.94625 | time=4.72s
       GWO KNN: 33/50 | iter=3/4 | last=0.94625 | best=0.94810
          fold 1/5 | acc=0.94781 | running_mean=0.94781 | time=4.59s
          fold 2/5 | acc=0.94812 | running_mean=0.94797 | time=4.23s
          fold 3/5 | acc=0.94885 | running_mean=0.94826 | time=4.29s
          fold 4/5 | acc=0.94500 | running_mean=0.94745 | time=4.26s
          fold 5/5 | acc=0.94667 | running_mean=0.94729 | time=4.43s
       GWO KNN: 34/50 | iter=3/4 | last=0.94729 | best=0.94810
          fold 1/5 | acc=0.94885 | running_mean=0.94885 | time=4.34s
          fold 2/5 | acc=0.94708 | running_mean=0.94797 | time=4.24s
          fold 3/5 | acc=0.94917 | running_mean=0.94837 | time=4.07s
          fold 4/5 | acc=0.94750 | running_mean=0.94815 | time=3.85s
          fold 5/5 | acc=0.94740 | running_mean=0.94800 | time=3.87s
       GWO KNN: 35/50 | iter=3/4 | last=0.94800 | best=0.94810
          fold 1/5 | acc=0.93969 | running_mean=0.93969 | time=5.28s
          fold 2/5 | acc=0.93990 | running_mean=0.93979 | time=4.98s
          fold 3/5 | acc=0.94125 | running_mean=0.94028 | time=4.92s
          fold 4/5 | acc=0.94031 | running_mean=0.94029 | time=5.13s
          fold 5/5 | acc=0.94021 | running_mean=0.94027 | time=5.26s
       GWO KNN: 36/50 | iter=3/4 | last=0.94027 | best=0.94810
          fold 1/5 | acc=0.94927 | running_mean=0.94927 | time=4.02s
          fold 2/5 | acc=0.94719 | running_mean=0.94823 | time=4.34s
          fold 3/5 | acc=0.94958 | running_mean=0.94868 | time=4.38s
          fold 4/5 | acc=0.94635 | running_mean=0.94810 | time=4.23s
          fold 5/5 | acc=0.94635 | running_mean=0.94775 | time=4.15s
       GWO KNN: 37/50 | iter=3/4 | last=0.94775 | best=0.94810
          fold 1/5 | acc=0.94781 | running_mean=0.94781 | time=4.18s
          fold 2/5 | acc=0.94812 | running_mean=0.94797 | time=4.23s
          fold 3/5 | acc=0.94885 | running_mean=0.94826 | time=4.22s
          fold 4/5 | acc=0.94500 | running_mean=0.94745 | time=4.14s
          fold 5/5 | acc=0.94667 | running_mean=0.94729 | time=4.39s
       GWO KNN: 38/50 | iter=3/4 | last=0.94729 | best=0.94810
          fold 1/5 | acc=0.94865 | running_mean=0.94865 | time=4.12s
          fold 2/5 | acc=0.94708 | running_mean=0.94786 | time=4.19s
          fold 3/5 | acc=0.94844 | running_mean=0.94806 | time=4.28s
          fold 4/5 | acc=0.94406 | running_mean=0.94706 | time=4.61s
          fold 5/5 | acc=0.94646 | running_mean=0.94694 | time=4.18s
       GWO KNN: 39/50 | iter=3/4 | last=0.94694 | best=0.94810
          fold 1/5 | acc=0.94812 | running_mean=0.94812 | time=4.37s
          fold 2/5 | acc=0.94625 | running_mean=0.94719 | time=4.22s
          fold 3/5 | acc=0.94823 | running_mean=0.94753 | time=4.43s
          fold 4/5 | acc=0.94427 | running_mean=0.94672 | time=4.35s
          fold 5/5 | acc=0.94542 | running_mean=0.94646 | time=4.66s
       GWO KNN: 40/50 | iter=3/4 | last=0.94646 | best=0.94810
       GWO KNN: iter 3/4 done → α=0.94810 β=0.94800 δ=0.94800
          fold 1/5 | acc=0.94802 | running_mean=0.94802 | time=3.76s
          fold 2/5 | acc=0.94698 | running_mean=0.94750 | time=3.76s
          fold 3/5 | acc=0.94990 | running_mean=0.94830 | time=4.19s
          fold 4/5 | acc=0.94771 | running_mean=0.94815 | time=3.91s
          fold 5/5 | acc=0.94719 | running_mean=0.94796 | time=4.51s
       GWO KNN: 41/50 | iter=4/4 | last=0.94796 | best=0.94810
          fold 1/5 | acc=0.94781 | running_mean=0.94781 | time=4.11s
          fold 2/5 | acc=0.94812 | running_mean=0.94797 | time=4.14s
          fold 3/5 | acc=0.94885 | running_mean=0.94826 | time=4.60s
          fold 4/5 | acc=0.94500 | running_mean=0.94745 | time=4.16s
          fold 5/5 | acc=0.94667 | running_mean=0.94729 | time=4.32s
       GWO KNN: 42/50 | iter=4/4 | last=0.94729 | best=0.94810
          fold 1/5 | acc=0.94865 | running_mean=0.94865 | time=3.55s
          fold 2/5 | acc=0.94698 | running_mean=0.94781 | time=3.69s
          fold 3/5 | acc=0.94760 | running_mean=0.94774 | time=3.72s
          fold 4/5 | acc=0.94688 | running_mean=0.94753 | time=3.85s
          fold 5/5 | acc=0.94781 | running_mean=0.94758 | time=3.58s
       GWO KNN: 43/50 | iter=4/4 | last=0.94758 | best=0.94810
          fold 1/5 | acc=0.94958 | running_mean=0.94958 | time=3.95s
          fold 2/5 | acc=0.94635 | running_mean=0.94797 | time=3.88s
          fold 3/5 | acc=0.94969 | running_mean=0.94854 | time=4.37s
          fold 4/5 | acc=0.94771 | running_mean=0.94833 | time=4.20s
          fold 5/5 | acc=0.94719 | running_mean=0.94810 | time=4.27s
       GWO KNN: 44/50 | iter=4/4 | last=0.94810 | best=0.94810
          fold 1/5 | acc=0.94885 | running_mean=0.94885 | time=4.17s
          fold 2/5 | acc=0.94708 | running_mean=0.94797 | time=4.00s
          fold 3/5 | acc=0.94917 | running_mean=0.94837 | time=4.44s
          fold 4/5 | acc=0.94750 | running_mean=0.94815 | time=3.97s
          fold 5/5 | acc=0.94740 | running_mean=0.94800 | time=4.05s
       GWO KNN: 45/50 | iter=4/4 | last=0.94800 | best=0.94810
          fold 1/5 | acc=0.94865 | running_mean=0.94865 | time=3.94s
          fold 2/5 | acc=0.94698 | running_mean=0.94781 | time=3.65s
          fold 3/5 | acc=0.94760 | running_mean=0.94774 | time=3.73s
          fold 4/5 | acc=0.94688 | running_mean=0.94753 | time=3.60s
          fold 5/5 | acc=0.94781 | running_mean=0.94758 | time=3.70s
       GWO KNN: 46/50 | iter=4/4 | last=0.94758 | best=0.94810
          fold 1/5 | acc=0.94948 | running_mean=0.94948 | time=3.91s
          fold 2/5 | acc=0.94635 | running_mean=0.94792 | time=3.72s
          fold 3/5 | acc=0.95021 | running_mean=0.94868 | time=3.88s
          fold 4/5 | acc=0.94708 | running_mean=0.94828 | time=4.04s
          fold 5/5 | acc=0.94792 | running_mean=0.94821 | time=4.11s
       GWO KNN: 47/50 | iter=4/4 | last=0.94821 | best=0.94810
          fold 1/5 | acc=0.94802 | running_mean=0.94802 | time=3.76s
          fold 2/5 | acc=0.94698 | running_mean=0.94750 | time=3.89s
          fold 3/5 | acc=0.94990 | running_mean=0.94830 | time=4.08s
          fold 4/5 | acc=0.94771 | running_mean=0.94815 | time=3.84s

{'status': 'completed',
 'best':   Model Optimal_Scaler  Best_CV_Mean  Best_Iteration  n_neighbors   weights     metric  p
 0   KNN            Raw      0.948208              47           16  distance  manhattan  4,
 'history':    Model  Iteration   CV_Mean  Best_Score_So_Far  Iteration_Runtime_Sec
 0    KNN          1  0.933875           0.933875              52.896784
 1    KNN          2  0.931729           0.933875              47.009800
 2    KNN          3  0.940333           0.940333              34.480783
 3    KNN          4  0.945979           0.945979              32.403624
 4    KNN          5  0.934875           0.945979              55.531824
 5    KNN          6  0.933646           0.945979              61.592063
 6    KNN          7  0.940083           0.945979              31.499503
 7    KNN          8  0.945875           0.945979              19.506548
 8    KNN          9  0.943500           0.945979              24.848678
 9    KNN         10  0.935604           0.945979               9.910044
 10   KNN         11  0.933875           0.945979              57.484123
 11   KNN         12  0.931729           0.945979              26.717545
 12   KNN         13  0.940333           0.945979              22.407237
 13   KNN         14  0.945979           0.945979              31.026784
 14   KNN         15  0.934875           0.945979              44.908232
 15   KNN         16  0.933646           0.945979              79.887552
 16   KNN         17  0.940083           0.945979              44.168909
 17   KNN         18  0.945875           0.945979              32.508838
 18   KNN         19  0.943500           0.945979              37.691152
 19   KNN         20  0.935604           0.945979              13.880095
 20   KNN         21  0.946917           0.948104              40.889605
 21   KNN         22  0.948104           0.948104              23.140934
 22   KNN         23  0.944875           0.948104              30.521142
 23   KNN         24  0.941208           0.948104              11.801562
 24   KNN         25  0.945979           0.948104              28.989477
 25   KNN         26  0.934229           0.948104              57.177536
 26   KNN         27  0.940333           0.948104              34.898941
 27   KNN         28  0.938979           0.948104              82.169724
 28   KNN         29  0.938063           0.948104              39.592424
 29   KNN         30  0.946917           0.948104              34.452918
 30   KNN         31  0.948000           0.948104              20.570773
 31   KNN         32  0.946917           0.948104              18.334482
 32   KNN         33  0.946250           0.948104              23.816157
 33   KNN         34  0.947292           0.948104              21.802291
 34   KNN         35  0.948000           0.948104              20.390191
 35   KNN         36  0.940271           0.948104              25.589704
 36   KNN         37  0.947750           0.948104              21.133257
 37   KNN         38  0.947292           0.948104              21.169124
 38   KNN         39  0.946937           0.948104              21.401892
 39   KNN         40  0.946458           0.948104              22.045806
 40   KNN         41  0.947958           0.948208              20.148492
 41   KNN         42  0.947292           0.948208              21.341600
 42   KNN         43  0.947583           0.948208              18.404360
 43   KNN         44  0.948104           0.948208              20.682914
 44   KNN         45  0.948000           0.948208              20.655412
 45   KNN         46  0.947583           0.948208              18.628515
 46   KNN         47  0.948208           0.948208              19.673846
 47   KNN         48  0.947958           0.948208              19.225507
 48   KNN         49  0.948104           0.948208              20.330100
 49   KNN         50  0.947292           0.948208              21.557208,
 'summary':   Method Model Optimal_Scaler      Split  Accuracy  Precision    Recall        F1     Kappa       MCC       AUC   LogLoss  Accuracy_CI_Lower  Accuracy_CI_Upper  Precision_CI_Lower  Precision_CI_Upper  Recall_CI_Lower  Recall_CI_Upper  F1_CI_Lower  F1_CI_Upper  AUC_CI_Lower  AUC_CI_Upper  LogLoss_CI_Lower  LogLoss_CI_Upper  Kappa_CI_Lower  Kappa_CI_Upper  MCC_CI_Lower  MCC_CI_Upper
 0    GWO   KNN            Raw  Train_OOF  0.948208   0.953371  0.966072  0.959680  0.887303  0.887455  0.989430  0.167388           0.946104           0.950188            0.950824            0.955783         0.964079         0.967995     0.958011     0.961247      0.988786      0.990050          0.163262          0.171852        0.882711        0.891721      0.882896      0.891875
 1    GWO   KNN            Raw       Test  0.954333   0.957872  0.971134  0.964457  0.900611  0.900777  0.991636  0.153561           0.950581           0.958083            0.953541            0.962289         0.967196         0.974762     0.961399     0.967381      0.990543      0.992691          0.147843          0.160461        0.892713        0.908813      0.892820      0.908976,
 'timing':   Model  GWO_Search_Sec  GWO_Evaluation_Sec  GWO_Total_Sec  Best_CV_Mean
 0   KNN     1560.956507          148.478211     1709.73015      0.948208}

In [51]:
run_gwo_model("LinearSVC")

LinearSVC  | Scaler: Power      | Available RAM: 6.53 GB | Kernel RSS: 209.4 MB
       Memory cleanup -> gc_collected=67, available=6.53 GB, used=58.5%, rss=209.4 MB
       Running 50 evaluations with n_jobs_cv=1, n_jobs_opt=8
       GWO progress for LinearSVC: 0/50 evaluations
       GWO LinearSVC: initializing population (10 wolves)...
          fold 1/5 | acc=0.89656 | running_mean=0.89656 | time=1.16s
          fold 2/5 | acc=0.89667 | running_mean=0.89661 | time=1.07s
          fold 3/5 | acc=0.89312 | running_mean=0.89545 | time=1.04s
          fold 4/5 | acc=0.89687 | running_mean=0.89581 | time=0.95s
          fold 5/5 | acc=0.90083 | running_mean=0.89681 | time=0.93s
       GWO LinearSVC: init 1/10 | last=0.89681 | best=0.89681
          fold 1/5 | acc=0.89677 | running_mean=0.89677 | time=0.70s
          fold 2/5 | acc=0.89583 | running_mean=0.89630 | time=0.71s
          fold 3/5 | acc=0.89365 | running_mean=0.89542 | time=0.69s
          fold 4/5 | acc=0.89771 | running_mean=0.89599 | time=0.63s
          fold 5/5 | acc=0.90125 | running_mean=0.89704 | time=0.70s
       GWO LinearSVC: init 2/10 | last=0.89704 | best=0.89704
          fold 1/5 | acc=0.86385 | running_mean=0.86385 | time=0.56s
          fold 2/5 | acc=0.86833 | running_mean=0.86609 | time=0.60s
          fold 3/5 | acc=0.86354 | running_mean=0.86524 | time=0.54s
          fold 4/5 | acc=0.86594 | running_mean=0.86542 | time=0.62s
          fold 5/5 | acc=0.86448 | running_mean=0.86523 | time=0.57s
       GWO LinearSVC: init 3/10 | last=0.86523 | best=0.89704
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=0.80s
          fold 2/5 | acc=0.89573 | running_mean=0.89630 | time=0.71s
          fold 3/5 | acc=0.89354 | running_mean=0.89538 | time=0.66s
          fold 4/5 | acc=0.89760 | running_mean=0.89594 | time=0.65s
          fold 5/5 | acc=0.90125 | running_mean=0.89700 | time=0.66s
       GWO LinearSVC: init 4/10 | last=0.89700 | best=0.89704
          fold 1/5 | acc=0.85198 | running_mean=0.85198 | time=0.55s
          fold 2/5 | acc=0.85719 | running_mean=0.85458 | time=0.53s
          fold 3/5 | acc=0.85219 | running_mean=0.85378 | time=0.50s
          fold 4/5 | acc=0.85594 | running_mean=0.85432 | time=0.55s
          fold 5/5 | acc=0.85500 | running_mean=0.85446 | time=0.53s
       GWO LinearSVC: init 5/10 | last=0.85446 | best=0.89704
          fold 1/5 | acc=0.89125 | running_mean=0.89125 | time=0.64s
          fold 2/5 | acc=0.89500 | running_mean=0.89312 | time=0.61s
          fold 3/5 | acc=0.88760 | running_mean=0.89128 | time=0.67s
          fold 4/5 | acc=0.89104 | running_mean=0.89122 | time=0.58s
          fold 5/5 | acc=0.89333 | running_mean=0.89165 | time=0.65s
       GWO LinearSVC: init 6/10 | last=0.89165 | best=0.89704
          fold 1/5 | acc=0.89656 | running_mean=0.89656 | time=0.66s
          fold 2/5 | acc=0.89604 | running_mean=0.89630 | time=0.71s
          fold 3/5 | acc=0.89333 | running_mean=0.89531 | time=0.62s
          fold 4/5 | acc=0.89760 | running_mean=0.89589 | time=0.71s
          fold 5/5 | acc=0.90115 | running_mean=0.89694 | time=0.65s
       GWO LinearSVC: init 7/10 | last=0.89694 | best=0.89704
          fold 1/5 | acc=0.88813 | running_mean=0.88813 | time=0.60s
          fold 2/5 | acc=0.89302 | running_mean=0.89057 | time=0.52s
          fold 3/5 | acc=0.88542 | running_mean=0.88885 | time=0.65s
          fold 4/5 | acc=0.88990 | running_mean=0.88911 | time=0.51s
          fold 5/5 | acc=0.88979 | running_mean=0.88925 | time=0.58s
       GWO LinearSVC: init 8/10 | last=0.88925 | best=0.89704
          fold 1/5 | acc=0.89167 | running_mean=0.89167 | time=0.56s
          fold 2/5 | acc=0.89573 | running_mean=0.89370 | time=0.58s
          fold 3/5 | acc=0.88958 | running_mean=0.89233 | time=0.55s
          fold 4/5 | acc=0.89396 | running_mean=0.89273 | time=0.51s
          fold 5/5 | acc=0.89844 | running_mean=0.89388 | time=0.59s
       GWO LinearSVC: init 9/10 | last=0.89388 | best=0.89704
          fold 1/5 | acc=0.89677 | running_mean=0.89677 | time=0.63s
          fold 2/5 | acc=0.89594 | running_mean=0.89635 | time=0.70s
          fold 3/5 | acc=0.89344 | running_mean=0.89538 | time=0.65s
          fold 4/5 | acc=0.89760 | running_mean=0.89594 | time=0.66s
          fold 5/5 | acc=0.90125 | running_mean=0.89700 | time=0.73s
       GWO LinearSVC: init 10/10 | last=0.89700 | best=0.89704
       GWO LinearSVC: init done → α=0.89704 β=0.89700 δ=0.89700
          fold 1/5 | acc=0.89656 | running_mean=0.89656 | time=0.99s
          fold 2/5 | acc=0.89667 | running_mean=0.89661 | time=1.15s
          fold 3/5 | acc=0.89312 | running_mean=0.89545 | time=1.00s
          fold 4/5 | acc=0.89687 | running_mean=0.89581 | time=1.13s
          fold 5/5 | acc=0.90083 | running_mean=0.89681 | time=1.27s
       GWO LinearSVC: 11/50 | iter=1/4 | last=0.89681 | best=0.89704
          fold 1/5 | acc=0.89677 | running_mean=0.89677 | time=0.66s
          fold 2/5 | acc=0.89583 | running_mean=0.89630 | time=0.75s
          fold 3/5 | acc=0.89365 | running_mean=0.89542 | time=0.70s
          fold 4/5 | acc=0.89771 | running_mean=0.89599 | time=0.66s
          fold 5/5 | acc=0.90125 | running_mean=0.89704 | time=0.80s
       GWO LinearSVC: 12/50 | iter=1/4 | last=0.89704 | best=0.89704
          fold 1/5 | acc=0.86385 | running_mean=0.86385 | time=0.57s
          fold 2/5 | acc=0.86833 | running_mean=0.86609 | time=0.66s
          fold 3/5 | acc=0.86354 | running_mean=0.86524 | time=0.55s
          fold 4/5 | acc=0.86594 | running_mean=0.86542 | time=0.59s
          fold 5/5 | acc=0.86448 | running_mean=0.86523 | time=0.56s
       GWO LinearSVC: 13/50 | iter=1/4 | last=0.86523 | best=0.89704
          fold 1/5 | acc=0.89687 | running_mean=0.89687 | time=0.70s
          fold 2/5 | acc=0.89573 | running_mean=0.89630 | time=0.62s
          fold 3/5 | acc=0.89354 | running_mean=0.89538 | time=0.68s
          fold 4/5 | acc=0.89760 | running_mean=0.89594 | time=0.61s
          fold 5/5 | acc=0.90125 | running_mean=0.89700 | time=0.70s
       GWO LinearSVC: 14/50 | iter=1/4 | last=0.89700 | best=0.89704
          fold 1/5 | acc=0.85198 | running_mean=0.85198 | time=0.56s
          fold 2/5 | acc=0.85719 | running_mean=0.85458 | time=0.55s
          fold 3/5 | acc=0.85219 | running_mean=0.85378 | time=0.51s
          fold 4/5 | acc=0.85594 | running_mean=0.85432 | time=0.50s
          fold 5/5 | acc=0.85500 | running_mean=0.85446 | time=0.58s
       GWO LinearSVC: 15/50 | iter=1/4 | last=0.85446 | best=0.89704
          fold 1/5 | acc=0.89125 | running_mean=0.89125 | time=0.63s
          fold 2/5 | acc=0.89500 | running_mean=0.89312 | time=0.68s
          fold 3/5 | acc=0.88760 | running_mean=0.89128 | time=0.60s
          fold 4/5 | acc=0.89104 | running_mean=0.89122 | time=0.64s
          fold 5/5 | acc=0.89333 | running_mean=0.89165 | time=0.60s
       GWO LinearSVC: 16/50 | iter=1/4 | last=0.89165 | best=0.89704
          fold 1/5 | acc=0.89656 | running_mean=0.89656 | time=0.68s
          fold 2/5 | acc=0.89604 | running_mean=0.89630 | time=0.63s
          fold 3/5 | acc=0.89333 | running_mean=0.89531 | time=0.66s
          fold 4/5 | acc=0.89760 | running_mean=0.89589 | time=0.68s
          fold 5/5 | acc=0.90115 | running_mean=0.89694 | time=0.70s
       GWO LinearSVC: 17/50 | iter=1/4 | last=0.89694 | best=0.89704
          fold 1/5 | acc=0.88813 | running_mean=0.88813 | time=0.62s
          fold 2/5 | acc=0.89302 | running_mean=0.89057 | time=0.56s
          fold 3/5 | acc=0.88542 | running_mean=0.88885 | time=0.62s
          fold 4/5 | acc=0.88990 | running_mean=0.88911 | time=0.55s
          fold 5/5 | acc=0.88979 | running_mean=0.88925 | time=0.53s
       GWO LinearSVC: 18/50 | iter=1/4 | last=0.88925 | best=0.89704
          fold 1/5 | acc=0.89167 | running_mean=0.89167 | time=0.60s
          fold 2/5 | acc=0.89573 | running_mean=0.89370 | time=0.53s
          fold 3/5 | acc=0.88958 | running_mean=0.89233 | time=0.59s
          fold 4/5 | acc=0.89396 | running_mean=0.89273 | time=0.53s
          fold 5/5 | acc=0.89844 | running_mean=0.89388 | time=0.62s
       GWO LinearSVC: 19/50 | iter=1/4 | last=0.89388 | best=0.89704
          fold 1/5 | acc=0.89677 | running_mean=0.89677 | time=0.62s
          fold 2/5 | acc=0.89594 | running_mean=0.89635 | time=0.71s
          fold 3/5 | acc=0.89344 | running_mean=0.89538 | time=0.63s
          fold 4/5 | acc=0.89760 | running_mean=0.89594 | time=0.64s
          fold 5/5 | acc=0.90125 | running_mean=0.89700 | time=0.63s
       GWO LinearSVC: 20/50 | iter=1/4 | last=0.89700 | best=0.89704
       GWO LinearSVC: iter 1/4 done → α=0.89704 β=0.89704 δ=0.89700
          fold 1/5 | acc=0.89667 | running_mean=0.89667 | time=0.76s
          fold 2/5 | acc=0.89604 | running_mean=0.89635 | time=0.84s
          fold 3/5 | acc=0.89344 | running_mean=0.89538 | time=0.81s
          fold 4/5 | acc=0.89792 | running_mean=0.89602 | time=0.84s
          fold 5/5 | acc=0.90146 | running_mean=0.89710 | time=0.81s
       GWO LinearSVC: 21/50 | iter=2/4 | last=0.89710 | best=0.89704
          fold 1/5 | acc=0.89667 | running_mean=0.89667 | time=0.87s
          fold 2/5 | acc=0.89594 | running_mean=0.89630 | time=0.99s
          fold 3/5 | acc=0.89365 | running_mean=0.89542 | time=0.90s
          fold 4/5 | acc=0.89760 | running_mean=0.89596 | time=0.80s
          fold 5/5 | acc=0.90125 | running_mean=0.89702 | time=0.78s
       GWO LinearSVC: 22/50 | iter=2/4 | last=0.89702 | best=0.89704
          fold 1/5 | acc=0.86927 | running_mean=0.86927 | time=0.60s
          fold 2/5 | acc=0.87490 | running_mean=0.87208 | time=0.64s
          fold 3/5 | acc=0.86958 | running_mean=0.87125 | time=0.57s
          fold 4/5 | acc=0.87385 | running_mean=0.87190 | time=0.62s
          fold 5/5 | acc=0.87021 | running_mean=0.87156 | time=0.58s
       GWO LinearSVC: 23/50 | iter=2/4 | last=0.87156 | best=0.89704
          fold 1/5 | acc=0.89677 | running_mean=0.89677 | time=0.70s
          fold 2/5 | acc=0.89573 | running_mean=0.89625 | time=0.64s
          fold 3/5 | acc=0.89354 | running_mean=0.89535 | time=0.69s
          fold 4/5 | acc=0.89760 | running_mean=0.89591 | time=0.64s
          fold 5/5 | acc=0.90125 | running_mean=0.89698 | time=0.68s
       GWO LinearSVC: 24/50 | iter=2/4 | last=0.89698 | best=0.89704
          fold 1/5 | acc=0.89667 | running_mean=0.89667 | time=0.65s
          fold 2/5 | acc=0.89594 | running_mean=0.89630 | time=0.68s
          fold 3/5 | acc=0.89365 | running_mean=0.89542 | time=0.62s
          fold 4/5 | acc=0.89760 | running_mean=0.89596 | time=0.63s
          fold 5/5 | acc=0.90125 | running_mean=0.89702 | time=0.69s
       GWO LinearSVC: 25/50 | iter=2/4 | last=0.89702 | best=0.89704
          fold 1/5 | acc=0.89667 | running_mean=0.89667 | time=0.65s
          fold 2/5 | acc=0.89594 | running_mean=0.89630 | time=0.69s
          fold 3/5 | acc=0.89365 | running_mean=0.89542 | time=0.62s
          fold 4/5 | acc=0.89760 | running_mean=0.89596 | time=0.69s
          fold 5/5 | acc=0.90125 | running_mean=0.89702 | time=0.66s
       GWO LinearSVC: 26/50 | iter=2/4 | last=0.89702 | best=0.89704
          fold 1/5 | acc=0.89677 | running_mean=0.89677 | time=0.72s
          fold 2/5 | acc=0.89573 | running_mean=0.89625 | time=0.68s
          fold 3/5 | acc=0.89354 | running_mean=0.89535 | time=0.64s
          fold 4/5 | acc=0.89760 | running_mean=0.89591 | time=0.65s
          fold 5/5 | acc=0.90125 | running_mean=0.89698 | time=0.69s
       GWO LinearSVC: 27/50 | iter=2/4 | last=0.89698 | best=0.89704
          fold 1/5 | acc=0.89667 | running_mean=0.89667 | time=0.63s
          fold 2/5 | acc=0.89594 | running_mean=0.89630 | time=0.70s
          fold 3/5 | acc=0.89365 | running_mean=0.89542 | time=0.69s
          fold 4/5 | acc=0.89760 | running_mean=0.89596 | time=0.63s
          fold 5/5 | acc=0.90125 | running_mean=0.89702 | time=0.70s
       GWO LinearSVC: 28/50 | iter=2/4 | last=0.89702 | best=0.89704
          fold 1/5 | acc=0.89656 | running_mean=0.89656 | time=0.83s
          fold 2/5 | acc=0.89667 | running_mean=0.89661 | time=0.86s
          fold 3/5 | acc=0.89302 | running_mean=0.89542 | time=0.88s
          fold 4/5 | acc=0.89708 | running_mean=0.89583 | time=1.08s
          fold 5/5 | acc=0.90115 | running_mean=0.89690 | time=0.87s
       GWO LinearSVC: 29/50 | iter=2/4 | last=0.89690 | best=0.89704
          fold 1/5 | acc=0.89667 | running_mean=0.89667 | time=0.81s
          fold 2/5 | acc=0.89563 | running_mean=0.89615 | time=0.76s
          fold 3/5 | acc=0.89365 | running_mean=0.89531 | time=0.65s
          fold 4/5 | acc=0.89771 | running_mean=0.89591 | time=0.68s
          fold 5/5 | acc=0.90125 | running_mean=0.89698 | time=0.65s
       GWO LinearSVC: 30/50 | iter=2/4 | last=0.89698 | best=0.89704
       GWO LinearSVC: iter 2/4 done → α=0.89710 β=0.89704 δ=0.89704
          fold 1/5 | acc=0.89677 | running_mean=0.89677 | time=0.69s
          fold 2/5 | acc=0.89583 | running_mean=0.89630 | time=0.63s
          fold 3/5 | acc=0.89365 | running_mean=0.89542 | time=0.70s
          fold 4/5 | acc=0.89760 | running_mean=0.89596 | time=0.62s
          fold 5/5 | acc=0.90125 | running_mean=0.89702 | time=0.69s
       GWO LinearSVC: 31/50 | iter=3/4 | last=0.89702 | best=0.89710
          fold 1/5 | acc=0.89677 | running_mean=0.89677 | time=6.53s
          fold 2/5 | acc=0.89583 | running_mean=0.89630 | time=6.94s
          fold 3/5 | acc=0.89198 | running_mean=0.89486 | time=6.44s
          fold 4/5 | acc=0.89740 | running_mean=0.89549 | time=6.51s
          fold 5/5 | acc=0.90073 | running_mean=0.89654 | time=6.87s
       GWO LinearSVC: 32/50 | iter=3/4 | last=0.89654 | best=0.89710
          fold 1/5 | acc=0.89719 | running_mean=0.89719 | time=1.47s
          fold 2/5 | acc=0.89687 | running_mean=0.89703 | time=1.72s
          fold 3/5 | acc=0.89292 | running_mean=0.89566 | time=1.53s
          fold 4/5 | acc=0.89719 | running_mean=0.89604 | time=1.48s
          fold 5/5 | acc=0.90146 | running_mean=0.89712 | time=1.51s
       GWO LinearSVC: 33/50 | iter=3/4 | last=0.89712 | best=0.89710
          fold 1/5 | acc=0.89635 | running_mean=0.89635 | time=0.89s
          fold 2/5 | acc=0.89687 | running_mean=0.89661 | time=0.87s
          fold 3/5 | acc=0.89333 | running_mean=0.89552 | time=0.93s
          fold 4/5 | acc=0.89698 | running_mean=0.89589 | time=0.82s
          fold 5/5 | acc=0.90104 | running_mean=0.89692 | time=0.84s
       GWO LinearSVC: 34/50 | iter=3/4 | last=0.89692 | best=0.89710
          fold 1/5 | acc=0.89667 | running_mean=0.89667 | time=0.67s
          fold 2/5 | acc=0.89594 | running_mean=0.89630 | time=0.71s
          fold 3/5 | acc=0.89365 | running_mean=0.89542 | time=0.66s
          fold 4/5 | acc=0.89760 | running_mean=0.89596 | time=0.63s
          fold 5/5 | acc=0.90125 | running_mean=0.89702 | time=0.70s
       GWO LinearSVC: 35/50 | iter=3/4 | last=0.89702 | best=0.89710
          fold 1/5 | acc=0.89677 | running_mean=0.89677 | time=7.07s
          fold 2/5 | acc=0.89583 | running_mean=0.89630 | time=6.55s
          fold 3/5 | acc=0.89198 | running_mean=0.89486 | time=6.68s
          fold 4/5 | acc=0.89740 | running_mean=0.89549 | time=6.76s
          fold 5/5 | acc=0.90073 | running_mean=0.89654 | time=7.95s
       GWO LinearSVC: 36/50 | iter=3/4 | last=0.89654 | best=0.89710
          fold 1/5 | acc=0.89667 | running_mean=0.89667 | time=0.89s
          fold 2/5 | acc=0.89594 | running_mean=0.89630 | time=0.98s
          fold 3/5 | acc=0.89365 | running_mean=0.89542 | time=0.83s
          fold 4/5 | acc=0.89760 | running_mean=0.89596 | time=0.73s
          fold 5/5 | acc=0.90125 | running_mean=0.89702 | time=0.83s
       GWO LinearSVC: 37/50 | iter=3/4 | last=0.89702 | best=0.89710
          fold 1/5 | acc=0.89573 | running_mean=0.89573 | time=0.83s
          fold 2/5 | acc=0.89573 | running_mean=0.89573 | time=0.82s
          fold 3/5 | acc=0.89302 | running_mean=0.89483 | time=0.83s
          fold 4/5 | acc=0.89740 | running_mean=0.89547 | time=0.77s
          fold 5/5 | acc=0.90083 | running_mean=0.89654 | time=0.81s
       GWO LinearSVC: 38/50 | iter=3/4 | last=0.89654 | best=0.89710
          fold 1/5 | acc=0.89667 | running_mean=0.89667 | time=0.91s
          fold 2/5 | acc=0.89594 | running_mean=0.89630 | time=0.90s
          fold 3/5 | acc=0.89344 | running_mean=0.89535 | time=0.79s
          fold 4/5 | acc=0.89781 | running_mean=0.89596 | time=0.87s
          fold 5/5 | acc=0.90156 | running_mean=0.89708 | time=0.90s
       GWO LinearSVC: 39/50 | iter=3/4 | last=0.89708 | best=0.89710
          fold 1/5 | acc=0.89573 | running_mean=0.89573 | time=0.91s
          fold 2/5 | acc=0.89563 | running_mean=0.89568 | time=0.96s
          fold 3/5 | acc=0.89302 | running_mean=0.89479 | time=0.77s
          fold 4/5 | acc=0.89729 | running_mean=0.89542 | time=0.68s
          fold 5/5 | acc=0.90083 | running_mean=0.89650 | time=0.78s
       GWO LinearSVC: 40/50 | iter=3/4 | last=0.89650 | best=0.89710
       GWO LinearSVC: iter 3/4 done → α=0.89712 β=0.89710 δ=0.89708
          fold 1/5 | acc=0.89677 | running_mean=0.89677 | time=0.68s
          fold 2/5 | acc=0.89594 | running_mean=0.89635 | time=0.75s
          fold 3/5 | acc=0.89365 | running_mean=0.89545 | time=0.68s
          fold 4/5 | acc=0.89760 | running_mean=0.89599 | time=0.72s
          fold 5/5 | acc=0.90125 | running_mean=0.89704 | time=0.80s
       GWO LinearSVC: 41/50 | iter=4/4 | last=0.89704 | best=0.89712
          fold 1/5 | acc=0.89667 | running_mean=0.89667 | time=0.74s
          fold 2/5 | acc=0.89583 | running_mean=0.89625 | time=0.77s
          fold 3/5 | acc=0.89365 | running_mean=0.89538 | time=0.68s
          fold 4/5 | acc=0.89760 | running_mean=0.89594 | time=0.78s
          fold 5/5 | acc=0.90125 | running_mean=0.89700 | time=0.73s
       GWO LinearSVC: 42/50 | iter=4/4 | last=0.89700 | best=0.89712
          fold 1/5 | acc=0.89667 | running_mean=0.89667 | time=0.70s
          fold 2/5 | acc=0.89615 | running_mean=0.89641 | time=0.77s
          fold 3/5 | acc=0.89333 | running_mean=0.89538 | time=0.65s
          fold 4/5 | acc=0.89760 | running_mean=0.89594 | time=0.75s
          fold 5/5 | acc=0.90115 | running_mean=0.89698 | time=0.78s
       GWO LinearSVC: 43/50 | iter=4/4 | last=0.89698 | best=0.89712
          fold 1/5 | acc=0.89438 | running_mean=0.89438 | time=1.05s
          fold 2/5 | acc=0.89542 | running_mean=0.89490 | time=1.00s
          fold 3/5 | acc=0.89250 | running_mean=0.89410 | time=0.92s
          fold 4/5 | acc=0.89667 | running_mean=0.89474 | time=0.96s
          fold 5/5 | acc=0.90063 | running_mean=0.89592 | time=0.96s
       GWO LinearSVC: 44/50 | iter=4/4 | last=0.89592 | best=0.89712
          fold 1/5 | acc=0.89677 | running_mean=0.89677 | time=0.96s
          fold 2/5 | acc=0.89594 | running_mean=0.89635 | time=0.88s
          fold 3/5 | acc=0.89365 | running_mean=0.89545 | time=0.77s
          fold 4/5 | acc=0.89760 | running_mean=0.89599 | time=0.88s
          fold 5/5 | acc=0.90125 | running_mean=0.89704 | time=0.79s
       GWO LinearSVC: 45/50 | iter=4/4 | last=0.89704 | best=0.89712
          fold 1/5 | acc=0.89615 | running_mean=0.89615 | time=0.85s
          fold 2/5 | acc=0.89594 | running_mean=0.89604 | time=0.93s
          fold 3/5 | acc=0.89333 | running_mean=0.89514 | time=0.83s
          fold 4/5 | acc=0.89750 | running_mean=0.89573 | time=0.93s
          fold 5/5 | acc=0.90104 | running_mean=0.89679 | time=1.15s
       GWO LinearSVC: 46/50 | iter=4/4 | last=0.89679 | best=0.89712
          fold 1/5 | acc=0.89708 | running_mean=0.89708 | time=2.33s
          fold 2/5 | acc=0.89698 | running_mean=0.89703 | time=1.83s
          fold 3/5 | acc=0.89312 | running_mean=0.89573 | time=1.62s
          fold 4/5 | acc=0.89667 | running_mean=0.89596 | time=1.81s
          fold 5/5 | acc=0.90115 | running_mean=0.89700 | time=1.66s
       GWO LinearSVC: 47/50 | iter=4/4 | last=0.89700 | best=0.89712

{'status': 'completed',
 'best':        Model Optimal_Scaler  Best_CV_Mean  Best_Iteration         C   loss  dual  max_iter  random_state
 0  LinearSVC          Power      0.897125              50  5.723709  hinge  auto      5000            42,
 'history':         Model  Iteration   CV_Mean  Best_Score_So_Far  Iteration_Runtime_Sec
 0   LinearSVC          1  0.896813           0.896813               5.177436
 1   LinearSVC          2  0.897042           0.897042               3.437735
 2   LinearSVC          3  0.865229           0.897042               2.908495
 3   LinearSVC          4  0.897000           0.897042               3.502862
 4   LinearSVC          5  0.854458           0.897042               2.679412
 5   LinearSVC          6  0.891646           0.897042               3.168312
 6   LinearSVC          7  0.896937           0.897042               3.352858
 7   LinearSVC          8  0.889250           0.897042               2.870456
 8   LinearSVC          9  0.893875           0.897042               2.813748
 9   LinearSVC         10  0.897000           0.897042               3.384375
 10  LinearSVC         11  0.896813           0.897042               5.561953
 11  LinearSVC         12  0.897042           0.897042               3.593702
 12  LinearSVC         13  0.865229           0.897042               2.945157
 13  LinearSVC         14  0.897000           0.897042               3.324392
 14  LinearSVC         15  0.854458           0.897042               2.713375
 15  LinearSVC         16  0.891646           0.897042               3.170326
 16  LinearSVC         17  0.896937           0.897042               3.364397
 17  LinearSVC         18  0.889250           0.897042               2.900272
 18  LinearSVC         19  0.893875           0.897042               2.884909
 19  LinearSVC         20  0.897000           0.897042               3.250356
 20  LinearSVC         21  0.897104           0.897104               4.084862
 21  LinearSVC         22  0.897021           0.897104               4.362614
 22  LinearSVC         23  0.871563           0.897104               3.025640
 23  LinearSVC         24  0.896979           0.897104               3.363688
 24  LinearSVC         25  0.897021           0.897104               3.287847
 25  LinearSVC         26  0.897021           0.897104               3.320191
 26  LinearSVC         27  0.896979           0.897104               3.390233
 27  LinearSVC         28  0.897021           0.897104               3.364102
 28  LinearSVC         29  0.896896           0.897104               4.541062
 29  LinearSVC         30  0.896979           0.897104               3.571020
 30  LinearSVC         31  0.897021           0.897125               3.350240
 31  LinearSVC         32  0.896542           0.897125              33.292885
 32  LinearSVC         33  0.897125           0.897125               7.714686
 33  LinearSVC         34  0.896917           0.897125               4.374227
 34  LinearSVC         35  0.897021           0.897125               3.383899
 35  LinearSVC         36  0.896542           0.897125              35.025990
 36  LinearSVC         37  0.897021           0.897125               4.273354
 37  LinearSVC         38  0.896542           0.897125               4.071558
 38  LinearSVC         39  0.897083           0.897125               4.396919
 39  LinearSVC         40  0.896500           0.897125               4.109281
 40  LinearSVC         41  0.897042           0.897125               3.642996
 41  LinearSVC         42  0.897000           0.897125               3.722743
 42  LinearSVC         43  0.896979           0.897125               3.674277
 43  LinearSVC         44  0.895917           0.897125               4.914071
 44  LinearSVC         45  0.897042           0.897125               4.295548
 45  LinearSVC         46  0.896792           0.897125               4.715747
 46  LinearSVC         47  0.897000           0.897125               9.272091
 47  LinearSVC         48  0.896417           0.897125               3.678787
 48  LinearSVC         49  0.896229           0.897125               3.507308
 49  LinearSVC         50  0.897125           0.897125               6.421142,
 'summary':   Method      Model Optimal_Scaler      Split  Accuracy  Precision    Recall        F1     Kappa       MCC       AUC  LogLoss  Accuracy_CI_Lower  Accuracy_CI_Upper  Precision_CI_Lower  Precision_CI_Upper  Recall_CI_Lower  Recall_CI_Upper  F1_CI_Lower  F1_CI_Upper  AUC_CI_Lower  AUC_CI_Upper  LogLoss_CI_Lower  LogLoss_CI_Upper  Kappa_CI_Lower  Kappa_CI_Upper  MCC_CI_Lower  MCC_CI_Upper
 0    GWO  LinearSVC          Power  Train_OOF  0.897125   0.915927  0.923524  0.919710  0.776578  0.776629  0.965949      NaN           0.894479           0.899896            0.912825            0.919158         0.920622         0.926656     0.917482     0.922012      0.964694      0.967276               NaN               NaN        0.770794        0.782732      0.770845      0.782789
 1    GWO  LinearSVC          Power       Test  0.905667   0.920253  0.932994  0.926579  0.794693  0.794840  0.968495      NaN           0.900417           0.910919            0.914141            0.926099         0.927192         0.938704     0.922242     0.930978      0.965983      0.971018               NaN               NaN        0.783513        0.806176      0.783715      0.806354,
 'timing':        Model  GWO_Search_Sec  GWO_Evaluation_Sec  GWO_Total_Sec  Best_CV_Mean
 0  LinearSVC      255.204246          105.376645     360.862531      0.897125}

In [77]:
run_gwo_model_with_policy("SVM")

[ResourcePolicy] model=SVM (HEAVY) | free_ram=3.07 GB | n_jobs_cv=1 | n_jobs_opt=2

SVM        | Scaler: Standard   | Available RAM: 3.07 GB | Kernel RSS: 205.5 MB
       Memory cleanup -> gc_collected=0, available=3.00 GB, used=80.9%, rss=205.6 MB
       Running 50 evaluations with n_jobs_cv=1, n_jobs_opt=2
       GWO progress for SVM: 0/50 evaluations
       GWO SVM: initializing population (10 wolves)...
          fold 1/5 | acc=0.75260 | running_mean=0.75260 | time=572.86s
          fold 2/5 | acc=0.75365 | running_mean=0.75313 | time=547.32s
          fold 3/5 | acc=0.75490 | running_mean=0.75372 | time=506.02s
          fold 4/5 | acc=0.75490 | running_mean=0.75401 | time=413.54s
          fold 5/5 | acc=0.75979 | running_mean=0.75517 | time=327.53s
       GWO SVM: init 1/10 | last=0.75517 | best=0.75517
          fold 1/5 | acc=0.73979 | running_mean=0.73979 | time=325.49s
          fold 2/5 | acc=0.73604 | running_mean=0.73792 | time=391.12s
          fold 3/5 | acc=0.74177 | running_mean=0.73920 | time=224.01s
          fold 4/5 | acc=0.73844 | running_mean=0.73901 | time=209.30s
          fold 5/5 | acc=0.73656 | running_mean=0.73852 | time=251.13s
       GWO SVM: init 2/10 | last=0.73852 | best=0.75517
          fold 1/5 | acc=0.99271 | running_mean=0.99271 | time=246.33s
          fold 2/5 | acc=0.99365 | running_mean=0.99318 | time=178.34s
          fold 3/5 | acc=0.99198 | running_mean=0.99278 | time=141.63s
          fold 4/5 | acc=0.98969 | running_mean=0.99201 | time=162.30s
          fold 5/5 | acc=0.99313 | running_mean=0.99223 | time=139.06s
       GWO SVM: init 3/10 | last=0.99223 | best=0.99223
          fold 1/5 | acc=0.98260 | running_mean=0.98260 | time=85.05s
          fold 2/5 | acc=0.98010 | running_mean=0.98135 | time=103.20s
          fold 3/5 | acc=0.98438 | running_mean=0.98236 | time=114.38s
          fold 4/5 | acc=0.98396 | running_mean=0.98276 | time=176.21s
          fold 5/5 | acc=0.98250 | running_mean=0.98271 | time=217.48s
       GWO SVM: init 4/10 | last=0.98271 | best=0.99223
          fold 1/5 | acc=0.72875 | running_mean=0.72875 | time=349.67s
          fold 2/5 | acc=0.72562 | running_mean=0.72719 | time=249.71s
          [EarlyStop] running_mean=0.72719 | gap=0.2650 > 0.045 | best=0.99223 → skip folds 3-5
       GWO SVM: init 5/10 | last=0.72719 | best=0.99223
          fold 1/5 | acc=0.97667 | running_mean=0.97667 | time=171.23s
          fold 2/5 | acc=0.97479 | running_mean=0.97573 | time=141.31s
          fold 3/5 | acc=0.97677 | running_mean=0.97608 | time=151.34s
          fold 4/5 | acc=0.97813 | running_mean=0.97659 | time=197.68s
  [GWO SVM] Time: 6769.12s | Memory Δ:   +82.9MB | Peak:   288.6MB

KeyboardInterrupt:

In [76]:
run_gwo_model_with_policy("AdaBoost")

[ResourcePolicy] model=AdaBoost (MEDIUM) | free_ram=4.37 GB | n_jobs_cv=1 | n_jobs_opt=3

AdaBoost   | Scaler: Raw        | Available RAM: 4.37 GB | Kernel RSS: 230.7 MB
       Memory cleanup -> gc_collected=1421, available=4.38 GB, used=72.2%, rss=230.7 MB
       Running 50 evaluations with n_jobs_cv=1, n_jobs_opt=3
       GWO progress for AdaBoost: 0/50 evaluations
       GWO AdaBoost: initializing population (10 wolves)...
          fold 1/5 | acc=0.87813 | running_mean=0.87813 | time=24.37s
          fold 2/5 | acc=0.87938 | running_mean=0.87875 | time=24.74s
          fold 3/5 | acc=0.87823 | running_mean=0.87858 | time=24.89s
          fold 4/5 | acc=0.87719 | running_mean=0.87823 | time=25.24s
          fold 5/5 | acc=0.87313 | running_mean=0.87721 | time=24.79s
       GWO AdaBoost: init 1/10 | last=0.87721 | best=0.87721
          fold 1/5 | acc=0.84542 | running_mean=0.84542 | time=20.42s
          fold 2/5 | acc=0.85281 | running_mean=0.84911 | time=20.49s
          fold 3/5 | acc=0.84969 | running_mean=0.84931 | time=24.86s
          fold 4/5 | acc=0.84615 | running_mean=0.84852 | time=24.88s
          fold 5/5 | acc=0.84219 | running_mean=0.84725 | time=19.75s
       GWO AdaBoost: init 2/10 | last=0.84725 | best=0.87721
          fold 1/5 | acc=0.91938 | running_mean=0.91938 | time=20.92s
          fold 2/5 | acc=0.92323 | running_mean=0.92130 | time=21.61s
          fold 3/5 | acc=0.91969 | running_mean=0.92076 | time=23.15s
          fold 4/5 | acc=0.92135 | running_mean=0.92091 | time=30.93s
          fold 5/5 | acc=0.91854 | running_mean=0.92044 | time=24.64s
       GWO AdaBoost: init 3/10 | last=0.92044 | best=0.92044
          fold 1/5 | acc=0.86667 | running_mean=0.86667 | time=16.43s
          fold 2/5 | acc=0.86979 | running_mean=0.86823 | time=14.60s
          [EarlyStop] running_mean=0.86823 | gap=0.0522 > 0.045 | best=0.92044 → skip folds 3-5
       GWO AdaBoost: init 4/10 | last=0.86823 | best=0.92044
          fold 1/5 | acc=0.92333 | running_mean=0.92333 | time=19.28s
          fold 2/5 | acc=0.92646 | running_mean=0.92490 | time=19.14s
          fold 3/5 | acc=0.92094 | running_mean=0.92358 | time=20.48s
          fold 4/5 | acc=0.92490 | running_mean=0.92391 | time=19.92s
          fold 5/5 | acc=0.92344 | running_mean=0.92381 | time=20.43s
       GWO AdaBoost: init 5/10 | last=0.92381 | best=0.92381
          fold 1/5 | acc=0.87323 | running_mean=0.87323 | time=9.33s
          fold 2/5 | acc=0.87646 | running_mean=0.87484 | time=9.95s
          [EarlyStop] running_mean=0.87484 | gap=0.0490 > 0.045 | best=0.92381 → skip folds 3-5
       GWO AdaBoost: init 6/10 | last=0.87484 | best=0.92381
          fold 1/5 | acc=0.90865 | running_mean=0.90865 | time=26.77s
          fold 2/5 | acc=0.90740 | running_mean=0.90802 | time=26.26s
          fold 3/5 | acc=0.90906 | running_mean=0.90837 | time=26.03s
          fold 4/5 | acc=0.90719 | running_mean=0.90807 | time=25.80s
          fold 5/5 | acc=0.90625 | running_mean=0.90771 | time=27.07s
       GWO AdaBoost: init 7/10 | last=0.90771 | best=0.92381
          fold 1/5 | acc=0.94365 | running_mean=0.94365 | time=13.38s
          fold 2/5 | acc=0.94042 | running_mean=0.94203 | time=13.08s
          fold 3/5 | acc=0.93969 | running_mean=0.94125 | time=13.48s
          fold 4/5 | acc=0.94021 | running_mean=0.94099 | time=13.25s
          fold 5/5 | acc=0.93979 | running_mean=0.94075 | time=12.94s
       GWO AdaBoost: init 8/10 | last=0.94075 | best=0.94075
          fold 1/5 | acc=0.85927 | running_mean=0.85927 | time=26.04s
          fold 2/5 | acc=0.86760 | running_mean=0.86344 | time=25.07s
          [EarlyStop] running_mean=0.86344 | gap=0.0773 > 0.045 | best=0.94075 → skip folds 3-5
       GWO AdaBoost: init 9/10 | last=0.86344 | best=0.94075
          fold 1/5 | acc=0.80354 | running_mean=0.80354 | time=4.47s
          fold 2/5 | acc=0.78260 | running_mean=0.79307 | time=4.55s
          [EarlyStop] running_mean=0.79307 | gap=0.1477 > 0.045 | best=0.94075 → skip folds 3-5
       GWO AdaBoost: init 10/10 | last=0.79307 | best=0.94075
       GWO AdaBoost: init done → α=0.94075 β=0.92381 δ=0.92044
          fold 1/5 | acc=0.87813 | running_mean=0.87813 | time=24.35s
          fold 2/5 | acc=0.87938 | running_mean=0.87875 | time=25.13s
          [EarlyStop] running_mean=0.87875 | gap=0.0620 > 0.045 | best=0.94075 → skip folds 3-5
       GWO AdaBoost: 11/50 | iter=1/4 | last=0.87875 | best=0.94075
          fold 1/5 | acc=0.84542 | running_mean=0.84542 | time=22.95s
          fold 2/5 | acc=0.85281 | running_mean=0.84911 | time=22.59s
          [EarlyStop] running_mean=0.84911 | gap=0.0916 > 0.045 | best=0.94075 → skip folds 3-5
       GWO AdaBoost: 12/50 | iter=1/4 | last=0.84911 | best=0.94075
          fold 1/5 | acc=0.91938 | running_mean=0.91938 | time=24.28s
          fold 2/5 | acc=0.92323 | running_mean=0.92130 | time=24.28s
          fold 3/5 | acc=0.91969 | running_mean=0.92076 | time=24.74s
          fold 4/5 | acc=0.92135 | running_mean=0.92091 | time=24.25s
          fold 5/5 | acc=0.91854 | running_mean=0.92044 | time=24.00s
       GWO AdaBoost: 13/50 | iter=1/4 | last=0.92044 | best=0.94075
          fold 1/5 | acc=0.86667 | running_mean=0.86667 | time=16.89s
          fold 2/5 | acc=0.86979 | running_mean=0.86823 | time=15.71s
          [EarlyStop] running_mean=0.86823 | gap=0.0725 > 0.045 | best=0.94075 → skip folds 3-5
       GWO AdaBoost: 14/50 | iter=1/4 | last=0.86823 | best=0.94075
          fold 1/5 | acc=0.92333 | running_mean=0.92333 | time=21.16s
          fold 2/5 | acc=0.92646 | running_mean=0.92490 | time=20.90s
          fold 3/5 | acc=0.92094 | running_mean=0.92358 | time=21.01s
          fold 4/5 | acc=0.92490 | running_mean=0.92391 | time=20.99s
          fold 5/5 | acc=0.92344 | running_mean=0.92381 | time=21.03s
       GWO AdaBoost: 15/50 | iter=1/4 | last=0.92381 | best=0.94075
          fold 1/5 | acc=0.87323 | running_mean=0.87323 | time=9.47s
          fold 2/5 | acc=0.87646 | running_mean=0.87484 | time=9.55s
          [EarlyStop] running_mean=0.87484 | gap=0.0659 > 0.045 | best=0.94075 → skip folds 3-5
       GWO AdaBoost: 16/50 | iter=1/4 | last=0.87484 | best=0.94075
          fold 1/5 | acc=0.90865 | running_mean=0.90865 | time=26.94s
          fold 2/5 | acc=0.90740 | running_mean=0.90802 | time=26.38s
          fold 3/5 | acc=0.90906 | running_mean=0.90837 | time=26.37s
          fold 4/5 | acc=0.90719 | running_mean=0.90807 | time=26.80s
          fold 5/5 | acc=0.90625 | running_mean=0.90771 | time=25.94s
       GWO AdaBoost: 17/50 | iter=1/4 | last=0.90771 | best=0.94075
          fold 1/5 | acc=0.94365 | running_mean=0.94365 | time=13.18s
          fold 2/5 | acc=0.94042 | running_mean=0.94203 | time=13.07s
          fold 3/5 | acc=0.93969 | running_mean=0.94125 | time=12.96s
          fold 4/5 | acc=0.94021 | running_mean=0.94099 | time=12.99s
          fold 5/5 | acc=0.93979 | running_mean=0.94075 | time=12.99s
       GWO AdaBoost: 18/50 | iter=1/4 | last=0.94075 | best=0.94075
          fold 1/5 | acc=0.85927 | running_mean=0.85927 | time=25.17s
          fold 2/5 | acc=0.86760 | running_mean=0.86344 | time=24.39s
          [EarlyStop] running_mean=0.86344 | gap=0.0773 > 0.045 | best=0.94075 → skip folds 3-5
       GWO AdaBoost: 19/50 | iter=1/4 | last=0.86344 | best=0.94075
          fold 1/5 | acc=0.80354 | running_mean=0.80354 | time=4.43s
          fold 2/5 | acc=0.78260 | running_mean=0.79307 | time=4.49s
          [EarlyStop] running_mean=0.79307 | gap=0.1477 > 0.045 | best=0.94075 → skip folds 3-5
       GWO AdaBoost: 20/50 | iter=1/4 | last=0.79307 | best=0.94075
       GWO AdaBoost: iter 1/4 done → α=0.94075 β=0.94075 δ=0.92381
          fold 1/5 | acc=0.90031 | running_mean=0.90031 | time=13.49s
          fold 2/5 | acc=0.89729 | running_mean=0.89880 | time=13.17s
          fold 3/5 | acc=0.90031 | running_mean=0.89931 | time=13.09s
          fold 4/5 | acc=0.90333 | running_mean=0.90031 | time=17.14s
          fold 5/5 | acc=0.89729 | running_mean=0.89971 | time=16.98s
       GWO AdaBoost: 21/50 | iter=2/4 | last=0.89971 | best=0.94075
          fold 1/5 | acc=0.71125 | running_mean=0.71125 | time=8.14s
          fold 2/5 | acc=0.71177 | running_mean=0.71151 | time=8.16s
          [EarlyStop] running_mean=0.71151 | gap=0.2292 > 0.045 | best=0.94075 → skip folds 3-5
       GWO AdaBoost: 22/50 | iter=2/4 | last=0.71151 | best=0.94075
          fold 1/5 | acc=0.91625 | running_mean=0.91625 | time=7.98s
          fold 2/5 | acc=0.91635 | running_mean=0.91630 | time=9.59s
          fold 3/5 | acc=0.91219 | running_mean=0.91493 | time=8.22s
          fold 4/5 | acc=0.91250 | running_mean=0.91432 | time=8.15s
          fold 5/5 | acc=0.91104 | running_mean=0.91367 | time=8.70s
       GWO AdaBoost: 23/50 | iter=2/4 | last=0.91367 | best=0.94075
          fold 1/5 | acc=0.73917 | running_mean=0.73917 | time=28.71s
          fold 2/5 | acc=0.73521 | running_mean=0.73719 | time=28.56s
          [EarlyStop] running_mean=0.73719 | gap=0.2036 > 0.045 | best=0.94075 → skip folds 3-5
       GWO AdaBoost: 24/50 | iter=2/4 | last=0.73719 | best=0.94075
          fold 1/5 | acc=0.91729 | running_mean=0.91729 | time=32.17s
          fold 2/5 | acc=0.91490 | running_mean=0.91609 | time=34.59s
          fold 3/5 | acc=0.91771 | running_mean=0.91663 | time=36.10s
          fold 4/5 | acc=0.91896 | running_mean=0.91721 | time=56.85s
          fold 5/5 | acc=0.91396 | running_mean=0.91656 | time=54.45s
       GWO AdaBoost: 25/50 | iter=2/4 | last=0.91656 | best=0.94075
          fold 1/5 | acc=0.73677 | running_mean=0.73677 | time=26.86s
          fold 2/5 | acc=0.73115 | running_mean=0.73396 | time=21.70s
          [EarlyStop] running_mean=0.73396 | gap=0.2068 > 0.045 | best=0.94075 → skip folds 3-5
       GWO AdaBoost: 26/50 | iter=2/4 | last=0.73396 | best=0.94075
          fold 1/5 | acc=0.71594 | running_mean=0.71594 | time=14.63s
          fold 2/5 | acc=0.71281 | running_mean=0.71437 | time=13.59s
          [EarlyStop] running_mean=0.71437 | gap=0.2264 > 0.045 | best=0.94075 → skip folds 3-5
       GWO AdaBoost: 27/50 | iter=2/4 | last=0.71437 | best=0.94075
          fold 1/5 | acc=0.92417 | running_mean=0.92417 | time=28.93s
          fold 2/5 | acc=0.92458 | running_mean=0.92437 | time=28.87s
          fold 3/5 | acc=0.92073 | running_mean=0.92316 | time=29.05s
          fold 4/5 | acc=0.92615 | running_mean=0.92391 | time=28.03s
          fold 5/5 | acc=0.92260 | running_mean=0.92365 | time=28.65s
       GWO AdaBoost: 28/50 | iter=2/4 | last=0.92365 | best=0.94075
          fold 1/5 | acc=0.73469 | running_mean=0.73469 | time=16.18s
          fold 2/5 | acc=0.73094 | running_mean=0.73281 | time=14.95s
          [EarlyStop] running_mean=0.73281 | gap=0.2079 > 0.045 | best=0.94075 → skip folds 3-5
       GWO AdaBoost: 29/50 | iter=2/4 | last=0.73281 | best=0.94075
          fold 1/5 | acc=0.91917 | running_mean=0.91917 | time=43.35s
          fold 2/5 | acc=0.91500 | running_mean=0.91708 | time=43.24s
          fold 3/5 | acc=0.91719 | running_mean=0.91712 | time=43.22s
          fold 4/5 | acc=0.91896 | running_mean=0.91758 | time=43.43s
          fold 5/5 | acc=0.91865 | running_mean=0.91779 | time=42.77s
       GWO AdaBoost: 30/50 | iter=2/4 | last=0.91779 | best=0.94075
       GWO AdaBoost: iter 2/4 done → α=0.94075 β=0.94075 δ=0.92381
          fold 1/5 | acc=0.88302 | running_mean=0.88302 | time=16.29s
          fold 2/5 | acc=0.88677 | running_mean=0.88490 | time=16.64s
          [EarlyStop] running_mean=0.88490 | gap=0.0559 > 0.045 | best=0.94075 → skip folds 3-5
       GWO AdaBoost: 31/50 | iter=3/4 | last=0.88490 | best=0.94075
          fold 1/5 | acc=0.92073 | running_mean=0.92073 | time=9.20s
          fold 2/5 | acc=0.92521 | running_mean=0.92297 | time=8.93s
          fold 3/5 | acc=0.92458 | running_mean=0.92351 | time=8.82s
          fold 4/5 | acc=0.92604 | running_mean=0.92414 | time=9.24s
          fold 5/5 | acc=0.92906 | running_mean=0.92512 | time=8.97s
       GWO AdaBoost: 32/50 | iter=3/4 | last=0.92512 | best=0.94075
          fold 1/5 | acc=0.72615 | running_mean=0.72615 | time=35.70s
          fold 2/5 | acc=0.71865 | running_mean=0.72240 | time=35.95s
          [EarlyStop] running_mean=0.72240 | gap=0.2184 > 0.045 | best=0.94075 → skip folds 3-5
       GWO AdaBoost: 33/50 | iter=3/4 | last=0.72240 | best=0.94075
          fold 1/5 | acc=0.73646 | running_mean=0.73646 | time=20.58s
          fold 2/5 | acc=0.73115 | running_mean=0.73380 | time=19.42s
          [EarlyStop] running_mean=0.73380 | gap=0.2069 > 0.045 | best=0.94075 → skip folds 3-5
       GWO AdaBoost: 34/50 | iter=3/4 | last=0.73380 | best=0.94075
          fold 1/5 | acc=0.73760 | running_mean=0.73760 | time=24.34s
          fold 2/5 | acc=0.73125 | running_mean=0.73443 | time=24.54s
          [EarlyStop] running_mean=0.73443 | gap=0.2063 > 0.045 | best=0.94075 → skip folds 3-5
       GWO AdaBoost: 35/50 | iter=3/4 | last=0.73443 | best=0.94075
          fold 1/5 | acc=0.73708 | running_mean=0.73708 | time=23.21s
          fold 2/5 | acc=0.73115 | running_mean=0.73411 | time=25.37s
          [EarlyStop] running_mean=0.73411 | gap=0.2066 > 0.045 | best=0.94075 → skip folds 3-5
       GWO AdaBoost: 36/50 | iter=3/4 | last=0.73411 | best=0.94075
          fold 1/5 | acc=0.93698 | running_mean=0.93698 | time=16.24s
          fold 2/5 | acc=0.93188 | running_mean=0.93443 | time=14.64s
          fold 3/5 | acc=0.93542 | running_mean=0.93476 | time=14.19s
          fold 4/5 | acc=0.93365 | running_mean=0.93448 | time=14.88s
          fold 5/5 | acc=0.93417 | running_mean=0.93442 | time=14.02s
       GWO AdaBoost: 37/50 | iter=3/4 | last=0.93442 | best=0.94075
          fold 1/5 | acc=0.91198 | running_mean=0.91198 | time=21.11s
          fold 2/5 | acc=0.91385 | running_mean=0.91292 | time=21.64s
          fold 3/5 | acc=0.90969 | running_mean=0.91184 | time=21.03s
          fold 4/5 | acc=0.91260 | running_mean=0.91203 | time=21.46s
          fold 5/5 | acc=0.90760 | running_mean=0.91115 | time=22.07s
       GWO AdaBoost: 38/50 | iter=3/4 | last=0.91115 | best=0.94075
          fold 1/5 | acc=0.92979 | running_mean=0.92979 | time=10.91s
          fold 2/5 | acc=0.93063 | running_mean=0.93021 | time=10.86s
          fold 3/5 | acc=0.93063 | running_mean=0.93035 | time=10.95s
          fold 4/5 | acc=0.92729 | running_mean=0.92958 | time=11.09s
          fold 5/5 | acc=0.92646 | running_mean=0.92896 | time=12.09s
       GWO AdaBoost: 39/50 | iter=3/4 | last=0.92896 | best=0.94075
          fold 1/5 | acc=0.91271 | running_mean=0.91271 | time=28.67s
          fold 2/5 | acc=0.91323 | running_mean=0.91297 | time=28.86s
          fold 3/5 | acc=0.91271 | running_mean=0.91288 | time=29.26s
          fold 4/5 | acc=0.91458 | running_mean=0.91331 | time=28.50s
          fold 5/5 | acc=0.90896 | running_mean=0.91244 | time=28.65s
       GWO AdaBoost: 40/50 | iter=3/4 | last=0.91244 | best=0.94075
       GWO AdaBoost: iter 3/4 done → α=0.94075 β=0.94075 δ=0.93442
          fold 1/5 | acc=0.71729 | running_mean=0.71729 | time=15.69s
          fold 2/5 | acc=0.71281 | running_mean=0.71505 | time=16.23s
          [EarlyStop] running_mean=0.71505 | gap=0.2257 > 0.045 | best=0.94075 → skip folds 3-5
       GWO AdaBoost: 41/50 | iter=4/4 | last=0.71505 | best=0.94075
          fold 1/5 | acc=0.93385 | running_mean=0.93385 | time=22.70s
          fold 2/5 | acc=0.92948 | running_mean=0.93167 | time=22.23s
          fold 3/5 | acc=0.93302 | running_mean=0.93212 | time=23.48s
          fold 4/5 | acc=0.93146 | running_mean=0.93195 | time=22.65s
          fold 5/5 | acc=0.93417 | running_mean=0.93240 | time=22.40s
       GWO AdaBoost: 42/50 | iter=4/4 | last=0.93240 | best=0.94075
          fold 1/5 | acc=0.89240 | running_mean=0.89240 | time=13.09s
          fold 2/5 | acc=0.89438 | running_mean=0.89339 | time=12.41s
          [EarlyStop] running_mean=0.89339 | gap=0.0474 > 0.045 | best=0.94075 → skip folds 3-5
       GWO AdaBoost: 43/50 | iter=4/4 | last=0.89339 | best=0.94075
          fold 1/5 | acc=0.90802 | running_mean=0.90802 | time=18.46s
          fold 2/5 | acc=0.90635 | running_mean=0.90719 | time=20.12s
          fold 3/5 | acc=0.90885 | running_mean=0.90774 | time=21.56s
          fold 4/5 | acc=0.90885 | running_mean=0.90802 | time=20.11s
          fold 5/5 | acc=0.90396 | running_mean=0.90721 | time=23.85s
       GWO AdaBoost: 44/50 | iter=4/4 | last=0.90721 | best=0.94075
          fold 1/5 | acc=0.72146 | running_mean=0.72146 | time=20.60s
          fold 2/5 | acc=0.71417 | running_mean=0.71781 | time=18.91s
          [EarlyStop] running_mean=0.71781 | gap=0.2229 > 0.045 | best=0.94075 → skip folds 3-5
       GWO AdaBoost: 45/50 | iter=4/4 | last=0.71781 | best=0.94075
          fold 1/5 | acc=0.71833 | running_mean=0.71833 | time=16.29s
          fold 2/5 | acc=0.71281 | running_mean=0.71557 | time=17.19s
          [EarlyStop] running_mean=0.71557 | gap=0.2252 > 0.045 | best=0.94075 → skip folds 3-5
       GWO AdaBoost: 46/50 | iter=4/4 | last=0.71557 | best=0.94075
          fold 1/5 | acc=0.93135 | running_mean=0.93135 | time=18.49s
          fold 2/5 | acc=0.93208 | running_mean=0.93172 | time=18.31s
          fold 3/5 | acc=0.93385 | running_mean=0.93243 | time=19.16s
          fold 4/5 | acc=0.93490 | running_mean=0.93305 | time=18.42s
          fold 5/5 | acc=0.93104 | running_mean=0.93265 | time=18.09s
       GWO AdaBoost: 47/50 | iter=4/4 | last=0.93265 | best=0.94075
          fold 1/5 | acc=0.91646 | running_mean=0.91646 | time=18.77s
          fold 2/5 | acc=0.91604 | running_mean=0.91625 | time=17.84s
          fold 3/5 | acc=0.91427 | running_mean=0.91559 | time=18.13s
          fold 4/5 | acc=0.91938 | running_mean=0.91654 | time=17.91s
          fold 5/5 | acc=0.90781 | running_mean=0.91479 | time=18.02s
       GWO AdaBoost: 48/50 | iter=4/4 | last=0.91479 | best=0.94075
          fold 1/5 | acc=0.71385 | running_mean=0.71385 | time=12.79s
          fold 2/5 | acc=0.71094 | running_mean=0.71240 | time=12.15s
          [EarlyStop] running_mean=0.71240 | gap=0.2284 > 0.045 | best=0.94075 → skip folds 3-5
       GWO AdaBoost: 49/50 | iter=4/4 | last=0.71240 | best=0.94075
          fold 1/5 | acc=0.93875 | running_mean=0.93875 | time=15.41s
          fold 2/5 | acc=0.93573 | running_mean=0.93724 | time=16.58s
          fold 3/5 | acc=0.93594 | running_mean=0.93681 | time=17.35s
          fold 4/5 | acc=0.93448 | running_mean=0.93622 | time=17.39s
          fold 5/5 | acc=0.93563 | running_mean=0.93610 | time=17.84s
       GWO AdaBoost: 50/50 | iter=4/4 | last=0.93610 | best=0.94075
       GWO AdaBoost: iter 4/4 done → α=0.94075 β=0.94075 δ=0.93610
  [GWO AdaBoost] Time: 3574.22s | Memory Δ:  -187.7MB | Peak:    43.0MB
  [GWO Eval AdaBoost] Time:  423.28s | Memory Δ:    -4.1MB | Peak:   202.2MB
       Memory cleanup -> gc_collected=64, available=3.14 GB, used=80.0%, rss=202.7 MB
       Exported GWO artifacts

{'status': 'completed',
 'best':       Model Optimal_Scaler  Best_CV_Mean  Best_Iteration  n_estimators  learning_rate algorithm  random_state
 0  AdaBoost            Raw       0.94075               8           210         1.7124   SAMME.R            42,
 'history':        Model  Iteration   CV_Mean  Best_Score_So_Far  Iteration_Runtime_Sec
 0   AdaBoost          1  0.877208           0.877208             124.055978
 1   AdaBoost          2  0.847250           0.877208             110.424588
 2   AdaBoost          3  0.920438           0.920438             121.257970
 3   AdaBoost          4  0.868229           0.920438              31.043243
 4   AdaBoost          5  0.923813           0.923813              99.263419
 5   AdaBoost          6  0.874844           0.923813              19.284147
 6   AdaBoost          7  0.907708           0.923813             131.942179
 7   AdaBoost          8  0.940750           0.940750              66.147841
 8   AdaBoost          9  0.863437           0.940750              51.114729
 9   AdaBoost         10  0.793073           0.940750               9.026730
 10  AdaBoost         11  0.878750           0.940750              49.494276
 11  AdaBoost         12  0.849115           0.940750              45.549773
 12  AdaBoost         13  0.920438           0.940750             121.557441
 13  AdaBoost         14  0.868229           0.940750              32.603596
 14  AdaBoost         15  0.923813           0.940750             105.106828
 15  AdaBoost         16  0.874844           0.940750              19.031069
 16  AdaBoost         17  0.907708           0.940750             132.446229
 17  AdaBoost         18  0.940750           0.940750              65.206888
 18  AdaBoost         19  0.863437           0.940750              49.572793
 19  AdaBoost         20  0.793073           0.940750               8.925328
 20  AdaBoost         21  0.899708           0.940750              73.865939
 21  AdaBoost         22  0.711510           0.940750              16.311648
 22  AdaBoost         23  0.913667           0.940750              42.660829
 23  AdaBoost         24  0.737187           0.940750              57.286533
 24  AdaBoost         25  0.916563           0.940750             214.191700
 25  AdaBoost         26  0.733958           0.940750              48.589852
 26  AdaBoost         27  0.714375           0.940750              28.234498
 27  AdaBoost         28  0.923646           0.940750             143.537211
 28  AdaBoost         29  0.732813           0.940750              31.150369
 29  AdaBoost         30  0.917792           0.940750             216.027878
 30  AdaBoost         31  0.884896           0.940750              32.951179
 31  AdaBoost         32  0.925125           0.940750              45.171747
 32  AdaBoost         33  0.722396           0.940750              71.663678
 33  AdaBoost         34  0.733802           0.940750              40.016059
 34  AdaBoost         35  0.734427           0.940750              48.895815
 35  AdaBoost         36  0.734115           0.940750              48.593292
 36  AdaBoost         37  0.934417           0.940750              73.989864
 37  AdaBoost         38  0.911146           0.940750             107.307597
 38  AdaBoost         39  0.928958           0.940750              55.920046
 39  AdaBoost         40  0.912438           0.940750             143.971010
 40  AdaBoost         41  0.715052           0.940750              31.935588
 41  AdaBoost         42  0.932396           0.940750             113.463202
 42  AdaBoost         43  0.893385           0.940750              25.519931
 43  AdaBoost         44  0.907208           0.940750             104.105545
 44  AdaBoost         45  0.717812           0.940750              39.530000
 45  AdaBoost         46  0.715573           0.940750              33.489879
 46  AdaBoost         47  0.932646           0.940750              92.483777
 47  AdaBoost         48  0.914792           0.940750              90.697722
 48  AdaBoost         49  0.712396           0.940750              24.950977
 49  AdaBoost         50  0.936104           0.940750              84.589861,
 'summary':   Method     Model Optimal_Scaler      Split  Accuracy  Precision    Recall        F1     Kappa       MCC       AUC   LogLoss  Accuracy_CI_Lower  Accuracy_CI_Upper  Precision_CI_Lower  Precision_CI_Upper  Recall_CI_Lower  Recall_CI_Upper  F1_CI_Lower  F1_CI_Upper  AUC_CI_Lower  AUC_CI_Upper  LogLoss_CI_Lower  LogLoss_CI_Upper  Kappa_CI_Lower  Kappa_CI_Upper  MCC_CI_Lower  MCC_CI_Upper
 0    GWO  AdaBoost            Raw  Train_OOF  0.940750   0.950652  0.956799  0.953715  0.871412  0.871447  0.987663  0.622492           0.938708           0.942792            0.948171            0.953051         0.954646         0.958986     0.952065     0.955348      0.987028      0.988335          0.622018          0.622963        0.866918        0.875848      0.866949      0.875900
 1    GWO  AdaBoost            Raw       Test  0.939917   0.947477  0.958986  0.953197  0.869320  0.869443  0.988414  0.621642           0.935583           0.944085            0.942502            0.952337         0.954368         0.963161     0.949757     0.956505      0.987105      0.989627          0.620691          0.622649        0.859742        0.878372      0.859839      0.878476,
 'timing':       Model  GWO_Search_Sec  GWO_Evaluation_Sec  GWO_Total_Sec  Best_CV_Mean
 0  AdaBoost       3574.2211          423.277397    3998.186607       0.94075}

In [ ]:
run_gwo_model_with_policy('RF')

[ResourcePolicy] model=RF (HEAVY) | free_ram=2.69 GB | n_jobs_cv=1 | n_jobs_opt=2

RF         | Scaler: MinMax     | Available RAM: 2.69 GB | Kernel RSS: 261.0 MB
       Memory cleanup -> gc_collected=67, available=2.67 GB, used=83.0%, rss=261.0 MB
       Running 50 evaluations with n_jobs_cv=1, n_jobs_opt=2
       GWO progress for RF: 0/50 evaluations
       GWO RF: initializing population (10 wolves)...
          fold 1/5 | acc=0.93875 | running_mean=0.93875 | time=34.69s
          fold 2/5 | acc=0.94312 | running_mean=0.94094 | time=41.21s
          fold 3/5 | acc=0.94302 | running_mean=0.94163 | time=31.37s
          fold 4/5 | acc=0.93875 | running_mean=0.94091 | time=31.79s
          fold 5/5 | acc=0.93656 | running_mean=0.94004 | time=46.25s
       GWO RF: init 1/10 | last=0.94004 | best=0.94004
          fold 1/5 | acc=0.94698 | running_mean=0.94698 | time=61.14s
          fold 2/5 | acc=0.95104 | running_mean=0.94901 | time=64.29s
          fold 3/5 | acc=0.94885 | running_mean=0.94896 | time=53.35s
          fold 4/5 | acc=0.94646 | running_mean=0.94833 | time=39.32s
          fold 5/5 | acc=0.94740 | running_mean=0.94815 | time=61.45s
       GWO RF: init 2/10 | last=0.94815 | best=0.94815
          fold 1/5 | acc=0.93948 | running_mean=0.93948 | time=18.88s
          fold 2/5 | acc=0.94219 | running_mean=0.94083 | time=35.21s
          fold 3/5 | acc=0.94167 | running_mean=0.94111 | time=28.27s
          fold 4/5 | acc=0.93937 | running_mean=0.94068 | time=24.21s
          fold 5/5 | acc=0.93781 | running_mean=0.94010 | time=18.84s
       GWO RF: init 3/10 | last=0.94010 | best=0.94815
          fold 1/5 | acc=0.93927 | running_mean=0.93927 | time=23.53s
          fold 2/5 | acc=0.94083 | running_mean=0.94005 | time=21.35s
          fold 3/5 | acc=0.94208 | running_mean=0.94073 | time=26.56s
          fold 4/5 | acc=0.93958 | running_mean=0.94044 | time=22.37s
          fold 5/5 | acc=0.93844 | running_mean=0.94004 | time=16.51s
       GWO RF: init 4/10 | last=0.94004 | best=0.94815
          fold 1/5 | acc=0.94688 | running_mean=0.94688 | time=192.83s
          fold 2/5 | acc=0.95323 | running_mean=0.95005 | time=204.76s
          fold 3/5 | acc=0.95125 | running_mean=0.95045 | time=199.71s
          fold 4/5 | acc=0.94552 | running_mean=0.94922 | time=187.79s
          fold 5/5 | acc=0.95073 | running_mean=0.94952 | time=146.46s
       GWO RF: init 5/10 | last=0.94952 | best=0.94952
          fold 1/5 | acc=0.95583 | running_mean=0.95583 | time=18.23s
          fold 2/5 | acc=0.95823 | running_mean=0.95703 | time=26.57s
          fold 3/5 | acc=0.95729 | running_mean=0.95712 | time=22.77s
          fold 4/5 | acc=0.95396 | running_mean=0.95633 | time=16.65s
          fold 5/5 | acc=0.95302 | running_mean=0.95567 | time=16.15s
       GWO RF: init 6/10 | last=0.95567 | best=0.95567
          fold 1/5 | acc=0.94833 | running_mean=0.94833 | time=50.45s
          fold 2/5 | acc=0.95188 | running_mean=0.95010 | time=57.14s
          fold 3/5 | acc=0.95083 | running_mean=0.95035 | time=29.77s
          fold 4/5 | acc=0.94792 | running_mean=0.94974 | time=33.93s
          fold 5/5 | acc=0.94865 | running_mean=0.94952 | time=41.99s
       GWO RF: init 7/10 | last=0.94952 | best=0.95567
          fold 1/5 | acc=0.88427 | running_mean=0.88427 | time=11.14s
          fold 2/5 | acc=0.89187 | running_mean=0.88807 | time=9.67s
          [EarlyStop] running_mean=0.88807 | gap=0.0676 > 0.045 | best=0.95567 → skip folds 3-5
       GWO RF: init 8/10 | last=0.88807 | best=0.95567
          fold 1/5 | acc=0.95646 | running_mean=0.95646 | time=119.16s
          fold 2/5 | acc=0.96229 | running_mean=0.95937 | time=128.78s
          fold 3/5 | acc=0.96219 | running_mean=0.96031 | time=109.83s
          fold 4/5 | acc=0.95698 | running_mean=0.95948 | time=167.94s
          fold 5/5 | acc=0.96104 | running_mean=0.95979 | time=149.81s
       GWO RF: init 9/10 | last=0.95979 | best=0.95979
          fold 1/5 | acc=0.93802 | running_mean=0.93802 | time=63.97s
          fold 2/5 | acc=0.94177 | running_mean=0.93990 | time=47.42s
          fold 3/5 | acc=0.94104 | running_mean=0.94028 | time=58.61s
          fold 4/5 | acc=0.93740 | running_mean=0.93956 | time=51.58s
          fold 5/5 | acc=0.93833 | running_mean=0.93931 | time=57.49s
       GWO RF: init 10/10 | last=0.93931 | best=0.95979
       GWO RF: init done → α=0.95979 β=0.95567 δ=0.94952
          fold 1/5 | acc=0.93875 | running_mean=0.93875 | time=45.77s
          fold 2/5 | acc=0.94312 | running_mean=0.94094 | time=61.18s
          fold 3/5 | acc=0.94302 | running_mean=0.94163 | time=59.66s
          fold 4/5 | acc=0.93875 | running_mean=0.94091 | time=62.38s
          fold 5/5 | acc=0.93656 | running_mean=0.94004 | time=61.99s
       GWO RF: 11/50 | iter=1/4 | last=0.94004 | best=0.95979
          fold 1/5 | acc=0.94698 | running_mean=0.94698 | time=86.12s
          fold 2/5 | acc=0.95104 | running_mean=0.94901 | time=89.87s
          fold 3/5 | acc=0.94885 | running_mean=0.94896 | time=72.67s
          fold 4/5 | acc=0.94646 | running_mean=0.94833 | time=50.88s
          fold 5/5 | acc=0.94740 | running_mean=0.94815 | time=62.28s
       GWO RF: 12/50 | iter=1/4 | last=0.94815 | best=0.95979
          fold 1/5 | acc=0.93948 | running_mean=0.93948 | time=28.46s
          fold 2/5 | acc=0.94219 | running_mean=0.94083 | time=27.11s
          fold 3/5 | acc=0.94167 | running_mean=0.94111 | time=27.20s
          fold 4/5 | acc=0.93937 | running_mean=0.94068 | time=28.00s
          fold 5/5 | acc=0.93781 | running_mean=0.94010 | time=28.95s
       GWO RF: 13/50 | iter=1/4 | last=0.94010 | best=0.95979
          fold 1/5 | acc=0.93927 | running_mean=0.93927 | time=19.75s
          fold 2/5 | acc=0.94083 | running_mean=0.94005 | time=20.58s
          fold 3/5 | acc=0.94208 | running_mean=0.94073 | time=20.32s
          fold 4/5 | acc=0.93958 | running_mean=0.94044 | time=19.09s
          fold 5/5 | acc=0.93844 | running_mean=0.94004 | time=15.64s
       GWO RF: 14/50 | iter=1/4 | last=0.94004 | best=0.95979
          fold 1/5 | acc=0.94688 | running_mean=0.94688 | time=150.23s
          fold 2/5 | acc=0.95323 | running_mean=0.95005 | time=144.55s
          fold 3/5 | acc=0.95125 | running_mean=0.95045 | time=152.83s
          fold 4/5 | acc=0.94552 | running_mean=0.94922 | time=172.35s
          fold 5/5 | acc=0.95073 | running_mean=0.94952 | time=219.56s
       GWO RF: 15/50 | iter=1/4 | last=0.94952 | best=0.95979
          fold 1/5 | acc=0.95583 | running_mean=0.95583 | time=18.54s
          fold 2/5 | acc=0.95823 | running_mean=0.95703 | time=20.52s
          fold 3/5 | acc=0.95729 | running_mean=0.95712 | time=20.88s
          fold 4/5 | acc=0.95396 | running_mean=0.95633 | time=19.74s
          fold 5/5 | acc=0.95302 | running_mean=0.95567 | time=23.41s
       GWO RF: 16/50 | iter=1/4 | last=0.95567 | best=0.95979
          fold 1/5 | acc=0.94833 | running_mean=0.94833 | time=57.89s
          fold 2/5 | acc=0.95188 | running_mean=0.95010 | time=52.50s
          fold 3/5 | acc=0.95083 | running_mean=0.95035 | time=54.96s
          fold 4/5 | acc=0.94792 | running_mean=0.94974 | time=57.37s
          fold 5/5 | acc=0.94865 | running_mean=0.94952 | time=58.72s
       GWO RF: 17/50 | iter=1/4 | last=0.94952 | best=0.95979
          fold 1/5 | acc=0.88427 | running_mean=0.88427 | time=16.20s
          fold 2/5 | acc=0.89187 | running_mean=0.88807 | time=15.90s
          [EarlyStop] running_mean=0.88807 | gap=0.0717 > 0.045 | best=0.95979 → skip folds 3-5
       GWO RF: 18/50 | iter=1/4 | last=0.88807 | best=0.95979
          fold 1/5 | acc=0.95646 | running_mean=0.95646 | time=146.23s
          fold 2/5 | acc=0.96229 | running_mean=0.95937 | time=155.19s
          fold 3/5 | acc=0.96219 | running_mean=0.96031 | time=151.40s
          fold 4/5 | acc=0.95698 | running_mean=0.95948 | time=161.24s
          fold 5/5 | acc=0.96104 | running_mean=0.95979 | time=148.61s
       GWO RF: 19/50 | iter=1/4 | last=0.95979 | best=0.95979
          [RAM repoll] free=4.09 GB → n_jobs_opt updated to 3
          fold 1/5 | acc=0.93802 | running_mean=0.93802 | time=46.56s
          fold 2/5 | acc=0.94177 | running_mean=0.93990 | time=43.81s
          fold 3/5 | acc=0.94104 | running_mean=0.94028 | time=40.48s
          fold 4/5 | acc=0.93740 | running_mean=0.93956 | time=32.90s
          fold 5/5 | acc=0.93833 | running_mean=0.93931 | time=42.12s
       GWO RF: 20/50 | iter=1/4 | last=0.93931 | best=0.95979
       GWO RF: iter 1/4 done → α=0.95979 β=0.95979 δ=0.95567
          fold 1/5 | acc=0.96948 | running_mean=0.96948 | time=124.19s
          fold 2/5 | acc=0.97208 | running_mean=0.97078 | time=143.76s
          fold 3/5 | acc=0.97219 | running_mean=0.97125 | time=111.70s
          fold 4/5 | acc=0.96896 | running_mean=0.97068 | time=106.63s
          fold 5/5 | acc=0.97271 | running_mean=0.97108 | time=134.03s
       GWO RF: 21/50 | iter=2/4 | last=0.97108 | best=0.95979
          fold 1/5 | acc=0.95354 | running_mean=0.95354 | time=19.02s
          fold 2/5 | acc=0.96052 | running_mean=0.95703 | time=18.94s
          fold 3/5 | acc=0.96000 | running_mean=0.95802 | time=17.49s
          fold 4/5 | acc=0.95708 | running_mean=0.95779 | time=24.13s
          fold 5/5 | acc=0.96219 | running_mean=0.95867 | time=19.56s
       GWO RF: 22/50 | iter=2/4 | last=0.95867 | best=0.95979
          fold 1/5 | acc=0.95427 | running_mean=0.95427 | time=89.21s
          fold 2/5 | acc=0.96198 | running_mean=0.95813 | time=80.56s
          fold 3/5 | acc=0.95958 | running_mean=0.95861 | time=113.68s
          fold 4/5 | acc=0.95469 | running_mean=0.95763 | time=139.82s
          fold 5/5 | acc=0.96021 | running_mean=0.95815 | time=148.63s
       GWO RF: 23/50 | iter=2/4 | last=0.95815 | best=0.95979
          fold 1/5 | acc=0.95469 | running_mean=0.95469 | time=74.60s
          fold 2/5 | acc=0.95979 | running_mean=0.95724 | time=66.08s
          fold 3/5 | acc=0.95719 | running_mean=0.95722 | time=61.41s
          fold 4/5 | acc=0.95365 | running_mean=0.95633 | time=64.60s
          fold 5/5 | acc=0.95865 | running_mean=0.95679 | time=74.29s
       GWO RF: 24/50 | iter=2/4 | last=0.95679 | best=0.95979
          fold 1/5 | acc=0.95854 | running_mean=0.95854 | time=40.11s
          fold 2/5 | acc=0.96354 | running_mean=0.96104 | time=39.21s
          fold 3/5 | acc=0.96313 | running_mean=0.96174 | time=38.81s
          fold 4/5 | acc=0.96021 | running_mean=0.96135 | time=38.82s
          fold 5/5 | acc=0.96521 | running_mean=0.96212 | time=32.09s
       GWO RF: 25/50 | iter=2/4 | last=0.96212 | best=0.95979
          fold 1/5 | acc=0.96385 | running_mean=0.96385 | time=70.67s
          fold 2/5 | acc=0.96677 | running_mean=0.96531 | time=63.56s
          fold 3/5 | acc=0.96646 | running_mean=0.96569 | time=91.51s
          fold 4/5 | acc=0.96260 | running_mean=0.96492 | time=82.34s
          fold 5/5 | acc=0.96604 | running_mean=0.96515 | time=70.04s
       GWO RF: 26/50 | iter=2/4 | last=0.96515 | best=0.95979
          fold 1/5 | acc=0.94688 | running_mean=0.94688 | time=20.21s
          fold 2/5 | acc=0.95135 | running_mean=0.94911 | time=17.17s
          fold 3/5 | acc=0.95135 | running_mean=0.94986 | time=18.81s
          fold 4/5 | acc=0.94708 | running_mean=0.94917 | time=17.85s
          fold 5/5 | acc=0.94854 | running_mean=0.94904 | time=18.35s
       GWO RF: 27/50 | iter=2/4 | last=0.94904 | best=0.95979
          fold 1/5 | acc=0.94521 | running_mean=0.94521 | time=26.29s
          fold 2/5 | acc=0.94802 | running_mean=0.94661 | time=27.83s
          fold 3/5 | acc=0.94563 | running_mean=0.94628 | time=28.11s
          fold 4/5 | acc=0.94188 | running_mean=0.94518 | time=25.20s
          fold 5/5 | acc=0.94302 | running_mean=0.94475 | time=20.93s
       GWO RF: 28/50 | iter=2/4 | last=0.94475 | best=0.95979
          fold 1/5 | acc=0.94708 | running_mean=0.94708 | time=11.65s
          fold 2/5 | acc=0.94917 | running_mean=0.94813 | time=10.01s
          fold 3/5 | acc=0.94844 | running_mean=0.94823 | time=11.84s
          fold 4/5 | acc=0.94615 | running_mean=0.94771 | time=14.90s
          fold 5/5 | acc=0.94458 | running_mean=0.94708 | time=15.04s
       GWO RF: 29/50 | iter=2/4 | last=0.94708 | best=0.95979
          [RAM repoll] free=2.28 GB → n_jobs_opt updated to 1
          fold 1/5 | acc=0.97010 | running_mean=0.97010 | time=256.09s
          fold 2/5 | acc=0.97177 | running_mean=0.97094 | time=178.39s
          fold 3/5 | acc=0.97198 | running_mean=0.97128 | time=260.36s
          fold 4/5 | acc=0.96927 | running_mean=0.97078 | time=252.15s
          fold 5/5 | acc=0.97250 | running_mean=0.97113 | time=277.60s
       GWO RF: 30/50 | iter=2/4 | last=0.97113 | best=0.95979
       GWO RF: iter 2/4 done → α=0.97113 β=0.97108 δ=0.96515
          fold 1/5 | acc=0.96656 | running_mean=0.96656 | time=188.49s
          fold 2/5 | acc=0.96885 | running_mean=0.96771 | time=168.48s
          fold 3/5 | acc=0.96937 | running_mean=0.96826 | time=180.78s
          fold 4/5 | acc=0.96719 | running_mean=0.96799 | time=180.79s
          fold 5/5 | acc=0.96906 | running_mean=0.96821 | time=181.15s
       GWO RF: 31/50 | iter=3/4 | last=0.96821 | best=0.97113
          fold 1/5 | acc=0.95562 | running_mean=0.95562 | time=68.95s
          fold 2/5 | acc=0.95844 | running_mean=0.95703 | time=61.27s
          fold 3/5 | acc=0.95927 | running_mean=0.95778 | time=59.03s
          fold 4/5 | acc=0.95354 | running_mean=0.95672 | time=33.82s
          fold 5/5 | acc=0.95427 | running_mean=0.95623 | time=31.08s
       GWO RF: 32/50 | iter=3/4 | last=0.95623 | best=0.97113
          fold 1/5 | acc=0.96490 | running_mean=0.96490 | time=79.13s
          fold 2/5 | acc=0.96729 | running_mean=0.96609 | time=54.41s
          fold 3/5 | acc=0.96771 | running_mean=0.96663 | time=63.00s
          fold 4/5 | acc=0.96500 | running_mean=0.96622 | time=71.09s
          fold 5/5 | acc=0.96896 | running_mean=0.96677 | time=64.74s
       GWO RF: 33/50 | iter=3/4 | last=0.96677 | best=0.97113
          fold 1/5 | acc=0.95740 | running_mean=0.95740 | time=94.34s
          fold 2/5 | acc=0.96104 | running_mean=0.95922 | time=104.30s
          fold 3/5 | acc=0.95917 | running_mean=0.95920 | time=116.61s
          fold 4/5 | acc=0.95667 | running_mean=0.95857 | time=188.79s
          fold 5/5 | acc=0.96042 | running_mean=0.95894 | time=170.07s
       GWO RF: 34/50 | iter=3/4 | last=0.95894 | best=0.97113
          fold 1/5 | acc=0.96698 | running_mean=0.96698 | time=159.92s
          fold 2/5 | acc=0.96885 | running_mean=0.96792 | time=156.55s
          fold 3/5 | acc=0.96917 | running_mean=0.96833 | time=181.99s
          fold 4/5 | acc=0.96646 | running_mean=0.96786 | time=217.04s
          fold 5/5 | acc=0.96896 | running_mean=0.96808 | time=311.35s
       GWO RF: 35/50 | iter=3/4 | last=0.96808 | best=0.97113
          fold 1/5 | acc=0.96260 | running_mean=0.96260 | time=237.27s
          fold 2/5 | acc=0.96656 | running_mean=0.96458 | time=242.97s
          fold 3/5 | acc=0.96583 | running_mean=0.96500 | time=153.29s
          fold 4/5 | acc=0.96344 | running_mean=0.96461 | time=237.28s
          fold 5/5 | acc=0.96594 | running_mean=0.96487 | time=244.71s
       GWO RF: 36/50 | iter=3/4 | last=0.96487 | best=0.97113
          fold 1/5 | acc=0.96990 | running_mean=0.96990 | time=162.51s
          fold 2/5 | acc=0.97115 | running_mean=0.97052 | time=207.26s
          fold 3/5 | acc=0.97292 | running_mean=0.97132 | time=200.62s
          fold 4/5 | acc=0.96896 | running_mean=0.97073 | time=104.90s
          fold 5/5 | acc=0.97260 | running_mean=0.97110 | time=97.64s
       GWO RF: 37/50 | iter=3/4 | last=0.97110 | best=0.97113
          fold 1/5 | acc=0.94760 | running_mean=0.94760 | time=29.81s
          fold 2/5 | acc=0.95250 | running_mean=0.95005 | time=32.13s
          fold 3/5 | acc=0.94969 | running_mean=0.94993 | time=32.25s
          fold 4/5 | acc=0.94906 | running_mean=0.94971 | time=30.18s
          fold 5/5 | acc=0.94875 | running_mean=0.94952 | time=28.49s
       GWO RF: 38/50 | iter=3/4 | last=0.94952 | best=0.97113
          fold 1/5 | acc=0.97188 | running_mean=0.97188 | time=106.67s
          fold 2/5 | acc=0.97260 | running_mean=0.97224 | time=106.54s
          fold 3/5 | acc=0.97281 | running_mean=0.97243 | time=104.97s
          fold 4/5 | acc=0.97073 | running_mean=0.97201 | time=106.21s
          fold 5/5 | acc=0.97417 | running_mean=0.97244 | time=114.53s
       GWO RF: 39/50 | iter=3/4 | last=0.97244 | best=0.97113
          [RAM repoll] free=3.76 GB → n_jobs_opt updated to 2
          fold 1/5 | acc=0.94635 | running_mean=0.94635 | time=47.16s
          fold 2/5 | acc=0.94896 | running_mean=0.94766 | time=42.28s
          fold 3/5 | acc=0.94979 | running_mean=0.94837 | time=51.48s
          fold 4/5 | acc=0.94375 | running_mean=0.94721 | time=51.67s
          fold 5/5 | acc=0.94698 | running_mean=0.94717 | time=85.92s
       GWO RF: 40/50 | iter=3/4 | last=0.94717 | best=0.97113
       GWO RF: iter 3/4 done → α=0.97244 β=0.97113 δ=0.97110
          fold 1/5 | acc=0.97031 | running_mean=0.97031 | time=176.97s
          fold 2/5 | acc=0.97188 | running_mean=0.97109 | time=173.19s
          fold 3/5 | acc=0.97229 | running_mean=0.97149 | time=171.60s
          fold 4/5 | acc=0.96927 | running_mean=0.97094 | time=170.01s
          fold 5/5 | acc=0.97333 | running_mean=0.97142 | time=147.93s
       GWO RF: 41/50 | iter=4/4 | last=0.97142 | best=0.97244
          fold 1/5 | acc=0.97052 | running_mean=0.97052 | time=124.69s
          fold 2/5 | acc=0.97188 | running_mean=0.97120 | time=128.92s
          fold 3/5 | acc=0.97302 | running_mean=0.97181 | time=132.16s
          fold 4/5 | acc=0.96948 | running_mean=0.97122 | time=142.49s
          fold 5/5 | acc=0.97271 | running_mean=0.97152 | time=102.86s
       GWO RF: 42/50 | iter=4/4 | last=0.97152 | best=0.97244
          fold 1/5 | acc=0.96958 | running_mean=0.96958 | time=75.49s
          fold 2/5 | acc=0.97188 | running_mean=0.97073 | time=69.85s
          fold 3/5 | acc=0.97208 | running_mean=0.97118 | time=75.37s
          fold 4/5 | acc=0.96865 | running_mean=0.97055 | time=71.33s
          fold 5/5 | acc=0.97260 | running_mean=0.97096 | time=78.11s
       GWO RF: 43/50 | iter=4/4 | last=0.97096 | best=0.97244
          fold 1/5 | acc=0.96323 | running_mean=0.96323 | time=129.78s
          fold 2/5 | acc=0.96729 | running_mean=0.96526 | time=108.52s
          fold 3/5 | acc=0.96781 | running_mean=0.96611 | time=103.73s
          fold 4/5 | acc=0.96354 | running_mean=0.96547 | time=116.31s
          fold 5/5 | acc=0.96781 | running_mean=0.96594 | time=104.02s
       GWO RF: 44/50 | iter=4/4 | last=0.96594 | best=0.97244
          fold 1/5 | acc=0.97083 | running_mean=0.97083 | time=130.35s
          fold 2/5 | acc=0.97219 | running_mean=0.97151 | time=156.40s
          fold 3/5 | acc=0.97385 | running_mean=0.97229 | time=165.62s
          fold 4/5 | acc=0.97052 | running_mean=0.97185 | time=158.42s
          fold 5/5 | acc=0.97333 | running_mean=0.97215 | time=168.62s
       GWO RF: 45/50 | iter=4/4 | last=0.97215 | best=0.97244
          fold 1/5 | acc=0.97208 | running_mean=0.97208 | time=169.11s
          fold 2/5 | acc=0.97365 | running_mean=0.97286 | time=176.22s
          fold 3/5 | acc=0.97552 | running_mean=0.97375 | time=154.36s
          fold 4/5 | acc=0.97115 | running_mean=0.97310 | time=163.12s
          fold 5/5 | acc=0.97562 | running_mean=0.97360 | time=162.38s
       GWO RF: 46/50 | iter=4/4 | last=0.97360 | best=0.97244
          fold 1/5 | acc=0.97177 | running_mean=0.97177 | time=149.99s
          fold 2/5 | acc=0.97313 | running_mean=0.97245 | time=152.78s
          fold 3/5 | acc=0.97437 | running_mean=0.97309 | time=145.02s
          fold 4/5 | acc=0.97104 | running_mean=0.97258 | time=149.27s
          fold 5/5 | acc=0.97385 | running_mean=0.97283 | time=159.46s
       GWO RF: 47/50 | iter=4/4 | last=0.97283 | best=0.97244

In [ ]:
run_gwo_model_with_policy('GB')

[ResourcePolicy] model=GB (HEAVY) | free_ram=6.09 GB | n_jobs_cv=1 | n_jobs_opt=2

In [62]:
run_gwo_model("XGB")

XGB        | Scaler: MinMax     | Available RAM: 5.22 GB | Kernel RSS: 248.6 MB
       Memory cleanup -> gc_collected=67, available=5.21 GB, used=66.9%, rss=248.6 MB
       Running 50 evaluations with n_jobs_cv=1, n_jobs_opt=2
       GWO progress for XGB: 0/50 evaluations
       GWO XGB: initializing population (10 wolves)...
          fold 1/5 | acc=0.97823 | running_mean=0.97823 | time=2.11s
          fold 2/5 | acc=0.97844 | running_mean=0.97833 | time=1.81s
          fold 3/5 | acc=0.97927 | running_mean=0.97865 | time=1.79s
          fold 4/5 | acc=0.97813 | running_mean=0.97852 | time=1.97s
          fold 5/5 | acc=0.97917 | running_mean=0.97865 | time=1.99s
       GWO XGB: init 1/10 | last=0.97865 | best=0.97865
          fold 1/5 | acc=0.97875 | running_mean=0.97875 | time=2.76s
          fold 2/5 | acc=0.98146 | running_mean=0.98010 | time=3.64s
          fold 3/5 | acc=0.98125 | running_mean=0.98049 | time=3.09s
          fold 4/5 | acc=0.98010 | running_mean=0.98039 | time=2.74s
          fold 5/5 | acc=0.97948 | running_mean=0.98021 | time=2.96s
       GWO XGB: init 2/10 | last=0.98021 | best=0.98021
          fold 1/5 | acc=0.97937 | running_mean=0.97937 | time=1.81s
          fold 2/5 | acc=0.97927 | running_mean=0.97932 | time=1.61s
          fold 3/5 | acc=0.98062 | running_mean=0.97976 | time=2.32s
          fold 4/5 | acc=0.97906 | running_mean=0.97958 | time=1.47s
          fold 5/5 | acc=0.97979 | running_mean=0.97962 | time=1.47s
       GWO XGB: init 3/10 | last=0.97962 | best=0.98021
          fold 1/5 | acc=0.93177 | running_mean=0.93177 | time=1.52s
          fold 2/5 | acc=0.93760 | running_mean=0.93469 | time=1.37s
          fold 3/5 | acc=0.93490 | running_mean=0.93476 | time=1.00s
          fold 4/5 | acc=0.93021 | running_mean=0.93362 | time=1.10s
          fold 5/5 | acc=0.93240 | running_mean=0.93338 | time=1.14s
       GWO XGB: init 4/10 | last=0.93338 | best=0.98021
          fold 1/5 | acc=0.95188 | running_mean=0.95188 | time=0.70s
          fold 2/5 | acc=0.95708 | running_mean=0.95448 | time=0.52s
          fold 3/5 | acc=0.95698 | running_mean=0.95531 | time=0.57s
          fold 4/5 | acc=0.95562 | running_mean=0.95539 | time=0.57s
          fold 5/5 | acc=0.95437 | running_mean=0.95519 | time=0.68s
       GWO XGB: init 5/10 | last=0.95519 | best=0.98021
          fold 1/5 | acc=0.97469 | running_mean=0.97469 | time=1.90s
          fold 2/5 | acc=0.97750 | running_mean=0.97609 | time=2.00s
          fold 3/5 | acc=0.97740 | running_mean=0.97653 | time=1.82s
          fold 4/5 | acc=0.97677 | running_mean=0.97659 | time=1.76s
          fold 5/5 | acc=0.97667 | running_mean=0.97660 | time=1.94s
       GWO XGB: init 6/10 | last=0.97660 | best=0.98021
          fold 1/5 | acc=0.97844 | running_mean=0.97844 | time=1.18s
          fold 2/5 | acc=0.97719 | running_mean=0.97781 | time=1.11s
          fold 3/5 | acc=0.97937 | running_mean=0.97833 | time=1.10s
          fold 4/5 | acc=0.98188 | running_mean=0.97922 | time=1.10s
          fold 5/5 | acc=0.98052 | running_mean=0.97948 | time=1.13s
       GWO XGB: init 7/10 | last=0.97948 | best=0.98021
          fold 1/5 | acc=0.98313 | running_mean=0.98313 | time=1.60s
          fold 2/5 | acc=0.98469 | running_mean=0.98391 | time=1.65s
          fold 3/5 | acc=0.98292 | running_mean=0.98358 | time=1.57s
          fold 4/5 | acc=0.98521 | running_mean=0.98398 | time=1.52s
          fold 5/5 | acc=0.98281 | running_mean=0.98375 | time=1.66s
       GWO XGB: init 8/10 | last=0.98375 | best=0.98375
          fold 1/5 | acc=0.94563 | running_mean=0.94563 | time=1.48s
          fold 2/5 | acc=0.94729 | running_mean=0.94646 | time=1.44s
          fold 3/5 | acc=0.95156 | running_mean=0.94816 | time=1.53s
          fold 4/5 | acc=0.94688 | running_mean=0.94784 | time=1.65s
          fold 5/5 | acc=0.94677 | running_mean=0.94763 | time=1.44s
       GWO XGB: init 9/10 | last=0.94763 | best=0.98375
          fold 1/5 | acc=0.98500 | running_mean=0.98500 | time=0.89s
          fold 2/5 | acc=0.98500 | running_mean=0.98500 | time=0.78s
          fold 3/5 | acc=0.98552 | running_mean=0.98517 | time=0.80s
          fold 4/5 | acc=0.98677 | running_mean=0.98557 | time=0.93s
          fold 5/5 | acc=0.98458 | running_mean=0.98538 | time=1.15s
       GWO XGB: init 10/10 | last=0.98538 | best=0.98538
       GWO XGB: init done → α=0.98538 β=0.98375 δ=0.98021
          fold 1/5 | acc=0.97823 | running_mean=0.97823 | time=2.21s
          fold 2/5 | acc=0.97844 | running_mean=0.97833 | time=1.87s
          fold 3/5 | acc=0.97927 | running_mean=0.97865 | time=1.99s
          fold 4/5 | acc=0.97813 | running_mean=0.97852 | time=1.82s
          fold 5/5 | acc=0.97917 | running_mean=0.97865 | time=2.15s
       GWO XGB: 11/50 | iter=1/4 | last=0.97865 | best=0.98538
          fold 1/5 | acc=0.97875 | running_mean=0.97875 | time=2.84s
          fold 2/5 | acc=0.98146 | running_mean=0.98010 | time=3.06s
          fold 3/5 | acc=0.98125 | running_mean=0.98049 | time=2.67s
          fold 4/5 | acc=0.98010 | running_mean=0.98039 | time=2.76s
          fold 5/5 | acc=0.97948 | running_mean=0.98021 | time=3.49s
       GWO XGB: 12/50 | iter=1/4 | last=0.98021 | best=0.98538
          fold 1/5 | acc=0.97937 | running_mean=0.97937 | time=1.68s
          fold 2/5 | acc=0.97927 | running_mean=0.97932 | time=1.81s
          fold 3/5 | acc=0.98062 | running_mean=0.97976 | time=1.63s
          fold 4/5 | acc=0.97906 | running_mean=0.97958 | time=1.86s
          fold 5/5 | acc=0.97979 | running_mean=0.97962 | time=1.72s
       GWO XGB: 13/50 | iter=1/4 | last=0.97962 | best=0.98538
          fold 1/5 | acc=0.93177 | running_mean=0.93177 | time=1.33s
          fold 2/5 | acc=0.93760 | running_mean=0.93469 | time=1.33s
          fold 3/5 | acc=0.93490 | running_mean=0.93476 | time=1.18s
          fold 4/5 | acc=0.93021 | running_mean=0.93362 | time=1.01s
          fold 5/5 | acc=0.93240 | running_mean=0.93338 | time=1.23s
       GWO XGB: 14/50 | iter=1/4 | last=0.93338 | best=0.98538
          fold 1/5 | acc=0.95188 | running_mean=0.95188 | time=0.71s
          fold 2/5 | acc=0.95708 | running_mean=0.95448 | time=0.79s
          fold 3/5 | acc=0.95698 | running_mean=0.95531 | time=0.67s
          fold 4/5 | acc=0.95562 | running_mean=0.95539 | time=0.64s
          fold 5/5 | acc=0.95437 | running_mean=0.95519 | time=0.56s
       GWO XGB: 15/50 | iter=1/4 | last=0.95519 | best=0.98538
          fold 1/5 | acc=0.97469 | running_mean=0.97469 | time=1.84s
          fold 2/5 | acc=0.97750 | running_mean=0.97609 | time=1.79s
          fold 3/5 | acc=0.97740 | running_mean=0.97653 | time=1.82s
          fold 4/5 | acc=0.97677 | running_mean=0.97659 | time=1.65s
          fold 5/5 | acc=0.97667 | running_mean=0.97660 | time=2.05s
       GWO XGB: 16/50 | iter=1/4 | last=0.97660 | best=0.98538
          fold 1/5 | acc=0.97844 | running_mean=0.97844 | time=1.13s
          fold 2/5 | acc=0.97719 | running_mean=0.97781 | time=1.13s
          fold 3/5 | acc=0.97937 | running_mean=0.97833 | time=1.06s
          fold 4/5 | acc=0.98188 | running_mean=0.97922 | time=1.18s
          fold 5/5 | acc=0.98052 | running_mean=0.97948 | time=1.13s
       GWO XGB: 17/50 | iter=1/4 | last=0.97948 | best=0.98538
          fold 1/5 | acc=0.98313 | running_mean=0.98313 | time=1.94s
          fold 2/5 | acc=0.98469 | running_mean=0.98391 | time=1.70s
          fold 3/5 | acc=0.98292 | running_mean=0.98358 | time=1.65s
          fold 4/5 | acc=0.98521 | running_mean=0.98398 | time=1.59s
          fold 5/5 | acc=0.98281 | running_mean=0.98375 | time=1.64s
       GWO XGB: 18/50 | iter=1/4 | last=0.98375 | best=0.98538
          fold 1/5 | acc=0.94563 | running_mean=0.94563 | time=1.70s
          fold 2/5 | acc=0.94729 | running_mean=0.94646 | time=1.51s
          fold 3/5 | acc=0.95156 | running_mean=0.94816 | time=1.53s
          fold 4/5 | acc=0.94688 | running_mean=0.94784 | time=1.72s
          fold 5/5 | acc=0.94677 | running_mean=0.94763 | time=1.57s
       GWO XGB: 19/50 | iter=1/4 | last=0.94763 | best=0.98538
          fold 1/5 | acc=0.98500 | running_mean=0.98500 | time=0.94s
          fold 2/5 | acc=0.98500 | running_mean=0.98500 | time=0.97s
          fold 3/5 | acc=0.98552 | running_mean=0.98517 | time=1.06s
          fold 4/5 | acc=0.98677 | running_mean=0.98557 | time=0.88s
          fold 5/5 | acc=0.98458 | running_mean=0.98538 | time=0.90s
       GWO XGB: 20/50 | iter=1/4 | last=0.98538 | best=0.98538
       GWO XGB: iter 1/4 done → α=0.98538 β=0.98538 δ=0.98375
          fold 1/5 | acc=0.97958 | running_mean=0.97958 | time=1.38s
          fold 2/5 | acc=0.98167 | running_mean=0.98063 | time=1.33s
          fold 3/5 | acc=0.98208 | running_mean=0.98111 | time=1.65s
          fold 4/5 | acc=0.98385 | running_mean=0.98180 | time=1.37s
          fold 5/5 | acc=0.98240 | running_mean=0.98192 | time=1.36s
       GWO XGB: 21/50 | iter=2/4 | last=0.98192 | best=0.98538
          fold 1/5 | acc=0.97906 | running_mean=0.97906 | time=1.88s
          fold 2/5 | acc=0.98104 | running_mean=0.98005 | time=1.76s
          fold 3/5 | acc=0.97990 | running_mean=0.98000 | time=2.04s
          fold 4/5 | acc=0.98104 | running_mean=0.98026 | time=1.96s
          fold 5/5 | acc=0.97833 | running_mean=0.97988 | time=2.10s
       GWO XGB: 22/50 | iter=2/4 | last=0.97988 | best=0.98538
          fold 1/5 | acc=0.98906 | running_mean=0.98906 | time=1.13s
          fold 2/5 | acc=0.99021 | running_mean=0.98964 | time=1.10s
          fold 3/5 | acc=0.98885 | running_mean=0.98938 | time=1.15s
          fold 4/5 | acc=0.99052 | running_mean=0.98966 | time=1.08s
          fold 5/5 | acc=0.99031 | running_mean=0.98979 | time=1.14s
       GWO XGB: 23/50 | iter=2/4 | last=0.98979 | best=0.98538
          fold 1/5 | acc=0.97146 | running_mean=0.97146 | time=1.72s
          fold 2/5 | acc=0.97219 | running_mean=0.97182 | time=1.37s
          fold 3/5 | acc=0.97260 | running_mean=0.97208 | time=1.33s
          fold 4/5 | acc=0.97083 | running_mean=0.97177 | time=1.51s
          fold 5/5 | acc=0.97208 | running_mean=0.97183 | time=1.42s
       GWO XGB: 24/50 | iter=2/4 | last=0.97183 | best=0.98538
          fold 1/5 | acc=0.97208 | running_mean=0.97208 | time=0.81s
          fold 2/5 | acc=0.97417 | running_mean=0.97313 | time=0.76s
          fold 3/5 | acc=0.97542 | running_mean=0.97389 | time=0.77s
          fold 4/5 | acc=0.97490 | running_mean=0.97414 | time=0.65s
          fold 5/5 | acc=0.97490 | running_mean=0.97429 | time=0.75s
       GWO XGB: 25/50 | iter=2/4 | last=0.97429 | best=0.98538
          fold 1/5 | acc=0.97833 | running_mean=0.97833 | time=0.80s
          fold 2/5 | acc=0.97958 | running_mean=0.97896 | time=0.67s
          fold 3/5 | acc=0.98104 | running_mean=0.97965 | time=0.74s
          fold 4/5 | acc=0.97937 | running_mean=0.97958 | time=0.67s
          fold 5/5 | acc=0.97927 | running_mean=0.97952 | time=0.76s
       GWO XGB: 26/50 | iter=2/4 | last=0.97952 | best=0.98538
          fold 1/5 | acc=0.98385 | running_mean=0.98385 | time=3.17s
          fold 2/5 | acc=0.98365 | running_mean=0.98375 | time=3.24s
          fold 3/5 | acc=0.98479 | running_mean=0.98410 | time=2.61s
          fold 4/5 | acc=0.98396 | running_mean=0.98406 | time=2.70s
          fold 5/5 | acc=0.98469 | running_mean=0.98419 | time=2.25s
       GWO XGB: 27/50 | iter=2/4 | last=0.98419 | best=0.98538
          fold 1/5 | acc=0.98010 | running_mean=0.98010 | time=1.28s
          fold 2/5 | acc=0.98188 | running_mean=0.98099 | time=1.25s
          fold 3/5 | acc=0.98260 | running_mean=0.98153 | time=1.35s
          fold 4/5 | acc=0.98292 | running_mean=0.98187 | time=1.25s
          fold 5/5 | acc=0.98302 | running_mean=0.98210 | time=1.28s
       GWO XGB: 28/50 | iter=2/4 | last=0.98210 | best=0.98538
          fold 1/5 | acc=0.97990 | running_mean=0.97990 | time=1.21s
          fold 2/5 | acc=0.98188 | running_mean=0.98089 | time=1.03s
          fold 3/5 | acc=0.98052 | running_mean=0.98076 | time=1.06s
          fold 4/5 | acc=0.97979 | running_mean=0.98052 | time=1.02s
          fold 5/5 | acc=0.98125 | running_mean=0.98067 | time=1.33s
       GWO XGB: 29/50 | iter=2/4 | last=0.98067 | best=0.98538
          fold 1/5 | acc=0.97719 | running_mean=0.97719 | time=0.99s
          fold 2/5 | acc=0.97990 | running_mean=0.97854 | time=0.95s
          fold 3/5 | acc=0.97906 | running_mean=0.97872 | time=0.90s
          fold 4/5 | acc=0.98177 | running_mean=0.97948 | time=0.94s
          fold 5/5 | acc=0.98000 | running_mean=0.97958 | time=1.01s
       GWO XGB: 30/50 | iter=2/4 | last=0.97958 | best=0.98538
       GWO XGB: iter 2/4 done → α=0.98979 β=0.98538 δ=0.98538
          fold 1/5 | acc=0.96781 | running_mean=0.96781 | time=1.30s
          fold 2/5 | acc=0.97156 | running_mean=0.96969 | time=1.25s
          fold 3/5 | acc=0.96948 | running_mean=0.96962 | time=1.33s
          fold 4/5 | acc=0.96823 | running_mean=0.96927 | time=1.48s
          fold 5/5 | acc=0.96948 | running_mean=0.96931 | time=1.29s
       GWO XGB: 31/50 | iter=3/4 | last=0.96931 | best=0.98979
          fold 1/5 | acc=0.98104 | running_mean=0.98104 | time=1.02s
          fold 2/5 | acc=0.98406 | running_mean=0.98255 | time=0.99s
          fold 3/5 | acc=0.98188 | running_mean=0.98233 | time=1.00s
          fold 4/5 | acc=0.98438 | running_mean=0.98284 | time=1.12s
          fold 5/5 | acc=0.98375 | running_mean=0.98302 | time=1.11s
       GWO XGB: 32/50 | iter=3/4 | last=0.98302 | best=0.98979
          fold 1/5 | acc=0.97021 | running_mean=0.97021 | time=1.23s
          fold 2/5 | acc=0.97010 | running_mean=0.97016 | time=1.40s
          fold 3/5 | acc=0.97125 | running_mean=0.97052 | time=1.31s
          fold 4/5 | acc=0.97208 | running_mean=0.97091 | time=1.22s
          fold 5/5 | acc=0.97052 | running_mean=0.97083 | time=1.34s
       GWO XGB: 33/50 | iter=3/4 | last=0.97083 | best=0.98979
          fold 1/5 | acc=0.99417 | running_mean=0.99417 | time=1.38s
          fold 2/5 | acc=0.99260 | running_mean=0.99339 | time=1.50s
          fold 3/5 | acc=0.99354 | running_mean=0.99344 | time=1.52s
          fold 4/5 | acc=0.99354 | running_mean=0.99346 | time=1.40s
          fold 5/5 | acc=0.99438 | running_mean=0.99365 | time=1.44s
       GWO XGB: 34/50 | iter=3/4 | last=0.99365 | best=0.98979
          fold 1/5 | acc=0.97500 | running_mean=0.97500 | time=0.99s
          fold 2/5 | acc=0.97708 | running_mean=0.97604 | time=0.87s
          fold 3/5 | acc=0.97740 | running_mean=0.97649 | time=0.86s
          fold 4/5 | acc=0.97802 | running_mean=0.97688 | time=0.91s
          fold 5/5 | acc=0.97562 | running_mean=0.97662 | time=0.83s
       GWO XGB: 35/50 | iter=3/4 | last=0.97662 | best=0.98979
          fold 1/5 | acc=0.97719 | running_mean=0.97719 | time=0.89s
          fold 2/5 | acc=0.97844 | running_mean=0.97781 | time=0.91s
          fold 3/5 | acc=0.97719 | running_mean=0.97760 | time=1.15s
          fold 4/5 | acc=0.97813 | running_mean=0.97773 | time=0.91s
          fold 5/5 | acc=0.97813 | running_mean=0.97781 | time=0.88s
       GWO XGB: 36/50 | iter=3/4 | last=0.97781 | best=0.98979
          fold 1/5 | acc=0.85542 | running_mean=0.85542 | time=0.49s
          fold 2/5 | acc=0.86260 | running_mean=0.85901 | time=0.52s
          fold 3/5 | acc=0.86052 | running_mean=0.85951 | time=0.54s
          fold 4/5 | acc=0.85708 | running_mean=0.85891 | time=0.49s
          fold 5/5 | acc=0.85562 | running_mean=0.85825 | time=0.52s
       GWO XGB: 37/50 | iter=3/4 | last=0.85825 | best=0.98979
          fold 1/5 | acc=0.98573 | running_mean=0.98573 | time=0.87s
          fold 2/5 | acc=0.98594 | running_mean=0.98583 | time=0.90s
          fold 3/5 | acc=0.98677 | running_mean=0.98615 | time=0.94s
          fold 4/5 | acc=0.99031 | running_mean=0.98719 | time=0.90s
          fold 5/5 | acc=0.98531 | running_mean=0.98681 | time=0.91s
       GWO XGB: 38/50 | iter=3/4 | last=0.98681 | best=0.98979
          fold 1/5 | acc=0.97958 | running_mean=0.97958 | time=0.93s
          fold 2/5 | acc=0.97688 | running_mean=0.97823 | time=0.90s
          fold 3/5 | acc=0.97667 | running_mean=0.97771 | time=0.89s
          fold 4/5 | acc=0.97906 | running_mean=0.97805 | time=0.87s
          fold 5/5 | acc=0.97885 | running_mean=0.97821 | time=0.90s
       GWO XGB: 39/50 | iter=3/4 | last=0.97821 | best=0.98979
          fold 1/5 | acc=0.98458 | running_mean=0.98458 | time=0.99s
          fold 2/5 | acc=0.98750 | running_mean=0.98604 | time=1.12s
          fold 3/5 | acc=0.98615 | running_mean=0.98608 | time=1.13s
          fold 4/5 | acc=0.98781 | running_mean=0.98651 | time=1.23s
          fold 5/5 | acc=0.98781 | running_mean=0.98677 | time=1.10s
       GWO XGB: 40/50 | iter=3/4 | last=0.98677 | best=0.98979
       GWO XGB: iter 3/4 done → α=0.99365 β=0.98979 δ=0.98681
          fold 1/5 | acc=0.99125 | running_mean=0.99125 | time=1.37s
          fold 2/5 | acc=0.99042 | running_mean=0.99083 | time=1.40s
          fold 3/5 | acc=0.98865 | running_mean=0.99010 | time=1.47s
          fold 4/5 | acc=0.99156 | running_mean=0.99047 | time=1.52s
          fold 5/5 | acc=0.99042 | running_mean=0.99046 | time=1.48s
       GWO XGB: 41/50 | iter=4/4 | last=0.99046 | best=0.99365
          fold 1/5 | acc=0.98729 | running_mean=0.98729 | time=1.26s
          fold 2/5 | acc=0.98708 | running_mean=0.98719 | time=1.25s
          fold 3/5 | acc=0.98875 | running_mean=0.98771 | time=1.21s
          fold 4/5 | acc=0.98990 | running_mean=0.98826 | time=1.20s
          fold 5/5 | acc=0.98719 | running_mean=0.98804 | time=1.28s
       GWO XGB: 42/50 | iter=4/4 | last=0.98804 | best=0.99365
          fold 1/5 | acc=0.99240 | running_mean=0.99240 | time=1.31s
          fold 2/5 | acc=0.99177 | running_mean=0.99208 | time=1.26s
          fold 3/5 | acc=0.99208 | running_mean=0.99208 | time=1.40s
          fold 4/5 | acc=0.99260 | running_mean=0.99221 | time=1.37s
          fold 5/5 | acc=0.99292 | running_mean=0.99235 | time=1.36s
       GWO XGB: 43/50 | iter=4/4 | last=0.99235 | best=0.99365
          fold 1/5 | acc=0.99396 | running_mean=0.99396 | time=1.16s
          fold 2/5 | acc=0.99062 | running_mean=0.99229 | time=1.16s
          fold 3/5 | acc=0.99229 | running_mean=0.99229 | time=1.20s
          fold 4/5 | acc=0.99187 | running_mean=0.99219 | time=1.26s
          fold 5/5 | acc=0.99292 | running_mean=0.99233 | time=1.19s
       GWO XGB: 44/50 | iter=4/4 | last=0.99233 | best=0.99365
          fold 1/5 | acc=0.99073 | running_mean=0.99073 | time=1.22s
          fold 2/5 | acc=0.98958 | running_mean=0.99016 | time=1.50s
          fold 3/5 | acc=0.98990 | running_mean=0.99007 | time=1.33s
          fold 4/5 | acc=0.99115 | running_mean=0.99034 | time=1.23s
          fold 5/5 | acc=0.99135 | running_mean=0.99054 | time=1.20s
       GWO XGB: 45/50 | iter=4/4 | last=0.99054 | best=0.99365
          fold 1/5 | acc=0.99375 | running_mean=0.99375 | time=1.34s
          fold 2/5 | acc=0.99167 | running_mean=0.99271 | time=1.43s
          fold 3/5 | acc=0.99260 | running_mean=0.99267 | time=1.23s
          fold 4/5 | acc=0.99458 | running_mean=0.99315 | time=1.24s
          fold 5/5 | acc=0.99313 | running_mean=0.99315 | time=1.42s
       GWO XGB: 46/50 | iter=4/4 | last=0.99315 | best=0.99365
          fold 1/5 | acc=0.98760 | running_mean=0.98760 | time=1.38s
          fold 2/5 | acc=0.98927 | running_mean=0.98844 | time=1.18s
          fold 3/5 | acc=0.98844 | running_mean=0.98844 | time=1.11s
          fold 4/5 | acc=0.98896 | running_mean=0.98857 | time=1.13s
          fold 5/5 | acc=0.98823 | running_mean=0.98850 | time=1.30s
       GWO XGB: 47/50 | iter=4/4 | last=0.98850 | best=0.99365
          fold 1/5 | acc=0.98854 | running_mean=0.98854 | time=1.27s
          fold 2/5 | acc=0.98969 | running_mean=0.98911 | time=1.19s
          fold 3/5 | acc=0.98813 | running_mean=0.98878 | time=1.20s
          fold 4/5 | acc=0.98906 | running_mean=0.98885 | time=1.44s

{'status': 'completed',
 'best':   Model Optimal_Scaler  Best_CV_Mean  Best_Iteration  n_estimators  learning_rate  max_depth  min_child_weight  subsample  colsample_bytree     gamma     reg_alpha    reg_lambda  random_state
 0   XGB         MinMax      0.993646              34           427            0.5          4                 1   0.756243          0.920541  0.331947  1.374810e-07  6.711895e-07            42,
 'history':    Model  Iteration   CV_Mean  Best_Score_So_Far  Iteration_Runtime_Sec
 0    XGB          1  0.978646           0.978646               9.686611
 1    XGB          2  0.980208           0.980208              15.212054
 2    XGB          3  0.979625           0.980208               8.686960
 3    XGB          4  0.933375           0.980208               6.142359
 4    XGB          5  0.955188           0.980208               3.052778
 5    XGB          6  0.976604           0.980208               9.433269
 6    XGB          7  0.979479           0.980208               5.632360
 7    XGB          8  0.983750           0.983750               8.015264
 8    XGB          9  0.947625           0.983750               7.549402
 9    XGB         10  0.985375           0.985375               4.555138
 10   XGB         11  0.978646           0.985375              10.061121
 11   XGB         12  0.980208           0.985375              14.821579
 12   XGB         13  0.979625           0.985375               8.720049
 13   XGB         14  0.933375           0.985375               6.089309
 14   XGB         15  0.955188           0.985375               3.392267
 15   XGB         16  0.976604           0.985375               9.166667
 16   XGB         17  0.979479           0.985375               5.639146
 17   XGB         18  0.983750           0.985375               8.529153
 18   XGB         19  0.947625           0.985375               8.053817
 19   XGB         20  0.985375           0.985375               4.755533
 20   XGB         21  0.981917           0.989792               7.109462
 21   XGB         22  0.979875           0.989792               9.763307
 22   XGB         23  0.989792           0.989792               5.617527
 23   XGB         24  0.971833           0.989792               7.357420
 24   XGB         25  0.974292           0.989792               3.746076
 25   XGB         26  0.979521           0.989792               3.642433
 26   XGB         27  0.984187           0.989792              13.979163
 27   XGB         28  0.982104           0.989792               6.424965
 28   XGB         29  0.980667           0.989792               5.658345
 29   XGB         30  0.979583           0.989792               4.807027
 30   XGB         31  0.969313           0.993646               6.659396
 31   XGB         32  0.983021           0.993646               5.264195
 32   XGB         33  0.970833           0.993646               6.513981
 33   XGB         34  0.993646           0.993646               7.257116
 34   XGB         35  0.976625           0.993646               4.469935
 35   XGB         36  0.977812           0.993646               4.756160
 36   XGB         37  0.858250           0.993646               2.570449
 37   XGB         38  0.986812           0.993646               4.529626
 38   XGB         39  0.978208           0.993646               4.506164
 39   XGB         40  0.986771           0.993646               5.591860
 40   XGB         41  0.990458           0.993646               7.258586
 41   XGB         42  0.988042           0.993646               6.215078
 42   XGB         43  0.992354           0.993646               6.705326
 43   XGB         44  0.992333           0.993646               5.990898
 44   XGB         45  0.990542           0.993646               6.496230
 45   XGB         46  0.993146           0.993646               6.677920
 46   XGB         47  0.988500           0.993646               6.114588
 47   XGB         48  0.988937           0.993646               6.428639
 48   XGB         49  0.983500           0.993646               6.162799
 49   XGB         50  0.978187           0.993646               6.576234,
 'summary':   Method Model Optimal_Scaler      Split  Accuracy  Precision    Recall        F1     Kappa       MCC       AUC   LogLoss  Accuracy_CI_Lower  Accuracy_CI_Upper  Precision_CI_Lower  Precision_CI_Upper  Recall_CI_Lower  Recall_CI_Upper  F1_CI_Lower  F1_CI_Upper  AUC_CI_Lower  AUC_CI_Upper  LogLoss_CI_Lower  LogLoss_CI_Upper  Kappa_CI_Lower  Kappa_CI_Upper  MCC_CI_Lower  MCC_CI_Upper
 0    GWO   XGB         MinMax  Train_OOF  0.993646   0.994229  0.995820  0.995024  0.986235  0.986238  0.999724  0.022391           0.992917           0.994333            0.993357            0.995098         0.995103         0.996497     0.994452     0.995561      0.999657      0.999781          0.021061          0.023731        0.984658        0.987708      0.984662      0.987715
 1    GWO   XGB         MinMax       Test  0.997333   0.997780  0.998041  0.997910  0.994226  0.994226  0.999825  0.016183           0.996417           0.998250            0.996728            0.998709         0.997004         0.998956     0.997174     0.998621      0.999669      0.999942          0.013868          0.018803        0.992243        0.996194      0.992243      0.996194,
 'timing':   Model  GWO_Search_Sec  GWO_Evaluation_Sec  GWO_Total_Sec  Best_CV_Mean
 0   XGB      342.092357           92.114863     434.491233      0.993646}

In [46]:
run_gwo_model("CB")

CB         | Scaler: MinMax     | Available RAM: 2.48 GB | Kernel RSS: 125.5 MB
       Memory cleanup -> gc_collected=0, available=2.42 GB, used=84.6%, rss=192.2 MB
       Running 50 evaluations with n_jobs_cv=1, n_jobs_opt=8
       GWO progress for CB: 0/50 evaluations
       GWO CB: initializing population (10 wolves)...
          fold 1/5 | acc=0.98333 | running_mean=0.98333 | time=11.40s
          fold 2/5 | acc=0.98219 | running_mean=0.98276 | time=12.53s
          fold 3/5 | acc=0.98823 | running_mean=0.98458 | time=12.27s
          fold 4/5 | acc=0.98740 | running_mean=0.98529 | time=12.71s
          fold 5/5 | acc=0.98354 | running_mean=0.98494 | time=12.64s
       GWO CB: init 1/10 | last=0.98494 | best=0.98494
          fold 1/5 | acc=0.98250 | running_mean=0.98250 | time=5.97s
          fold 2/5 | acc=0.98271 | running_mean=0.98260 | time=5.92s
          fold 3/5 | acc=0.98510 | running_mean=0.98344 | time=5.27s
          fold 4/5 | acc=0.98479 | running_mean=0.98378 | time=5.16s
          fold 5/5 | acc=0.98271 | running_mean=0.98356 | time=4.94s
       GWO CB: init 2/10 | last=0.98356 | best=0.98494
          fold 1/5 | acc=0.98906 | running_mean=0.98906 | time=5.37s
          fold 2/5 | acc=0.98813 | running_mean=0.98859 | time=5.48s
          fold 3/5 | acc=0.98948 | running_mean=0.98889 | time=5.88s
          fold 4/5 | acc=0.98979 | running_mean=0.98911 | time=5.96s
          fold 5/5 | acc=0.99042 | running_mean=0.98938 | time=5.93s
       GWO CB: init 3/10 | last=0.98938 | best=0.98938
          fold 1/5 | acc=0.98906 | running_mean=0.98906 | time=11.80s
          fold 2/5 | acc=0.98740 | running_mean=0.98823 | time=11.74s
          fold 3/5 | acc=0.99042 | running_mean=0.98896 | time=12.26s
          fold 4/5 | acc=0.99115 | running_mean=0.98951 | time=12.02s
          fold 5/5 | acc=0.98990 | running_mean=0.98958 | time=11.98s
       GWO CB: init 4/10 | last=0.98958 | best=0.98958
          fold 1/5 | acc=0.94521 | running_mean=0.94521 | time=7.91s
          fold 2/5 | acc=0.94729 | running_mean=0.94625 | time=7.46s
          fold 3/5 | acc=0.95073 | running_mean=0.94774 | time=10.39s
          fold 4/5 | acc=0.94844 | running_mean=0.94792 | time=10.46s
          fold 5/5 | acc=0.94979 | running_mean=0.94829 | time=9.83s
       GWO CB: init 5/10 | last=0.94829 | best=0.98958
          fold 1/5 | acc=0.99146 | running_mean=0.99146 | time=8.66s
          fold 2/5 | acc=0.98687 | running_mean=0.98917 | time=9.57s
          fold 3/5 | acc=0.99062 | running_mean=0.98965 | time=8.29s
          fold 4/5 | acc=0.99187 | running_mean=0.99021 | time=8.27s
          fold 5/5 | acc=0.99167 | running_mean=0.99050 | time=9.22s
       GWO CB: init 6/10 | last=0.99050 | best=0.99050
          fold 1/5 | acc=0.91375 | running_mean=0.91375 | time=1.36s
          fold 2/5 | acc=0.92115 | running_mean=0.91745 | time=1.33s
          fold 3/5 | acc=0.91906 | running_mean=0.91799 | time=1.28s
          fold 4/5 | acc=0.91833 | running_mean=0.91807 | time=1.35s
          fold 5/5 | acc=0.91552 | running_mean=0.91756 | time=1.30s
       GWO CB: init 7/10 | last=0.91756 | best=0.99050
          fold 1/5 | acc=0.97479 | running_mean=0.97479 | time=15.98s
          fold 2/5 | acc=0.97479 | running_mean=0.97479 | time=14.93s
          fold 3/5 | acc=0.97781 | running_mean=0.97580 | time=14.58s
          fold 4/5 | acc=0.97729 | running_mean=0.97617 | time=14.69s
          fold 5/5 | acc=0.97625 | running_mean=0.97619 | time=15.72s
       GWO CB: init 8/10 | last=0.97619 | best=0.99050
          fold 1/5 | acc=0.90896 | running_mean=0.90896 | time=6.77s
          fold 2/5 | acc=0.91448 | running_mean=0.91172 | time=7.25s
          fold 3/5 | acc=0.91500 | running_mean=0.91281 | time=7.14s
          fold 4/5 | acc=0.91448 | running_mean=0.91323 | time=6.69s
          fold 5/5 | acc=0.91010 | running_mean=0.91260 | time=6.08s
       GWO CB: init 9/10 | last=0.91260 | best=0.99050
          fold 1/5 | acc=0.98906 | running_mean=0.98906 | time=7.74s
          fold 2/5 | acc=0.98813 | running_mean=0.98859 | time=7.93s
          fold 3/5 | acc=0.99031 | running_mean=0.98917 | time=7.47s
          fold 4/5 | acc=0.98802 | running_mean=0.98888 | time=7.88s
          fold 5/5 | acc=0.99010 | running_mean=0.98912 | time=9.06s
       GWO CB: init 10/10 | last=0.98912 | best=0.99050
       GWO CB: init done → α=0.99050 β=0.98958 δ=0.98938
          fold 1/5 | acc=0.98333 | running_mean=0.98333 | time=14.73s
          fold 2/5 | acc=0.98219 | running_mean=0.98276 | time=14.31s
          fold 3/5 | acc=0.98823 | running_mean=0.98458 | time=14.59s
          fold 4/5 | acc=0.98740 | running_mean=0.98529 | time=14.96s
          fold 5/5 | acc=0.98354 | running_mean=0.98494 | time=14.16s
       GWO CB: 11/50 | iter=1/4 | last=0.98494 | best=0.99050
          fold 1/5 | acc=0.98250 | running_mean=0.98250 | time=7.07s
          fold 2/5 | acc=0.98271 | running_mean=0.98260 | time=6.76s
          fold 3/5 | acc=0.98510 | running_mean=0.98344 | time=6.94s
          fold 4/5 | acc=0.98479 | running_mean=0.98378 | time=7.06s
          fold 5/5 | acc=0.98271 | running_mean=0.98356 | time=7.06s
       GWO CB: 12/50 | iter=1/4 | last=0.98356 | best=0.99050
          fold 1/5 | acc=0.98906 | running_mean=0.98906 | time=7.65s
          fold 2/5 | acc=0.98813 | running_mean=0.98859 | time=7.63s
          fold 3/5 | acc=0.98948 | running_mean=0.98889 | time=7.76s
          fold 4/5 | acc=0.98979 | running_mean=0.98911 | time=7.89s
          fold 5/5 | acc=0.99042 | running_mean=0.98938 | time=7.53s
       GWO CB: 13/50 | iter=1/4 | last=0.98938 | best=0.99050
          fold 1/5 | acc=0.98906 | running_mean=0.98906 | time=15.37s
          fold 2/5 | acc=0.98740 | running_mean=0.98823 | time=15.45s
          fold 3/5 | acc=0.99042 | running_mean=0.98896 | time=16.54s
          fold 4/5 | acc=0.99115 | running_mean=0.98951 | time=20.29s
          fold 5/5 | acc=0.98990 | running_mean=0.98958 | time=18.02s
       GWO CB: 14/50 | iter=1/4 | last=0.98958 | best=0.99050
          fold 1/5 | acc=0.94521 | running_mean=0.94521 | time=8.39s
          fold 2/5 | acc=0.94729 | running_mean=0.94625 | time=8.35s
          fold 3/5 | acc=0.95073 | running_mean=0.94774 | time=8.03s
          fold 4/5 | acc=0.94844 | running_mean=0.94792 | time=10.18s
          fold 5/5 | acc=0.94979 | running_mean=0.94829 | time=8.36s
       GWO CB: 15/50 | iter=1/4 | last=0.94829 | best=0.99050
          fold 1/5 | acc=0.99146 | running_mean=0.99146 | time=7.35s
          fold 2/5 | acc=0.98687 | running_mean=0.98917 | time=7.40s
          fold 3/5 | acc=0.99062 | running_mean=0.98965 | time=7.01s
          fold 4/5 | acc=0.99187 | running_mean=0.99021 | time=7.00s
          fold 5/5 | acc=0.99167 | running_mean=0.99050 | time=6.71s
       GWO CB: 16/50 | iter=1/4 | last=0.99050 | best=0.99050
          fold 1/5 | acc=0.91375 | running_mean=0.91375 | time=0.96s
          fold 2/5 | acc=0.92115 | running_mean=0.91745 | time=1.07s
          fold 3/5 | acc=0.91906 | running_mean=0.91799 | time=1.07s
          fold 4/5 | acc=0.91833 | running_mean=0.91807 | time=1.03s
          fold 5/5 | acc=0.91552 | running_mean=0.91756 | time=1.13s
       GWO CB: 17/50 | iter=1/4 | last=0.91756 | best=0.99050
          fold 1/5 | acc=0.97479 | running_mean=0.97479 | time=14.96s
          fold 2/5 | acc=0.97479 | running_mean=0.97479 | time=14.66s
          fold 3/5 | acc=0.97781 | running_mean=0.97580 | time=14.17s
          fold 4/5 | acc=0.97729 | running_mean=0.97617 | time=14.31s
          fold 5/5 | acc=0.97625 | running_mean=0.97619 | time=14.53s
       GWO CB: 18/50 | iter=1/4 | last=0.97619 | best=0.99050
          fold 1/5 | acc=0.90896 | running_mean=0.90896 | time=6.37s
          fold 2/5 | acc=0.91448 | running_mean=0.91172 | time=6.61s
          fold 3/5 | acc=0.91500 | running_mean=0.91281 | time=6.49s
          fold 4/5 | acc=0.91448 | running_mean=0.91323 | time=6.38s
          fold 5/5 | acc=0.91010 | running_mean=0.91260 | time=6.49s
       GWO CB: 19/50 | iter=1/4 | last=0.91260 | best=0.99050
          fold 1/5 | acc=0.98906 | running_mean=0.98906 | time=7.55s
          fold 2/5 | acc=0.98813 | running_mean=0.98859 | time=7.23s
          fold 3/5 | acc=0.99031 | running_mean=0.98917 | time=6.99s
          fold 4/5 | acc=0.98802 | running_mean=0.98888 | time=6.85s
          fold 5/5 | acc=0.99010 | running_mean=0.98912 | time=7.13s
       GWO CB: 20/50 | iter=1/4 | last=0.98912 | best=0.99050
       GWO CB: iter 1/4 done → α=0.99050 β=0.99050 δ=0.98958
          fold 1/5 | acc=0.98938 | running_mean=0.98938 | time=11.46s
          fold 2/5 | acc=0.98823 | running_mean=0.98880 | time=10.95s
          fold 3/5 | acc=0.99042 | running_mean=0.98934 | time=11.45s
          fold 4/5 | acc=0.99021 | running_mean=0.98956 | time=11.34s
          fold 5/5 | acc=0.98802 | running_mean=0.98925 | time=11.97s
       GWO CB: 21/50 | iter=2/4 | last=0.98925 | best=0.99050
          fold 1/5 | acc=0.98854 | running_mean=0.98854 | time=13.41s
          fold 2/5 | acc=0.98500 | running_mean=0.98677 | time=12.99s
          fold 3/5 | acc=0.98625 | running_mean=0.98660 | time=12.96s
          fold 4/5 | acc=0.99000 | running_mean=0.98745 | time=13.15s
          fold 5/5 | acc=0.98698 | running_mean=0.98735 | time=13.70s
       GWO CB: 22/50 | iter=2/4 | last=0.98735 | best=0.99050
          fold 1/5 | acc=0.99094 | running_mean=0.99094 | time=8.41s
          fold 2/5 | acc=0.99083 | running_mean=0.99089 | time=8.33s
          fold 3/5 | acc=0.99021 | running_mean=0.99066 | time=8.89s
          fold 4/5 | acc=0.99010 | running_mean=0.99052 | time=8.95s
          fold 5/5 | acc=0.99219 | running_mean=0.99085 | time=8.60s
       GWO CB: 23/50 | iter=2/4 | last=0.99085 | best=0.99050
          fold 1/5 | acc=0.97333 | running_mean=0.97333 | time=20.98s
          fold 2/5 | acc=0.97354 | running_mean=0.97344 | time=27.85s
          fold 3/5 | acc=0.97583 | running_mean=0.97424 | time=28.03s
          fold 4/5 | acc=0.97365 | running_mean=0.97409 | time=27.54s
          fold 5/5 | acc=0.97281 | running_mean=0.97383 | time=23.71s
       GWO CB: 24/50 | iter=2/4 | last=0.97383 | best=0.99050
          fold 1/5 | acc=0.98760 | running_mean=0.98760 | time=11.44s
          fold 2/5 | acc=0.98875 | running_mean=0.98818 | time=12.43s
          fold 3/5 | acc=0.98573 | running_mean=0.98736 | time=12.52s
          fold 4/5 | acc=0.98990 | running_mean=0.98799 | time=13.16s
          fold 5/5 | acc=0.99177 | running_mean=0.98875 | time=11.82s
       GWO CB: 25/50 | iter=2/4 | last=0.98875 | best=0.99050
          fold 1/5 | acc=0.98625 | running_mean=0.98625 | time=8.61s
          fold 2/5 | acc=0.98406 | running_mean=0.98516 | time=8.86s
          fold 3/5 | acc=0.98073 | running_mean=0.98368 | time=8.72s
          fold 4/5 | acc=0.98125 | running_mean=0.98307 | time=9.57s
          fold 5/5 | acc=0.98448 | running_mean=0.98335 | time=8.34s
       GWO CB: 26/50 | iter=2/4 | last=0.98335 | best=0.99050
          fold 1/5 | acc=0.98875 | running_mean=0.98875 | time=7.64s
          fold 2/5 | acc=0.98594 | running_mean=0.98734 | time=7.73s
          fold 3/5 | acc=0.98823 | running_mean=0.98764 | time=7.89s
          fold 4/5 | acc=0.99010 | running_mean=0.98826 | time=5.58s
          fold 5/5 | acc=0.98948 | running_mean=0.98850 | time=5.44s
       GWO CB: 27/50 | iter=2/4 | last=0.98850 | best=0.99050
          fold 1/5 | acc=0.99187 | running_mean=0.99187 | time=12.82s
          fold 2/5 | acc=0.99146 | running_mean=0.99167 | time=13.42s
          fold 3/5 | acc=0.98948 | running_mean=0.99094 | time=14.14s
          fold 4/5 | acc=0.99333 | running_mean=0.99154 | time=14.29s
          fold 5/5 | acc=0.99042 | running_mean=0.99131 | time=14.40s
       GWO CB: 28/50 | iter=2/4 | last=0.99131 | best=0.99050
          fold 1/5 | acc=0.99510 | running_mean=0.99510 | time=8.64s
          fold 2/5 | acc=0.99187 | running_mean=0.99349 | time=8.35s
          fold 3/5 | acc=0.99156 | running_mean=0.99285 | time=8.56s
          fold 4/5 | acc=0.99385 | running_mean=0.99310 | time=8.19s
          fold 5/5 | acc=0.99313 | running_mean=0.99310 | time=8.44s
       GWO CB: 29/50 | iter=2/4 | last=0.99310 | best=0.99050
          fold 1/5 | acc=0.96833 | running_mean=0.96833 | time=12.49s
          fold 2/5 | acc=0.96896 | running_mean=0.96865 | time=12.55s
          fold 3/5 | acc=0.97177 | running_mean=0.96969 | time=12.40s
          fold 4/5 | acc=0.97104 | running_mean=0.97003 | time=11.82s
          fold 5/5 | acc=0.96948 | running_mean=0.96992 | time=11.36s
       GWO CB: 30/50 | iter=2/4 | last=0.96992 | best=0.99050
       GWO CB: iter 2/4 done → α=0.99310 β=0.99131 δ=0.99085
          fold 1/5 | acc=0.99219 | running_mean=0.99219 | time=18.30s
          fold 2/5 | acc=0.99198 | running_mean=0.99208 | time=18.54s
          fold 3/5 | acc=0.99260 | running_mean=0.99226 | time=17.12s
          fold 4/5 | acc=0.99427 | running_mean=0.99276 | time=15.90s
          fold 5/5 | acc=0.99344 | running_mean=0.99290 | time=16.53s
       GWO CB: 31/50 | iter=3/4 | last=0.99290 | best=0.99310
          fold 1/5 | acc=0.98938 | running_mean=0.98938 | time=9.28s
          fold 2/5 | acc=0.99052 | running_mean=0.98995 | time=9.82s
          fold 3/5 | acc=0.98906 | running_mean=0.98965 | time=10.89s
          fold 4/5 | acc=0.98938 | running_mean=0.98958 | time=9.20s
          fold 5/5 | acc=0.98927 | running_mean=0.98952 | time=8.39s
       GWO CB: 32/50 | iter=3/4 | last=0.98952 | best=0.99310
          fold 1/5 | acc=0.98927 | running_mean=0.98927 | time=7.11s
          fold 2/5 | acc=0.98990 | running_mean=0.98958 | time=8.22s
          fold 3/5 | acc=0.98958 | running_mean=0.98958 | time=10.16s
          fold 4/5 | acc=0.99031 | running_mean=0.98977 | time=11.18s
          fold 5/5 | acc=0.98802 | running_mean=0.98942 | time=12.02s
       GWO CB: 33/50 | iter=3/4 | last=0.98942 | best=0.99310
          fold 1/5 | acc=0.98635 | running_mean=0.98635 | time=13.18s
          fold 2/5 | acc=0.98542 | running_mean=0.98589 | time=15.64s
          fold 3/5 | acc=0.98677 | running_mean=0.98618 | time=13.99s
          fold 4/5 | acc=0.98510 | running_mean=0.98591 | time=14.00s
          fold 5/5 | acc=0.98635 | running_mean=0.98600 | time=14.27s
       GWO CB: 34/50 | iter=3/4 | last=0.98600 | best=0.99310
          fold 1/5 | acc=0.99469 | running_mean=0.99469 | time=9.18s
          fold 2/5 | acc=0.99365 | running_mean=0.99417 | time=8.91s
          fold 3/5 | acc=0.99406 | running_mean=0.99413 | time=9.17s
          fold 4/5 | acc=0.99562 | running_mean=0.99451 | time=9.06s
          fold 5/5 | acc=0.99417 | running_mean=0.99444 | time=8.51s
       GWO CB: 35/50 | iter=3/4 | last=0.99444 | best=0.99310
          fold 1/5 | acc=0.92896 | running_mean=0.92896 | time=1.58s
          fold 2/5 | acc=0.93406 | running_mean=0.93151 | time=1.77s
          fold 3/5 | acc=0.93437 | running_mean=0.93247 | time=1.64s
          fold 4/5 | acc=0.93208 | running_mean=0.93237 | time=1.64s
          fold 5/5 | acc=0.92948 | running_mean=0.93179 | time=1.42s
       GWO CB: 36/50 | iter=3/4 | last=0.93179 | best=0.99310
          fold 1/5 | acc=0.98573 | running_mean=0.98573 | time=6.91s
          fold 2/5 | acc=0.98500 | running_mean=0.98536 | time=7.53s
          fold 3/5 | acc=0.98792 | running_mean=0.98622 | time=7.71s
          fold 4/5 | acc=0.98385 | running_mean=0.98562 | time=7.73s
          fold 5/5 | acc=0.98823 | running_mean=0.98615 | time=7.87s
       GWO CB: 37/50 | iter=3/4 | last=0.98615 | best=0.99310
          fold 1/5 | acc=0.98698 | running_mean=0.98698 | time=1.90s
          fold 2/5 | acc=0.98708 | running_mean=0.98703 | time=1.90s
          fold 3/5 | acc=0.98677 | running_mean=0.98694 | time=1.88s
          fold 4/5 | acc=0.98594 | running_mean=0.98669 | time=1.83s
          fold 5/5 | acc=0.98646 | running_mean=0.98665 | time=1.74s
       GWO CB: 38/50 | iter=3/4 | last=0.98665 | best=0.99310
          fold 1/5 | acc=0.97729 | running_mean=0.97729 | time=17.70s
          fold 2/5 | acc=0.98542 | running_mean=0.98135 | time=19.23s
          fold 3/5 | acc=0.97792 | running_mean=0.98021 | time=18.59s
          fold 4/5 | acc=0.97792 | running_mean=0.97964 | time=18.22s
          fold 5/5 | acc=0.98250 | running_mean=0.98021 | time=17.59s
       GWO CB: 39/50 | iter=3/4 | last=0.98021 | best=0.99310
          fold 1/5 | acc=0.98802 | running_mean=0.98802 | time=16.26s
          fold 2/5 | acc=0.98562 | running_mean=0.98682 | time=16.10s
          fold 3/5 | acc=0.98719 | running_mean=0.98694 | time=16.95s
          fold 4/5 | acc=0.98802 | running_mean=0.98721 | time=17.11s
          fold 5/5 | acc=0.98844 | running_mean=0.98746 | time=16.79s
       GWO CB: 40/50 | iter=3/4 | last=0.98746 | best=0.99310
       GWO CB: iter 3/4 done → α=0.99444 β=0.99310 δ=0.99290
          fold 1/5 | acc=0.99281 | running_mean=0.99281 | time=10.93s
          fold 2/5 | acc=0.99250 | running_mean=0.99266 | time=11.84s
          fold 3/5 | acc=0.99396 | running_mean=0.99309 | time=8.22s
          fold 4/5 | acc=0.99417 | running_mean=0.99336 | time=7.19s
          fold 5/5 | acc=0.99490 | running_mean=0.99367 | time=7.24s
       GWO CB: 41/50 | iter=4/4 | last=0.99367 | best=0.99444
          fold 1/5 | acc=0.99354 | running_mean=0.99354 | time=8.17s
          fold 2/5 | acc=0.99417 | running_mean=0.99385 | time=7.59s
          fold 3/5 | acc=0.99323 | running_mean=0.99365 | time=11.41s
          fold 4/5 | acc=0.99458 | running_mean=0.99388 | time=10.14s
          fold 5/5 | acc=0.99323 | running_mean=0.99375 | time=9.58s
       GWO CB: 42/50 | iter=4/4 | last=0.99375 | best=0.99444
          fold 1/5 | acc=0.99375 | running_mean=0.99375 | time=7.37s
          fold 2/5 | acc=0.99281 | running_mean=0.99328 | time=9.41s
          fold 3/5 | acc=0.99510 | running_mean=0.99389 | time=10.00s
          fold 4/5 | acc=0.99458 | running_mean=0.99406 | time=7.09s
          fold 5/5 | acc=0.99385 | running_mean=0.99402 | time=7.50s
       GWO CB: 43/50 | iter=4/4 | last=0.99402 | best=0.99444
          fold 1/5 | acc=0.99240 | running_mean=0.99240 | time=10.23s
          fold 2/5 | acc=0.98917 | running_mean=0.99078 | time=10.80s
          fold 3/5 | acc=0.99042 | running_mean=0.99066 | time=12.00s
          fold 4/5 | acc=0.99198 | running_mean=0.99099 | time=9.03s
          fold 5/5 | acc=0.99000 | running_mean=0.99079 | time=8.58s
       GWO CB: 44/50 | iter=4/4 | last=0.99079 | best=0.99444
          fold 1/5 | acc=0.99260 | running_mean=0.99260 | time=4.92s
          fold 2/5 | acc=0.99250 | running_mean=0.99255 | time=5.02s
          fold 3/5 | acc=0.99375 | running_mean=0.99295 | time=5.57s
          fold 4/5 | acc=0.99292 | running_mean=0.99294 | time=5.20s
          fold 5/5 | acc=0.99375 | running_mean=0.99310 | time=6.13s
       GWO CB: 45/50 | iter=4/4 | last=0.99310 | best=0.99444
          fold 1/5 | acc=0.99271 | running_mean=0.99271 | time=18.11s
          fold 2/5 | acc=0.99219 | running_mean=0.99245 | time=20.86s
          fold 3/5 | acc=0.99438 | running_mean=0.99309 | time=17.63s
          fold 4/5 | acc=0.99490 | running_mean=0.99354 | time=17.83s
          fold 5/5 | acc=0.99240 | running_mean=0.99331 | time=17.69s
       GWO CB: 46/50 | iter=4/4 | last=0.99331 | best=0.99444
          fold 1/5 | acc=0.99333 | running_mean=0.99333 | time=5.85s
          fold 2/5 | acc=0.99208 | running_mean=0.99271 | time=5.43s
          fold 3/5 | acc=0.99292 | running_mean=0.99278 | time=5.42s
          fold 4/5 | acc=0.99333 | running_mean=0.99292 | time=5.66s
          fold 5/5 | acc=0.99281 | running_mean=0.99290 | time=5.45s
       GWO CB: 47/50 | iter=4/4 | last=0.99290 | best=0.99444
          fold 1/5 | acc=0.99115 | running_mean=0.99115 | time=10.54s
          fold 2/5 | acc=0.98969 | running_mean=0.99042 | time=8.60s
          fold 3/5 | acc=0.99094 | running_mean=0.99059 | time=11.03s

{'status': 'completed',
 'best':   Model Optimal_Scaler  Best_CV_Mean  Best_Iteration  iterations  \
 0    CB         MinMax      0.994438              35         361

    learning_rate  depth  l2_leaf_reg  border_count  bagging_temperature  \
 0            0.5      6         10.0           251             2.192955

    random_state
 0            42  ,
 'history':    Model  Iteration   CV_Mean  Best_Score_So_Far  Iteration_Runtime_Sec
 0     CB          1  0.984938           0.984938              61.591209
 1     CB          2  0.983563           0.984938              27.301666
 2     CB          3  0.989375           0.989375              28.645044
 3     CB          4  0.989583           0.989583              59.832264
 4     CB          5  0.948292           0.989583              46.088523
 5     CB          6  0.990500           0.990500              44.062657
 6     CB          7  0.917563           0.990500               6.660882
 7     CB          8  0.976187           0.990500              75.957383
 8     CB          9  0.912604           0.990500              33.968977
 9     CB         10  0.989125           0.990500              40.119361
 10    CB         11  0.984938           0.990500              72.802265
 11    CB         12  0.983563           0.990500              34.930913
 12    CB         13  0.989375           0.990500              38.496207
 13    CB         14  0.989583           0.990500              85.707403
 14    CB         15  0.948292           0.990500              43.334671
 15    CB         16  0.990500           0.990500              35.500995
 16    CB         17  0.917563           0.990500               5.295655
 17    CB         18  0.976187           0.990500              72.668784
 18    CB         19  0.912604           0.990500              32.370943
 19    CB         20  0.989125           0.990500              35.776160
 20    CB         21  0.989250           0.993104              57.203459
 21    CB         22  0.987354           0.993104              66.240473
 22    CB         23  0.990854           0.993104              43.216762
 23    CB         24  0.973833           0.993104             128.154095
 24    CB         25  0.988750           0.993104              61.404614
 25    CB         26  0.983354           0.993104              44.138889
 26    CB         27  0.988500           0.993104              34.318771
 27    CB         28  0.991312           0.993104              69.106223
 28    CB         29  0.993104           0.993104              42.221611
 29    CB         30  0.969917           0.993104              60.663185
 30    CB         31  0.992896           0.994438              86.445475
 31    CB         32  0.989521           0.994438              47.630966
 32    CB         33  0.989417           0.994438              48.740117
 33    CB         34  0.986000           0.994438              71.127348
 34    CB         35  0.994438           0.994438              44.865556
 35    CB         36  0.931792           0.994438               8.091173
 36    CB         37  0.986146           0.994438              37.774175
 37    CB         38  0.986646           0.994438               9.294817
 38    CB         39  0.980208           0.994438              91.367889
 39    CB         40  0.987458           0.994438              83.248094
 40    CB         41  0.993667           0.994438              45.465912
 41    CB         42  0.993750           0.994438              46.926528
 42    CB         43  0.994021           0.994438              41.404296
 43    CB         44  0.990792           0.994438              50.693946
 44    CB         45  0.993104           0.994438              26.879480
 45    CB         46  0.993313           0.994438              92.165159
 46    CB         47  0.992896           0.994438              27.854103
 47    CB         48  0.991271           0.994438              52.295778
 48    CB         49  0.992896           0.994438              46.096843
 49    CB         50  0.993396           0.994438              44.465924,
 'summary':   Method Model Optimal_Scaler      Split  Accuracy  Precision    Recall  \
 0    GWO    CB         MinMax  Train_OOF  0.994437   0.994720  0.996571
 1    GWO    CB         MinMax       Test  0.996917   0.996352  0.998824

          F1     Kappa       MCC  ...  F1_CI_Lower  F1_CI_Upper  AUC_CI_Lower  \
 0  0.995645  0.987949  0.987952  ...     0.995074     0.996135      0.999707
 1  0.997587  0.993319  0.993324  ...     0.996761     0.998310      0.999876

    AUC_CI_Upper  LogLoss_CI_Lower  LogLoss_CI_Upper  Kappa_CI_Lower  \
 0      0.999831          0.025445          0.027721        0.986397
 1      0.999964          0.019723          0.023001        0.991018

    Kappa_CI_Upper  MCC_CI_Lower  MCC_CI_Upper
 0        0.989300      0.986402      0.989302
 1        0.995312      0.991025      0.995316

 [2 rows x 28 columns],
 'timing':   Model  GWO_Search_Sec  GWO_Evaluation_Sec  GWO_Total_Sec  Best_CV_Mean
 0    CB     2490.765721          161.800362    2653.542326      0.994438}

In [60]:
run_gwo_model("SGD")

SGD        | Scaler: Power      | Available RAM: 6.50 GB | Kernel RSS: 227.3 MB
       Memory cleanup -> gc_collected=67, available=6.50 GB, used=58.7%, rss=227.3 MB
       Running 50 evaluations with n_jobs_cv=1, n_jobs_opt=3
       GWO progress for SGD: 0/50 evaluations
       GWO SGD: initializing population (10 wolves)...
          fold 1/5 | acc=0.87406 | running_mean=0.87406 | time=0.54s
          fold 2/5 | acc=0.88021 | running_mean=0.87714 | time=0.50s
          fold 3/5 | acc=0.87438 | running_mean=0.87622 | time=0.55s
          fold 4/5 | acc=0.87760 | running_mean=0.87656 | time=0.48s
          fold 5/5 | acc=0.87719 | running_mean=0.87669 | time=0.52s
       GWO SGD: init 1/10 | last=0.87669 | best=0.87669
          fold 1/5 | acc=0.86125 | running_mean=0.86125 | time=0.52s
          fold 2/5 | acc=0.86760 | running_mean=0.86443 | time=0.54s
          fold 3/5 | acc=0.86146 | running_mean=0.86344 | time=0.54s
          fold 4/5 | acc=0.86438 | running_mean=0.86367 | time=0.49s
          fold 5/5 | acc=0.86187 | running_mean=0.86331 | time=0.55s
       GWO SGD: init 2/10 | last=0.86331 | best=0.87669
          fold 1/5 | acc=0.89187 | running_mean=0.89187 | time=0.52s
          fold 2/5 | acc=0.89344 | running_mean=0.89266 | time=0.62s
          fold 3/5 | acc=0.89240 | running_mean=0.89257 | time=0.52s
          fold 4/5 | acc=0.89521 | running_mean=0.89323 | time=0.61s
          fold 5/5 | acc=0.89406 | running_mean=0.89340 | time=0.55s
       GWO SGD: init 3/10 | last=0.89340 | best=0.89340
          fold 1/5 | acc=0.89156 | running_mean=0.89156 | time=0.70s
          fold 2/5 | acc=0.88750 | running_mean=0.88953 | time=0.61s
          fold 3/5 | acc=0.89010 | running_mean=0.88972 | time=0.68s
          fold 4/5 | acc=0.89240 | running_mean=0.89039 | time=0.63s
          fold 5/5 | acc=0.89667 | running_mean=0.89165 | time=0.67s
       GWO SGD: init 4/10 | last=0.89165 | best=0.89340
          fold 1/5 | acc=0.86906 | running_mean=0.86906 | time=0.47s
          fold 2/5 | acc=0.87344 | running_mean=0.87125 | time=0.54s
          fold 3/5 | acc=0.86875 | running_mean=0.87042 | time=0.49s
          fold 4/5 | acc=0.87406 | running_mean=0.87133 | time=0.50s
          fold 5/5 | acc=0.87135 | running_mean=0.87133 | time=0.50s
       GWO SGD: init 5/10 | last=0.87133 | best=0.89340
          fold 1/5 | acc=0.86198 | running_mean=0.86198 | time=0.47s
          fold 2/5 | acc=0.86927 | running_mean=0.86562 | time=0.52s
          fold 3/5 | acc=0.86396 | running_mean=0.86507 | time=0.47s
          fold 4/5 | acc=0.86635 | running_mean=0.86539 | time=0.49s
          fold 5/5 | acc=0.86354 | running_mean=0.86502 | time=0.53s
       GWO SGD: init 6/10 | last=0.86502 | best=0.89340
          fold 1/5 | acc=0.89083 | running_mean=0.89083 | time=0.65s
          fold 2/5 | acc=0.88969 | running_mean=0.89026 | time=0.66s
          fold 3/5 | acc=0.89146 | running_mean=0.89066 | time=0.62s
          fold 4/5 | acc=0.89312 | running_mean=0.89128 | time=0.65s
          fold 5/5 | acc=0.89406 | running_mean=0.89183 | time=0.65s
       GWO SGD: init 7/10 | last=0.89183 | best=0.89340
          fold 1/5 | acc=0.86354 | running_mean=0.86354 | time=0.47s
          fold 2/5 | acc=0.86979 | running_mean=0.86667 | time=0.54s
          fold 3/5 | acc=0.86583 | running_mean=0.86639 | time=0.54s
          fold 4/5 | acc=0.86656 | running_mean=0.86643 | time=0.59s
          fold 5/5 | acc=0.86625 | running_mean=0.86640 | time=0.54s
       GWO SGD: init 8/10 | last=0.86640 | best=0.89340
          fold 1/5 | acc=0.88656 | running_mean=0.88656 | time=0.56s
          fold 2/5 | acc=0.89146 | running_mean=0.88901 | time=0.60s
          fold 3/5 | acc=0.88521 | running_mean=0.88774 | time=0.52s
          fold 4/5 | acc=0.88583 | running_mean=0.88727 | time=0.53s
          fold 5/5 | acc=0.88938 | running_mean=0.88769 | time=0.53s
       GWO SGD: init 9/10 | last=0.88769 | best=0.89340
          fold 1/5 | acc=0.89198 | running_mean=0.89198 | time=0.73s
          fold 2/5 | acc=0.88583 | running_mean=0.88891 | time=0.68s
          fold 3/5 | acc=0.89281 | running_mean=0.89021 | time=0.76s
          fold 4/5 | acc=0.88813 | running_mean=0.88969 | time=0.68s
          fold 5/5 | acc=0.89198 | running_mean=0.89015 | time=0.68s
       GWO SGD: init 10/10 | last=0.89015 | best=0.89340
       GWO SGD: init done → α=0.89340 β=0.89183 δ=0.89165
          fold 1/5 | acc=0.87406 | running_mean=0.87406 | time=0.49s
          fold 2/5 | acc=0.88021 | running_mean=0.87714 | time=0.48s
          fold 3/5 | acc=0.87438 | running_mean=0.87622 | time=0.51s
          fold 4/5 | acc=0.87760 | running_mean=0.87656 | time=0.54s
          fold 5/5 | acc=0.87719 | running_mean=0.87669 | time=0.52s
       GWO SGD: 11/50 | iter=1/4 | last=0.87669 | best=0.89340
          fold 1/5 | acc=0.86125 | running_mean=0.86125 | time=0.53s
          fold 2/5 | acc=0.86760 | running_mean=0.86443 | time=0.55s
          fold 3/5 | acc=0.86146 | running_mean=0.86344 | time=0.51s
          fold 4/5 | acc=0.86438 | running_mean=0.86367 | time=0.53s
          fold 5/5 | acc=0.86187 | running_mean=0.86331 | time=0.53s
       GWO SGD: 12/50 | iter=1/4 | last=0.86331 | best=0.89340
          fold 1/5 | acc=0.89187 | running_mean=0.89187 | time=0.57s
          fold 2/5 | acc=0.89344 | running_mean=0.89266 | time=0.53s
          fold 3/5 | acc=0.89240 | running_mean=0.89257 | time=0.55s
          fold 4/5 | acc=0.89521 | running_mean=0.89323 | time=0.57s
          fold 5/5 | acc=0.89406 | running_mean=0.89340 | time=0.59s
       GWO SGD: 13/50 | iter=1/4 | last=0.89340 | best=0.89340
          fold 1/5 | acc=0.89156 | running_mean=0.89156 | time=0.71s
          fold 2/5 | acc=0.88750 | running_mean=0.88953 | time=0.65s
          fold 3/5 | acc=0.89010 | running_mean=0.88972 | time=0.66s
          fold 4/5 | acc=0.89240 | running_mean=0.89039 | time=0.65s
          fold 5/5 | acc=0.89667 | running_mean=0.89165 | time=0.65s
       GWO SGD: 14/50 | iter=1/4 | last=0.89165 | best=0.89340
          fold 1/5 | acc=0.86906 | running_mean=0.86906 | time=0.65s
          fold 2/5 | acc=0.87344 | running_mean=0.87125 | time=0.64s
          fold 3/5 | acc=0.86875 | running_mean=0.87042 | time=0.53s
          fold 4/5 | acc=0.87406 | running_mean=0.87133 | time=0.49s
          fold 5/5 | acc=0.87135 | running_mean=0.87133 | time=0.52s
       GWO SGD: 15/50 | iter=1/4 | last=0.87133 | best=0.89340
          fold 1/5 | acc=0.86198 | running_mean=0.86198 | time=0.50s
          fold 2/5 | acc=0.86927 | running_mean=0.86562 | time=0.49s
          fold 3/5 | acc=0.86396 | running_mean=0.86507 | time=0.47s
          fold 4/5 | acc=0.86635 | running_mean=0.86539 | time=0.48s
          fold 5/5 | acc=0.86354 | running_mean=0.86502 | time=0.51s
       GWO SGD: 16/50 | iter=1/4 | last=0.86502 | best=0.89340
          fold 1/5 | acc=0.89083 | running_mean=0.89083 | time=0.63s
          fold 2/5 | acc=0.88969 | running_mean=0.89026 | time=0.67s
          fold 3/5 | acc=0.89146 | running_mean=0.89066 | time=0.67s
          fold 4/5 | acc=0.89312 | running_mean=0.89128 | time=0.68s
          fold 5/5 | acc=0.89406 | running_mean=0.89183 | time=0.64s
       GWO SGD: 17/50 | iter=1/4 | last=0.89183 | best=0.89340
          fold 1/5 | acc=0.86354 | running_mean=0.86354 | time=0.50s
          fold 2/5 | acc=0.86979 | running_mean=0.86667 | time=0.52s
          fold 3/5 | acc=0.86583 | running_mean=0.86639 | time=0.49s
          fold 4/5 | acc=0.86656 | running_mean=0.86643 | time=0.50s
          fold 5/5 | acc=0.86625 | running_mean=0.86640 | time=0.48s
       GWO SGD: 18/50 | iter=1/4 | last=0.86640 | best=0.89340
          fold 1/5 | acc=0.88656 | running_mean=0.88656 | time=0.54s
          fold 2/5 | acc=0.89146 | running_mean=0.88901 | time=0.53s
          fold 3/5 | acc=0.88521 | running_mean=0.88774 | time=0.52s
          fold 4/5 | acc=0.88583 | running_mean=0.88727 | time=0.52s
          fold 5/5 | acc=0.88938 | running_mean=0.88769 | time=0.53s
       GWO SGD: 19/50 | iter=1/4 | last=0.88769 | best=0.89340
          fold 1/5 | acc=0.89198 | running_mean=0.89198 | time=0.70s
          fold 2/5 | acc=0.88583 | running_mean=0.88891 | time=0.62s
          fold 3/5 | acc=0.89281 | running_mean=0.89021 | time=0.63s
          fold 4/5 | acc=0.88813 | running_mean=0.88969 | time=0.65s
          fold 5/5 | acc=0.89198 | running_mean=0.89015 | time=0.69s
       GWO SGD: 20/50 | iter=1/4 | last=0.89015 | best=0.89340
       GWO SGD: iter 1/4 done → α=0.89340 β=0.89340 δ=0.89183
          fold 1/5 | acc=0.87948 | running_mean=0.87948 | time=0.54s
          fold 2/5 | acc=0.88740 | running_mean=0.88344 | time=0.52s
          fold 3/5 | acc=0.88010 | running_mean=0.88233 | time=0.54s
          fold 4/5 | acc=0.88250 | running_mean=0.88237 | time=0.50s
          fold 5/5 | acc=0.88240 | running_mean=0.88238 | time=0.51s
       GWO SGD: 21/50 | iter=2/4 | last=0.88238 | best=0.89340
          fold 1/5 | acc=0.88062 | running_mean=0.88062 | time=0.51s
          fold 2/5 | acc=0.88813 | running_mean=0.88438 | time=0.51s
          fold 3/5 | acc=0.88073 | running_mean=0.88316 | time=0.53s
          fold 4/5 | acc=0.88375 | running_mean=0.88331 | time=0.51s
          fold 5/5 | acc=0.88438 | running_mean=0.88352 | time=0.51s
       GWO SGD: 22/50 | iter=2/4 | last=0.88352 | best=0.89340
          fold 1/5 | acc=0.88177 | running_mean=0.88177 | time=0.52s
          fold 2/5 | acc=0.88344 | running_mean=0.88260 | time=0.52s
          fold 3/5 | acc=0.87875 | running_mean=0.88132 | time=0.49s
          fold 4/5 | acc=0.88156 | running_mean=0.88138 | time=0.49s
          fold 5/5 | acc=0.88062 | running_mean=0.88123 | time=0.52s
       GWO SGD: 23/50 | iter=2/4 | last=0.88123 | best=0.89340
          fold 1/5 | acc=0.89115 | running_mean=0.89115 | time=0.58s
          fold 2/5 | acc=0.89438 | running_mean=0.89276 | time=0.55s
          fold 3/5 | acc=0.89260 | running_mean=0.89271 | time=0.56s
          fold 4/5 | acc=0.89583 | running_mean=0.89349 | time=0.56s
          fold 5/5 | acc=0.89938 | running_mean=0.89467 | time=0.61s
       GWO SGD: 24/50 | iter=2/4 | last=0.89467 | best=0.89340
          fold 1/5 | acc=0.88615 | running_mean=0.88615 | time=0.53s
          fold 2/5 | acc=0.89146 | running_mean=0.88880 | time=0.51s
          fold 3/5 | acc=0.88479 | running_mean=0.88747 | time=0.53s
          fold 4/5 | acc=0.88719 | running_mean=0.88740 | time=0.51s
          fold 5/5 | acc=0.88927 | running_mean=0.88777 | time=0.53s
       GWO SGD: 25/50 | iter=2/4 | last=0.88777 | best=0.89340
          fold 1/5 | acc=0.89083 | running_mean=0.89083 | time=0.62s
          fold 2/5 | acc=0.89333 | running_mean=0.89208 | time=0.69s
          fold 3/5 | acc=0.89198 | running_mean=0.89205 | time=0.59s
          fold 4/5 | acc=0.89729 | running_mean=0.89336 | time=0.64s
          fold 5/5 | acc=0.89844 | running_mean=0.89438 | time=0.62s
       GWO SGD: 26/50 | iter=2/4 | last=0.89438 | best=0.89340
          fold 1/5 | acc=0.88385 | running_mean=0.88385 | time=0.52s
          fold 2/5 | acc=0.88833 | running_mean=0.88609 | time=0.51s
          fold 3/5 | acc=0.88323 | running_mean=0.88514 | time=0.52s
          fold 4/5 | acc=0.88792 | running_mean=0.88583 | time=0.51s
          fold 5/5 | acc=0.88573 | running_mean=0.88581 | time=0.54s
       GWO SGD: 27/50 | iter=2/4 | last=0.88581 | best=0.89340
          fold 1/5 | acc=0.89469 | running_mean=0.89469 | time=0.57s
          fold 2/5 | acc=0.89708 | running_mean=0.89589 | time=0.63s
          fold 3/5 | acc=0.89240 | running_mean=0.89472 | time=0.58s
          fold 4/5 | acc=0.89312 | running_mean=0.89432 | time=0.60s
          fold 5/5 | acc=0.90042 | running_mean=0.89554 | time=0.59s
       GWO SGD: 28/50 | iter=2/4 | last=0.89554 | best=0.89340
          fold 1/5 | acc=0.88198 | running_mean=0.88198 | time=0.93s
          fold 2/5 | acc=0.89073 | running_mean=0.88635 | time=0.88s
          fold 3/5 | acc=0.89021 | running_mean=0.88764 | time=0.97s
          fold 4/5 | acc=0.88990 | running_mean=0.88820 | time=0.99s
          fold 5/5 | acc=0.89563 | running_mean=0.88969 | time=0.99s
       GWO SGD: 29/50 | iter=2/4 | last=0.88969 | best=0.89340
          fold 1/5 | acc=0.88917 | running_mean=0.88917 | time=0.59s
          fold 2/5 | acc=0.89219 | running_mean=0.89068 | time=0.58s
          fold 3/5 | acc=0.88865 | running_mean=0.89000 | time=0.53s
          fold 4/5 | acc=0.89365 | running_mean=0.89091 | time=0.58s
          fold 5/5 | acc=0.89542 | running_mean=0.89181 | time=0.60s
       GWO SGD: 30/50 | iter=2/4 | last=0.89181 | best=0.89340
       GWO SGD: iter 2/4 done → α=0.89554 β=0.89467 δ=0.89438
          fold 1/5 | acc=0.88875 | running_mean=0.88875 | time=0.52s
          fold 2/5 | acc=0.89344 | running_mean=0.89109 | time=0.55s
          fold 3/5 | acc=0.88656 | running_mean=0.88958 | time=0.54s
          fold 4/5 | acc=0.89167 | running_mean=0.89010 | time=0.53s
          fold 5/5 | acc=0.89302 | running_mean=0.89069 | time=0.54s
       GWO SGD: 31/50 | iter=3/4 | last=0.89069 | best=0.89554
          fold 1/5 | acc=0.87656 | running_mean=0.87656 | time=0.52s
          fold 2/5 | acc=0.87729 | running_mean=0.87693 | time=0.50s
          fold 3/5 | acc=0.87333 | running_mean=0.87573 | time=0.53s
          fold 4/5 | acc=0.87719 | running_mean=0.87609 | time=0.50s
          fold 5/5 | acc=0.87542 | running_mean=0.87596 | time=0.53s
       GWO SGD: 32/50 | iter=3/4 | last=0.87596 | best=0.89554
          fold 1/5 | acc=0.89104 | running_mean=0.89104 | time=0.55s
          fold 2/5 | acc=0.89438 | running_mean=0.89271 | time=0.59s
          fold 3/5 | acc=0.89156 | running_mean=0.89233 | time=0.51s
          fold 4/5 | acc=0.89604 | running_mean=0.89326 | time=0.53s
          fold 5/5 | acc=0.89875 | running_mean=0.89435 | time=0.60s
       GWO SGD: 33/50 | iter=3/4 | last=0.89435 | best=0.89554
          fold 1/5 | acc=0.89417 | running_mean=0.89417 | time=0.60s
          fold 2/5 | acc=0.89167 | running_mean=0.89292 | time=0.59s
          fold 3/5 | acc=0.88979 | running_mean=0.89188 | time=0.57s
          fold 4/5 | acc=0.89396 | running_mean=0.89240 | time=0.60s
          fold 5/5 | acc=0.90010 | running_mean=0.89394 | time=0.62s
       GWO SGD: 34/50 | iter=3/4 | last=0.89394 | best=0.89554
          fold 1/5 | acc=0.89229 | running_mean=0.89229 | time=0.56s
          fold 2/5 | acc=0.89198 | running_mean=0.89214 | time=0.51s
          fold 3/5 | acc=0.88573 | running_mean=0.89000 | time=0.56s
          fold 4/5 | acc=0.89021 | running_mean=0.89005 | time=0.49s
          fold 5/5 | acc=0.89083 | running_mean=0.89021 | time=0.58s
       GWO SGD: 35/50 | iter=3/4 | last=0.89021 | best=0.89554
          fold 1/5 | acc=0.89135 | running_mean=0.89135 | time=0.74s
          fold 2/5 | acc=0.89677 | running_mean=0.89406 | time=0.68s
          fold 3/5 | acc=0.89240 | running_mean=0.89351 | time=0.54s
          fold 4/5 | acc=0.89312 | running_mean=0.89341 | time=0.59s
          fold 5/5 | acc=0.89844 | running_mean=0.89442 | time=0.58s
       GWO SGD: 36/50 | iter=3/4 | last=0.89442 | best=0.89554
          fold 1/5 | acc=0.88156 | running_mean=0.88156 | time=0.54s
          fold 2/5 | acc=0.88198 | running_mean=0.88177 | time=0.51s
          fold 3/5 | acc=0.87750 | running_mean=0.88035 | time=0.53s
          fold 4/5 | acc=0.88073 | running_mean=0.88044 | time=0.50s
          fold 5/5 | acc=0.87698 | running_mean=0.87975 | time=0.51s
       GWO SGD: 37/50 | iter=3/4 | last=0.87975 | best=0.89554
          fold 1/5 | acc=0.89135 | running_mean=0.89135 | time=0.56s
          fold 2/5 | acc=0.89427 | running_mean=0.89281 | time=0.57s
          fold 3/5 | acc=0.89229 | running_mean=0.89264 | time=0.57s
          fold 4/5 | acc=0.89563 | running_mean=0.89339 | time=0.58s
          fold 5/5 | acc=0.89885 | running_mean=0.89448 | time=0.62s
       GWO SGD: 38/50 | iter=3/4 | last=0.89448 | best=0.89554
          fold 1/5 | acc=0.89146 | running_mean=0.89146 | time=0.63s
          fold 2/5 | acc=0.89479 | running_mean=0.89312 | time=0.70s
          fold 3/5 | acc=0.89312 | running_mean=0.89312 | time=0.62s
          fold 4/5 | acc=0.89010 | running_mean=0.89237 | time=0.60s
          fold 5/5 | acc=0.89740 | running_mean=0.89338 | time=0.60s
       GWO SGD: 39/50 | iter=3/4 | last=0.89338 | best=0.89554
          fold 1/5 | acc=0.87729 | running_mean=0.87729 | time=0.55s
          fold 2/5 | acc=0.87844 | running_mean=0.87786 | time=0.53s
          fold 3/5 | acc=0.87667 | running_mean=0.87747 | time=0.51s
          fold 4/5 | acc=0.87979 | running_mean=0.87805 | time=0.55s
          fold 5/5 | acc=0.87594 | running_mean=0.87763 | time=0.51s
       GWO SGD: 40/50 | iter=3/4 | last=0.87763 | best=0.89554
       GWO SGD: iter 3/4 done → α=0.89554 β=0.89467 δ=0.89448
          fold 1/5 | acc=0.88667 | running_mean=0.88667 | time=0.53s
          fold 2/5 | acc=0.89094 | running_mean=0.88880 | time=0.50s
          fold 3/5 | acc=0.88323 | running_mean=0.88694 | time=0.51s
          fold 4/5 | acc=0.88802 | running_mean=0.88721 | time=0.51s
          fold 5/5 | acc=0.88615 | running_mean=0.88700 | time=0.53s
       GWO SGD: 41/50 | iter=4/4 | last=0.88700 | best=0.89554
          fold 1/5 | acc=0.89427 | running_mean=0.89427 | time=0.62s
          fold 2/5 | acc=0.89719 | running_mean=0.89573 | time=0.60s
          fold 3/5 | acc=0.88958 | running_mean=0.89368 | time=0.58s
          fold 4/5 | acc=0.89427 | running_mean=0.89383 | time=0.71s
          fold 5/5 | acc=0.89990 | running_mean=0.89504 | time=0.71s
       GWO SGD: 42/50 | iter=4/4 | last=0.89504 | best=0.89554
          fold 1/5 | acc=0.89125 | running_mean=0.89125 | time=0.66s
          fold 2/5 | acc=0.89458 | running_mean=0.89292 | time=0.54s
          fold 3/5 | acc=0.89229 | running_mean=0.89271 | time=0.54s
          fold 4/5 | acc=0.89583 | running_mean=0.89349 | time=0.54s
          fold 5/5 | acc=0.89969 | running_mean=0.89473 | time=0.57s
       GWO SGD: 43/50 | iter=4/4 | last=0.89473 | best=0.89554
          fold 1/5 | acc=0.89354 | running_mean=0.89354 | time=0.57s
          fold 2/5 | acc=0.89490 | running_mean=0.89422 | time=0.58s
          fold 3/5 | acc=0.89198 | running_mean=0.89347 | time=0.53s
          fold 4/5 | acc=0.89740 | running_mean=0.89445 | time=0.54s
          fold 5/5 | acc=0.89948 | running_mean=0.89546 | time=0.56s
       GWO SGD: 44/50 | iter=4/4 | last=0.89546 | best=0.89554
          fold 1/5 | acc=0.88792 | running_mean=0.88792 | time=0.50s
          fold 2/5 | acc=0.89333 | running_mean=0.89062 | time=0.57s
          fold 3/5 | acc=0.88698 | running_mean=0.88941 | time=0.50s
          fold 4/5 | acc=0.89021 | running_mean=0.88961 | time=0.52s
          fold 5/5 | acc=0.89042 | running_mean=0.88977 | time=0.50s
       GWO SGD: 45/50 | iter=4/4 | last=0.88977 | best=0.89554
          fold 1/5 | acc=0.88552 | running_mean=0.88552 | time=0.53s
          fold 2/5 | acc=0.88677 | running_mean=0.88615 | time=0.56s
          fold 3/5 | acc=0.88167 | running_mean=0.88465 | time=0.50s
          fold 4/5 | acc=0.88573 | running_mean=0.88492 | time=0.50s
          fold 5/5 | acc=0.88448 | running_mean=0.88483 | time=0.50s
       GWO SGD: 46/50 | iter=4/4 | last=0.88483 | best=0.89554
          fold 1/5 | acc=0.89187 | running_mean=0.89187 | time=0.66s
          fold 2/5 | acc=0.89469 | running_mean=0.89328 | time=0.61s
          fold 3/5 | acc=0.89271 | running_mean=0.89309 | time=0.60s
          fold 4/5 | acc=0.89719 | running_mean=0.89411 | time=0.64s
          fold 5/5 | acc=0.89938 | running_mean=0.89517 | time=0.62s
       GWO SGD: 47/50 | iter=4/4 | last=0.89517 | best=0.89554
          fold 1/5 | acc=0.89167 | running_mean=0.89167 | time=0.64s
          fold 2/5 | acc=0.89219 | running_mean=0.89193 | time=0.66s
          fold 3/5 | acc=0.89271 | running_mean=0.89219 | time=0.60s
          fold 4/5 | acc=0.89708 | running_mean=0.89341 | time=0.62s

{'status': 'completed',
 'best':   Model Optimal_Scaler  Best_CV_Mean  Best_Iteration            loss penalty    alpha  l1_ratio  max_iter  random_state
 0   SGD          Power      0.895542              28  modified_huber      l1  0.00091  0.630203      2000            42,
 'history':    Model  Iteration   CV_Mean  Best_Score_So_Far  Iteration_Runtime_Sec
 0    SGD          1  0.876688           0.876688               2.609132
 1    SGD          2  0.863312           0.876688               2.659617
 2    SGD          3  0.893396           0.893396               2.852707
 3    SGD          4  0.891646           0.893396               3.294501
 4    SGD          5  0.871333           0.893396               2.515096
 5    SGD          6  0.865021           0.893396               2.503521
 6    SGD          7  0.891833           0.893396               3.253172
 7    SGD          8  0.866396           0.893396               2.699696
 8    SGD          9  0.887687           0.893396               2.744540
 9    SGD         10  0.890146           0.893396               3.535036
 10   SGD         11  0.876688           0.893396               2.561201
 11   SGD         12  0.863312           0.893396               2.647821
 12   SGD         13  0.893396           0.893396               2.835434
 13   SGD         14  0.891646           0.893396               3.338147
 14   SGD         15  0.871333           0.893396               2.850722
 15   SGD         16  0.865021           0.893396               2.464022
 16   SGD         17  0.891833           0.893396               3.304731
 17   SGD         18  0.866396           0.893396               2.498284
 18   SGD         19  0.887687           0.893396               2.650107
 19   SGD         20  0.890146           0.893396               3.309571
 20   SGD         21  0.882375           0.895542               2.618794
 21   SGD         22  0.883521           0.895542               2.578336
 22   SGD         23  0.881229           0.895542               2.555372
 23   SGD         24  0.894667           0.895542               2.871314
 24   SGD         25  0.887771           0.895542               2.620914
 25   SGD         26  0.894375           0.895542               3.174103
 26   SGD         27  0.885812           0.895542               2.608406
 27   SGD         28  0.895542           0.895542               2.991525
 28   SGD         29  0.889687           0.895542               4.772443
 29   SGD         30  0.891813           0.895542               2.887170
 30   SGD         31  0.890687           0.895542               2.694891
 31   SGD         32  0.875958           0.895542               2.595805
 32   SGD         33  0.894354           0.895542               2.794920
 33   SGD         34  0.893938           0.895542               2.994159
 34   SGD         35  0.890208           0.895542               2.714480
 35   SGD         36  0.894417           0.895542               3.151021
 36   SGD         37  0.879750           0.895542               2.597996
 37   SGD         38  0.894479           0.895542               2.914464
 38   SGD         39  0.893375           0.895542               3.149299
 39   SGD         40  0.877625           0.895542               2.658106
 40   SGD         41  0.887000           0.895542               2.589015
 41   SGD         42  0.895042           0.895542               3.241802
 42   SGD         43  0.894729           0.895542               2.866587
 43   SGD         44  0.895458           0.895542               2.793539
 44   SGD         45  0.889771           0.895542               2.624491
 45   SGD         46  0.884833           0.895542               2.604365
 46   SGD         47  0.895167           0.895542               3.148097
 47   SGD         48  0.894271           0.895542               3.115996
 48   SGD         49  0.895104           0.895542               2.674020
 49   SGD         50  0.895292           0.895542               3.075821,
 'summary':   Method Model Optimal_Scaler      Split  Accuracy  Precision    Recall        F1     Kappa       MCC       AUC   LogLoss  Accuracy_CI_Lower  Accuracy_CI_Upper  Precision_CI_Lower  Precision_CI_Upper  Recall_CI_Lower  Recall_CI_Upper  F1_CI_Lower  F1_CI_Upper  AUC_CI_Lower  AUC_CI_Upper  LogLoss_CI_Lower  LogLoss_CI_Upper  Kappa_CI_Lower  Kappa_CI_Upper  MCC_CI_Lower  MCC_CI_Upper
 0    GWO   SGD          Power  Train_OOF  0.895542   0.912825  0.924569  0.918659  0.772742  0.772865  0.963259  0.326180           0.892791           0.898271            0.909611            0.916027         0.921589         0.927624     0.916392     0.920902      0.961803      0.964721          0.310168          0.343345        0.766856        0.778671      0.767017       0.77879
 1    GWO   SGD          Power       Test  0.901333   0.912650  0.934822  0.923603  0.784398  0.784849  0.966176  0.300174           0.896083           0.906750            0.906470            0.918859         0.929184         0.940295     0.919172     0.927882      0.963353      0.968862          0.271824          0.330032        0.772891        0.796160      0.773489       0.79656,
 'timing':   Model  GWO_Search_Sec  GWO_Evaluation_Sec  GWO_Total_Sec  Best_CV_Mean
 0   SGD       143.85429           97.614988     241.709159      0.895542}

In [ ]:
# =====================================================================
# CELL 9: Final Aggregation with Comprehensive Analysis & Resource Efficiency Report
# =====================================================================

print("\n" + "="*80)
print("FINAL AGGREGATION & RESOURCE EFFICIENCY ANALYSIS")
print("="*80)

# =====================================================================
# 0. Resource Efficiency Report
# =====================================================================

final_memory = psutil.Process(os.getpid()).memory_info().rss / (1024**2)
peak_memory_percent = (final_memory / (TOTAL_MEMORY_GB * 1024)) * 100

print(f"\nSystem resource usage:")
print(f"  Final Memory:            {final_memory:.1f} MB ({peak_memory_percent:.1f}% of total)")
print(f"  CPU Cores Utilized:      {N_JOBS_CV} (from {CPU_COUNT} available)")
print(f"  Adaptive Mode:           {'ON' if AVAILABLE_MEMORY_GB < 12 else 'Optimized'}")
print(f"  Garbage Collection:      Enabled (post-model cleanup)")

# =====================================================================
# 1. Reload timing data if cells were run separately
# =====================================================================

if 'tpe_timing_df' not in dir():
    tpe_timing_file = RESULTS_DIR / "tpe_timing_per_model.csv"
    if tpe_timing_file.exists():
        tpe_timing_df = pd.read_csv(tpe_timing_file)
        print("\n✓ Loaded TPE timing from file")
else:
    print("\n✓ TPE timing in memory")

if 'gwo_timing_df' not in dir():
    gwo_timing_file = RESULTS_DIR / "gwo_timing_per_model.csv"
    if gwo_timing_file.exists():
        gwo_timing_df = pd.read_csv(gwo_timing_file)
        print("✓ Loaded GWO timing from file")
else:
    print("✓ GWO timing in memory")

# =====================================================================
# 2. Create comprehensive optimization comparison with efficiency metrics
# =====================================================================

if 'tpe_timing_df' in dir() and 'gwo_timing_df' in dir():
    comparison_timing = pd.merge(
        tpe_timing_df[["Model", "TPE_Search_Sec", "TPE_Evaluation_Sec", "TPE_Total_Sec", "Best_CV_Mean"]].rename(columns={"Best_CV_Mean": "TPE_Best_CV"}),
        gwo_timing_df[["Model", "GWO_Search_Sec", "GWO_Evaluation_Sec", "GWO_Total_Sec", "Best_CV_Mean"]].rename(columns={"Best_CV_Mean": "GWO_Best_CV"}),
        on="Model",
        how="outer"
    )
    
    # Efficiency metrics
    comparison_timing["TPE_Faster"] = comparison_timing["TPE_Total_Sec"] < comparison_timing["GWO_Total_Sec"]
    comparison_timing["Time_Difference_Sec"] = (comparison_timing["GWO_Total_Sec"] - comparison_timing["TPE_Total_Sec"]).abs()
    comparison_timing["CV_Improvement"] = (comparison_timing["GWO_Best_CV"] - comparison_timing["TPE_Best_CV"]) * 100
    # Efficiency: improvement per second
    comparison_timing["Efficiency_Score"] = comparison_timing["CV_Improvement"] / (comparison_timing["Time_Difference_Sec"] + 1e-6)
    
    comparison_timing.to_csv(RESULTS_DIR / "optimization_method_comparison_timing.csv", index=False)
    
    print("\n" + "="*80)
    print("OPTIMIZATION METHOD COMPARISON (Timing, Performance & Efficiency)")
    print("="*80)
    print(comparison_timing[["Model", "TPE_Total_Sec", "GWO_Total_Sec", "TPE_Faster", "TPE_Best_CV", "GWO_Best_CV", "CV_Improvement", "Efficiency_Score"]].to_string(index=False))
    
    # Summary statistics with efficiency analysis
    print("\n" + "-"*80)
    print("SUMMARY STATISTICS & EFFICIENCY METRICS:")
    print("-"*80)
    total_tpe_time = comparison_timing['TPE_Total_Sec'].sum()
    total_gwo_time = comparison_timing['GWO_Total_Sec'].sum()
    total_cv_improvement = comparison_timing['CV_Improvement'].mean()
    
    print(f"Total TPE time:          {total_tpe_time:8.2f}s ({total_tpe_time/60:6.2f} min)")
    print(f"Total GWO time:          {total_gwo_time:8.2f}s ({total_gwo_time/60:6.2f} min)")
    print(f"Time ratio (GWO/TPE):    {total_gwo_time/total_tpe_time:8.2f}x")
    print(f"TPE mean time/model:     {comparison_timing['TPE_Total_Sec'].mean():8.2f}s")
    print(f"GWO mean time/model:     {comparison_timing['GWO_Total_Sec'].mean():8.2f}s")
    print(f"Mean CV improvement:     {total_cv_improvement:+.4f} pp (GWO vs TPE)")
    print(f"Models faster with TPE:  {(~comparison_timing['TPE_Faster']).sum():2d} / {len(comparison_timing)}")
    print(f"Efficiency winner:       {'TPE' if total_tpe_time < total_gwo_time else 'GWO'}")

# =====================================================================
# 3. Inference Time Analysis (critical for deployment)
# =====================================================================

print("\n" + "="*80)
print("INFERENCE TIME ANALYSIS (Per Sample)")
print("="*80)

inference_timing_records = []

if not tpe_results_df.empty:
    tpe_test_df = tpe_results_df[tpe_results_df["Split"] == "Test"].copy()
    for _, row in tpe_test_df.iterrows():
        model_code = row["Model"]
        params = {k: v for k, v in row.items() if k not in ["Method", "Model", "Optimal_Scaler", "Split", "Accuracy", "Precision", "Recall", "F1", "AUC", "LogLoss", "Kappa", "MCC"] + [c for c in row.index if "CI_" in c]}
        
        pipeline = make_pipeline(model_code, params, row["Optimal_Scaler"])
        pipeline.fit(X_train, y_train)
        
        # Time inference on test set (3 runs for stability)
        times = []
        for _ in range(3):
            inference_start = time.perf_counter()
            _ = pipeline.predict(X_test)
            times.append(time.perf_counter() - inference_start)
        
        inference_time_total = np.mean(times)
        inference_time_per_sample_us = (inference_time_total / len(X_test)) * 1_000_000
        
        inference_timing_records.append({
            "Method": "TPE",
            "Model": model_code,
            "Optimal_Scaler": row["Optimal_Scaler"],
            "Inference_Time_Total_Sec": float(inference_time_total),
            "Inference_Time_Per_Sample_Us": float(inference_time_per_sample_us),
            "Test_Samples": len(X_test),
            "CV_Accuracy": row["Accuracy"],
        })

if not gwo_results_df.empty:
    gwo_test_df = gwo_results_df[gwo_results_df["Split"] == "Test"].copy()
    for _, row in gwo_test_df.iterrows():
        model_code = row["Model"]
        params = {k: v for k, v in row.items() if k not in ["Method", "Model", "Optimal_Scaler", "Split", "Accuracy", "Precision", "Recall", "F1", "AUC", "LogLoss", "Kappa", "MCC"] + [c for c in row.index if "CI_" in c]}
        
        pipeline = make_pipeline(model_code, params, row["Optimal_Scaler"])
        pipeline.fit(X_train, y_train)
        
        # Time inference (3 runs for stability)
        times = []
        for _ in range(3):
            inference_start = time.perf_counter()
            _ = pipeline.predict(X_test)
            times.append(time.perf_counter() - inference_start)
        
        inference_time_total = np.mean(times)
        inference_time_per_sample_us = (inference_time_total / len(X_test)) * 1_000_000
        
        inference_timing_records.append({
            "Method": "GWO",
            "Model": model_code,
            "Optimal_Scaler": row["Optimal_Scaler"],
            "Inference_Time_Total_Sec": float(inference_time_total),
            "Inference_Time_Per_Sample_Us": float(inference_time_per_sample_us),
            "Test_Samples": len(X_test),
            "CV_Accuracy": row["Accuracy"],
        })

inference_timing_df = pd.DataFrame(inference_timing_records)
inference_timing_df.to_csv(RESULTS_DIR / "inference_timing_analysis.csv", index=False)

if not inference_timing_df.empty:
    print("\nInference Timing Summary:")
    print(inference_timing_df[["Method", "Model", "Inference_Time_Per_Sample_Us", "Inference_Time_Total_Sec", "CV_Accuracy"]].to_string(index=False))
    
    print("\n" + "-"*80)
    print("INFERENCE PERFORMANCE METRICS:")
    print("-"*80)
    for method in ["TPE", "GWO"]:
        subset = inference_timing_df[inference_timing_df["Method"] == method]
        if not subset.empty:
            print(f"{method} Method:")
            print(f"  Mean inference time per sample: {subset['Inference_Time_Per_Sample_Us'].mean():8.2f} µs")
            print(f"  Min  inference time per sample: {subset['Inference_Time_Per_Sample_Us'].min():8.2f} µs ({subset.loc[subset['Inference_Time_Per_Sample_Us'].idxmin(), 'Model']})")
            print(f"  Max  inference time per sample: {subset['Inference_Time_Per_Sample_Us'].max():8.2f} µs ({subset.loc[subset['Inference_Time_Per_Sample_Us'].idxmax(), 'Model']})")
            print()

# =====================================================================
# 4. Consolidate all results (Baseline, TPE, GWO)
# =====================================================================

all_results_frames = [baseline_results_df]
if not gwo_results_df.empty:
    all_results_frames.append(gwo_results_df)
if not tpe_results_df.empty:
    all_results_frames.append(tpe_results_df)

all_results_df = pd.concat(all_results_frames, ignore_index=True)
all_results_df["Method"] = pd.Categorical(all_results_df["Method"], categories=METHOD_ORDER, ordered=True)
all_results_df["Model"] = pd.Categorical(all_results_df["Model"], categories=MODEL_ORDER, ordered=True)
all_results_df = all_results_df.sort_values(["Split", "Model", "Method"]).reset_index(drop=True)

comparison_table = all_results_df[["Method", "Model", "Optimal_Scaler", "Split", *METRICS]].copy()
comparison_table.to_csv(RESULTS_DIR / "all_methods_results_point_estimates.csv", index=False)
all_results_df.to_csv(RESULTS_DIR / "all_methods_results_with_ci.csv", index=False)

ci_long_rows = []
for _, row in all_results_df.iterrows():
    for metric_name in METRICS:
        ci_long_rows.append(
            {
                "Method": row["Method"],
                "Model": row["Model"],
                "Optimal_Scaler": row["Optimal_Scaler"],
                "Split": row["Split"],
                "Metric": metric_name,
                "Point_Estimate": row[metric_name],
                "CI_Lower": row[f"{metric_name}_CI_Lower"],
                "CI_Upper": row[f"{metric_name}_CI_Upper"],
            }
        )

ci_long_df = pd.DataFrame(ci_long_rows)
ci_long_df.to_csv(RESULTS_DIR / "all_methods_metric_ci_long.csv", index=False)

run_metadata = {
    "data_path": str(DATA_PATH),
    "results_dir": str(RESULTS_DIR),
    "random_state": RANDOM_STATE,
    "test_size": TEST_SIZE,
    "n_splits": N_SPLITS,
    "n_trials_per_model": N_TRIALS_PER_MODEL,
    "gwo_population_size": GWO_POPULATION_SIZE,
    "gwo_iterations": GWO_ITERATIONS,
    "n_bootstrap": N_BOOTSTRAP,
    "selected_feature_count": len(selected_features),
    "selected_features": selected_features,
    "optimized_models": sorted(list(SEARCH_SPACES.keys())),
    "all_models": MODEL_ORDER,
    "system_resources": {
        "cpu_cores": CPU_COUNT,
        "total_memory_gb": TOTAL_MEMORY_GB,
        "available_memory_gb": AVAILABLE_MEMORY_GB,
        "n_jobs_cv": N_JOBS_CV,
        "n_jobs_optimization": N_JOBS_OPT,
    },
    "optimization_note": "Separate TPE and GWO cells with adaptive parallelization and resource monitoring",
}
with open(RESULTS_DIR / "run_metadata.json", "w", encoding="utf-8") as handle:
    json.dump(run_metadata, handle, indent=2)

gc.collect()  # Final cleanup

print("\n" + "="*80)
print("✓ UNIFIED PIPELINE COMPLETED SUCCESSFULLY")
print("="*80)
print(f"Point estimates:          {RESULTS_DIR / 'all_methods_results_point_estimates.csv'}")
print(f"Results with CI:          {RESULTS_DIR / 'all_methods_results_with_ci.csv'}")
print(f"Long-format CI:           {RESULTS_DIR / 'all_methods_metric_ci_long.csv'}")
print(f"Timing comparison:        {RESULTS_DIR / 'optimization_method_comparison_timing.csv'}")
print(f"Inference analysis:       {RESULTS_DIR / 'inference_timing_analysis.csv'}")
print(f"TPE timing per model:     {RESULTS_DIR / 'tpe_timing_per_model.csv'}")
print(f"GWO timing per model:     {RESULTS_DIR / 'gwo_timing_per_model.csv'}")
print("="*80)